### ISSUE TITLE
Clients dropped when sending large messages over secure socket connection

### ISSUE THREAD

**Issue by qristin** [uWebSockets/uWebSockets#143]
When a secure websocket connection is set up and a large amount of data is sent from the client to the server the connections are dropped by the server. This only occurs when tested on two different machines. To reproduce see the small case example [here](https://github.com/qristin/uws-connections-dropped)

**Comment by Dillybob92** [comment]
Is this only on SSL?

**Comment by alexhultman** [comment]
I will take a look at this later on. This is good news, I haven't had much testing done with SSL. Are you triggering some kind of renegotiation?

**Comment by qristin** [comment]
@Dillybob92 Yes indeed, only over SSL

@alexhultman Not explicitly and I cannot find evidence that the client lib does it under water. I also saw the issue with a different client library. I did some debugging and found that the 1006 error on line [926](https://github.com/alexhultman/uWebSockets/blob/master/src/uWS.cpp#L926) is thrown. Not sure why though.

**Comment by alexhultman** [comment]
The close at 926 happens when SSL_read returns a size of 0 or -1, which is supposed to be when a close happened as far as I can see: https://www.openssl.org/docs/manmaster/ssl/SSL_read.html

**Comment by qristin** [comment]
I have changed nothing on the test setup. With small messages it works with larger it doesn't.

**Comment by alexhultman** [comment]
I can trigger it with a 125mb text file, will take a look at this. Should be simple now that I easily can trigger it.

**Comment by alexhultman** [comment]
This fixes it: fdfa9a4de6bb08d6caf924e3f5186e19ee8ac5bf. Will be in next version.

**Comment by alexhultman** [comment]
This is published as 0.7.0 now.
