### ISSUE TITLE
uws needs to be registered last in EventEmitter chain of http(s) server

### ISSUE THREAD

**Issue by kapouer** [uWebSockets/uWebSockets#149]
Under very light load, when i'm serving socket.io over SSL using uws 0.4.1 and at the same time i'm making HTTP POST (to a middleware mounted on a different path, obviously), the POST sometimes just hangs until client times out.

This is something that appeared when i replaced ws by uws - and now i'm going to check that affirmation by going back to ws on the SSL service (which is idling all day anyway).

**Comment by alexhultman** [comment]
You can only have a bunch of uws servers attached to the same https server currently. The socket gets closed so any use of it is not really going to work. Try and register the uws oaths last in the chain and see if that works.

**Comment by kapouer** [comment]
Sounds correct, i was registering it first. Maybe this should be documented somewhere ?

**Comment by alexhultman** [comment]
Or fixed, hehehe :wink:

**Comment by alexhultman** [comment]
@kapouer Could you try the lastest uws.js?

**Comment by alexhultman** [comment]
It seems to work as it should, it's still not 100% perfect though (it doesn't track removeListener for 'upgrade' but who cares, really).

**Comment by kapouer** [comment]
I'll give it a shot before tomorrow.

**Comment by kapouer** [comment]
Using uws@0.7.0 for a week, i still can see the same problem on production servers, but much less often. It seems not directly related to current load. (It is not an immediate issue for the application i'm using - it just adds a delay before retrying, that's why i can keep testing it). Maybe your latest commits already fixed this... do you think i should try them ?

**Comment by alexhultman** [comment]
I haven't done anything more with this issue. If you register uws last, then it works?

How are you using the constructor of uws.Server? What options and in what order. HTTP POST should no be affected at all, we only register to 'upgrade' event and this fix I did only solves conflicts in the 'upgrade' event chain, not in anything else.

**Comment by kapouer** [comment]
uws first through socket.io then some express post handler.
Options are ```
  noServer: true,
  clientTracking: false,
  perMessageDeflate: false
```

This is the piece registering socket.io then some other post handler:
https://paste.gnome.org/pkrbyqdq1

I'll figure a way to register the post handler first and see if that makes the problem disappear.

**Comment by alexhultman** [comment]
Nothing of what I fixed applies to you. You pass noServer, so there is no communication with any HTTP server at all. If you look in uws.js you see that most of everything is ignored when passing noServer. The only way of controlling uws with noServer is via handleUpgrade which will close the socket (it will of course take ownership of that connection). So I cannot see any relation between your HTTP POST isues and uws, it depends on how handleUpgrade is being used, but I cannot see any possibility of using it in a way that would break anything.

**Comment by alexhultman** [comment]
What is the connection, the relation, between uws and your HTTP POST server? I don't think they are related at all? Where ins the code is there any intersection between the two pieces?
