### ISSUE TITLE
Support IPv6 with the C++ HTTP server

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#163]
I have been targeting Node.js as HTTP server for quite some time now and left the built-in HTTP server quite unfinished. This needs to get some attention to allow SSL connections and IPv6.

**Comment by alexhultman** [comment]
http://long.ccaba.upc.es/long/045Guidelines/eva/ipv6.html

**Comment by alexhultman** [comment]
http://long.ccaba.upc.es/long/045Guidelines/eva/ipv6.html

**Comment by KrishnaPG** [comment]
Came across this while looking for some good REST c++ server library.  Is it possible to use this library to provide basic HTTP server functionality to existing C++ applications? For example, handle not only websocket clients, but also HTTP clients for GET/POST etc.

Or does this only work with NodeJS?

**Comment by alexhultman** [comment]
There is no HTTP support currently, you need to either transfer the connection from another HTTP server by passing file descriptor and SSL pointer to µWS, or just run HTTP on one port and WebSockets on another port. I want to support HTTP eventually.
