### ISSUE TITLE
Make noDelay true by default

### ISSUE THREAD

**Issue by githubaccount624** [uWebSockets/uWebSockets#164]
Hi, I'd really like to use this for my website but with the default option of noDelay being false, most packets are way too slow. For example, with ws if I click a button and send a packet, I get a response back immediately. With uws it takes a couple seconds and as a result, seems very laggy to the end user.

I'd just set it to true but I'm using primus and do not know of a way to reach under the hood to set it to true.

All the other websocket implementations have noDelay set to true so shouldn't this project as well? It makes the end-user experience so much nicer and more responsive.

**Comment by lpinca** [comment]
In `pimus@5.2.2` the Nagle algorithm is disabled, see https://github.com/primus/primus/blob/4624a2d4d2669125b0a56eb1277701d65fab0394/transformers/uws/server.js#L36.

**Comment by alexhultman** [comment]
I guess it makes sense to use noDelay with WebSockets since they are less of a stream and more of a flow of complete messages. Instead I could expose cork/uncork functions to explicitly control when data gets sent (Linux only, though).

**Comment by alexhultman** [comment]
noDelay is now true by default. Thanks for input
