### ISSUE TITLE
Scaling Horizontally

### ISSUE THREAD

**Issue by iCyberon** [uWebSockets/uWebSockets#165]
The library looks amazing, just did a benchmark and it's definitely much faster than ws. I'm thinking about changing my current implementation of ws in my project, so have a questions (might be dump).

How do you scale horizontally?

To keep it simple let's assume we're using redis as a pub/sub server. Thanks.

**Comment by alexhultman** [comment]
It should work just like ws? We both implement the same interface so whatever scaling method you currently use should translate into uws. That is the idea, I might have missed something though?

**Comment by iCyberon** [comment]
@alexhultman Thanks for prompt reply. Just did a quick test with my current scaling solution. Works as expected 👍

**Comment by alexhultman** [comment]
:+1:

**Comment by ad34** [comment]
@alexhultman can you give more details about your redis implementation. I used to use uwebsocket as an engine with socket.io & redis adapter, but didn't dive into implementation details , would be nice to get a working exemple.

**Comment by sd031** [comment]
Any one know's how to properly do horizontally scaling UWS, even ws, so that I can try the same, any help will be appreciated.

**Comment by sd031** [comment]
Hi @iCyberon, 

which npm library or solution you have used to do horizontal scaling, can you let us know that will help us to use somewhat same kind of situation facing here, any suggestion will be appreciated.

**Comment by iCyberon** [comment]
@sd031 I'm not using node.js anymore. My current solution is based on C++ version. But it shouldn't be different. You can use redis for pub/sub. Basically, all your nodes should be able to receive and send messages from/to all connected sockets. Optionally, you use use [uTT](https://github.com/uNetworking/uTT) if you need better performance. If you're using nodejs, you can check [socket.io-redis](https://github.com/socketio/socket.io-redis) as an example. The performance isn't great, but it'll give you an idea how to implement horizontal scaling. Good luck.

**Comment by ad34** [comment]
started working on the adapter on my own as I need my project to be scalable. socket.io-redis is a good start point but uwebsockets has some differences, for example I can't find the concept of socket id in uwebsockets , I will probably create an id on my own . other things like broadcast are not implemented in uwebsockets.

So , socket.io-redis is a good exemple to check what s needed , but implementing on top on uwebsocket would require some work. if anyone intersseted in sharing the work please let me know. I hope such an adapter will be on github in the future, as most projects build on top on uwebsockets will require scaling.
