### ISSUE TITLE
Support SPDY and HTTP/2 with the C++ HTTP server

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#170]

**Comment by SEAPUNK** [comment]
I don't even know if that's possible with HTTP/2. I keep reading articles here and there that HTTP/2 never added back the "Upgrade" header.

**Comment by alexhultman** [comment]
Maybe it is only SPDY then. I get all scrambled up headers when using SSL, they need to get decompressed to make sense.

**Comment by SEAPUNK** [comment]
I'm pretty sure it's the same for SPDY, considering it was essentially HTTP/2 pre-alpha. http://stackoverflow.com/a/12103981

**Comment by alexhultman** [comment]
AH! I was trying to connect SSL to a non-SSL server and got all scrambled up headers so I thought it had to be SPDY stuff. I simply couldn't get Chrome to connect via SSL. So yeah, this SPDY thing is not really needed at all - it works now that I actually enabled SSL again hahaha

**Comment by ronkorving** [comment]
Ueah, afaik WebSockets don't travel over HTTP2. A real shame that.

**Comment by alexhultman** [comment]
I connected SSL to a non-SSL server and since SPDY is part of the SSL negotiation process, integrated into OpenSSL kind of, I got scrambled binary with holes of text where it said "spdy/3.1" or something so I got confused :wink:
