### ISSUE TITLE
C++ Server and SSL

### ISSUE THREAD

**Issue by AlexVK79** [uWebSockets/uWebSockets#173]
I have got C++ examples running fine on Ubuntu (using ws:// on client-side js).
However when I try to connect  via wss:// it does not work.

Is there something else needed on C++ server side (for wss to work) or 
just a problem with SSL certificate not configured properly?
Any tips for local debugging?

**Comment by alexhultman** [comment]
Do you pass a uWS::SSLContext to the uWS::Server constructor? You specify certificate and key that way.

**Comment by AlexVK79** [comment]
Oh, thanks! It works now.

Do you have any tips regarding lowest latency and the optional flags ?
    PERMESSAGE_DEFLATE = 1,
    SERVER_NO_CONTEXT_TAKEOVER = 2,
    CLIENT_NO_CONTEXT_TAKEOVER = 4,
    NO_DELAY = 8
I guess NO_DELAY is a must for a game scenario, but what about the others ?

**Comment by alexhultman** [comment]
The other options are permessage-deflate options. They are quite complex because of negotiation rules (client_no_context_takeover is not guaranteed to be used, while server_no_context_takeover is).

Btw, NO_DELAY is not really implemented yet. You could PR that, it should be a simple one liner using setsockopt with TCP_NODELAY.

**Comment by AlexVK79** [comment]
Thanks!

**Comment by AlexVK79** [comment]
Ooops! 
I thought wss started to work, but it was actually ws on client side.
When I changed client to wss it didn't work.

When I do :

Server server(3000, ...);

I suppose uWS also runs a very simple HTTP/HTTPS server on that port ?
So to validate self-signed certificate I tried to direct browser to https://localhost:3000 first.

Firefox gave me error:
Secure Connection Failed
---------------------------------------------------
An error occurred during a connection to localhost:3000. The server rejected the handshake because the client downgraded to a lower TLS version than the server supports. Error code: SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT

Google Chrome gave a bit different error:
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Maybe I should setup OpenSSL in C++ code for server to support some protocol versions
they don't di by fefault?

**Comment by alexhultman** [comment]
This sounds like something other than uws itself. OpenSSL should automatically select an appropriate SSL protocol. If you Google the error you will find all kinds of solutions like restarting your computer, disabling "anti-virus", etc. What version of OpenSSL are you using? What OS? You could tinker with the SSLContext in Server.cpp if you want but that code is very simple and it is pretty much identical to the "hello world server" from OpenSSL itself so I don't think I can do anything about this.

**Comment by AlexVK79** [comment]
Ubuntu 16.04 TLS
openssl version gives me: OpenSSL 1.0.2g-fips  1 Mar 2016

**Comment by alexhultman** [comment]
What version of Chrome are you running? With the latest commit I disabled SSLv3, so the only supported versions are TLS1 and above, the same as Chrome 40+ supports. I cannot reproduce your issue and the SSL code is very minimal and according to documentation. The browser should not negotiate anything lower than TLSv1 (SSLv2, SSLv3 disabled).

**Comment by AlexVK79** [comment]
I tried with Chrome 51.0.2704.103 m
Will try again tomorrow with different "tricks" like disabling firewall/anti-virus/etc.

**Comment by alexhultman** [comment]
I have openssl-1:1.0.2h-1.fc23.x86_64 and google-chrome-stable-51.0.2704.106-1.x86_64. I cannot find anything particularly wrong with the SSL code: https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_new.html

I pass SSLv23_server_method() as method (recommended) and I now disable SSLv3 (also recommended). Other than this, the OpenSSL should automatically negotiate things and it does work in Chrome and Firefox for me.

**Comment by alexhultman** [comment]
```
SSLv23_method(), SSLv23_server_method(), SSLv23_client_method()
These are the general-purpose version-flexible SSL/TLS methods. The actual protocol version used will be negotiated to the highest version mutually supported by the client and the server. The supported protocols are SSLv2, SSLv3, TLSv1, TLSv1.1 and TLSv1.2. Most applications should use these method, and avoid the version specific methods described below.

The list of protocols available can be further limited using the SSL_OP_NO_SSLv2, SSL_OP_NO_SSLv3, SSL_OP_NO_TLSv1, SSL_OP_NO_TLSv1_1 and SSL_OP_NO_TLSv1_2 options of the SSL_CTX_set_options or SSL_set_options functions. Clients should avoid creating "holes" in the set of protocols they support, when disabling a protocol, make sure that you also disable either all previous or all subsequent protocol versions. In clients, when a protocol version is disabled without disabling all previous protocol versions, the effect is to also disable all subsequent protocol versions.

The SSLv2 and SSLv3 protocols are deprecated and should generally not be used. Applications should typically use SSL_CTX_set_options in combination with the SSL_OP_NO_SSLv3 flag to disable negotiation of SSLv3 via the above version-flexible SSL/TLS methods. The SSL_OP_NO_SSLv2 option is set by default, and would need to be cleared via SSL_CTX_clear_options in order to enable negotiation of SSLv2.
```

**Comment by alexhultman** [comment]
If you compare that description with the code, it looks okay. The only thing happening after this code is SSL_accept, SSL_read and SSL_write, so any settings are really just set on the SSL_CTX below:
```c++
SSLContext::SSLContext(std::string certFileName, std::string keyFileName)
{
    static bool first = true;
    if (first) {
        SSL_library_init();
        atexit([]() {
            EVP_cleanup();
        });
        first = false;
    }

    sslContext = SSL_CTX_new(SSLv23_server_method());
    if (!sslContext) {
        throw ERR_SSL;
    }

    SSL_CTX_set_options(sslContext, SSL_OP_NO_SSLv3);

    if (SSL_CTX_use_certificate_file(sslContext, certFileName.c_str(), SSL_FILETYPE_PEM) < 0) {
        throw ERR_SSL;
    } else if (SSL_CTX_use_PrivateKey_file(sslContext, keyFileName.c_str(), SSL_FILETYPE_PEM) < 0) {
        throw ERR_SSL;
    }
}
```

**Comment by AlexVK79** [comment]
Greate news! I've got wss/SSL working.
The problem was that my paths to certFileName/keyFileName were wrong and there is a bug in SSLContext::SSLContext checking this.

According to specs of SSL_CTX_use_certificate_file/SSL_CTX_use_PrivateKey_file:

> On success, the functions return 1. Otherwise check out the error stack to find out the reason.
So SSLContext didn't throw ERR_SL with wrong paths;

 You should check it like this:
 `if (SSL_CTX_use_certificate_file(sslContext, certFileName.c_str(), SSL_FILETYPE_PEM) != 1) {
        throw ERR_SSL;
    } else if (SSL_CTX_use_PrivateKey_file(sslContext, keyFileName.c_str(), SSL_FILETYPE_PEM) != 1) {
        throw ERR_SSL;
    }`

**Comment by alexhultman** [comment]
Nice, I fixed that in d62f728efe2d77259d264d43120af25141280b94

**Comment by herpiko** [comment]
@AlexVK79 @alexhultman  sorry for bringing this up. Can I have an example of your implementation? I'm using the example from README.Md, with `uWS::Hub`, not `uWS::Server`. How to pass the `uWS::SSLContext` to this `Hub`?

**Comment by alexhultman** [comment]
@herpiko There are a butt load of examples and issue questions for this, and if you would just look at the auto-complete in your IDE for 2 seconds it would be astoundingly obvious.

**Comment by herpiko** [comment]
@alexhultman Thank you!
