### ISSUE TITLE
WS and WSS mix

### ISSUE THREAD

**Issue by AlexVK79** [uWebSockets/uWebSockets#178]
When server is wss it does not serve ws clients, I guess this is by design?

Well I try to setup 2 servers ws and wss

> Server server_ws(3000, true);
> Server server_wss(3001, false, NO_DELAY|PERMESSAGE_DEFLATE, 1048576, sslcontext);

How do I run them both? (ideally in the same uv_loop).

**Comment by alexhultman** [comment]
Both need to be master = true, and you only need to run one of the servers.

**Comment by AlexVK79** [comment]
Great! Thanks!
