### ISSUE TITLE
removeAllListeners seems broken

### ISSUE THREAD

**Issue by ronkorving** [uWebSockets/uWebSockets#179]
https://github.com/uWebSockets/uWebSockets/blob/22f82496f73fcd14ae9bb4f86f9758d2158d986e/nodejs/dist/uws.js#L125-L133

The else-cases prevent the "no eventName" path from working. It'll only reset the first listener (`onmessage`) to `noop`, but none of the others.

**Comment by alexhultman** [comment]
f9ff8cf9ee9016945e4e1fbeda6a4bf1671e79d8
