### ISSUE TITLE
dependency header in public header files

### ISSUE THREAD

**Issue by chemhack** [uWebSockets/uWebSockets#180]
libuv, zlib and openssl 's header files are referenced in header files referenced by uWS.h. 

When using uWS and a dependency for a third-party building target(not build with cmake in the same project), those libraries' headers need to be available to the third-party target as well.

Considering uWS's C++ API do not explicitly require libuv or openssl datatypes, is it possible to hide uWS's implementation details from public headers? 

Pimpl idiom can solve this, but will make the source structure a little bit ugly. 

@alexhultman what do you think?

**Comment by alexhultman** [comment]
I had this design prior to the refactor, every pointer to uv, zlib and OpenSSL structures were void prts. "Expert" people (read: retards) called me an idiot for "using unchecked ptrs" which of course is just bullshit. So I opted for removing it and just including all headers where ever they were needed.

**Comment by alexhultman** [comment]
I agree 120% with you.

**Comment by alexhultman** [comment]
Edit: Okay so I never had pimpl but I had opaque pointers before the refactor. I guess the indirection is negligible if one does not use virtual functions. We can test, I'm all for it if it doesn't harm performance. I like the idea of having opaque dependencies - it is kind of a total opposite of what WebSocket++ does, they have everything in the headers.

**Comment by chemhack** [comment]
I looked into it last few days, there are a few problems to be discussed before I can implement this.

Server.h:
- `SSLContext` do not need to exposed publicly. We can add a new struct with cert/key paths for Server's constructor.
- `onUpgrade` callback is using `uv_os_sock_t`, this can be solved by our own os_sock_t.

WebSocket.h
- `WebSocket` class is only a thin wrapper around `uv_poll_t*`, it doesn't make too much sense to add a wrapper for `WebSocket`. I would suggest just make use `void*` instead. 

Regarding performance, if we only make a wrapper for `Server` class, performance harm is close to zero, as the `Server` class is only used to init configs(constructor), and set callbacks. 

@alexhultman if you agree i can implement necessary changes.

**Comment by alexhultman** [comment]
This is very similar to the design prior to the refactor. I don't know, I don't have any trouble using the lib on Linux thanks to the sane environment where dependencies are easily installed and easily found. It should be easy on OS X too with homebrew.
