### ISSUE TITLE
No make install target

### ISSUE THREAD

**Issue by limekake** [uWebSockets/uWebSockets#185]
I'm new to using cmake but it seems that it's not generating the install target for the subsequent makefile.

Am I missing something or was this intentional?

**Comment by alexhultman** [comment]
PR welcomed. I don't know CMake that well either.

**Comment by limekake** [comment]
Ended up doing the same thing as jimmy, installed the files manually.

Would like to point out that a -luWS flag is needed for the compiler to not complain. So might want to make a note of that too!

**Comment by alexhultman** [comment]
How does that location work on Windows? Are install targets only for Unix? Personally I have always installed to /usr/include /usr/lib64

**Comment by jimmyt857** [comment]
Unfortunately I have 0 experience using cmake with Windows  :disappointed:

**Comment by alexhultman** [comment]
You only need to install `Agent.h  EventSystem.h  Server.h uWS.h  WebSocket.h` and `libuWS.so`.

**Comment by alexhultman** [comment]
I'm on Fedora and I have to install to lib64. Does lib64 exist in Ubuntu and other Debian based systems? It really seems like a mess but I read somewhere that Debian systems have a link from lib64 to lib, which is their 64-bit folder. If this is true, I should just install to /usr/lib64 (yes, I don't see why I should install to /usr/local/lib64).

**Comment by alexhultman** [comment]
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 81d1101..b77edf0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,10 +9,9 @@ find_package(ZLIB REQUIRED)
 find_path(LIBUV_INCLUDE_DIR uv.h)
 find_library(LIBUV_LIBRARY NAMES uv uv1)
 
-add_library(uWS SHARED src/Extensions.cpp src/HTTPSocket.cpp src/Network.cpp src/Server.cpp src/UTF8.cpp src/WebSocket.cpp src/EventSystem.cpp)
-target_include_directories(uWS PUBLIC src)
+add_library(uWS SHARED src/Extensions.cpp src/HTTPSocket.cpp src/Network.cpp src/Server.cpp src/UTF8.cpp src/WebSocket.cpp src/EventSystem.cpp src/Agent.cpp)
 
-target_include_directories(uWS PUBLIC ${LIBUV_INCLUDE_DIR})
+target_include_directories(uWS PUBLIC src)
 target_include_directories(uWS PUBLIC ${LIBUV_INCLUDE_DIR})
 target_include_directories(uWS PUBLIC ${ZLIB_INCLUDE_DIRS})
 target_include_directories(uWS PUBLIC ${OPENSSL_INCLUDE_DIR})
@@ -23,6 +22,8 @@ target_link_libraries (uWS LINK_PUBLIC ${ZLIB_LIBRARY})
 
 if (UNIX)
 target_link_libraries (uWS LINK_PUBLIC pthread)
+install (TARGETS uWS DESTINATION /usr/lib64)
+install (FILES src/Agent.h src/EventSystem.h src/Server.h src/WebSocket.h src/uWS.h DESTINATION /usr/include/uWS)
 endif (UNIX)
 
 add_subdirectory(examples)
```

**Comment by dushyantw** [comment]
i was able to update my openssl version and was able to install uwebsockets on my mac running 10.10.5. I verified the install using "openssl version". Then i returned to my c++ project, ran cmake which ran ok and then when i ran make i get this error

ain.cpp:1:10: fatal error: 
      'uWS/uWS.h' file not found
#include <uWS/uWS.h>

I am a rookie and am getting limited support from other sources. Google points to multiple directions but the thread above (although closed) makes most sense. Can anyone help?

**Comment by alexhultman** [comment]
@dushyantw You compiler has certain paths that it looks for header files. On Unix (Linux, OS X) these are usually /usr/include or /usr/local/include. If you manage to put the headers (uWS folder) using whatever method (cmake, make or whatever) it should work. Otherwise you have -I flag and -L flag to use.

**Comment by OverRatedTech** [comment]
@alexhultman Does it matter where we manage the uWs folder if we have both paths (/usr/local/include and /usr/include)?
