### ISSUE TITLE
[JS] Use events like MessageEvent and CloseEvent for parity with "ws" and the WebSocket spec

### ISSUE THREAD

**Issue by ide** [uWebSockets/uWebSockets#188]
Currently code that uses "ws" to create a WS server expects MessageEvents so "uws" isn't a drop-in replacement. The WebSocket spec uses event objects. For example the argument passed to the `onmessage` callback is a MessageEvent object (https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) instead of just a string or buffer.

See: https://github.com/websockets/ws/blob/e591ba61022ffc7a6c0c865c8759309c2b2a35c3/lib/WebSocket.js#L440

**Comment by alexhultman** [comment]
This is for React-Native? Do you have any code that triggers the incompatibility? There are a few quirks with uws, I don't think it will ever be a 100% drop-in replacement but it should be close to 90%. I don't really like the ws interface at all and would much rather implement a much more effective and minimal one in the future. If your usage is easy to tweak for compatibility that would be one solution.

**Comment by ide** [comment]
Yeah, it's for React Native and should be easy to change. One of the benefits of using the MessageEvent interface is that it matches the browser's WebSocket spec, which seems more beneficial than matching the ws interface. (Although, the ws interface is close to the WebSocket spec so it's like killing two birds with one stone.)

**Comment by alexhultman** [comment]
I don't get how MessageEvent works. The documentation is obviously wrong because it says the contructor takes no arguments, yet ws passes 3 arguments. Does it have some kind of "toString()" that makes it possible to just use the message as a string? I thought ws just returned strings or buffers - that's what I've been doing for a long time and no one has noticed.

Are you relying on message**.data**?

**Comment by alexhultman** [comment]
is it possible to do something like (message.data ? message.data : message)?

**Comment by ide** [comment]
Yes it's possible to do that and is an easy change. But if you wanted to follow the WebSocket spec there's some benefit to that. The idea is that all event types extend from the base Event type (https://developer.mozilla.org/en-US/docs/Web/API/Event) and for WebSockets there are two special subtypes, MessageEvent and CloseEvent. The constructors aren't documented since MessageEvent is an interface, not a class: https://html.spec.whatwg.org/multipage/comms.html#the-messageevent-interfaces.

**Comment by alexhultman** [comment]
ws implement their own MessageEvent:

https://github.com/websockets/ws/blob/e591ba61022ffc7a6c0c865c8759309c2b2a35c3/lib/WebSocket.js#L494

I could do this, absolutely. But I still don't get how MessageEvent can be evaluated to a string when used like this:

```javascript
ws.on('message', function(message) {
console.log(message); // this works in ws, obviously there is some kind of toString involved? I don't get it!
});
```

**Comment by alexhultman** [comment]
AHAAAAAAAAAAAAAAAAAAAAAAAAAA!

onmessage is a different callback which is called with a MessageEvent, while the on('message', callback) is called with a message just like the one in uws. So yeah, I can definitely fix this up.

Is this the only missing thing for React Native integration?

**Comment by ide** [comment]
I'm not sure, there may be other issues that pop up. But I am experimenting with uws :)

**Comment by alexhultman** [comment]
If you want to do some initial testing with this, you basically can just go to uws.js and change:

```javascript
        this.nativeServer.onMessage((nativeSocket, message, binary, socket) => {
            socket.onmessage(binary ? message : message.toString());
        });
```

with

```javascript
        this.nativeServer.onMessage((nativeSocket, message, binary, socket) => {
            socket.onmessage({data: binary ? message : message.toString()});
        });
```

I'm pretty sure that will work, otherwise you can just add the properties you need.

**Comment by alexhultman** [comment]
That won't work, I see that you use a mix of the EventEmitter and the WebSocket browser interface. I'm just searching through the code on GitHub and it really seems to be pretty small and simple. I think the best solution is to just port all usages to the EventEmitter interface. It's not very simple to implement both onmessage and on('message', cb) with no memory overhead or performance overhead.

**Comment by alexhultman** [comment]
@ide Hey man I think I have a pretty good solution going now, so never mind - I will fix this up.

**Comment by alexhultman** [comment]
@ide I just finished this, it is published as 0.7.5 and I'm pretty sure this will work as a drop-in. I looked though the sources of RN and this should solve it (absolutely no way 0.7.4 would have worked, not even the corret binary type ArrayBuffer vs Node.js buffer).

**Comment by ide** [comment]
@alexhultman it's working out of the box now, thanks for your quick work!

**Comment by alexhultman** [comment]
@ive So what is the plan regarding the swap from ws? We talked about this some months ago but it never happened. I guess it should be possible to swap now that it actually works? :wink:

**Comment by ide** [comment]
My thinking is that now that uws works with react native, we can experiment comparing it with ws and see which works better for our needs (e.g. reliability, number of people who have problems with it).
