### ISSUE TITLE
ES6/ES7 errors in Webpack builds

### ISSUE THREAD

**Issue by mirague** [uWebSockets/uWebSockets#189]
When trying to produce a build that relies on a dependency using `uws` we're getting the following errors on the es7 "fat arrow" declaration:

```
SyntaxError:
Unexpected token:
punc ()) [/Users/melvin/Projects/trail-homepage/~/socketcluster-server/~/uws/uws.js:8,0]
```

**uws.js:8,0:**
```
const uws = (() => {
    try {
        return require(`./uws_${process.platform}_${process.versions.modules}`);
    } catch (e) {
        throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
        'available for your system. Please install a supported C++11 compiler and reinstall the module \'uws\'.');
    }
})();
```

How can we make sure it runs in non-es6 environments?

**Comment by SEAPUNK** [comment]
Run it through Babel.

**Comment by alexhultman** [comment]
What version of Node.js are you running? We only support 4.x and up.

**Comment by mirague** [comment]
I was using Node 6.3 but it seems there was an error on my side in how I was running webpack.

Closing this.
