### ISSUE TITLE
Add emit to "Socket" class

### ISSUE THREAD

**Issue by henopied** [uWebSockets/uWebSockets#190]
I'm working on getting uws to work with multiogar and the issue right now is we have a bit of code that triggers the close event itself and as the `Socket` class does not have a full event emitter in it this throws an error because `emit` does not exist. Hopefully there is a simple fix.

**Comment by alexhultman** [comment]
I added emit in 0.7.6, test it out and see how it works.

**Comment by henopied** [comment]
Thank you!

**Comment by alexhultman** [comment]
If you get it working and deploy it somewhere I can reach I would like to test play it :smile:

**Comment by David1ali12** [comment]
thx my server so smooth now :+1:

**Comment by alexhultman** [comment]
Link?

**Comment by henopied** [comment]
You can play with: [vanilla agar.io client here](agar.io/?ip=146.185.132.74:443).

**Comment by alexhultman** [comment]
Rofl, the names. Yeah but it seems to work nicely. Is is smoother or is it just placebo?

**Comment by henopied** [comment]
Smoother than what?

**Comment by henopied** [comment]
Oh, it might be but I think the main difference is how many players can be on the same server without lag.

**Comment by alexhultman** [comment]
I think you will need to stress it some more yep. Also, if you run physics maybe that is the bottleneck.

**Comment by henopied** [comment]
The creator of multiogar said about 20% of the cpu usage was websocket and 70% was physics, but I could imagine how that would change as you get more connections.

**Comment by acydwarp** [comment]
uws is a lot more CPU efficient compared to ws, no doubt about it. I will try to get some proper benchmarks running the game and share them. Would make for a nice success story. Thanks for the swift commits!

**Comment by alexhultman** [comment]
@henopied You should disable permessage-deflate. It's currently enabled and not something you want in a game server. It will get a massive boost in perf if you pass perMessageDeflate: false as a server option.

**Comment by David1ali12** [comment]
I have tested uws my server on c9.io 75 players no lag with ws 50 players laggy abit
my server link:http://agar.io/?ip=siri-server-serverps.c9users.io
