### ISSUE TITLE
Server option pingInterval

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#191]
I can't find any automatic ping/timeout support in ws? To properly track disconnections you need to ping and this is very inefficient from the JavaScript interface (you need to keep a vector of all the sockets and iterate over them and keep track of timeouts and remove/add to this vector which is all very inefficient).

pingInterval could be a simple integer option you pass, pingInterval: 10000 will disconnect any client not sending a pong within 10 seconds from getting a ping.

Does a similar thing exist in ws? Would this feature be helpful? I could use the optimized broadcast internally to broadcast the ping in a much more efficient way than possible with the JavaScript interface.

**Comment by SEAPUNK** [comment]
IIRC, in the ws module, the pings have to be manual, for some reason.

Also, it might be a good idea to automatically pong on ping (if it already doesn't exist), emitting a "ping" event.

The feature would definitely be useful.

**Comment by FlorianBELLAZOUZ** [comment]
https://github.com/websockets/ws/pull/635

**Comment by sanderploegsma** [comment]
> Also, it might be a good idea to automatically pong on ping from the client (if it already doesn't exist), emitting a "ping" event.

NB: This is already implemented (I actually proposed a PR for the 'ping' event). When the server receives a ping, it'll automatically send back a 'pong'.

**Comment by sanderploegsma** [comment]
By the way, handling client pings from the native server may reduce a lot of overhead, although I think that most users (me anyway) still have to keep track of connections anyway. Otherwise, there would be no way of sending a client something, would there?
