### ISSUE TITLE
SSL_accept blocks

### ISSUE THREAD

**Issue by chemhack** [uWebSockets/uWebSockets#193]
In `Server::acceptHandler`, `SSL_accept` is used to perform SSL handshake, however this function call is blocking by default, result in very low server performance in real network environments.

**Comment by alexhultman** [comment]
You can solve it by moving uv_poll_init_socket out from HTTPSocket contructor into Server.cpp below accept and swap the clientFd == -1 check with if (uv_poll_init_socket(...)) to make it cross-platform. uv_poll_init_socket sets the socket to non-blocking. The rest should work automatically.

**Comment by alexhultman** [comment]
I also see that SSL_ERROR_WANT_WRITE is not properly handeled, it needs to poll for writable and readable when this error is received.

**Comment by alexhultman** [comment]
3922bae15752368f261005606bc7c2331a3f1ecb

**Comment by alexhultman** [comment]
An even better solution is to simply call SSL_set_accept_state() on the SSL instead of SSL_accept. Then OpenSSL will automatically handle any accept under the hood via first SSL_read, making it very convenient.
