### ISSUE TITLE
Close connection when maximum payload size is exceeded

### ISSUE THREAD

**Issue by lpinca** [uWebSockets/uWebSockets#196]
Right now if a message larger than the maximum allowed size is received on the server, that message is simply truncated to `maxPayload` bytes and handled as it was a valid message.
```js
'use strict';

const WebSocket = require('ws');
const http = require('http');
const uws = require('uws');

const server = http.createServer();
const wss = new uws.Server({
  perMessageDeflate: false,
  maxPayload: 5,
  server
});

wss.on('connection', (ws) => {
  ws.on('message', (msg) => {
    console.log(msg);
    throw new Error('Fail');
  });
});

server.listen(3000, () => {
  const ws = new WebSocket('ws://localhost:3000');
  ws.on('close', () => console.log('close'));
  ws.on('open', () => ws.send('abcdef'));
});
```
This is inconsistent with other WebSocket implementations like `ws` or `faye-websocket` where:

- The `onmessage` handler is not called with truncated data.
- The `onerror` handler is called with an error.
- The connection is closed with a specific close code (1009).

**Comment by lpinca** [comment]
@alexhultman any comment here?
It is partially a blocker for https://github.com/primus/primus/pull/477 as I would like to avoid using a custom test only for uws.

**Comment by alexhultman** [comment]
I could do this, seems reasonable. But it's not a top priority right this instant.
