### ISSUE TITLE
perf issue in  'ws'  "drop-in

### ISSUE THREAD

**Issue by socmag** [uWebSockets/uWebSockets#198]
Hey, thanks for working on improving ws performance.

I realize this is a micro-benchmark, but it w

**Comment by alexhultman** [comment]
What are you talking about?

**Comment by socmag** [comment]
Wtf, I haven't even posted the issue yet!  How are you even seeing this?

**Comment by SEAPUNK** [comment]
You posted the issue.

**Comment by socmag** [comment]
No I didn't. I literally just posted it this second!

Weird...

**Comment by SEAPUNK** [comment]
https://github.com/uWebSockets/uWebSockets/issues/198

**Comment by socmag** [comment]
Yeah I know exactly what you are talking about. I'm just saying, I started
receiving feedback from you before I even hit the Post button. I was stool
in the middle of editing it!

Very strange.

Anyway ... Posted now in complete form.
