### ISSUE TITLE
C binding (unlocks Swift binding)

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#200]
I'm working on a C binding that other bindings can build upon (hello Swift?). It is an opaque binding with indirection to every call but initial benchmarkings shows pretty much zero overhead.

The C binding will be a separate project just like the nodejs binding, under a separate folder. It will only contain one header file and one .cpp file.

This is what I have currently, feel free to PR / help out: https://github.com/uWebSockets/uws_c

**Comment by tsl0922** [comment]
Any update for this?

**Comment by alexhultman** [comment]
I talked with the devs of Perfect and they are not using libuv so it wouldn't just be as simple as creating a C binding and be done with it. You also need to spend time integrating it with their HTTP servers and such.
