### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by nagalun** [uWebSockets/uWebSockets#201]
Hi, I'm getting massive memory usage when connecting more clients than the maximum number of open files (ulimit -n) (1024 by default).
These are the steps to reproduce:
Compile the uWS.cpp and throughput.cpp in the benchmark folder
Run the uWS server, then connect more than (ulimit -n) clients with the throughput tool.
Watch as the 'Connections:' counter gets stuck (memory still normal)
Now connect another client, I did this with chrome:
u = new WebSocket("ws://localhost:3000");
Memory usage should start to increase very quickly.

I'm using the v0.7.8/v0.7.9 release and GCC 5.4.0

**Comment by alexhultman** [comment]
What OS is this on?

**Comment by alexhultman** [comment]
Obviously this is Linux, I need to sleep.

**Comment by alexhultman** [comment]
Well this is kind of obvious. Just look in Server.cpp, Server::acceptHandler. I return when accept fail after allocating a new uv_poll_t. So this will just loop forever. That return should be something else.

**Comment by alexhultman** [comment]
This diff fixes the memory leak, I will apply it after finishing up merging the client support. You could apply this yourself in the mean time.
```
diff --git a/src/Server.cpp b/src/Server.cpp
index c848450..114d284 100644
--- a/src/Server.cpp
+++ b/src/Server.cpp
@@ -37,9 +37,8 @@ void Server::acceptHandler(uv_poll_t *p, int status, int events)
     socklen_t listenAddrLength = sizeof(sockaddr_in);
     uv_os_sock_t serverFd;
     uv_fileno((uv_handle_t *) p, (uv_os_fd_t *) &serverFd);
-    uv_poll_t *clientPoll = new uv_poll_t;
     uv_os_sock_t clientFd = accept(serverFd, (sockaddr *) &server->listenAddr, &listenAddrLength);
-    if (uv_poll_init_socket(server->loop, clientPoll, clientFd)) {
+    if (clientFd == INVALID_SOCKET) {
         return;
     }
 
@@ -54,6 +53,8 @@ void Server::acceptHandler(uv_poll_t *p, int status, int events)
         SSL_set_accept_state((SSL *) ssl);
     }
 
+    uv_poll_t *clientPoll = new uv_poll_t;
+    uv_poll_init_socket(server->loop, clientPoll, clientFd);
     new HTTPSocket(clientPoll, server, ssl);
 }
```

**Comment by nagalun** [comment]
Awesome, it works. Thanks.
