### ISSUE TITLE
undefined reference to `uv_fileno'

### ISSUE THREAD

**Issue by Dimon4eg** [uWebSockets/uWebSockets#202]
Hi,

I tried to compile uWebSockets-v0.7.9 and receive linker error:
uwebsockets $ make
[ 63%] Built target uWS
[ 72%] Linking CXX executable multithreaded_echo
../libuWS.so: undefined reference to `uv_fileno'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/multithreaded_echo] Error 1
make[1]: *** [examples/CMakeFiles/multithreaded_echo.dir/all] Error 2
make: *** [all] Error 2

My system is Linux Mint 17.3.
libuv-v1.9.1

**Comment by alexhultman** [comment]
uv_fileno was added in libuv 1.0.0

**Comment by Dimon4eg** [comment]
I use libuv-v1.9.1

**Comment by Dimon4eg** [comment]
OK, thanks

**Comment by alexhultman** [comment]
I just built it with libuv 1.9.1 without any issues. You haven't properly installed your libuv.
