### ISSUE TITLE
compile error with Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by liketemple** [uWebSockets/uWebSockets#203]
on OSX:
#cmake .
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.dylib;/usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib (found version "1.0.2d") 
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mac/gitsrc/uWebSockets

#make

[  7%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.o
[ 15%] Building CXX object CMakeFiles/uWS.dir/src/HTTPSocket.cpp.o
[ 23%] Building CXX object CMakeFiles/uWS.dir/src/Network.cpp.o
[ 30%] Building CXX object CMakeFiles/uWS.dir/src/Server.cpp.o
[ 38%] Building CXX object CMakeFiles/uWS.dir/src/UTF8.cpp.o
[ 46%] Building CXX object CMakeFiles/uWS.dir/src/WebSocket.cpp.o
[ 53%] Building CXX object CMakeFiles/uWS.dir/src/EventSystem.cpp.o
[ 61%] Building CXX object CMakeFiles/uWS.dir/src/Agent.cpp.o
[ 69%] Linking CXX shared library libuWS.dylib
Undefined symbols for architecture x86_64:
  "uWS::WebSocket<0>::sendPrepared(uWS::WebSocket<0>::PreparedMessage*)", referenced from:
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
  "uWS::WebSocket<0>::prepareMessage(char*, unsigned long, uWS::OpCode, bool)", referenced from:
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
  "uWS::WebSocket<0>::finalizeMessage(uWS::WebSocket<0>::PreparedMessage*)", referenced from:
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
  "uWS::WebSocket<0>::link(uv_poll_s*)", referenced from:
      uWS::Server::upgradeHandler(uWS::Server*) in Server.cpp.o
  "uWS::WebSocket<0>::next()", referenced from:
      uWS::Server::closeHandler(uWS::Server*) in Server.cpp.o
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
  "uWS::WebSocket<0>::close(bool, unsigned short, char*, unsigned long)", referenced from:
      uWS::Server::closeHandler(uWS::Server*) in Server.cpp.o
  "uWS::WebSocket<0>::write(char*, unsigned long, bool, void (*)(uWS::WebSocket<0>, void*, bool), void*, bool)", referenced from:
      uWS::Server::upgradeHandler(uWS::Server*) in Server.cpp.o
  "uWS::WebSocket<0>::initPoll(uWS::Server*, int, void*, void*)", referenced from:
      uWS::Server::upgradeHandler(uWS::Server*) in Server.cpp.o
  "uWS::WebSocket<0>::WebSocket(uv_poll_s*)", referenced from:
      uWS::Server::upgradeHandler(uWS::Server*) in Server.cpp.o
      uWS::Server::closeHandler(uWS::Server*) in Server.cpp.o
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
  "uWS::WebSocket<0>::operator bool()", referenced from:
      uWS::Server::closeHandler(uWS::Server*) in Server.cpp.o
      uWS::Server::broadcast(char*, unsigned long, uWS::OpCode) in Server.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libuWS.dylib] Error 1
make[1]: *** [CMakeFiles/uWS.dir/all] Error 2
make: *** [all] Error 2

**Comment by liketemple** [comment]
I also tried cmake . -DCMAKE_OSX_ARCHITECTURES=x86_64, nothing changed.

**Comment by alexhultman** [comment]
You should reset to a tag

**Comment by liketemple** [comment]
Sure, I reset to 1f3c3123a57ba8ea770dd8af1cd9a5ba0343bc07:
Fix leak on ERR_LISTEN. Now the uWS library is OK to compile.
But, I found the example won't compile since introduce the EventSystem.

**Comment by alexhultman** [comment]
The latest tag ("release") is 0.7.8/0.7.9. You need to reset to thos latest tag, or download the released version tarball. Master is a bit messed up right now.

**Comment by liketemple** [comment]
Thanks a lot !
