### ISSUE TITLE
Add `server.clients` property

### ISSUE THREAD

**Issue by kripod** [uWebSockets/uWebSockets#205]
See https://github.com/websockets/ws#server-sending-broadcast-data for further information.

**Comment by alexhultman** [comment]
Broadcast is already implemented out of the box in uws.

The clients array is a tricky thing to implement since we don't use an array to keep track of added and removed clients. As you might understand, an array is the worst kind of data type for tracking a set of nodes that gets added and removed in any order all the time. This is why we use a doubly linked list instead. I want to implement a way of traversing this link from JS land but currently this is not done. You will need to build your own container of sockets the way you want it.

**Comment by kripod** [comment]
Thank you for your response, I didn't know that broadcast was implemented out of the box.

**Comment by alexhultman** [comment]
The broadcast in uws is optimized to format the message (including compression if possible) once and then reuse this buffer for all sends and then remove the buffer when the last send finished. This is also something you can use via the extensions prepareMessage, finalizeMessage, sendPrepared to boost performance in a pub/sub set-up.

I guess I should implement the server.clients.forEach function as some kind of spoof that simply lifts the function over the linked list. That is probably the closest I can get to the ws interface.

**Comment by kripod** [comment]
That would be awesome! I'm currently building my own lightweight socket framework, and currently using a `Set` to keep connected clients in. Groups of clients can also be made, and messages could be sent to all by iterating through the set of clients.

**Comment by alexhultman** [comment]
If you want to go nuts you could use the native addon straight up just like Primus does. You can see how they do in their uws transformer sources. A socket is just a 64-bit Number in that interface so you can easily scale to 1 million connections with like 300 mb of ram usage then (excluding kernel space). This in comparison with 2 GB that the ws interface requires.

**Comment by kripod** [comment]
Thanks for the tip, I'll try to stay with JS, though. The goal is to keep the framework's entire source code below 300 CLOC by leveraging the magnificent features of ES6+, while providing browser and middleware compatibility.

**Comment by alexhultman** [comment]
Sure but the "native addon" is exposed as a set of JS functions, so it would still be JS, only a little more C-like.

**Comment by lpinca** [comment]
@kripod a `Set` makes perfect sense, delete complexity is sublinear per spec.

**Comment by alexhultman** [comment]
Hehe, it's far better than splicing an Array like ws does. That shit is linear in time with the amount of sockets and most definitely leaves huge amounts of garbage the GC needs to collect. A doubly linked list is constant in time though and doesn't require any extra allocation.

**Comment by lpinca** [comment]
`Set` has been added with ES6 so it wasn't available when `ws` was written.
I agree that using an array is not the best option but in `ws` you can set the `clientTracking` option to `false` and it will not keep the sockets in the array. It will be up to you how to handle them.

**Comment by alexhultman** [comment]
Ah, so that's what that option does!

**Comment by kripod** [comment]
By the way, here is my little framework I was talking about: https://github.com/kripod/wsx

Sorry for the self-promotion, I thought it was a good idea to share the project here.

**Comment by kripod** [comment]
@alexhultman Could you implement performant Socket.IO-like broadcast functionality? (Send to everyone except the client who is used for broadcasting)

**Comment by kripod** [comment]
I think I optimized wsx's [`Server#bulkSend`](https://github.com/kripod/wsx/blob/6074f24ea729190cff777b90a94b1f4da4771a5b/src/server/server.js#L161-L177) method as much as possible, resulting in performance improvements for [`ServerSideSocket#broadcast`](https://github.com/kripod/wsx/blob/6074f24ea729190cff777b90a94b1f4da4771a5b/src/server/server.js#L87-L101) and [`SocketGroup#send`](https://github.com/kripod/wsx/blob/6074f24ea729190cff777b90a94b1f4da4771a5b/src/server/socket-group.js#L54-L61).

@alexhultman Please tell me if there are any more performance improvements I could do. I'll also try to lower network throughput while keeping the flexibility of JSON by creating a [MsgPack](https://github.com/kawanet/msgpack-lite) message serialization plugin for wsx. :blush:

**Comment by alexhultman** [comment]
It that bulkSend looks nice. Did you benchmark it?

**Comment by socmag** [comment]
Bulk send? I'd love to know too... send is dominating my server right now

**Comment by alexhultman** [comment]
If you send an identical message to multiple recipients you should use prepareMessage, sendPrepared & finalizeMessage.

**Comment by socmag** [comment]
Oh yum

**Comment by kripod** [comment]
@alexhultman I don't have a benchmark suite for wsx to date, it's a pretty young project. But whether the userbase gets large enough, I may make one.

**Comment by JoshuaWise** [comment]
I see two good options:
- Using a JS Set (https://v8docs.nodesource.com/node-6.0/d2/d5e/classv8_1_1_set.html)
- Using a doubly linked list (or other non-V8 container), and exposing a `.forEach` method

**Comment by blakelapierre** [comment]
Is there anything that tracks the number of clients connected ("`server.clients.length`")?

Perhaps `Group`s could keep a count of the total number of items?

**Comment by alexhultman** [comment]
Nope, you need to update that counter yourself.

**Comment by alexhultman** [comment]
But you could try and expose an Array-like interface by implementing server.clients.forEach, and also implement server.clients.length. But this is not done yet, should be done at some point.

**Comment by alexhultman** [comment]
Is this correct?

```javascript
    get clients() {
        return {
            length: native.server.group.getSize(),
            forEach: native.server.group.forEach.bind(this.serverGroup)
        };
    }
```

where native.server.group.forEach takes a group pointer and a function as callback

**Comment by SEAPUNK** [comment]
Can you make it an iterable, so people can iterate through it via `for...of`, as well as giving people the ability to convert it to an array w/ `Array.from`?

**Comment by alexhultman** [comment]
You can do that yourself, you have write access :wink:

**Comment by SEAPUNK** [comment]
Haha, alright. I'll look into it.
