### ISSUE TITLE
websocket.terminate() is not defined as available in node "ws" library

### ISSUE THREAD

**Issue by chintan39** [uWebSockets/uWebSockets#206]
there is an incompatibility with "ws" library.
below defined method is not found

**websocket.terminate() - Immediately shuts down the connection**

**Comment by alexhultman** [comment]
When would you need this? The close is graceful but will force close after 15 seconds of no response so terminate could pretty much just wrap close, right?

**Comment by chintan39** [comment]
Closing the connection goes into "close" event.
Which we don't require in our case.
Just terminate the connection immediately.

**Comment by ronkorving** [comment]
Can be useful when dealing with heavy load or DOS scenarios.
