### ISSUE TITLE
Connection hanging with SSL

### ISSUE THREAD

**Issue by christopherhenard** [uWebSockets/uWebSockets#208]
Hi,

With release v0.7.8/v0.7.9, I cannot make the server work with SSL.

When I try to connect a client with `wss://localhost:3000` it just seems to hang up. 
It works with `ws://localhost:3000`. Same problem on a distant machine.

I created the uWS::SSLContext with the certificate and key and passed it to the  uWS::Server constructor.
The certificate and key have been generated with this command:
` openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 100`
When I launch the server I'm asked to enter the PEM pass phrase.

I tried to see what happens and noticed that this branch
`if (server->sslContext) {
        ssl = server->sslContext.newSSL(clientFd);
        SSL_set_accept_state((SSL *) ssl);
 }`

in `Server::acceptHandler`  (line 52 in `Server.cpp`) is never reached.

Am I missing something?

**Comment by alexhultman** [comment]
How does your code look like and does you browser / client accept your certificate? Do you pass the SSLContext to Server constructor?

**Comment by christopherhenard** [comment]
The code is the `echo.cpp` example provided. I have added this line:
`SSLContext sslContext("cert.pem", "key.pem");`

and I changed the call to the Server constructor to take the ssl context as parameter:
`Server server(3000, true, PERMESSAGE_DEFLATE, sslContext);`

For the client I tried Firefox (importing the certificates in the preferences), the `thor` benchmarking/load generator tool and the example client from libwebsockets. 
I'm not sure but I think that the server doesn't send the certificate to the client to be able to accept it.

**Comment by alexhultman** [comment]
You are passing SSLContext as maxPayload argument. SSLContext has a bool operator so it converts to bool which is fine for int:
```c++
Server(int port = 0, bool master = true, unsigned int options = 0, unsigned int maxPayload = 1048576, SSLContext sslContext = SSLContext());
```

I tried it here, it's pretty cool OpenSSL asks for password just like that.

**Comment by jimmyt857** [comment]
I think it would be cleaner to move towards a single struct containing all of the options, which would have the side benefit of eliminating any of the confusion here.

**Comment by alexhultman** [comment]
Yep some kind of better way of passing options, something like:

Server(
port(3000),
maxPayload(123123123),
ssl("cert.pem", "key.pem"),
);

where you can pass them in any order?

**Comment by socmag** [comment]
Oh, while you guys are on the topic of SSL.  I haven't got to that yet, but
I thought I noticed that you are passing file names for the very and key
files.

I haven't checked, but is there any way for the app to pass the data. The
reason is they might not be coming from a file.

**Comment by alexhultman** [comment]
Yes but that is not implemented yet, but it is super easy to add. Just add a new constructor to SSLContext that takes char * and size_t. The idea is to extend SSLContext with a lot of different constructors for different needs.

**Comment by socmag** [comment]
Okay cool, sounds good. (y)
