### ISSUE TITLE
Subprotocol support

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#209]
The server should respond to Sec-WebSocket-Protocol and pass the protocol string to onConnect to allow different handling of different protocols.

Or solve it in any other way.

**Comment by arpu** [comment]
any news on this? 
Sec-WebSocket-Protocol:null

is not send as response 
node ws
Connection:Upgrade
Sec-WebSocket-Accept:ck8Nlo55jMwOLrVjuKm5bJD+d9Y=
Sec-WebSocket-Extensions:permessage-deflate
Sec-WebSocket-Protocol:null
Upgrade:websocket


uws
Connection:Upgrade
Sec-WebSocket-Accept:XzQ5qiMoOTkhT+0XHdZ3h2YjPDk=
Sec-WebSocket-Extensions:permessage-deflate; server_no_context_takeover; client_no_context_takeover
Server:uWebSockets
Upgrade:websocke

Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

**Comment by alexhultman** [comment]
I can do new features after the next release. Next release will focus on client/server support and is planned for 1st October.

You can achieve multiple protocols currently by having the fist sent message be the protocol to use, and then add this to your socket data. Let the connection event attach a struct with an enum describing what protocol this socket is using, and have it be UNDECIDED at first. Then you dispatch the message using the correct function ptr:

onConnection -> attach data with protocol = UNDECIDED

onMessage -> handle message with messageHandler[protocol]

where messageProtocol[UNDECIDED] is something like:

if (message is "some protocol") {
socketData->protocol = SOME_PROTOCOL;
} else {
socket.close();
}

and messageHandler[SOME_PROTOCOL] is where you handle your protocol specific stuff.

This is the same way you would have to handle it anyways, the only difference would be that you get to know the protocol at connection instead of at first message.

**Comment by arputcu** [comment]
sorry i do not understand all this :/ 
i only test uws in our node server and dedect that uws do not send the 
Sec-WebSocket-Protocol:null  and all clients disconnect

**Comment by arpu** [comment]
sorry i do not understand all this :/ 
i only test uws in our node server and dedect that uws do not send the 
Sec-WebSocket-Protocol:null  and all clients disconnect

**Comment by alexhultman** [comment]
#264
