### ISSUE TITLE
SSL via BoringSSL?

### ISSUE THREAD

**Issue by socmag** [uWebSockets/uWebSockets#212]
Just a thought, but was wondering if this might be a better direction for uWebSockets.

It's much lighter weight, and higher performance than OpenSSL (using thread-local storage, and avoiding some nasty mutex's)... 

In short, more in-line with the uWebSockets

https://www.imperialviolet.org/2015/10/17/boringssl.html
[https://boringssl.googlesource.com/boringssl/+/HEAD/INCORPORATING.md](url)

**Comment by AlexVK79** [comment]
uWebSockets actually compile and works just fine with BoringSSL (just a few changes in cmakelists.txt)

**Comment by socmag** [comment]
Great (y)

On Aug 12, 2016 2:49 PM, "AlexVK79" <notifications@github.com> wrote:
>
> uWebSockets actually compile and works just fine with BoringSSL (just a
few changes in cmakelists.txt)

**Comment by alexhultman** [comment]
That's cool, we could have some flag to change the implementation. I don't mind having BoringSSL by default when building the C++ stand-alone server but we need OpenSSL when building the Node.js addon since Node.js makes use of OpenSSL.

**Comment by socmag** [comment]
Right, okay that makes sense.
