### ISSUE TITLE
Server ignores pre-sent messages

### ISSUE THREAD

**Issue by jimmyt857** [uWebSockets/uWebSockets#213]
When a client sends a message immediately following the initial handshake, in anticipation of getting a successful reply, the server will drop the message. This is because HttpSocket throws out any bytes after the '\r\n\r\n' instead of passing the remainder along to the socket.

This issue is not part of the websocket protocol, and I think clients are supposed to wait for the reply before sending their first message. I only found this because I tried running an old client I wrote awhile ago when I needed something quick. However, you might want to at least throw an error when there are extra bytes instead of silently ignoring the data.

**Comment by alexhultman** [comment]
I haven't had any issue with any browser but yes, it should push any pre-sent data to the parser.

**Comment by jimmyt857** [comment]
I went back and looked at the websocket standard, and it explicitly states that clients should not send data before receiving the handshake reply.

**Comment by alexhultman** [comment]
That's nice, I guess we just close this then.
