### ISSUE TITLE
HTTPSocket.obj : error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by azharuniverse** [uWebSockets/uWebSockets#214]
HTTPSocket.obj : error LNK2001: unresolved external symbol _SSL_free [C:\Projects\MyProject\node_modules\uws\build\uw
s.vcxproj]
HTTPSocket.obj : error LNK2001: unresolved external symbol _SSL_read [C:\Projects\MyProject\node_modules\uws\build\uw
s.vcxproj]
HTTPSocket.obj : error LNK2001: unresolved external symbol _SSL_get_error [C:\Projects\MyProject\node_modules\uws\bui
ld\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_new [C:\Projects\MyProject\node_modules\uws\build\uws.vcx
proj]
Server.obj : error LNK2001: unresolved external symbol _SSL_CTX_free [C:\Projects\MyProject\node_modules\uws\build\uw
s.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_CTX_ctrl [C:\Projects\MyProject\node_modules\uws\build\uw
s.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_library_init [C:\Projects\MyProject\node_modules\uws\buil
d\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _EVP_cleanup [C:\Projects\MyProject\node_modules\uws\build\uws
.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_CTX_new [C:\Projects\MyProject\node_modules\uws\build\uws
.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_ctrl [C:\Projects\MyProject\node_modules\uws\build\uws.vc
xproj]
Server.obj : error LNK2001: unresolved external symbol _SHA1 [C:\Projects\MyProject\node_modules\uws\build\uws.vcxpro
j]
Server.obj : error LNK2001: unresolved external symbol _SSLv23_server_method [C:\Projects\MyProject\node_modules\uws\
build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol _SSL_set_accept_state [C:\Projects\MyProject\node_modules\uws\
build\uws.vcxproj]
WebSocket.obj : error LNK2001: unresolved external symbol _SSL_write [C:\Projects\MyProject\node_modules\uws\build\uw
s.vcxproj]
WebSocket.obj : error LNK2001: unresolved external symbol _SSL_shutdown [C:\Projects\MyProject\node_modules\uws\build
\uws.vcxproj]
C:\Projects\MyProject\node_modules\uws\build\Release\uws.node : fatal error LNK1120: 15 unresolved externals [C:\Proj
ects\MyProject\node_modules\uws\build\uws.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yyyyy\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--openssl-root=C:\\Users\\yyyyy\\Downloads\\openssl-1.0.2d-fips-2.0.10\\openssl-1.0.2d-fips-2.0.10\\bin" "--python=C:\\Users\\yyyyyy\\.windows-build-tools\\python27\\python.exe"
gyp ERR! cwd C:\Projects\xxxxxxxx\node_modules\uws
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by alexhultman** [comment]
You need Node.js 6.3.1+ to run µWS 0.7.9 on Windows, and you will need Node.js 6.4.0+ to run 0.8.0 on Windows.

**Comment by azharuniverse** [comment]
Thanks @alexhultman  it worked. I just updated nodejs and changed  'cp' to 'copy' in binding.gyp action.
I am so stupid wasted hour just on this.

**Comment by alexhultman** [comment]
Ah, so "cp" doesn't work on Windows, that's a shame. But it should still work with the pre-compiled binary shipped with the module.
