### ISSUE TITLE
no uws.clients ?

### ISSUE THREAD

**Issue by budinschi** [uWebSockets/uWebSockets#217]
since uws is following the wss usage and structure.. I assumed uws.clients is an array of connected clients, like wss has. I was wrong.
https://github.com/websockets/ws#server-sending-broadcast-data

**Comment by alexhultman** [comment]
#205

**Comment by budinschi** [comment]
Thank you for the reference.. but its not enough. How would I send a message to a specific set of clients ? I have them grouped, only receiving specific data per group

**Comment by SEAPUNK** [comment]
Keep track of the list yourself, for now. Put them in a Map, or something.

**Comment by budinschi** [comment]
Got it. As a feature request.. it would be nice to be able to organize clients into channels / groups.. and broadcast data with a channel argument.

**Comment by alexhultman** [comment]
That's not even possible with `ws`. Any grouping is up to the user to maintain in both ws and uws. If you need a complete pub/sub solution there are many solutions available, SocketCluster being one that makes use of uws by default.

**Comment by budinschi** [comment]
I didn't said its possible with ws. I just mentioned because its a lack in both modules, and it would be a +for uws to have it, in order to take advantage of uws`s broadcasting performance. If I maintain my own set of clients .. there no use for broadcasting, just regular loop > send

**Comment by alexhultman** [comment]
Grouping is not part of this library, it exposes just enough to allow more abstract projects to implement stuff efficiently. Consider uws a minimal "websocket engine". SocketCluster does (or at least does plan to) use the speedy broadcasting features of uws so you don't need to worry about it.
