### ISSUE TITLE
adding support for meson build system

### ISSUE THREAD

**Issue by agauniyal** [uWebSockets/uWebSockets#218]
Would you mind adding support for [meson](https://github.com/mesonbuild/meson) build system, [probably](https://github.com/mesonbuild/meson/wiki/Adding%20new%20projects%20to%20wrapdb) through [wrapdb](https://wrapdb.mesonbuild.com/) which would make things a little bit easier for some of us.

**Comment by alexhultman** [comment]
Don't know what any of those projects are but you are free to make a PR if the change is nonobtrusive. I already have a QMake project and a CMake one so adding more is no problem. But you will have to PR it yourself.

**Comment by agauniyal** [comment]
I've opened a new PR #219 for it. Feel free to take a look and offer suggestions 😄
