### ISSUE TITLE
need help.client support ssl

### ISSUE THREAD

**Issue by karlcounter** [uWebSockets/uWebSockets#223]
hello,I am now use uWebSockets as a Server.it works very well.now I want to use uwebsocket client.but it does not support ssl.could you please add ssl support to client? thanks a lot.

**Comment by Barbosik** [comment]
the same question. With uws I get the following error:
```
WebSocket connection to 'wss://bubble-wars.tk:4445/' failed: WebSocket opening handshake was canceled
index.js:599 socket close: [1006] 
```
It works ok with ws module

**Comment by socmag** [comment]
I believe there is an open ticket about it, so I know Alex and Jimmy are
aware of it.

I'm not party to the plan, but I'm sure it's high pri.

**Comment by SEAPUNK** [comment]
Yes, it's still a work in progress.

https://github.com/uWebSockets/uWebSockets/issues/171#issuecomment-239505359

**Comment by alexhultman** [comment]
There is no client support merged yet

**Comment by alexhultman** [comment]
Client SSL is done in the rewrite

**Comment by MakanMakan83** [comment]
Using this example: https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/ssl.js

Still doesnt work for me ... when i use my self signed certification files with require("ws") everything works fine ... please help me !

**Comment by ad34** [comment]
up to date ssl sample in node.js : https://github.com/uNetworking/bindings/blob/master/nodejs/examples/ssl.js
