### ISSUE TITLE
WebSocket::send parameters

### ISSUE THREAD

**Issue by agauniyal** [uWebSockets/uWebSockets#225]
Shouldn't the 'message' in `void WebSocket::send(char *message...)` be of type `const char *` instead of `char *` here? Or is that function is allowed to modify the underlying chars passed to it?

I'm asking this because it would help using `std::string`'s `c_str()` method which returns a const. Otherwise I would've to manually allocate and free new `char*`s which I don't really want to do :/

**Comment by agauniyal** [comment]
If you're using either of `ssize_t write(int fd, const void *buf, size_t count);` or it's relative `send()` call under the hood, then it should be fine to use `const char *` unless you're trying to modify data in some way before sending it.

Here I'm using several of those calls with c++ string classes - https://gist.github.com/agauniyal/8c4fa7550f2581bf5dcc

**Comment by socmag** [comment]
Yes it sure should.

**Comment by alexhultman** [comment]
It should be const yes, but you can just cast it to char ptr.

**Comment by socmag** [comment]
Well we do, of course :-) is there a reason for not changing it?

**Comment by socmag** [comment]
It's a pain in the ass

**Comment by alexhultman** [comment]
No, you can PR it and I'll merge it.

**Comment by socmag** [comment]
Lol. Okay

**Comment by socmag** [comment]
You know what this means though. If I start issuing pull requests, going to
get medieval on the fucker.... Incoming :-)))

Well it will have to wait for tomorrow, I'm far too happy and smashed
tonight.

OTOH, I guess it is our responsibility to improve the thing, not just yours.

**Comment by agauniyal** [comment]
Duplicate of #226 hence closing.
