### ISSUE TITLE
Messages to send should be const char * not mutable char *

### ISSUE THREAD

**Issue by socmag** [uWebSockets/uWebSockets#226]
Currently send takes a char* for the buffer which is confusing to the user of the library since it implies that the API might change the buffer during the call; which is not the case as per the implementation.

Let's change it to const char *  so it is very clear that the API Is faithful to the semantics of the underlying socket send, and make everyone happy.

**Comment by agauniyal** [comment]
@socmag I guess you're working on this?

**Comment by agauniyal** [comment]
ping @socmag .

**Comment by agauniyal** [comment]
ping @socmag.

**Comment by socmag** [comment]
Sorry guys, I have a huge demo to give this week... I know I've gone dark,
apologies.

Unfortunately I'm not able to commit any time to PR's on uWS right now.
I've got bigger fish to fry getting this demo done.

Still carrying the torch for uWS though

**Comment by socmag** [comment]
Go for it :-)

**Comment by alexhultman** [comment]
All you need to change is make formatMessage take a const char *src, make send take const char * and same with ping.

**Comment by agauniyal** [comment]
can be closed now - #236

**Comment by alexhultman** [comment]
Thanks
