### ISSUE TITLE
Can we avoid malloc in send?

### ISSUE THREAD

**Issue by socmag** [uWebSockets/uWebSockets#227]
Currently, if the send channel is backed up for a client, uWebSockets allows buffers to queue pending sends.

That is totally reasonable, however we can do better. We can at least use a buffer pool so that a lock contentious allocation is generally avoided.

In addition, it might be possible to coalesce multiple sends at a higher level than NAGLE if we do this right. A batch send API should be doable.

It is not currently possible to do this on the application side as it stands since there is no way to let uWebSockets know there will be further sends on the way.

This probably isn't an issue for Node, where performance is already way better than ws, but it is an issue for higher performance C++ applications.

Worth investigating.

**Comment by alexhultman** [comment]
Yep you can do it far better but I haven't had malloc be an issue when profiling things. WebSockets are pretty low-perf compared to TCP anyways. If you use a memory pool you will trade perf for memory usage and you still need to perform the copy.

It would be nice to expose some kind of "ownership-transferring" send where you just pass it memory which is just straight up queued and never buffered.

**Comment by socmag** [comment]
I'm seeing malloc at 80% of my server load based on send traffic.

Here is the scenario. With thousands of clients, a single publisher can result in many listeners receiving messages.

Lots of pubs to a single address can trigger the mallocs on the clients.

Unfortunately, the messages transferred to each of the subscribing clients will be slightly different based on a header with a client specific subscription I'd.

Sucks to be me.

So unfortunately I can't use a genarilized batch scatter send API due to the slightly varying header.

The Windows NT kernel has the "SendPackets" primitive, but I don't know if there is anything similar to this in libuv? That would definitely help fix the thing..

Think implementing Pokemon Go here, but that's not precisely what I'm doing ofc.

**Comment by alexhultman** [comment]
The best would be to have identical messages sent to all clients. Doing lots of sends with varying data is not optimized for and I know SocketCluster publish identical data to all clients that subscribe to the same channel. Why would you need different data per client?

**Comment by ronkorving** [comment]
Why not use API to send multiple buffers in a single system call? Libuv supports it, as does every OS out there afaik.

**Comment by alexhultman** [comment]
What's the status on this? Is there something specific that you can put a finger on that is needed? Batch send is implemented, prepared send is implemented (which in a way allows to pre-allocate outside of send). @socmag

**Comment by socmag** [comment]
Sorry, not been paying attention too much, really busy here.  I can confirm that batch/prepared send works.
