### ISSUE TITLE
API to allow reads / writes from application buffers

### ISSUE THREAD

**Issue by socmag** [uWebSockets/uWebSockets#228]
The uWebSocket API is very user friendly for the 99% use case, and performs well for the general case.

That said, for even higher performance applications, it might be better if the application can provide the buffers into which the underlying socket will read into or write from, which would avoid copies.

Although this is not compatible with the ws API, it would be advantageous for higher performance apps, and in line with the IOCP model that libuv provides.

Rather than the user friendly API of onMessage for example, it would be better if the app could issue a read with its own buffer and a completion callback.  Same for write.

These application allocated buffers can have semantics that require the app to provide over allocation for framing etc. 

Lifetime should be controlled via the callback.

This is probably a non-trivial change, and definitely "niche", but would be in-keeping with the perf goals of the lib in general.

**Comment by alexhultman** [comment]
This is against the design of the (reactive) design of the lib. Sure, it can be better in some cases to directly write into application buffers but then you land in the land of terrible memory scalability (just like the rest of the libs). The reactive model is extremely good for memory scalability and has shown to (also) outperform other libs.
