### ISSUE TITLE
memory leak in Server::acceptHandler ?

### ISSUE THREAD

**Issue by KrishnaPG** [uWebSockets/uWebSockets#229]
At https://github.com/uWebSockets/uWebSockets/blob/master/src/Server.cpp#L58 ?

The ` new HTTPSocket` is potentially leaking the object

**Comment by alexhultman** [comment]
Yeah it looks weird but the object owns itself (it registers itself as part of the data of a uv_poll_t, which is owned by the loop, which will remove the poll and its data on timeout or close event).

**Comment by KrishnaPG** [comment]
Thank you @alexhultman Yes, the `HTTPSocket::onTimeout` has the delete call, as well the other methods.

**Comment by KrishnaPG** [comment]
Another quick question: [this line](https://github.com/uWebSockets/uWebSockets/blob/master/src/HTTPSocket.cpp#L118) has below code
````
length = recv(fd, httpData->server->recvBuffer, Server::LARGE_BUFFER_SIZE, 0);
````
Given that there is only sever object and multiple `HTTPSocket` client objects doing the `recv` at the same time, will this not result in multiple receives trying to read into same buffer?

**Comment by alexhultman** [comment]
All sockets share the same buffer but they use it at mutual exclusive times.

**Comment by KrishnaPG** [comment]
Thank you. Is that because of libUV being single-threaded or something else?

In other words, what is preventing two client objects from doing the `recv` at the same time? Is it because the application is inherently single threaded?

**Comment by KrishnaPG** [comment]
I guess it is because the app is doing polling and `recv` does not block.

**Comment by alexhultman** [comment]
The event loop is single threaded so only one recv can be executed at any given time (in one specific thread). When the data is received it is parsed and shown to the application and then disposed.
