### ISSUE TITLE
options to turn on TCP keepAlive

### ISSUE THREAD

**Issue by terrywh** [uWebSockets/uWebSockets#230]
as described in the title, can you add some options or methods for users to turn on TCP KeepAlive ?

**Comment by alexhultman** [comment]
Normally you use prings and pongs (because of the limitation of some proxies). You can enable keep-alive with setsockopt on the file descriptor though, if that works for you.

**Comment by terrywh** [comment]
i mean yes i can use setsockopt, but where can i get the socket handle? as far as i can tell, there no public interface to do just that.

**Comment by alexhultman** [comment]
You could add a function like:

uv_os_sock_t WebSocket::getNativeHandle() {
uv_os_sock_t handle;
uv_fileno((uv_handle_t *) p, (uv_os_fd_t *) &handle);
return handle;
}

**Comment by terrywh** [comment]
thanks. i'll try that, and try to implement using `ping()`
