### ISSUE TITLE
Streaming files with uWebsockets causes broken data

### ISSUE THREAD

**Issue by tresdin** [uWebSockets/uWebSockets#231]
I've tried uploading some files via `WebSocket`. Basically, I just slice those files into chunks of data then simultaneously send them  via `WebSocket`. And here are the results on `uws` and `ws` respectively.

**uws**

![1-8x-5](https://cloud.githubusercontent.com/assets/7781091/18085378/1dd9dcb4-6ed5-11e6-8b28-e77074d8e8aa.jpg)
![1-8x-2](https://cloud.githubusercontent.com/assets/7781091/18085377/1dd87626-6ed5-11e6-90c5-6a50848c895b.jpg)
![1-8x-8](https://cloud.githubusercontent.com/assets/7781091/18085379/1ddadb14-6ed5-11e6-8257-f2b86a1aead4.jpg)

**ws**

![1-8y-2](https://cloud.githubusercontent.com/assets/7781091/18085432/5f3392d6-6ed5-11e6-9c10-f6687176f684.jpg)
![1-8y-5](https://cloud.githubusercontent.com/assets/7781091/18085433/5f35de88-6ed5-11e6-8c9f-e2cc86281747.jpg)
![1-8w-5](https://cloud.githubusercontent.com/assets/7781091/18085431/5f02c052-6ed5-11e6-9366-3e4567eccdfc.jpg)

**Source**

![phone-wallpapers-hd-android-4](https://cloud.githubusercontent.com/assets/7781091/18085327/ec5b519a-6ed4-11e6-90a4-02845c5fa04e.jpg)
![dna_nano_tech-wide](https://cloud.githubusercontent.com/assets/7781091/18085328/ec5d1462-6ed4-11e6-9145-228fa2080967.jpg)
![marvellous-forza-motorsport-5-hd-desktop-wallpaper-wallpaper-hd](https://cloud.githubusercontent.com/assets/7781091/18085329/ec672100-6ed4-11e6-874d-bd9233bd8b6a.jpg)

As you can see from the results, those files sent via `uws` are broken. I initially think that this bug was caused by the app code. However, after spending hours on debugging the code and still having no paticular result, I decided to switch the websocket server to the `ws` module. The error was surprisingly gone.

**Comment by alexhultman** [comment]
You will need to copy the Node.js buffer from the callback. uws gives you references to a shared buffer while ws probably gives you a copy of a copy of a copy of a copy of the original data. My point is, we use zero-copy through the entire library so you are probably hitting an inconsistency with the ws interface.

**Comment by tresdin** [comment]
@alexhultman I've applied the fix and the error is gone. Thank you.

I strongly second your point. This single point is enough for making `uws` superior to `ws` in term of memory management. As a result, in my case, streaming 2.5MB file with `ws` requires approximately 13MB total heap size, while this number is insignificant with `uws`.

I also think that it should be the default approach for buffer handling. Most of the times, buffers should be viewed, not copied.
.
