### ISSUE TITLE
Rewrite #2

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#233]
I'm currently working on a rewrite of the lib. The early versions of the lib were one single source file with dependencies all over. Then I refactored it / rewrote it into multiple source files with a little more control of the dependencies. But still, there are some crazy dependencies between different parts of the lib that needs to be solved.

* Parser should be free of dependencies, allow unit-testing
* All networking / SSL should be in its own stand-alone lib and reused by HTTP and WebSocket

With this rewrite I will be looking to support client/server WebSocket and also HTTP serving (basic).

The parser is already done, it passes Autobahn as both client and server and is completely separate from any other part. The networking is something I'm working on separately.

**Comment by agauniyal** [comment]
HTTP serving via cpp?

**Comment by alexhultman** [comment]
Obviously you cannot have identical interface if the rewrite is a client/server and the original is only server.

**Comment by socmag** [comment]
This sounds great, and basic HTTP serving on the same socket would be
awesome. Actually it would also be great if you could just throw up a
raw TCP server as well if that happened to drop out of the rewrite, so we
could roll our own protocol on the same base layer.

Good stuff!

**Comment by agauniyal** [comment]
Ofcourse I know that 😆 , I was talking about the existing api with which we're familiar.

**Comment by alexhultman** [comment]
The rewrite is brewing and is currently outperforming the original: 4100 echoes/ms vs. 4700 echoes/ms for my particular test.

**Comment by socmag** [comment]
Nice :-)... Hey, saw your mention on HN by the way.  Very cool!

**Comment by alexhultman** [comment]
What mention? How do I see mentions?

**Comment by agauniyal** [comment]
Probably this - https://news.ycombinator.com/item?id=12547279

**Comment by alexhultman** [comment]
Well, seems the rewrite is able to get 5200 echoes/ms while the original is stuck at 4300 echoes/ms. Don't know why but I guess it's good news -> that's pretty significant.

**Comment by socmag** [comment]
Uhhuh :-)

**Comment by alexhultman** [comment]
I just wrapped the Node.js part up and tested the client support - works great, does not add any memory or throughput overhead. I only have a few items left on my todo list then I'll release this.
