### ISSUE TITLE
ws "close" event: code is always 0

### ISSUE THREAD

**Issue by silverwind** [uWebSockets/uWebSockets#235]
The `'close'` event of `ws` seems to always emit closeCode `0` when a socket is closed. For example, I expect a `1000` code when a browser closes the tab.

**Comment by alexhultman** [comment]
I just tested this and the behavior is that you get closeCode = 0 and message = '' when getting a close frame without anything specified. If you connect with a client and close with a code and message you will receive this. So if you want you could add some kind of filtering like if (!closeCode) { closeCode = 1000; } but more than that is not needed.

**Comment by alexhultman** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/uws.js#L398

This could be `code ? code : 1000` instead of `code`.

**Comment by silverwind** [comment]
I noticed this because `ws` was returning 1000, but if I interpret https://github.com/websockets/ws/blob/4167e5c7997633334fed5ba270567687d4b0b8ce/lib/Receiver.js#L644 correctly, that may just be manually set and not part of the close frame after all. I'll check it out in Wireshark.

**Comment by alexhultman** [comment]
Yeah it's manually set. A close frame has no code by default. So that's kind of an interpretation. I did fix it now so that it returns 1000 if no code was present.

**Comment by silverwind** [comment]
Given that close codes are optional (A quick test shows Firefox and Safari both send 1000, Chrome sends none), I think it might actually be more in line with the RFC to return `null` when no code is observed (so the receiver can distingish from a `0` code, and more importantly, from an actual `1000`).

Of course, that wouldn't be compatible with `ws`, but I'm not really a fan of their default 1000.

**Comment by silverwind** [comment]
On the other hand, this is probably not something worth breaking compatibilty over. Can't really think of a use-case for the `null` close code, except client fingerprinting. 😉
