### ISSUE TITLE
node.js addon benchmark results in readme

### ISSUE THREAD

**Issue by mscdex** [uWebSockets/uWebSockets#238]
It would be nice to actually see the node.js addon benchmark results in the table in the readme since I think a lot of people would be using it in this way and it would be useful information to have.

**Comment by alexhultman** [comment]
Well this project is a C++ lib that happens to have a Node.js addon. You lose a lot of perf by using it with Node.js and any JS code ontop of the lib will kill perf even more.

The addon is about 10x faster than ws, while the native thing is anywhere from 30 to 150 to 300x faster (depending on level of fabrication, short message throughput). You also kill perf by sending text instead of binary since JS strings kills perf even more than buffers.

**Comment by alexhultman** [comment]
Memory usage is also completely blown up when using it from Node.js. JS objects are astronomical in size.

**Comment by mscdex** [comment]
Right, this is just a request to put those numbers in the readme so everyone can know what to expect :-)

**Comment by alexhultman** [comment]
I can put those numbers in the readme when socket.io and ws put their "numbers" in their readme.

**Comment by ronkorving** [comment]
@alexhultman But you are already putting the `ws` numbers in your readme, so wouldn't it be great to complete the picture? This is nothing personal, people just want to be informed.

**Comment by alexhultman** [comment]
This is the kind of marketing I'm up against:

"FEATURING THE FASTEST AND MOST RELIABLE
REAL-TIME ENGINE"

"`ws`: The fastest cross platform RFC-6455 WebSocket implementation for Node.js."

People don't give one shit about benchmarks, this whole Node.js universe is driven by hype and nothing else.

**Comment by mscdex** [comment]
I agree with @ronkorving.

IMHO if your library is faster and you have solid benchmarks and results to prove it, there is nothing to worry about. Also, I would argue that there *are* people that care about performance and benchmarks (as long as they portray real world scenarios) in the node.js community and beyond (I am one of those people).

If the problem is that you feel most people aren't aware of this library/addon, then spread the word by tweeting about it, writing a blog post, submitting this repo to various relevant news sites (e.g. echojs.com and others -- I see you already submitted it to HN a couple times some time ago). When you have major changes, let people know so the library will be fresh in their minds.

On a semi-related note, it would also be interesting to have published benchmark results when spreading the workload across multiple cores in one way or another (e.g. for node this would be via the `cluster` module).

Anyway, that's my two cents.

**Comment by tresdin** [comment]
@alexhultman If you have that benchmark, I'm willing to file an issue on `ws` issue tracker to ask for either a removal of their marketing title or a mention about `uws` as the faster one.

By the way, performance is the only reason that I'm using `uws` for my web application instead of `ws`. So yes, I do care about the benchmark. I also believe that sooner or later, the majority of `uws` users will be from *the Node.js universe*.

**Comment by alexhultman** [comment]
Yeah well go stand in line. Arnout is a piece of shit douchebag that shits on others opinions. He already got like 10 people telling him about uws yet he simply ignores it. I don't give a shit about him anymore.

**Comment by lpinca** [comment]
> Arnout is a piece of shit douchebag that shits on others opinions.

Sorry but this is not true. Everyone can read the discussions on `ws` issue tracker and judge.

**Comment by JoshuaWise** [comment]
Before bashing Arnout and the Node.js community so much, you might want to learn how to write a basic event emitter.

With you "addon" API, you cannot remove events that were added via `.once()`. Further, if you try to register an event inside a `.once`d listener of the same event name, it will throw an error.

**Comment by alexhultman** [comment]
I accept PRs.

**Comment by JoshuaWise** [comment]
Just saying, this thing won't be as great as it could be without the community. So don't bash it.

**Comment by alexhultman** [comment]
I'm aware of this. Much of the testing has been done by @lpinca, he also wrote most of the initial JS. Others have helped and I appreciate that. I'm however not a PC person and I will say whatever I wish to say about whatever I want to talk about.
