### ISSUE TITLE
Registering more than one listener to WebSocket is not supported

### ISSUE THREAD

**Issue by tresdin** [uWebSockets/uWebSockets#239]
This error occurred while I was trying to add multiple event listeners to Websocket. I think this behaviour will hardly make sense. This issue is also causing a quite serious problem to my application. 

What is the point of not supporting multiple event listeners? If it's all about the memory leaks issue, then why doesn't `uws` just support multiple event listeners and throw a warning instead?

**Comment by SEAPUNK** [comment]
I don't think a full event system should be done on the uWS level. You should wrap your uWS instance in an event emitter instead.

```js
const eventSystem = new EventEmitter()
wss.on('connection', eventSystem.emit.bind(eventSystem, 'connection'))
eventSystem.on('connection', doThings)
eventSystem.on('connection', doOtherThings)
```

**Comment by lpinca** [comment]
> I don't think a full event system should be done on the uWS level.

I disagree, almost everything in node is an `EventEmitter`, and `uws` was originally extending the `EventEmitter` class as well. Then it was removed in favor of the current limited implementation to save something like 50 mb of memory when dealing with 1 million of open connection.
I think this is the third time this issue pops up and I think it will keep being opened because it's natural for node developers to work with `EventEmitter`s. Using a proper `EventEmitter` will greatly clean up the JS code and fix some open issues.
Also you are suggesting to forward the events to an `EventEmitter` which basically defeat the point of not having an `EventEmitter` in the first place.

**Comment by SEAPUNK** [comment]
@lpinca 
> I disagree, almost everything in node is an EventEmitter

Fair enough, but the question here is: Should it? I mean, almost everything in node is a callback function (although it's starting to slowly move towards Promises), and I can think of a few reasons why almost everything in node probably _shouldn't_ be a callback.

> Also you are suggesting to forward the events to an EventEmitter which basically defeat the point of not having an EventEmitter in the first place.

I gave them a workaround, showing them how to achieve the functionality they desire. I'm saying it shouldn't be done in core.

**Comment by lpinca** [comment]
> Should it?

If your "thing" emits events and you should listen to those events (eventually using multiple listeners) then yes, I think it makes sense.

**Comment by tresdin** [comment]
@lpinca Supporting full event system and allowing to add more than one event listener are two different issues. And I don't really care about the first one.

**Comment by alexhultman** [comment]
If you want bad performance you should use ws.

**Comment by lpinca** [comment]
@tresdin yes/no adding support for multiple listeners is another step toward a full featured `EE`.

**Comment by lpinca** [comment]
> If you want bad performance you should use ws.

Seriously what impact had the `EE` on the overall perfomance? 1%?

**Comment by alexhultman** [comment]
#36

**Comment by lpinca** [comment]
Oh yeah I still have this same [opinion](https://github.com/uWebSockets/uWebSockets/issues/36#issuecomment-209082807). I have shared it enough :)

**Comment by tresdin** [comment]
@alexhultman The problem is mostly about the native Nodejs implementation of event emitters. I think what we should do is to write a better implementation instead of dropping it. Something written in ES6 might be better.
```
class EventEmitter{
	constructor() {
		this.listeners = new Map();
	}
	addListener(type, listener) {
		this.listeners.set(listener.bind(this), {type, listener});
	}
	removeListener(type, listener) {
		for(let [key, value] of this.listeners){
			if(value.type !== type || listener !== value.listener){
				continue;
			}
			this.listeners.delete(key);
		}
	}
	emit(type, ...args) {
		this['on' + type] && this['on' + type](...args);
		for (let [key, value] of this.listeners) {
			if (value.type !== type) {
			continue;
			}
			value.listener(...args);
		}
	}
};

**Comment by SEAPUNK** [comment]
> If your "thing" emits events and you should listen to those events (eventually using multiple listeners) then yes, I think it makes sense.

Okay, but EventEmitter is not the only way to handle events. There are Observables, there is the middleware model, and I'm sure there are many other ways to handle data coming in.

Then the question is: What if you want to conditionally handle an event? What if this? What if that? [I've had issues with how EventEmitter limited me before](https://github.com/nodejs/node/issues/6339), which is why I'm so leery of it.

**Comment by lpinca** [comment]
> What if you want to conditionally handle an event? What if this? What if that? What if one of the handlers throws an error?

This a bit off topic but yes I get what you are saying.

**Comment by alexhultman** [comment]
The idea is to not pay for what you don't need. Most projects use one single listener while some use multiple. If you need multiple listeners you solve that yourself. There are about 3 other incompatibilities with ws that will not be fixed. Uws will never be 1:1 with ws.

**Comment by tresdin** [comment]
@alexhultman May I know about those other ones? Or do you have a complete list of them? I just want to fix them all at a time.

**Comment by alexhultman** [comment]
* You can only register one listener per websocket
* There is no net.Socket in ws._socket
* Binary messages received are references you cannot keep without performing a copy
* ws.upgradeReq is stripped a lot

These are design decisions and not bugs to be fixed

**Comment by lpinca** [comment]
- no client tracking

**Comment by tresdin** [comment]
@lpinca I'm not very clear about these 2 points.
In which cases can my application be affected by the client tracking stuff? And also, does the third point include the error events of both `WebSocketServer` and its sockets?

**Comment by lpinca** [comment]
> In which cases can my application be affected by the client tracking stuff?

Are you using `wss.clients` in your code? where `wss` is the WebSocket server? If no you can safely ignore this point.

> Does the third point include the error events of both WebSocketServer and its sockets?

Yes.

**Comment by alexhultman** [comment]
So basically the ws interface is spoofed a la 90% and works in most cases with no code change but won't work out of the box in 100% of the cases. In those cases you will need to port your code over, which should be a 5 minute work or less.

**Comment by tresdin** [comment]
@lpinca Thank you for the clarification. I actually have my own client list so I think I can ignore it.

**Comment by tresdin** [comment]
I think I'm ok with solving this issue myself. Thank you all for the helpful information.
