### ISSUE TITLE
follow semver convention?

### ISSUE THREAD

**Issue by Pomax** [uWebSockets/uWebSockets#245]
With 0.9.0 being [interface-breaking](https://github.com/uWebSockets/uWebSockets/releases/tag/v0.9.0), the proper [semver](http://semver.org) approach is to use a `major` version change, not a `minor`.

Using semver, this should have been `1.0.0`, where `1.0.0` is not a signal that your code is now "production ready" or some other overloaded interpretation of a "version 1", but *only* mean that this version is API-breaking with respect to the previous version. Since npm's versioning is based on the rules of semver version 2, using `0.9.0` despite being interface breaking means that codebases may automatically get updated to your new version despite the fact that it may break codebases and deployes.

Good idea to retract this version and instead run an `npm version major` (if you're not using `npm` itself for the version management, great idea to start doing that - `npm version major`, `npm version minor` and `npm version patch` all bump up the version according to semver rules, and generate a git tag to push up to your repo)

**Comment by socmag** [comment]
I think Alex's general philosophy has been that prior to a 1.0 all bets
were off.

That's pretty typical, and A lot of early adopters were cool with that.

That said, obviously people are using it now to the point where more
communication of versioning might be a good thing.

Possibly was a bit of a surprise the rapid adoption, though given the
perf, stability and need of uWS otoh maybe not surprising.

**Comment by alexhultman** [comment]
This project is still pre-release and only enforces compatibility of patch versions. Just like how Node.js v0.12.x broke all addons written for v0.10.x - at this early stage we use "minor" to denote "major". Also, I rather have some users get obvious breakages, easy to fix, than have users get random crashes that are hard to find. One example is how binary data is zero-copy in uws but copy in ws. The swap to ArrayBuffer forces the user to take action and adapt their code for this change.

After 1.0.0 thingfs will be production ready and follow a more strict versioning.

**Comment by SEAPUNK** [comment]
@Pomax When version is 0.x.y, the x is considered the "major" version.

The 0 at the beginning means that the project is still unstable.

**Comment by Pomax** [comment]
@socmag @alexhultman ah, fair enough!
