### ISSUE TITLE
more c++ examples?

### ISSUE THREAD

**Issue by agauniyal** [uWebSockets/uWebSockets#248]
Since there isn't a good source of documentation and although I agree the codebase isn't very large, but this repo could benefit from a few examples on c++ usage. Apart from nodejs package, I personally believe there is a good amount of interest for using it as c++ websockets lib, as there isn't a good competitor atm.

Documentation would be perfect solution, but till then 2-3 examples of different usages(probably highlighting `uWS::EventSystem` & `uWS::Server` is and how to use them) could be posted?

**Comment by alexhultman** [comment]
Documentation will be written for the rewrite. If you want you can PR some more examples for both JS and C++.

**Comment by agauniyal** [comment]
I plan to write some as soon as I get some time, btw what happened to multithreaded example, it's empty atm 😕

**Comment by alexhultman** [comment]
Hehehe - yeah that's what happens when you need to quickly fix some build errors - just remove the code and voila! :smile_cat: 

There are "examples" in tests that you can look at. I really should take some time and write some documentation soon.

**Comment by agauniyal** [comment]
Haha I'll take a look at examples, and congratulations on your release ✌️

**Comment by alexhultman** [comment]
Yeah thanks.

**Comment by not-implemented** [comment]
Oh yeah, some more C++ examples will be really helpful :-) Some questions I'm currently searching for:

How to gracefully close the server and disconnect all clients? Is this the correct way? `hub->getDefaultGroup<uWS::SERVER>().close();` - nothing else? All done by µWebSockes? Seems so ... cool :-)
Is it correct, that it force-closes all clients after max 15 seconds timeout then? (I think, this is a very good default, but there's currently no chance to change it, right?)

Another example would be, how to send to multiple clients (but not all). I found the `broadcast()` method and its optimization to `prepareMessage()` / `sendPrepared()` / `finalizeMessage()` and the reference-counted WebSocket-message - is it the best, to just copy this code and do my own loop? By the way a very nice performance feature, which should be better promoted in examples to show the power of the library ;-)

**Comment by alexhultman** [comment]
Yep, spot on. I do recommend using the prepareMessage and just loop over your own subset. The 15 sec is just a shot from the hip - it could be made an argument instead.

**Comment by alexhultman** [comment]
Examples can be seen in test/main.cpp

**Comment by jgupta** [comment]
Is broadcast in multithread possible? Is this correct [piece of code](https://github.com/uWebSockets/uWebSockets/blob/master/tests/main.cpp#L466)?

Still trying to wrap my mind around uWS.

**Comment by ssj17vegeta** [comment]
Hi ! Since this issue seems to be an acceptable way of asking questions, I had one, if I may :)

I need to keep track of connected clients in a vector<Some_Class_Which_Contains_The_Socket>.

Problem : I want to clean this vector when a client disconnects by erasing the appropriate entry, but since the socket seems to be already destroyed, I can't use the operator == (crashes with segfault). Can this be achieved in any way ?

It would seem like a good C++ example :) I still have trouble with understanding the code without comments. Good luck documenting that, and thanks in advance for your answer :-)

**Comment by alexhultman** [comment]
If you have trouble storing the WebSocket as is (I think this should work?) then you can instead try and store the WebSocket::getPollHandle() and use that to construct a WebSocket(poll handle) with. But I think it should work without that

**Comment by ssj17vegeta** [comment]
I confirm that storing the uv_poll_t* instead of the socket fixes the issue. Thanks a bunch man !

**Comment by MergHQ** [comment]
Hello! I figured I'd ask a question too. How can I send stuff to a specific clients? Is there a vector or something that contains every connected client?
