### ISSUE TITLE
Listening on UNIX socket instead of on TCP/IP

### ISSUE THREAD

**Issue by Rush** [uWebSockets/uWebSockets#249]
I added a PR implementing support for it. Here's rationale:

If one is using a reverse proxy or some other custom connection scheme, unix socket can improve security and performance over a regular TCP socket.

**Comment by alexhultman** [comment]
Seems reasonable. If it is nonubtrusive we can add it.

**Comment by Rush** [comment]
Hm, why is this closed? I don't see any commits implementing support for it.

**Comment by alexhultman** [comment]
You haven't fixed it for 3 months, then I close it as it is not my idea but your. Your history with this project has been that you repeatedly come and say "hey, I can do this", and then you don't actually do anything for months and then you come back and say you can do something new. If you want this you have to implement it yourself - it is not my problem. I even remember how you said you would set up Travis and such back in March or April and you never did. I don't have time for people like that.
