### ISSUE TITLE
Compile Faild.

### ISSUE THREAD

**Issue by liketemple** [uWebSockets/uWebSockets#252]
I am compile this lib on macOS seirra with openssl 1.02t. and I met this incomplete type error:

[ 16%] Building CXX object CMakeFiles/uWS.dir/src/HTTPSocket.cpp.o
[ 25%] Building CXX object CMakeFiles/uWS.dir/src/Network.cpp.o
[ 33%] Building CXX object CMakeFiles/uWS.dir/src/Server.cpp.o
/Users/mac/gitsrc/uWebSockets/src/Server.cpp:323:19: error: member access into incomplete type 'SSL_CTX' (aka 'ssl_ctx_st')
        sslContext->references++;
                  ^
/usr/local/include/openssl/ossl_typ.h:145:16: note: forward declaration of 'ssl_ctx_st'
typedef struct ssl_ctx_st SSL_CTX;
               ^
1 error generated.
make[2]: *** [CMakeFiles/uWS.dir/src/Server.cpp.o] Error 1
make[1]: *** [CMakeFiles/uWS.dir/all] Error 2
make: *** [all] Error 2

Any help will be grateful. Thanks.

**Comment by alexhultman** [comment]
In OpenSSL 1.1.0 (I'm pretty sure you are using 1.1.0, not 1.0.2t) the CTX has become opaque and increasing the ref count is done with SSL_CTX_up_ref instead. I will fix this up and add support for this new OpenSSL version.

**Comment by alexhultman** [comment]
This adds OpenSSL 1.1.x: a8118cb3e9c576c5ce9e84020427e1bd32a02cc9

**Comment by liketemple** [comment]
Oh, I am using openssl 1.1.0, and with SSL_CTX_up_ref, it works now. Thanks a lot!
$ openssl version
OpenSSL 1.1.0  25 Aug 2016

**Comment by alexhultman** [comment]
Nice, thanks for reporting
