### ISSUE TITLE
Cannot build benchmark

### ISSUE THREAD

**Issue by JoshuaWise** [uWebSockets/uWebSockets#254]
When I try to `make` the benchmark, I get this:
```
g++ -std=c++11 -O3 scalability.cpp -s -o scalability -lpthread
scalability.cpp: In function ‘int main(int, char**)’:
scalability.cpp:94:36: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(line, sizeof(line), pipe);
                                    ^
scalability.cpp:114:36: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(line, sizeof(line), pipe);
                                    ^
g++ -std=c++11 -O3 throughput.cpp -s -o throughput -luv
g++ -std=c++11 -O3 -I ../src ../src/Extensions.cpp ../src/HTTPSocket.cpp ../src/Network.cpp ../src/Server.cpp ../src/UTF8.cpp ../src/WebSocket.cpp ../examples/echo.cpp -o uWS -luv -lcrypto -lssl -lz
/tmp/cc7Z57gj.o: In function `uWS::WebSocket::sendPrepared(uWS::WebSocket::PreparedMessage*)':
WebSocket.cpp:(.text+0x294): undefined reference to `uWS::EventSystem::changePollAsync(uv_poll_s*)'
/tmp/cc7Z57gj.o: In function `uWS::WebSocket::close(bool, unsigned short, char*, unsigned long)':
WebSocket.cpp:(.text+0x9b2): undefined reference to `uWS::EventSystem::changePollAsync(uv_poll_s*)'
/tmp/cc7Z57gj.o: In function `uWS::WebSocket::write(char*, unsigned long, bool, void (*)(uWS::WebSocket, void*, bool), void*, bool)':
WebSocket.cpp:(.text+0xe8b): undefined reference to `uWS::EventSystem::changePollAsync(uv_poll_s*)'
/tmp/cc7Z57gj.o: In function `uWS::WebSocket::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket, void*, bool), void*, unsigned long)':
WebSocket.cpp:(.text+0x1204): undefined reference to `uWS::EventSystem::changePollAsync(uv_poll_s*)'
/tmp/cc7Z57gj.o: In function `uWS::WebSocket::ping(char const*, unsigned long)':
WebSocket.cpp:(.text+0x2114): undefined reference to `uWS::EventSystem::changePollAsync(uv_poll_s*)'
/tmp/cc7Z57gj.o:WebSocket.cpp:(.text+0x24a4): more undefined references to `uWS::EventSystem::changePollAsync(uv_poll_s*)' follow
/tmp/ccPRPnR8.o: In function `main':
echo.cpp:(.text.startup+0x23): undefined reference to `uWS::EventSystem::EventSystem(uWS::LoopType)'
echo.cpp:(.text.startup+0x116): undefined reference to `uWS::EventSystem::run()'
echo.cpp:(.text.startup+0x12d): undefined reference to `uWS::EventSystem::~EventSystem()'
echo.cpp:(.text.startup+0x16a): undefined reference to `uWS::EventSystem::~EventSystem()'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```

Any ideas?

**Comment by alexhultman** [comment]
I can be real with you if you can be real with me. I'm not  going to spend 1 second on you unless you help me out. You''re the new `ws` maintainer and I expect collaboration from your end if I help you out.

So you want to benchmark the two modules, I suppose? I already know the outcome - when you conclude the same, I need you to update the `ws` marketing to something other than "fastest". Otherwise, I'm not going to bother with you whatsoever.

**Comment by SEAPUNK** [comment]
What does that have to do with this issue?

**Comment by alexhultman** [comment]
We have here, the new `ws` maintainer looking to get the benchmark working. I'm not going to bother with these people unless they accept fact.

**Comment by SEAPUNK** [comment]
He isn't asking a question about `ws`, he's asking a question about `uws`. Regardless of him being a `ws` maintainer or not, you're being completely unreasonable here.

I mean sure, I love your project, and I think it's great, but you're letting your ego get the best of you here. Even if `ws` keeps saying that it's "the fastest", _so what_? People here already know that your module is faster, and from what I'm seeing, it's not really hurting your project.

I'm seeing how people are just migrating from `ws` to `uws`, and they seem to like it a lot. If you already asked the 3rd-Eden to update the description, and he flat out refused to or whatever, let _him_ be the one that is seen as the "asshole", or whatever. You don't need to stoop down to that level yourself.

And hell, if @JoshuaWise is asking you how to do the benchmarks, you'd think that he's at least considering helping you out.

**Comment by JoshuaWise** [comment]
Well, at the time of its conception, `ws` *was* the fastest. And I'm fairly sure it's *still* the fastest one written in JavaScript. Yours is written in C++, it's a completely different thing. So if it makes you happy, after I run the benchmarks and see the results you expect me to see, I wouldn't have a problem with changing the description to something like "fastest pure JavaScript WebSockets implementation" or whatever

**Comment by JoshuaWise** [comment]
But SEAPUNK its right, I don't know who got on your bad side, but it'd be nice if you did something about that serious 'tude you're throwing around. If 3rd-Eden is resentful or something and not responding to you, then fine, let him be. But also he told me his lack of responsiveness *in general* recently has been due to health problems. So there's that to consider before judging him.
