### ISSUE TITLE
how does transfer of connection work?

### ISSUE THREAD

**Issue by anjanikumarsharma** [uWebSockets/uWebSockets#255]
In the following lines, as stated in **`examples/multithreaded_echo.cpp`** 
```cpp
server.onUpgrade([](uv_os_fd_t fd, const char *secKey, void *ssl, const char *extensions, size_t extensionsLength) {
    // we transfer the connection to one of the other servers
    threadedServer[rand() % THREADS]->upgrade(fd, secKey, ssl, extensions, extensionsLength);
});
```

What happens with this line - `upgrade(fd, secKey, ssl, extensions, extensionsLength)` ?

So far I know `EventSystem es(MASTER);` describes es as `MASTER` and `EventSystem tes(WORKER)` as workers in other threads, `Server server(es, 3000)` is the master socket listening to port 3000.

Does `upgrade(fd, secKey, ssl, extensions, extensionsLength)` here is somewhat like `accept()` call as it is in tcp sockets? But its being called on one of the random `threadedServer`. `accept` call is made on original socket and then we `fork()` and create a new socket essentially closing the previous one. I'm familiar with tcp sockets but I'm having a hard time grasping these.

**Comment by anjanikumarsharma** [comment]
and does that example mean there can be only 4 concurrent websocket connections simultaneously, the other connections will wait till then right? Can't we like allocate new workers in separate thread for each new connection?

**Comment by alexhultman** [comment]
This lib is async, aka you hold one or many connections per server. With 4 workers you can hold millions of connections. Upgrade transfers the connection from the master to one of the workers. Accept is being called by the master, then the worker will perform the upgrade and deal with the connection for the remainder of the time.

**Comment by anjanikumarsharma** [comment]
Sorry for troubling you again but I'll be using your lib for my sem project and I need to learn it 😸 .

I was talking about **concurrent** connections by which I mean server is able to communicate with client. Maybe I've misunderstood something, but do you mean to say with 1 server instance I can communicate with more than 1 client without closing the connection to previous client?

Say in this example - 

```cpp

server.onUpgrade([](uv_os_fd_t fd, const char *secKey, void *ssl, const char *extensions, size_t extensionsLength) {
    // we transfer the connection to one of the other servers
    threadedServer[rand() % THREADS]->upgrade(fd, secKey, ssl, extensions, extensionsLength);
});

```

Ther `server.onUpgrade` is master server which listens to incoming ws connections, and it deals with it inside the lamda `[ ]( ){ }` after which it's responsibility is over. But since inside the lamda `upgrade()` is called on one of the workers, they take up the responsibility and carry over to their lamda.. is my understanding fine?

Also is there any resource where I could read about websockets, MDN dosen't tells much..

**Comment by alexhultman** [comment]
Use the multithreaded server only when you have to. Normal usage is single threaded and yes, like I said, one server thread holds millions of connections at the same time.
