### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by palamccc** [uWebSockets/uWebSockets#257]
I tried to use uWebSocket in alpine linux (docker image) and got error message that 'Compilation of µWebSockets has failed and there is no pre-compiled binary...' and i was able to fix the problem.

https://github.com/uWebSockets/uWebSockets/blob/5f2cf2169ebd5689daf6d337b9b085c6bafae097/nodejs/dist/uws.js#L14-L22

In my case, i was missing 'libc.so.6' file, but instead uwebsockets prints a friendly message, completly ignoring actually exception **e**. I finally added additional console.log statements to debug the issue.

Exception may happen due to mutiple reasons, so i request you to print **e.message** also along with friendly error message.

**Comment by alexhultman** [comment]
#284
