### ISSUE TITLE
Node.js addon benchmarks

### ISSUE THREAD

**Issue by lpinca** [uWebSockets/uWebSockets#258]
I spent some time benchmarking the Node.js addon, actually not the addon directly but the wrapper around it that is shipped with the `uws` package on npm.
I did it because I was curious and because it was previously requested in #238.
I used the benchmarks included in this repo and compared `ws+bufferutil` with `uws`.

This is the `ws` server code. `ws` has been installed with `npm i websockets/ws` (latest commit in master):

```js
'use strict';

const ws = require('ws');

const wss = new ws.Server({
  perMessageDeflate: false,
  clientTracking: false,
  maxPayload: Infinity,
  port: 3000
});

wss.on('connection', (ws) => {
  ws.on('message', (message) => {
    ws.send(message, { binary: true });
  });
});
```

This is the `uws` server code (using latest commit in master):

```js
'use strict';

const uws = require('../nodejs/dist/uws');

const wss = new uws.Server({
  perMessageDeflate: false,
  maxPayload: Infinity,
  port: 3000
});

wss.on('connection', (ws) => {
  ws.on('message', (message) => {
    ws.send(message, { binary: true });
  });
});
```

## Results

`./scalability 100000 3000`

uws                                            | ws
-----------------------------------------------|-----------------------------------------------
Connection performance: 3.67796 connections/ms | Connection performance: 2.84147 connections/ms
Memory performance: 83.7179 connections/mb     | Memory performance: 50.004 connections/mb

`./throughput 10000 20 10 3000`

uws                                            | ws
-----------------------------------------------|-----------------------------------------------
Echo performance: 234.255 echoes/ms            | Echo performance: 18.1615 echoes/ms
Echo performance: 243.689 echoes/ms            | Echo performance: 18.1882 echoes/ms
Echo performance: 246.92 echoes/ms             | Echo performance: 18.5074 echoes/ms
Echo performance: 247.919 echoes/ms            | Echo performance: 18.4772 echoes/ms

`./throughput 1 104857600 1 3000`

uws                                            | ws
-----------------------------------------------|-----------------------------------------------
Echo performance: 0.0059362 echoes/ms          | Echo performance: 0.00575768 echoes/ms
Echo performance: 0.00741724 echoes/ms         | Echo performance: 0.0058394 echoes/ms
Echo performance: 0.00807983 echoes/ms         | Echo performance: 0.00584849 echoes/ms
Echo performance: 0.00845898 echoes/ms         | Echo performance: 0.00603802 echoes/ms

## Notes

- `uws` uses `ArrayBuffer` so it doesn't have to convert it to Node.js `Buffer`. `ws` uses `Buffer`.
- I ran the benchmarks with Node.js 6.6.0. This version introduced a regression which affects the `Buffer` performance (https://github.com/nodejs/node/issues/8733) so `ws` performance could be a bit better once the issue is fixed.
- The benchmarks have been only run with binary data. They should also be run with text data.

**Comment by alexhultman** [comment]
What platform is this? OS X?

**Comment by lpinca** [comment]
`Linux fedora 4.7.4-200.fc24.x86_64 #1 SMP Thu Sep 15 18:42:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by alexhultman** [comment]
Seems legit. You can get a little boost in `ws` short message throughput perf by corking:

```javascript
'use strict';

const uws = require('ws');

const wss = new uws.Server({
  perMessageDeflate: false,
  maxPayload: Infinity,
  port: 3000
});

wss.on('connection', (ws) => {
  var i = 0;
  ws.on('message', (message) => {

  const tmp = i % 10;
  if (tmp == 0) {
    ws._socket.cork();
  } else if (tmp == 9) {
    ws._socket.uncork();
  }

  ws.send(message, { binary: true });
  i++;
  });
});
```

This makes `ws` 2x faster here, leaving a gap of 10x to `uws`.

**Comment by lpinca** [comment]
If these benchmarks are correct I think that the table in your README should report these numbers. Comparing the C++ server with `ws` is not fair imho.

**Comment by alexhultman** [comment]
That's not going to happen. Read my comments in #238.

**Comment by lpinca** [comment]
Well sorry if I'm being rude but then you are not that different from the people you called assclowns or douchebags, and to be honest `ws` description is still valid in a certain sense as:

1. It always had "for Node.js", they never claimed to be the fastest WebSocket implementation out there (only the Node.js one)
2. `uws` works fine on Windows only with node >= 6.4.0 (not a LTS version yet)
3. `uws` does not compile on some Node.js supported platforms that have an old compiler.

**Comment by alexhultman** [comment]
Everyone is entitled to their own opinion.

**Comment by lpinca** [comment]
Totally true it's slinging the mud that is unacceptable :smile:

**Comment by lpinca** [comment]
Feel free to clean up this thread and leave only the relevant stuff or delete it completely.

**Comment by lpinca** [comment]
lol, I wish I could get back your deleted comments (not on this thread).

**Comment by alexhultman** [comment]
You are making a lot of noise over a bagatelle. You just concluded in your own testing that `uws` for Node.js is 10x faster than `ws`. What is the issue here? In what cases are `ws` faster than `uws`?

I personally patched Node.js 6.4.0 to allow addons to use OpenSSL on Windows - I was not allowed to land it in the LTS. If you have any problem with this you have to take it up with the Node.js maintainers.

**Comment by lpinca** [comment]
That's not my point. You started to insult people because `ws` **incorrectly** uses "The fastest cross platform RFC-6455 WebSocket implementation for Node.js" as its description which again in a certain sense is true imho. This is the table in your README:

Implementation | User space memory scaling | Connection performance | Short message throughput | Huge message throughput
--- | --- | --- | --- | ---
ws v1.1.0 + binary addons | µWS is **47x** as lightweight | µWS is **18x** as performant | µWS is **33x** as performant | µWS is **2x** as performant

If that is **correct** for you then fine end of discussion.

**Comment by alexhultman** [comment]
You understand the concept of context, right? You just posted an excerpt of the section of the front page. If you actually do read the whole information you can clearly see this:

Quote from right under your excerpt:

*Benchmarks are run with default settings in all libraries, except for ws which is run with the native performance addons. These results were achieved with the native C++ server, not the Node.js addon. Expect worse performance and scalability when using Node.js (don't worry, the Node.js addon will run circles around ws).*

The front page clearly states the table is using the native server as a reference. As we now have yet again validated - the text is correct. `uws` literally runs in circles around `ws`.

Still, somehow you equate this with how `ws` writes this on their front page:

Quote:

*`ws`: The fastest cross platform RFC-6455 WebSocket implementation for Node.js.*

Calling `ws` "fastest" is simply invalid.

**Comment by lpinca** [comment]
> Expect worse performance and scalability when using Node.js (don't worry, the Node.js addon will run circles around ws).

How much worse? Why not showing the real data instead of comparing C++ to JavaScript?

**Comment by alexhultman** [comment]
The table compares implementations. Language has nothing to do with it:

libwebsockets is written in C.
WebSocket++ is written in C++.
Kaazing Gateway is written in Java.
ws is written in JavaScript.

You do realize that the more work I need to put into doing benchmarkings, the less work I get to put into improving the code? I do not want to list every possible combination of every possible perspective. I also do not want to bloat the very front page with more than the absolute required amount of information to convey the purpose of this repo. Why should a new user pick this lib? Do I really need to explain basic marketing strategies to you? How would it look like if I displayed a table of 20 rows? It would be overwhelming and not quick and to the point.

Again, consider what you are arguing about. We have the single line "ws: The fastest cross platform RFC-6455 WebSocket implementation for Node.js." claiming omnipotence in a single line - and you are complaining about how µWS front page "only" shows 4 rows of benchmarking information.

**Comment by lpinca** [comment]
> You do realize that the more work I need to put into doing benchmarkings, the less work I get to put into improving the code?

You call yourself a performance enthusiast, I think these are your own words, so yes I expect your benchmarks to be as accurate as possible.

> Do I really need to explain basic marketing strategies to you?

I think this says all. You are fighting over the "The fastest cross platform RFC-6455 WebSocket implementation for Node.js." but you use the same strategy.

> How would it look like if I displayed a table of 20 rows?

You could put it in another document and add a link to it in the README.

> and you are complaining about how µWS front page "only" shows 4 rows of benchmarking information.

Yes 4 lines created ad hoc exactly how `ws` description is.

**Comment by alexhultman** [comment]
>> Calling ws "fastest" is simply invalid.

> AFAIK ws is the fastest on the platforms where uws does not work.

Then go use `ws`. Why are you here complaining? If you consider the fact that `uws` does not run on AmigaOS such a big deal then go use `ws`. You are free to pick whatever implementation you want.

**Comment by lpinca** [comment]
CentOS 6 !== AmigaOS, just an example

**Comment by alexhultman** [comment]
Okay, go use `ws` then. Have a nice time. Bye, bye.

**Comment by lpinca** [comment]
Bye :)
