### ISSUE TITLE
Document internal (low-level) Node.js interface

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#259]
The `ws` interface is implemented in JavaScript on top of the native V8 interface. This adds a lot of overhead since every connection is represented as a JavaScript object with multiple closures per event. By exposing the internal low-level layer as a stable interface for developers to use, you get the ability to scale to even higher levels with `uws` from within Node.js.

Primus already builds their transformer on top of this internal interface, but they still add tons of overhead by wrapping it up in their "Spark" object which is very bloated. A (user-space) WebSocket in the low-level interface is just a JavaScript Number (64-bit).

The `ws` interface is good for initial testing, but any real solution should look to move over to the low-level interface with time.

**Comment by silverwind** [comment]
Having a documented high-level interface would also be nice, now that the API has somwhat diverged from `ws`.

**Comment by alexhultman** [comment]
Yep documentation is very lacking for this project overall.
