### ISSUE TITLE
Compile failed on macOS, be64toh undeclared and onEnd() of HTTPSocket is private to Hub 

### ISSUE THREAD

**Issue by liketemple** [uWebSockets/uWebSockets#260]
Hi, I just pull and compile the newest code.
I found the CMakelist.txt need to update, since some cpp files has changed its's name, and some were removed.
I try to fix CMakelikst.txt on my own, then I found be64toh() undeclared error in WebSocketProtocol.h, and HTTPSocket::onEnd() is private method to Hub.cpp line 10.

**Comment by alexhultman** [comment]
Master is broken, use a release.
