### ISSUE TITLE
how use uws with cross domain

### ISSUE THREAD

**Issue by noman798** [uWebSockets/uWebSockets#261]
the uws works fine with the same domain 

However, when I  uws with cross-domain, the following error will appear

![image](https://cloud.githubusercontent.com/assets/12876555/18917611/e316cc74-85ca-11e6-8d51-1bca06c589ff.png)
![image](https://cloud.githubusercontent.com/assets/12876555/18917317/15315bd0-85ca-11e6-9614-0aca1845e2b7.png)

**Comment by ronkorving** [comment]
Your HTTP server needs to expose CORS headers in response to OPTIONS requests. More info: http://www.html5rocks.com/en/tutorials/cors/

**Comment by alexhultman** [comment]
Whatever settings you apply to your HTTP server will be used if you pass {server: youHTTPServer} as options to uws.Server constructor.

**Comment by alexhultman** [comment]
Does it differ from how ws behaves?

**Comment by noman798** [comment]
Now, I use the sub domain of the same domain , then everything is ok
