### ISSUE TITLE
Remove upgradeReq after connection event handler

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#262]
This object is MASSIVE. That's why I've stripped it to only url, headers and connection fields so far. Now, I want to remove it completely. After the connection event handler has been run, it will be deleted to save 600 mb of memory per 1 million connections (2.0 GB -> 1.4 GB per 1 mil).

Thoughts?

**Comment by SupremeTechnopriest** [comment]
My project needs to get the ip address from `ws.upgradeReq.connection.remoteAddress`.  Is there another place to get the ip?

**Comment by alexhultman** [comment]
If you only need the ip you can attach it to the websocket at connection event. The idea is that you pay for what you use. So just assign it at connection and you're done.

**Comment by SupremeTechnopriest** [comment]
Great thanks!
