### ISSUE TITLE
andriod browser error  "Sec-WebSocket-Protocol"

### ISSUE THREAD

**Issue by noman798** [uWebSockets/uWebSockets#263]
WebSocket connection to 'ws://ws.u88.vc:30032/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received d88fef259ffcd4f88a3f.js:4

![image](https://cloud.githubusercontent.com/assets/12876555/18956585/82ee8714-868e-11e6-810c-02f22c884764.png)

use ws , then everyting is ok
![image](https://cloud.githubusercontent.com/assets/12876555/18956620/a176f36a-868e-11e6-9e78-eada3e909abf.png)

**Comment by alexhultman** [comment]
#209

**Comment by alexhultman** [comment]
@arpu @noman798 does the Android browser send Sec-WebSocket-Protocol by itself? There is no way to turn that off?

How does the HTTP headers look like?

**Comment by arpu** [comment]
@alexhultman 
its non Desktop chrome 
Version 53.0.2785.116 Fedora Project (64-bit)
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:APRn1FIODi+8GNr8HV3VnA==
Sec-WebSocket-Protocol:null
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by arpu** [comment]
hmm maybe because i use 
https://github.com/gamestdio/websocket.js  for reconnection 
need to test this without this lib

**Comment by arpu** [comment]
same problem without websocket.js

**Comment by alexhultman** [comment]
This is fixed in the next version. It will simply echo whatever Sec-WebSocket-Protocol is sent.

**Comment by alexhultman** [comment]
#264
