### ISSUE TITLE
Add routing mechanism

### ISSUE THREAD

**Issue by SmileGobo** [uWebSockets/uWebSockets#264]
I can't find how route request by uri. When my microservise authentification(wss://host.com/auth) return auth-token(guid).  My web application connect to wss://host.com/[service name]/auth-token

**Comment by alexhultman** [comment]
Are you using Node.js? In that case you can do it with the path support.

**Comment by SmileGobo** [comment]
No I'm use c++.

**Comment by alexhultman** [comment]
So it makes sense to pass uri/subprotocol as strings to onConnection of both client and server. That way the application can easily decide what to do based on this -> adds routing and subprotocol support in one go.

**Comment by alexhultman** [comment]
Okay so I have added subprotocol and path support to the rewrite. This will become v0.10.0 in a couple of days.

It works like this:

```c++
h.onConnection([](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo ui) {
    std::string path(ui.path, ui.pathLength);
    std::string subprotocol(ui.subprotocol, ui.subprotocolLength);

    // do whatever you wish with the strings, terminate connection if you want to
});
```

**Comment by alexhultman** [comment]
You can find this on master now

**Comment by SmileGobo** [comment]
I test it. Good work!
