### ISSUE TITLE
Non block run and stop mechanism

### ISSUE THREAD

**Issue by SmileGobo** [uWebSockets/uWebSockets#265]
I believe that we need a mechanism for non-blocking start **Hub :: run()** server. And stop **Hub :: stop ()**
```
int WEBSockTestApp::main(const std::vector<std::string>& args){
    uWS::Hub server;
    auto& log= logger();
    server.onConnection([&log](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo ui) {
       // ...
    });
    server.onMessage([&log](uWS::WebSocket<uWS::SERVER> sock, char *msg, size_t size, uWS::OpCode code){
       // ...
    });
    server.listen(config().getValue<std::uint16_t>("port"));
    server.run();
    log.information("app start!");
    waitForTerminationRequest();  //method wait until user press ctrl-c
    server.stop();                            //Kill all connections
    return Application::EXIT_OK;
}
```

**Comment by alexhultman** [comment]
In your case you would stop with server.getDefaultGroup<uWS::SERVER>().close();

**Comment by SmileGobo** [comment]
For enable non blocking mode I try chnage run method
```
void Node::run() {
    nodeData->tid = pthread_self();

    //uv_run(loop, UV_RUN_DEFAULT);
    uv_run(loop, UV_RUN_NOWAIT);
}
```

But no have result - messages from server not send.

**Comment by alexhultman** [comment]
run is supposed to block, it runs the event-loop. You need to register signal listeners to the uv loop or run them in a separate thread. Hub::getLoop() gives you a uv_loop_t ptr which you can use to register timers, signals, etc

**Comment by alexhultman** [comment]
http://docs.libuv.org/en/v1.x/signal.html

**Comment by SmileGobo** [comment]
Got it! But when hub object destruct call uv_loop_delete(loop); with assertion 

> assert(err == 0);
This is because uv_loop_close returns a non-zero result. It seems that is not enough to cause Group :: close ().
Now I examine how correctly to stop the cycle. Yet it would be necessary to implement the stop method. If you do not mind, I will try to do it.

**Comment by alexhultman** [comment]
You don't call uv_loop_close, you call Group::close and let it finish.
