### ISSUE TITLE
node-gyp won't overwrite prebuilt binary when cp is aliased to cp -i

### ISSUE THREAD

**Issue by mstdokumaci** [uWebSockets/uWebSockets#266]
When you `npm install` uws on an unusual linux, prebuilt binaries are incompatible and won't work.

`node-gyp` script overwrites the binary anyway, however it fails on systems with aliased `cp`.

Check this line:
https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/binding.gyp#L55

If there is an existing incompatible binary, and `cp` is aliased to `cp -i` by default, this above line fails to overwrite.

Possible solutions:

1. Do not include any prebuilt binaries in npm package, so `node-gyp` will make the necessary one at install time.
2. Use `\cp` instead of `cp` so it'll skip alias and use original `cp` command.

**Comment by alexhultman** [comment]
I'm not aware of the "\cp" thing. Is that a Unix thing or something special to node-gyp?

**Comment by mstdokumaci** [comment]
it's a unix & linux thing as i can find:
https://unix.stackexchange.com/questions/39291/run-a-command-that-is-shadowed-by-an-alias

**Comment by alexhultman** [comment]
So I did this: 7b44f15729405777ce3072f61f2d335e23aa79e4

**Comment by alexhultman** [comment]
I had to revert the prefix, it did not work.

**Comment by mstdokumaci** [comment]
For now, our workaround is an npm install script like this:
`(test -d ../uws && cd ../uws && rm uws_*.node && npm install) || (test -d node_modules/uws && cd node_modules/uws && rm uws_*.node && npm install)`

this basically finds uws folder deletes prebuilt binaries and runs the node-gyp again.
it's an ugly solution but it works for us.

the \cp solution i suggested was from here: https://stackoverflow.com/questions/8488253/how-to-force-cp-to-overwrite-without-confirmation

you might test `yes | cp` or `command cp` as well.
