### ISSUE TITLE
update meson build files

### ISSUE THREAD

**Issue by agauniyal** [uWebSockets/uWebSockets#267]
I'm going to update meson build files acc to v0.10, are there any extra files excluding those of `src` folder that I need to take care of?

**Comment by alexhultman** [comment]
They are in src yes. Is it possible to move that meson file out of the src folder? No big deal but it would be nice to only have sources there.

**Comment by agauniyal** [comment]
I will try tomorrow and see if it's possible. should be or otherwise I'll use some glob pattern over the directory for all `*.cpp` files 👍

**Comment by agauniyal** [comment]
The following code inside echo example - 
```
#include <uWS.h>

int main()
{
    uWS::Hub h;

    h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode) {
        ws.send(message, length, opCode);
    });

    h.listen(3000);
    h.run();
}
```

used to wait for incoming connections. Now it just exists... is this intentional?

**Comment by alexhultman** [comment]
h.listen() might return true if the listen failed, then it will just fall through just as before. The diff is that you are not getting an exception thrown now so I guess you just missed the error checking.

**Comment by alexhultman** [comment]
Well, I wrote it so, I missed to check for error :sweat_smile:

**Comment by agauniyal** [comment]
>h.listen() might return true if the listen failed

wait.. true for error? shouldn't it be false?
And I tried wrapping whole code into a `try{}catch(...){}` block but it didn't throw any exceptions. Ofcourse changing port to something random worked 😄

**Comment by alexhultman** [comment]
This version doesn't throw any exceptions. The return code of everything follows the zlib/OpenSSL/Unix model of returning false (aka 0) on success and true (aka not 0) on error.

**Comment by alexhultman** [comment]
Well, maybe I messed up the return of listen, I don't know. Cannot keep track of it anymore. But yeah it should follow the Unix model. Will have to fix that up.

**Comment by SEAPUNK** [comment]
So, like process exit codes, from what I'm understanding. If so, that makes sense, as you could "customize" the error codes.

**Comment by agauniyal** [comment]
They still don't throw `true` as in `1` for error, usually they have some global variable which is set as -ve numbers for errors. You might need to document that explicitly because listen throwing false in case of success seems slightly confusing at first haha.

**Comment by SEAPUNK** [comment]
Huh? [Exit code 1 is a catch-all exit code](http://tldp.org/LDP/abs/html/exitcodes.html)... or are we not talking about the same thing?

**Comment by agauniyal** [comment]
I wasn't talking about unix process as such but unix methods involving networking? eg `socket()` or `bind()` call? Process exit code shouldn't really apply to method exit codes I guess, and that method returns `bool` so 0 or 1.

**Comment by SEAPUNK** [comment]
```
$ man 2 bind

BIND(2)
NAME
       bind - bind a name to a socket

[...]

RETURN VALUE
       On success, zero is returned.  On error, -1 is returned, and errno is set appropriately.

```

**Comment by agauniyal** [comment]
Yes that's what I'm saying, on success 0 and on error some -ve number with global set.

**Comment by SEAPUNK** [comment]
Ah, you had me confused for a bit about `-ve`, you meant negative number. I see.

**Comment by agauniyal** [comment]
@alexhultman I would still recommend reconsidering if not all but some methods for their return values, eg if I had to modify that original program to exit with 1 in case of listen fails, it would look like this -

```
#include <uWS.h>

int main()
{
    uWS::Hub h;

    h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode) {
        ws.send(message, length, opCode);
    });


    if(h.listen(3000)){
       return -1; 
    }

    // or

    auto res = h.listen(3000);
    if(res){
       return -1; 
    }

    h.run();
}
```

Even if I change `res` to `fail` as -
```
auto fail = h.listen(3000);
    if(fail){
       return -1; 
    }
```
it will definitely confuse new user since why would `h.listen()` return fail at first. Rest I respect your choice though previous interface with exceptions was my fav 😸

**Comment by socmag** [comment]
Just my 2 cents.  I much prefer code that never throws exceptions.

As for what the return codes should be,  I'm ambivalent as long as they are
consistent and intuitive.

**Comment by agauniyal** [comment]
Ha, current implementation is correct imo, listen returns true for success and not false - https://github.com/uWebSockets/uWebSockets/blob/master/src/Hub.cpp#L62

**Comment by alexhultman** [comment]
Lol I need to swap that then. Hub::listen should return like Node::listen aka 0 for success and anything else for failure.

**Comment by agauniyal** [comment]
okay.
