### ISSUE TITLE
terminate called after throwing an instance of 'std::regex_error'

### ISSUE THREAD

**Issue by smallnewer** [uWebSockets/uWebSockets#276]
error:
````
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
已放弃
````

node v6.7.0
uws v0.10.5
gcc 4.8.5
test.js:
````js
var WebSocket = require('uws');
var ws = new WebSocket('ws://echo.websocket.org');
````

When I run `node test.js` then I get the error;

**Comment by alexhultman** [comment]
Maybe a localization issue?

**Comment by alexhultman** [comment]
Do you know what those signs mean? Are they garbage or a real message? What language is that?

**Comment by SEAPUNK** [comment]
The last line is Chinese, saying "Abandoned" or "Aborted", something along those lines.

I think it's a localization issue.

**Comment by alexhultman** [comment]
Seems that regex is not supported in GCC until 4.9?

**Comment by alexhultman** [comment]
https://gcc.gnu.org/gcc-4.9/changes.html

```
Improved support for C++11, including:
support for <regex>;
```

**Comment by alexhultman** [comment]
I makes sense to remove the usage of regex. It reduces binary size from 1.7 mb down to 1.3 when building statically, which is sane to do since many users have problems on older Linux distros.
