### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [uWebSockets/uWebSockets#278]
I find that include guards like "[`NODE_H`](https://github.com/uWebSockets/uWebSockets/blob/8b0056d85c1054eb545140bb94710e0189a3063b/src/Node.h#L1)" and "[`UWS_H`](https://github.com/uWebSockets/uWebSockets/blob/29e882841701adf32f189a3ab9b9f1d11b62e809/src/uWS.h#L1)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by elfring** [comment]
I would appreciate another constructive comment for this software situation.

**Comment by agauniyal** [comment]
I too agree with this one, someone is likely to put up a `NODE_H` include guard since node could mean a ton of different abstractions in cs.

**Comment by alexhultman** [comment]
Fair point. PR if you find this important.

**Comment by agauniyal** [comment]
https://github.com/uWebSockets/uWebSockets/pull/282

**Comment by alexhultman** [comment]
Thanks
