### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [uWebSockets/uWebSockets#279]
Would you like to [replace any double quotes](https://github.com/uWebSockets/uWebSockets/blob/8b0056d85c1054eb545140bb94710e0189a3063b/src/Hub.h#L4 "Check header file inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by SEAPUNK** [comment]
> For #include "filename" the preprocessor searches in the same directory as the file containing the directive. This method is normally used to include **programmer-defined header files**.

Why would he?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by SEAPUNK** [comment]
To me it sounds too much like nit-picking, but if you really want it fixed, feel free to open up a PR.

**Comment by SEAPUNK** [comment]
That, and as the last link you linked says,

```
#include "file"
    This variant is used for header files of your own program.
```

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by alexhultman** [comment]
Please stop.
