### ISSUE TITLE
ws.onerror is not implemented (ws.on('error') is, though)

### ISSUE THREAD

**Issue by kdex** [uWebSockets/uWebSockets#283]
In `uws@0.10.5`, I couldn't get any WebSocket client event listener to fire. According to the spec, there should be the `EventListener` properties `onerror`, `onmessage`, `onclose` and `onopen`, so it should work like this: 

``` js
import WebSocket from "uws";
const client = new WebSocket("ws://localhost:1234");
client.onerror = e => console.log(e);
```

Note that at `localhost:1234`, there's no server running, so `onerror` should be called almost immediately and log an `error` event. Browsers and `ws` do this, `uws` does not.

**Comment by kdex** [comment]
I also observed that when calling `close()` on a WebSocket server instance and passing it a callback function, the callback never gets executed.

**Comment by alexhultman** [comment]
The onerror has not been implemented yet, while the on('error') has. So that should be fixed with time. Close has no callback, it will call the on('close') callback instead. You could probably "hack-solve" it by simply calling on('close', cb) when passing a cb to close.

But yes, the JS code is a bit unfinished / non-strictly ws compatible.

**Comment by Nicolab** [comment]
Two events handlers for this. May be it's not necessary to add a footprint in UWS for a hack that can be added into the user space by the rare persons who need it.

**Comment by alexhultman** [comment]
Well uws does not add the memory overhead of two handlers, it implements onerror and on('error') using the same memory. So this would not add any memory overhead. PR is welcomed.

**Comment by gigafied** [comment]
@alexhultman I was going to PR this, but in looking at the source, wanted to kind of cleanup the events logic. Would something like that be welcome?

i.e. 

```    set onmessage (f) {
        this._wrapListener('message', f ? message => f({data: message}) : null);
    }

    set onclose (f) {
        this._wrapListener('close', f ? (code, message) => f({code: code, reason: message}) : null);
    }

    set onerror (f) {
        this._wrapListener('error', f ? err => f(err) : null);
    }

    _wrapListener (event, f) {
        if (!f) return this._setListener(event, noop);
        this._listeners[event] = f;
    }
```

**Comment by alexhultman** [comment]
Sure. Rule is: do whatever you want as long as it doesn't add any memory or perf overhead (of hot path).

**Comment by alexhultman** [comment]
Scratch that. This change adds massive overhead

**Comment by gigafied** [comment]
@alexhultman would you care to clarify? Are you referring to storing the listeners in an Object instead of directly on the instances themselves?

**Comment by alexhultman** [comment]
Yes any addition of JS data types results in significant penalties not only in memory usage

**Comment by gigafied** [comment]
easily addressed with a minor tweak: 
````
    _wrapListener (event, f) {
        let p = `internalOn${event}`;
        if (!f) return this[p] = noop;
        this[p] = f;
    }
````

**Comment by alexhultman** [comment]
I'm not a fan of adding dynamic lookup from string just to save a few lines of code. This function basically adds a dynamic indirection of string-to-function (even if this will never matter in real usage). It is a principle to not add overhead in exchange for neater code.

**Comment by gigafied** [comment]
Fair enough, I disagree as setting listeners is not a hot code path, but it's not my project :)

**Comment by alexhultman** [comment]
I agree, it is not at all a hot path but my gut feeling is to stay as far away from anything dynamic as possible.

**Comment by gigafied** [comment]
Must be evil JavaScript rubbing off on me.

**Comment by Nicolab** [comment]
This sugar can be a mixin out of uws, like:

mixin.js
```js
function onmessage(f) {
  if (f) {
    f = (message) => f({data: message});
  }

  this.on('message', f);
}

// onerror, onclose, ...
// ...
module.exports = function mixin(client) {
  onmessage = onmessage.bind(client);
  // onerror = onerror.bind(client);
  // ...

  Object.defineProperty(client, "onmessage", {
    get: onmessage,
    set: onmessage,
    writable : true,
    enumerable : true,
    configurable : false
  });
};
```

app.js
```js
import WebSocket from "uws";
import browserLikeMixin from './mixin';

const client = browserLikeMixin(new WebSocket("ws://localhost:1234"));
client.onmessage = (e) => console.log(e.data);
```
