### ISSUE TITLE
Move package.json to repository root

### ISSUE THREAD

**Issue by silverwind** [uWebSockets/uWebSockets#285]
This would allow one to put `uws` as a [git dependency](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in their `package.json`.

**Comment by SEAPUNK** [comment]
This might take some time, as even if the package.json file is moved to the root of the repo, there will still have to be some kind of more-or-less [lengthy build process](https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/Makefile) for the package to get it to a usable state for node.js.

**Comment by SEAPUNK** [comment]
One thing that I think would work better -- splitting the package into two packages, one package being the binary addons, and the other being the pure JS, kinda like how Level does it with [levelup](https://github.com/level/levelup) and [leveldown](https://github.com/level/leveldown)...

**Comment by SEAPUNK** [comment]
I've set up the https://github.com/uWebSockets/uWebSockets/tree/root-package-json branch to look into this.

**Comment by SEAPUNK** [comment]
Yeah, there needs to be some kind of build process to install the package, and it's going to be very difficult to have a compatible setup without either significantly changing the build process, or cluttering the project root.

@alexhultman Is it alright if the `uws` node.js package is split into its own repository? Same package name, just a different build process, which includes:

- Using [`prebuild`](https://github.com/mafintosh/prebuild) to generate the binaries, and host them on the GitHub releases tab on every release, allowing
    - This will change the install process to try to fetch a prebuilt binary first, falling back to a build process, which we can reasonably allow errors for, which will fix #284
- Potentially automating (most of) the release process by using Travis

This will let us cleanly manage the C++ side of `uws` in one repo, and cleanly manage the node.js side of `uws` in another.

**Comment by alexhultman** [comment]
I don't know what to say. I thought NPM was considered "the shit".

**Comment by SEAPUNK** [comment]
npm is alright, the node.js community just still hasn't figured out one solid way to do binary addons yet; it's a tricky topic.

**Comment by SEAPUNK** [comment]
Anyways, I'll set up a test repo on my account sometime later and try out my vision for deploying `uws` npm packages; I'll be sure to let you know the results.

**Comment by silverwind** [comment]
Two repos might make things easier, but it has the downside of splitting the community a bit, e.g. you're likely to get issues opened in the wrong repo. I'm sure it could be done cleanly in a single repo, but two repos are of course also an option if you'd like to have a more strict separation.

**Comment by alexhultman** [comment]
Two repos is GitHub suicide.

**Comment by kapouer** [comment]
[Some people](https://github.com/prosemirror) committed mass sacrifice, then.

**Comment by SEAPUNK** [comment]
@silverwind Not necessarily. You could disable issues in the node.js repo, and have people post issues in the main repo, while the PRs would be split up.

**Comment by agauniyal** [comment]
@kapouer maybe he's much more comfortable in managing multiple repos for same thing, it's all about preference, and moreover those different repos seem to be plugins/extensions for the original package, which uws might not fit too.

**Comment by alexhultman** [comment]
I honestly cannot see the problem here. It's one project, one repo. It has worked just fine for 6 months now.

**Comment by SEAPUNK** [comment]
Sure; my only concerns are:

- To achieve the ability to install the package from the GitHub repo will require a change in how the package "installs", which will most likely affect and in turn, change how the npm package is built and published.
- The aforementioned new build and packaging process, if to be done in the same repo, will have to somehow integrate with the existing build and release process of your C++ code, which you might not like.

**Comment by silverwind** [comment]
Either way, big +1 to using [`prebuild`](https://github.com/mafintosh/prebuild). On-demand downloaded prebuilds will reduce installation size and allow the build log to be shown.

**Comment by SEAPUNK** [comment]
Not too sure about that -- the prebuild dependency itself could pull more data than bundling all of the binaries together.

**Comment by silverwind** [comment]
Ah, of course. `prebuild` is 15M with all its dependencies.

**Comment by SEAPUNK** [comment]
Yeah. So instead of using `prebuild`, I might set up the build process in my test repo to generate the binaries, and publish them in-package, but other than that, the ideas are still more-or-less the same.

**Comment by alexhultman** [comment]
This is prebuild: https://xkcd.com/927/

Yet another build system that tries to solve what we have already solved a million times before: QMake, CMake, Meson, Makefile, node-gyp, ninja-whatever, etc.

This Makefile is standard in any Unix and works without any dependencies whatsoever: https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/Makefile

Clone the repo, cd into nodejs, hit make -> done!

**Comment by SEAPUNK** [comment]
prebuild is a tool that tries to use an existing prebuilt binary, and then fallback to building the binary, if it could not find or use it.

The current installation process (npm's install script) is to build a binary regardless of the prebuilt's existence.

**Comment by alexhultman** [comment]
I mean you are free to redistribute the package in whatever way you want but the main package will never use prebuild, nan, or any of those other bullshit projects.

**Comment by alexhultman** [comment]
Babel is one other project that will never be used.

**Comment by alexhultman** [comment]
WebPack is another

**Comment by SEAPUNK** [comment]
I hear you, I hear you. I want the process to be as lean and fast and simple as possible, like you do. Right now we're just exploring possibilities.

**Comment by alexhultman** [comment]
Pretty much any of the mentioned packages here will never be used: https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.d0dw0xtj8

**Comment by agauniyal** [comment]
Tbh Cmake generates Makefiles and Meson generates Ninja sources ie Cmake == Meson and make == ninja. The purpose of these build systems was to solve complex hierarchies and distribution of source code among directories and their dependencies which led to huge several hours build times. Fortunately uws isn't one of them.

**Comment by alexhultman** [comment]
IMO, Microsoft should just shut up and go with the Unix standard Makefile that has been around for like 80 years. Then we could just ditch all those meta-build-systems and use native standardized Makefiles.

**Comment by alexhultman** [comment]
https://en.wikipedia.org/wiki/Make_(software)

39 years ago. Holy shit, and we see new build systems come up every day now. It is truly https://xkcd.com/927/ all over.

**Comment by agauniyal** [comment]
Add package managers to your list - https://techcrunch.com/2016/10/11/facebook-partners-with-google-others-to-launch-a-new-javascript-package-manager/

**Comment by alexhultman** [comment]
Well the NPM package manager is kind of the reason why this issue is even brought up at all. With a real package manager that understood binaries and binary dependencies we would not really have to bother at all. It could build the sources in their cloud and then only download the right version for your specific Node.js version. They could also make sure to download whatever versions of libstdc++ and whatnot that was needed. This is ofc already solved by *every real* package manager in the Linux world. But not with NPM, not with NPM - the new shiny package manager created 20 years after pretty much every other package manager.

**Comment by SEAPUNK** [comment]
Well, the npm package manager is generally built around Javascript; binary addons are mostly an afterthought, especially considering the pain in the ass [build requirements](https://github.com/nodejs/node-gyp#installation) that would need to be bundled with node.js if building binary addons was a requirement with node.js and npm.

**Comment by alexhultman** [comment]
> It could build the sources in their cloud and then only download the right version for your specific Node.js version.

Also known as, it simply works out of the box. No compilation needed, no set-up needed. You simply download an already build binary (which is the way all software has been distributed since the dawn of computers).

**Comment by silverwind** [comment]
You don't seem to stricly have to have prebuild as a dependency. You could just publish the binaries to a GitHub release and have a simple shell script that pulls the correct one down on install.

**Comment by alexhultman** [comment]
Yep but what is then the point of NPM? If I need to make NPM download some kind of shim script that in turn downloads the correct version - that's a big fat sign of how terrible NPM is at doing its job. "Ah, okay, I'm just going to download this package manager using this package manager so that I can get my package". It's so ridiculous.

**Comment by SEAPUNK** [comment]
@silverwind Then the fun part will be the fetching, and making it compatible with Linux, Windows, and Darwin. I think it'll be better to bundle the binaries in the published package; we just have to make the installation build step more useful, so it works at the project root level.

**Comment by alexhultman** [comment]
NPM should offer package authors to upload one package per ABI version and OS. Then it should *only* download that particular package that satisfies the users ABI and OS. (This is how *all* package managers work on Linux).

**Comment by SEAPUNK** [comment]
Well, it just ain't so, and NPM probably isn't going to do that anytime soon. Oh well, we'll just have to work with what we have.

**Comment by alexhultman** [comment]
Yep, that is the problem -> NPM doesn't care about its users. So we have to find some kind of sweet spot between terrible and even more terrible. I believe that sweetspot is to simply ship every single ABI and OS binaries in one single large package that simply gets downloaded no matter what platform you are on.

**Comment by alexhultman** [comment]
I mean you could probably (PROBABLY) add some kind of test script that tries to require the module as part of the NPM install. If that fails -> display the build errors.

**Comment by alexhultman** [comment]
NPM install:

* try and build, do not show any errors. if succeed -> overwrites the prebuilt
* test require('uws') -> if exception -> display build_log to the user / display messages -> emit install error

**Comment by alexhultman** [comment]
But this fucks up what already works nice. SocketCluster simply installs uws and requires it, if it fails, it simply swaps to ws and runs as if nothing has happened. The same applies to DS. If you would instead get an NPM install error that workflow would not work.

**Comment by alexhultman** [comment]
Same goes with Socket.IO. All of those projects seem perfectly happy with how the install process is, and SC's Jonathan told me to use this current install process - it works just fine for him.

**Comment by silverwind** [comment]
Build on require failure could be done like:

`node -e "try {require('./uws_darwin_48.node'); } catch(e) {process.exit(1)}" || node-gyp rebuild`

**Comment by alexhultman** [comment]
@silverwind Yep, that's nice and all but you know some users are just going to complain about "the binaries are built by illuminati, I don't trust them, the build process from source HAS to come before the pre-built binaires" (Yes my friend, I have had that comment come up before).

In short -> there are a lot of diferent people that have completely different opinions on how things are supposed to be done and the way it works currently has been a nice sweetspot for a couple of months now and most users seem to accept how it works now.

**Comment by agauniyal** [comment]
Well people won't trust pre-built binaries for a very valid reason, see what sourceforge did, and many such incidents.

**Comment by alexhultman** [comment]
@agauniyal You kind of prove my point. You simply cannot massage the inner thigh of every user at once.

**Comment by alexhultman** [comment]
Then you have the other end of the criticism spectrum: those who simply refuse to install a compiler and will simply toss the computer out the window and scream at me because it doesn't work out of the box. I have had that happen as well. Some Windows user was ultra mad because it didn't work (he didn't have a compiler and I didn't ship a prebuilt binary at that point for Windows users). So I tried to help him for like an hour and he just spew a bunch of profanity and whatnot. So I compiled the binary and published it and boom - it worked and he was happy. So yeah, this whole ecosystem of demanding users are very hard to keep up with and you kind of need to go with the flow when you have found something that works without your inbox filling up with hate.

**Comment by alexhultman** [comment]
So for the time being I think this is better discussed on Gitter, and better experimented with in a fork or branch or something like that.

**Comment by SEAPUNK** [comment]
Opening this back up, because I'm in the process of making this happen.

**Comment by SEAPUNK** [comment]
I have created a quick and dirty branch for testing install scripts and such: https://github.com/SEAPUNK/uwebsockets/tree/cleanout

@silverwind Does this work for you?:

`npm install git://github.com/SEAPUNK/uwebsockets#cleanout`

**Comment by silverwind** [comment]
Yes that works 👍 It fails to load the prebuilt on macOS 10.12 (unsure why) and falls back to building from source, which succeeds.

**Comment by SEAPUNK** [comment]
Well, that's because there is no prebuilt binaries in the GitHub repo, only in the published package itself.

**Comment by silverwind** [comment]
Ah, maybe you can print something like  `Prebuild unavilable, attempting to build...` instead of `Prebuilt addon did not work, attempting to build...` to clear that up.

**Comment by SEAPUNK** [comment]
Yeah, good point. I'll quickly make the change now so I don't forget about it.

**Comment by SEAPUNK** [comment]
https://github.com/SEAPUNK/uWebSockets/commit/7eafed1f93e0aaa3fe0a2b5ee3ea2f7926643962

**Comment by SEAPUNK** [comment]
All that's left for me to do is figure out the nodejs directory and file structure, and write the packaging script. Once that's done, then I'll open up a PR for this change. Later on, I'll also start writing test suites for the node addon, as well as an improved Travis CI script.
