### ISSUE TITLE
Desire the uWebSocket module in node v0.12.7

### ISSUE THREAD

**Issue by stuartZhang** [uWebSockets/uWebSockets#286]
Hello,

Because of the historical reasons, my web project is still built upon node v0.12.7. However, I'd like to enjoy the awesome module.

Could you please introduce Babel into the project build so that the module is also available to node v0.12.7?

As of this writing, running the module in node v0.12.7 throws SyntaxError, due to the ES 6 language features.

**Comment by SEAPUNK** [comment]
Anything below Node.js v4.x is not supported, due to those versions being EOL'd. You'll just have to catch your project up to the latest Node.js version.
