### ISSUE TITLE
c++ client example 

### ISSUE THREAD

**Issue by cjzzm** [uWebSockets/uWebSockets#287]
any repply will be appreciate 
thx

**Comment by alexhultman** [comment]
If you look in the test folder there are some examples. Especially testConnections.

**Comment by jeremyong** [comment]
The examples make no sense? All instances of Hub::connect happen before Hub::run. How do you dynamically create client connections at runtime? Sorry if I missed it but i wasn't able to find any examples that exhibited this behavior and in my test cases, connect *after* run does nothing.

**Comment by alexhultman** [comment]
@jeremyong They work just like Node.js does. Hub::run is called once and will block for ever (it is the event-loop). Compare that to how Node.js enters its event-loop after first executing the global scope of your script. Same thing here - you set up timers, connections, whatever first and then enter into an event-driven async pattern (Hub::run is identical to uv_run, which is what Node.js calls).

**Comment by jeremyong** [comment]
Thanks for the explanation @alexhultman . I had sort of (wrongly) assumed that `connect` would queue an event on the loop so additional sockets would be spawned, analogously to how the acceptor loop works. (for context, I am using this library both as a user-facing websocket server but also internal proxying/egress/ingress from node to node).
