### ISSUE TITLE
Remote IP with reverse proxy

### ISSUE THREAD

**Issue by DiegoRBaquero** [uWebSockets/uWebSockets#289]
First: Let me just say HOLY MOTHER uWS! From 450MB to 60MB RAM for 800+ active peers at a given time.

Based on https://github.com/feross/bittorrent-tracker/issues/175 I decided to take a look into uWS and try and replace ws as it was consuming RAM like Chrome does.

I had to tweak a few things but I got it working easily.

Now, the issue:
When the websockets are proxied by a proxy server like nginx (my case) the remote IP address will always be 127.0.0.1. The bittorrent-tracker module had [this line](socket.upgradeReq.headers['x-forwarded-for']) to fix that and it would be great if uWS could integrate it so no functionality is lost and enable others to do the same. About the header: https://en.wikipedia.org/wiki/X-Forwarded-For

Awesome work with this library.

**Comment by silverwind** [comment]
`ws.upgradeReq` has been dropped in 0.10.x because the sockets are no longer descended from Node.js's sockets IIRC. This breaks compatibilty with `ws`. I'll leave it to @alexhultman if this hould be reimplemented, but you can shim this property on the `connection` event for compatibilty:

````js
ws.on('connection', function(ws) {
  ws.upgradeReq = {headers: {'x-forwarded-for' : ws._socket.remoteAddress}};
  // your code
});
````

**Comment by alexhultman** [comment]
Sockets has never been net.Socket in uws. The upgradeReq exists for the time the connection handler runs.

**Comment by DiegoRBaquero** [comment]
@silverwind that won't work as I want the real IP, I already have 127.0.0.1 (ws._socket.remoteAddress)

**Comment by silverwind** [comment]
Oh, right. In that case it should be possible to access `upgradeReq` during connection and cache it as a property on `ws`. I'll try something like that later.

**Comment by alexhultman** [comment]
I don't understand the problem. uws makes use of the Node.js HTTP server so it has the same proxy features that any other Node.js lib has.

**Comment by DiegoRBaquero** [comment]
@alexhultman I can load the real IP from upgradeReq before it's nullified. My proposal is that uws provides the real IP in socket._socket.remoteAddress if it was proxied, instead of 127.0.0.1

How I did it: https://github.com/DiegoRBaquero/bittorrent-tracker/blob/0ac1c940b36e54bf3c9076529ef54737986b345c/server.js#L450-L452

If left as is, I'd be cool to add the note in docs.

**Comment by alexhultman** [comment]
So you are working with https://webtorrent.io/? If so, that's pretty sweet dude

**Comment by DiegoRBaquero** [comment]
Yeah, I'm a core team member :)

**Comment by alexhultman** [comment]
https://www.youtube.com/watch?v=vjUqUVrXclE

**Comment by silverwind** [comment]
Note that these headers for originating IP (and port) aren't really standardized and while there is [an RFC](https://tools.ietf.org/html/rfc7239) for a standard, no major reverse proxy implements it (and probably never will given the complexity of that spec). I'm feeling that this task is better left to the user.

**Comment by alexhultman** [comment]
Pssst, don't tell this to anyone but I have never used a proxy in my life. At least not directly.

**Comment by silverwind** [comment]
We should of course clearly document this, as it's a major difference to `uws` which seems to keep `upgradeReq` available during the whole lifecycle of the request.

**Comment by alexhultman** [comment]
It is documented on the front page. Under Usage -> Node.js

**Comment by lucasterra** [comment]
How would I get the upgrade headers in C++?

**Comment by alexhultman** [comment]
@lucasterra Could you maybe PR in this? The UpgradeInfo passed to the onConnection should also pass a new HTTPRequest so that you can iterate the headers there.

**Comment by alexhultman** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/src/HTTPSocket.cpp#L119

You want to also pass a new HTTPParser via the UpgradeInfo like so:

HTTPParser httpParser = (char *) httpData->httpBuffer.data();

**Comment by lucasterra** [comment]
I'll work on it and submit the PR @alexhultman. Thanks!
