### ISSUE TITLE
Question : how does uws handling slow clients ? 

### ISSUE THREAD

**Issue by meiry** [uWebSockets/uWebSockets#291]
Hello i just starting to test the lib , 
after testing libwebsockets lib , that have well defined handling in sending back frames to slow clients 
it has some internal event loop ,   
how does this lib handling the slow clients ? 
flow control

**Comment by alexhultman** [comment]
You register a callback to send -> it gets called when that memory has been handed over to the kernel.

**Comment by meiry** [comment]
Thanks for your fast replay , is there any examples ? open source projects i can learn from ? 
something ?

**Comment by meiry** [comment]
How can i avoid compiling it with OPENSSL?
using cmake i dont need ssl

**Comment by alexhultman** [comment]
You need OpenSSL to build.

**Comment by meiry** [comment]
Yeah i notice , im starting to work with it and in the end i will create beginner tutorial using this lib 
and Cocos2d-x 
as i did with libwebsockets and netty you can check them here on the left menu:

> Part 1: WebSocket Game server in C using libuv & libwebsockets

and 

> Multiplayer Card Game using WebSockets,Java Netty Server ,Cocos2d-x-HTML5 - Part 1

at this site :  
http://www.gamedevcraft.com/


as aside note in windows compilation 
the cmake doesn't include the addition path to include files and path for the lib files .
this is common problem with cmake on windows . 
also those lib's are missing as part of windows compilation : 
```
ws2_32.lib
iphlpapi.lib
psapi.lib
userenv.lib
```

**Comment by alexhultman** [comment]
If you know how to fix the CMake that would be a nice PR

**Comment by meiry** [comment]
well first it need to compile in visual studio 2015
