### ISSUE TITLE
Prebuild on Debian 7.0 needs static linking to glibc

### ISSUE THREAD

**Issue by silverwind** [uWebSockets/uWebSockets#292]
Lifted off: https://github.com/silverwind/droppy/issues/267#issuecomment-252698175

```
root@299874ffe56a:/app/node_modules/uws# ldd uws_linux_48.node
./uws_linux_48.node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./uws_linux_48.node)
    linux-vdso.so.1 =>  (0x00007fff46fa3000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa13a801000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa13a474000)
    /lib64/ld-linux-x86-64.so.2 (0x000055b1f8ef6000)
```

Would static linking be an option here? What would it mean regarding module size?

**Comment by alexhultman** [comment]
Yes you can ship the libc as part of the NPM module. Will probably be done at some point. Should add maybe 2 mb or something like that.

It seems you cannot link statically to libc, at least not when building a node addon (but I have no idea).
