### ISSUE TITLE
What is serverGroup?

### ISSUE THREAD

**Issue by Nicolab** [uWebSockets/uWebSockets#294]
Hello,

What is [serverGroup and native.server.group](https://github.com/uWebSockets/uWebSockets/blob/5ab2a0c0e5116a77056e05d698a2990fce10993c/nodejs/dist/uws.js#L328)?
A group of sockets by sub-process (fork) in a cluster mode?

**Comment by alexhultman** [comment]
A group has a set of callbacks and sockets. Server group holds server calöbacks and server sockets. It is single process single thread.

**Comment by Nicolab** [comment]
Ok, thank you!
And thanks for this great package :)
