### ISSUE TITLE
TypeError inside uws.js

### ISSUE THREAD

**Issue by iCyberon** [uWebSockets/uWebSockets#295]
So this happened twice already.
```
App 22349 stderr: TypeError: Cannot assign to read only property 'external' of 3219525
App 22349 stderr:     at /app/node_modules/uws/uws.js:394:32
```

My guess is, the passed websocket object isn't valid anymore.

**Comment by alexhultman** [comment]
I have no idea, 0.10 still seems pretty broken #290 

Eventually things will calm down and be stable again...

**Comment by alexhultman** [comment]
Could you compile and try 0.10.10 from master?

**Comment by iCyberon** [comment]
Yup, will do in a few.

**Comment by alexhultman** [comment]
It's on NPM now

**Comment by iCyberon** [comment]
👍 Just updated. Will let you know if it crashes again.

**Comment by alexhultman** [comment]
There's also 0.10.11 now

**Comment by iCyberon** [comment]
Have some feedback for you. I've tested v0.10.10 for 24 hours, about 40,000 concurrent clients at least. No crashes at all, cpu's under 4%. 👍

**Comment by alexhultman** [comment]
Nice dude, maybe 0.10.x finally got stable 🤗
