### ISSUE TITLE
µUV as an optional backend

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#298]
I've made some benchmarks of my very very initial libuv reimplementation and it does in fact bring both performance and memory usage improvements over the official libuv:

* 20k users echo, 10 messages per send: 1116 echoes/ms vs. 1133 echoes/ms
* 10k users, one message per send: 135 echoes/ms vs. 145 echoes/ms

And ofc, the main point: µWS with µUV can do 1 million connections with 202 mb of user space memory usage, while µWS with libuv does that using 355 mb.

It would be nice to have µUV be some kind of compilation flag when building the lib. I think further memory optimizations will need a more slim implementation of the libuv calls.

**Comment by socmag** [comment]
Hey Alex, what platform and configuration are these benchmarks comparing
against? Is this a Node server? The reason I ask is we can already handle
100 echo requests per second per client with 20k connections on uWebSockets
with LibUV (in C++).

Could you share what the "before" perf was as comparison.

Anyway, can't wait to try out uUV, sounds great!

cheers,
-Chris

**Comment by alexhultman** [comment]
This is C++ only. Same benchmark as always. Linux only.

**Comment by SEAPUNK** [comment]
I believe it is uWS on libuv vs uWS on uUV.

**Comment by socmag** [comment]
No I mean, I don't know (recall) what the throughput Alex was getting prior
to uWS. Undoubtedly less than now I'm sure.

And of course, the memory savings are really great to hear

**Comment by alexhultman** [comment]
Lol I clearly posted the difference. The throughput is basically the same only a little better when doing 1 message per send (stresses polling more).

**Comment by socmag** [comment]
Sorry I'm really quite blind. The little bit at the end that says. vs...

Apologies, missed that.

**Comment by alexhultman** [comment]
The diff is mainly in memory yep.

**Comment by alexhultman** [comment]
But µUV is definitely one step closer to mTCP since libuv does not support it and probably never will.

**Comment by alexhultman** [comment]
Also allows one to implement ASIO backends, leading to wider adoption -> can write one backend for Vapor and have it used from there, etc. It breaks out of the Node.js universe in short.

**Comment by socmag** [comment]
Gotcha, I'll try integrate late this week and report back. Very cool about
the memory!
