### ISSUE TITLE
Socket.IO wsEngine 'uWebSockets'

### ISSUE THREAD

**Issue by leonard-sxy** [uWebSockets/uWebSockets#301]
Thanks for the great job.  I am using uWebSockets in the below way:
```
const io = require('socket.io')(8080, {
	serveClient: true,
	path: '/socket.io',
	pingTimeout: 60000,
	pingInterval: 25000,
	maxHttpBufferSize: 10E7,
	transports: ['websocket'],
	allowUpgrades: true,
	perMessageDeflate: {
		threshold: 1024
	},
	httpCompression: {
		threshold: 1024
	},
	cookie: false,
	cookiePath: false,
	wsEngine: 'uws'
});

io.engine.ws = new (require('uws').Server)({
    noServer: true,
    perMessageDeflate: false
});
```

And I checked how engine.io constructed the WebSocketServer by using **ws**:
```
this.ws = new WebSocketServer({
      noServer: true,
      clientTracking: false,
      perMessageDeflate: this.perMessageDeflate,
      maxPayload: this.maxHttpBufferSize
});
```

So I want to know since I passed in **_perMessageDeflate: false_**, how uWebSockets will deal with this options and other options, and what are the others potential problems? Thanks

**Comment by alexhultman** [comment]
Potential problems: socket.io is a bloated piece of garbage and you shouldn't use it. Other than that, I don't know.

**Comment by leonard-sxy** [comment]
@alexhultman  LOL, I kindly agreed with u, but without socket.io, in the client side, especially the mobile devices I need to find one low level lib for providing to my client side developers, they are lazy to deal with low level stuff, sad.

BTW, do u have some good recommendations? for the client side low level RFC 6455 lib for all kinds of mobile devices?

**Comment by agauniyal** [comment]
@leonard-sxy https://github.com/search?l=JavaScript&q=websocket&type=Repositories&utf8=%E2%9C%93

**Comment by leonard-sxy** [comment]
@agauniyal thank u, yea, for browser there is totally no any problem, but for mobile devices, especially android, cannot find any actively well maintained one.

**Comment by agauniyal** [comment]
Ah okay, I misunderstood client side as mobile browsers. I've no idea about native client libraries.

**Comment by alexhultman** [comment]
There are about one million clients for Android and iOS. You can pick any client you want, it doesn't matter the slightest compared to the server.

**Comment by alexhultman** [comment]
All I'm saying is, since you ask, that Socket.IO is pure garbage. I mean it sincerely -> at deepstream we have now removed engine.io and the performance increase is astronomical. From absolute garbage to something that actually works.

**Comment by leonard-sxy** [comment]
@agauniyal  thanks a lot, checked that stack-overflow topic days ago, and after went through one by one, nearly all of them the last commit is 1 even 4 years ago...., bunch of issues no one is looking into, no any documentation etc.

And simply tested https://github.com/TakahikoKawasaki/nv-websocket-client, can work, and but this lib is actually maintained only by one guy, will try to contribute, thanks again.

**Comment by leonard-sxy** [comment]
@alexhultman thanks a lot, guess u can close this issue, will try to fully switch to uWebSockets.

**Comment by tetreault** [comment]
So barring your opinions on socket.io @alexhultman - do you have any rough estimate on how much more performant using `wsEngine: 'uws'` is in socket.io as opposed to not?

**Comment by DiegoRBaquero** [comment]
@tetreault I have tried uws in engine.io and socket.io, in terms of memory it is at least, AT LEAST, 10x better with 100+ clients.

**Comment by tetreault** [comment]
That's awesome to know @DiegoRBaquero thanks for a quick response!

**Comment by maxime1992** [comment]
@ldshi I also have `socket.io` and find it slow.
According to benchmarks here, I'm sure it'd help to setup `uWebSocket` ! 😄

If I could setup it up in a simple way, it would be perfect but I don't understand how to do that in my code comparing to yours. Can you help ?

```
const express = require('express')
const app = express()
const server = require('http').Server(app)
const io = require('socket.io')(server)
// how should I tell here socket.io to use uws ?
```

If needed, the whole file is here https://github.com/maxime1992/pizza-sync/blob/master/backend/index.js

Thanks !

**Comment by DiegoRBaquero** [comment]
@maxime1992 uws is used by default in engine.io/socket.io now. You just need to install it as it's an optional dependency. Setting it as your project's dep should work.

**Comment by maxime1992** [comment]
@DiegoRBaquero I don't understand then why it's so slow.

How can I check if it's used ?
I really just need to make a `yarn add uws` ?
Then what ?

**Comment by aPoCoMiLogin** [comment]
@maxime1992 nothing, thats enough: https://github.com/socketio/engine.io/blob/master/lib/server.js#L115

it will try to load `uws` first, then fallback to `ws`.

**Comment by alexhultman** [comment]
You can determine if it is running uws by checking the websocket upgrade headers. It clearly says uWebSockets when properly running.

**Comment by calbertts** [comment]
@aPoCoMiLogin Current Socket.IO version is not using Enging.IO 3.x yet, so isn't enough just installing `uws`
