### ISSUE TITLE
Support armhf

### ISSUE THREAD

**Issue by gigafied** [uWebSockets/uWebSockets#304]
Currently, the addons are compiled and published with the package, however arch is completely ignored when naming and loading the addons.

Somehow, running on arm seems to work right now, but I Imagine we shouldn't be using the same binary for x86 and arm.

**Comment by gigafied** [comment]
So, looks like it tries to rebuild anytime it's installed, was going off of the README:

"Prebuilt native modules are provided for most modern platforms. If the prebuilt module fails to load, gcc > 4.8.0 (or compatible) and make are required to build the native module from source."

So, no matter what it always tries to build on install, falling back to the prebuilt addon if it can't build. Think it would still be worthwhile to add arch into the naming of the prebuilt files so that armhf environments won't try to fallback to x86 binaries.

**Comment by alexhultman** [comment]
Yep. I didn't even know this compiled on ARM.

**Comment by gigafied** [comment]
Well, now you know! :) We actually cross-compile all of our addons in Jenkins, both work.

**Comment by silverwind** [comment]
@gigafied thanks, I just update https://github.com/uWebSockets/uWebSockets#nodejs-developers to be more accurate on what's actually happening when installing/loading.

**Comment by silverwind** [comment]
Oh, and I also run this on a Rasperry Pi 3 (armv7l), and I value lightweight modules greatly on such limited hardware ;)
