### ISSUE TITLE
WebSocket::close -> WebSocket::onEnd = havoc

### ISSUE THREAD

**Issue by terrywh** [uWebSockets/uWebSockets#305]
close() -> startTimeout() clears user data cause user context lost when websocket disconnect abnormaly

here is my code where `client` is the wrong pointer:
![image](https://cloud.githubusercontent.com/assets/968222/19558517/8d75d3c0-96fd-11e6-89a5-e78f27da75e7.png)

the abnormal closing came from here: `WebSocketImpl.cpp`
![1](https://cloud.githubusercontent.com/assets/968222/19558741/b7dc09bc-96fe-11e6-9f6f-d60785aa84ec.png)

**Comment by alexhultman** [comment]
Yeah this makes sense together with #297

**Comment by alexhultman** [comment]
Also makes sense that @socmag is not getting this bug since he is not using set/get data.

**Comment by alexhultman** [comment]
Nice font dude :+1:

**Comment by terrywh** [comment]
:simple_smile: happy to help.

**Comment by alexhultman** [comment]
Do you have a complete example and instructions how to trigger? When I call ws.close() it does drop the user data, but it calls the disconnection handler *before* it does this, so it is still legal for me here. How do I trigger the issue?

**Comment by alexhultman** [comment]
```c++
    uWS::Hub h;

    h.onConnection([](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo ui) {
        ws.setUserData((void *) 1234);
        std::cout << "UserData server connect: " << (long) ws.getUserData() << std::endl;
    });

    h.onDisconnection([](uWS::WebSocket<uWS::SERVER> ws, int code, char *message, size_t length) {
        std::cout << "UserData server disconnect: " << (long) ws.getUserData() << std::endl;
    });

    h.onConnection([](uWS::WebSocket<uWS::CLIENT> ws, uWS::UpgradeInfo ui) {
        unsigned char message[1] = {0xff};
        ws.send((char *) message, 1, uWS::OpCode::TEXT);
    });

    h.onDisconnection([](uWS::WebSocket<uWS::CLIENT> ws, int code, char *message, size_t length) {
        std::cout << "User data client disconnection: " << (long) ws.getUserData() << std::endl;
    });

    h.listen(3000);
    h.connect("ws://localhost:3000", (void *) 5678);

    h.run();
```

This outputs:

```
UserData server connect: 1234
UserData server disconnect: 1234
User data client disconnection: 5678
```

**Comment by terrywh** [comment]
i'm not sure how. i was using it on production server, it usually happens after a few hours waiting. when  onDisconnection is called i got segfault when reclaim the memory, the stacktrace shown below:

![stacktrace](https://cloud.githubusercontent.com/assets/968222/19562800/41026234-9710-11e6-8ca6-3e995b700e69.png)

as it get called from some unusual way.

**Comment by terrywh** [comment]
i did some digging find the same conclusion you made. let me try something tommorrow if i can produce in a controlled env. 

(i get this error every few hours on production server)

**Comment by alexhultman** [comment]
Your stack trace shows a normal graceful close. What I'm considering is the question if you are somehow getting two calls to onDisconnect - one that works and one that has the scrambled user data. You could track this by using a std::set of websockets and have onConnection add to the set and onDisconnection remove. If the set does not contain the websocket on removal you know you have somehow gotten an unbalanced set of callbacks. This way you can also track the user data along with the websocket and see if you really are getting the wrong user data

**Comment by alexhultman** [comment]
I have stress tested this server with all kinds of shit under Valgrind and whatnot - I simply cannot trigger any kind of mismatch:

```c++
    uWS::Hub h;

    std::map<uWS::WebSocket<uWS::SERVER>, void *> validityCheck;

    h.onConnection([&validityCheck](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo ui) {
        void *userData = (void *) rand();
        ws.setUserData(userData);
        validityCheck[ws] = userData;
    });

    h.onDisconnection([&validityCheck](uWS::WebSocket<uWS::SERVER> ws, int code, char *message, size_t length) {
        if (validityCheck[ws] != ws.getUserData()) {
            std::cout << "MISMATCH!" << std::endl;
            exit(-1);
        }
    });

    h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode) {
        ws.send(message, length, opCode);
    });

    h.listen(3000);
    h.run();
```

You would need to give an example of how to trigger this. How are you using the lib? What kind of functions do you use? Can you base your server on the above example and get it to trigger a "MISMATCH"?

**Comment by alexhultman** [comment]
Okay I have found a suspect now:

```c++
template <bool isServer>
void WebSocket<isServer>::close(int code, char *message, size_t length) {
    static const int MAX_CLOSE_PAYLOAD = 123;
    length = std::min<size_t>(MAX_CLOSE_PAYLOAD, length);
    ((Group<isServer> *) getSocketData()->nodeData)->removeWebSocket(*this);
    ((Group<isServer> *) getSocketData()->nodeData)->disconnectionHandler(*this, code, message, length);

    char closePayload[MAX_CLOSE_PAYLOAD + 2];
    int closePayloadLength = WebSocketProtocol<isServer>::formatClosePayload(closePayload, code, message, length);
    send(closePayload, closePayloadLength, OpCode::CLOSE, [](void *p, void *data, bool cancelled) {
        if (!cancelled) {
            Socket((uv_poll_t *) p).shutdown();
        }
    });

    getSocketData()->shuttingDown = true;
    startTimeout<WebSocket<isServer>::onEnd>(0);
}
```

If send fails here, it will call WebSocket::onEnd before we have set shutdown to true, so it will call the disconnection handler twice.

**Comment by alexhultman** [comment]
So in your case you are probably having a double-free issue rather than the user data being reset. Since the disconnection handler might be called twice you will delete the same memory twice and segfault on that. Right?

**Comment by alexhultman** [comment]
Ah! I can see that you are absolutely correct. The stack trace you sent actually shows this exact thing. Sorry I missed that it was not a proper graceful close.

Yes you can see that your WebSocket::close calls into WebSocket::onEnd, because of the failed send.

**Comment by alexhultman** [comment]
@terrywh Could you try with 62d93cb572eb6b57e500df06d57685156eec5b36

**Comment by terrywh** [comment]
confirm fixed.

**Comment by alexhultman** [comment]
Thanks for the trace
