### ISSUE TITLE
Websockets randomly closing with code CLOSE_ABNORMAL when using autoping

### ISSUE THREAD

**Issue by lawlmart** [uWebSockets/uWebSockets#313]
I just upgrade uws and enabled autoping and after 10-20 seconds my sockets are closing with code 1006. Am I misunderstanding the purpose of autoping, or is this a bug?

**Comment by alexhultman** [comment]
If you pass a message to it, the client needs to respond in time.

**Comment by lawlmart** [comment]
I assumed this was lower level than the client js interface, but are you saying I need to call ws.send for every onmessage callback?

**Comment by alexhultman** [comment]
You need to read the release text, and also tell me more than this. You haven't really described anything of what you are doing. I cannot guess what you are trying to do. We use this autoping feature at DS and it works there.

**Comment by lawlmart** [comment]
It's just a basic node server and chrome client. I'll just go back to my own scheme, apologies.

**Comment by sd031** [comment]
I am also getting that CLOSE_ABNORMAL when using autoping with code 1006 , any fix ?

**Comment by ad34** [comment]
I also use autoping, working fine on local server, but on AWS (ALB).

I got a disconnection after a 2 minutes or so with code 0x3ee (1006, CLOSE_ABNORMAL) and no message.

I use a workaround : I sent a lightweight message with send every 30 seconds and it fixes the issue (no disconnection) 

@alexhultman not sure if it's related to uWebSockets in itself, but the autoping feature is not working properly with AWS Application Load Balancer.
