### ISSUE TITLE
Getting 502 errors often

### ISSUE THREAD

**Issue by valeriansaliou** [uWebSockets/uWebSockets#314]
Hello there!

We are using uWS successfully on Crisp (https://crisp.im/) since last July, and I must say it helped us reduce tremendously our server load, thanks!

However we are running into an issue that can happen to all clients often, but not everytime. We get a lot of 502 errors. More below.

First, some details on our architecture:

 - Running latest Socket.IO + uWS versions, with Socket.IO-Redis for sharding
 - A pool of Debian Jessie 32 bits workers, running Node v6.9.1 (ulimits are fine)
 - 4 edge servers running NGINX
 - CloudFlare WebSocket on the top of it

--

Since we updated to the reworked 0.9 uws (now we are running latest 0.11), we notice a persistent issue across all versions that are 0.9+: some sessions cannot be started because the socket server returns a 502 to the HTTP upgrade request. Thus, this is fully independent from any code we wrote (we use the standard NodeJS `http` server module). We suspect the issue comes from `uws.Server` itself.

We initially thought CloudFlare had some issues at some locations, but we could trace the 502s in our NGINX edge logs, which then traced back to the socket servers.

**Our initialization code for Socket.IO/uWS:**

```javascript
    this.server = http.createServer();

    this.server.listen(
      this.__listen_config.port,
      this.__listen_config.host
    );

    this.io = socketio.listen(this.server, {
      path : "/"
    });

    this.io.engine.ws = new (require("uws").Server)({
      noServer                    : true,
      perMessageDeflate  : false
    });
```

So now the question is: can this be an internal Node error (stated by the node word at the beginning of the trace), or could uWS be linked to this (does it bind any component from itself to the pre-WebSocket upgrade process?).

As you would guess, this issue is quite annoying since it prevents some Socket.IO clients to connect, thus the chatbox from appearing. Socket.IO retries 10-20 secs later and the following connect usually works fine.

Thanks for your work on uWS.

Cheers,

Valérian.

**Comment by alexhultman** [comment]
Why did you edit out the "trace":

```
The error trace we get (only this):

(node:10086) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): undefined
```

You need to provide a full trace (not just the very tip) otherwise there is no chance I can help in any way. uws does not make use of promises and it does not reject them either. It seems you are missing some kind of catch in your JS code.

**Comment by valeriansaliou** [comment]
The "trace" has been edited since I did further checks and this one was our fault.

But, definitely the 502 errors are not linked to our code since they occur during the HTTP upgrade process/request.

Do you have any recommended way I can run some dumps on Node and get internal traces to confirm it is related to uWS? Thanks!

**Comment by alexhultman** [comment]
You still need to provide more info. This doesn't really tell me anything to go by. Does the Node.js process crash? If so, where does it crash, how does the stack trace look like. Etc, etc. The fact that your NGINX reports bad gateway doesn't really tell me anything.

Since you posted a promise rejection error, that you later decided was caused by your own code - that makes me wonder if you really did *only* update uws and nothing else. I think you need to dig deeper into your own code and report issues here only if you find that something is wrong with uws (which absolutely can be the case). First of all you need to check if the Node.js process crashed at all, and if so you need to dig deeper. There has been some small behavior changes in uws that might trigger problems for you.

**Comment by valeriansaliou** [comment]
Found an explanation coming from the CF <> NGINX setup we have. I close this for now and will do further check on uWS side before reporting anything if it happens again. Sorry for bothering!

**Comment by alexhultman** [comment]
You can report any issue but it has to be approachable in some way. I cannot figure out things from very general errors.

**Comment by prdn** [comment]
@alexhultman same issue is happening to me too. I have a nginx + uws (node.js) setup.
On production, where I have a huge ws traffic, it happens once every few minutes. I'll try to collect more informations I can to help you debugging and in the meantime I switched back to 0.9 version.

**Comment by valeriansaliou** [comment]
@prdn not happening for us anymore. Can you tell a bit more about your setup? I fixed it using a trick that I suspect caused it.

The big picture: we have 4 socket workers, 4 NGINX load balancers on the top of it, Cloudflare on the top of NGINX. If there's some Websocket timeout or else, then NGINX declares the socket worker as dead for 10 seconds, and isolate it from the pool for 4 workers. But, it reports a 5xx error to Cloudflare, which itself also runs on NGINX and has the same "isolation" techniques. Thus, Cloudflare put the edge load balancer that reported the 5xx message in its "isolation" pool for a few seconds.

The trick we implemented is a combination of techniques to fool each NGINX layer not to isolate the socket. We rewrite all 5xx to a static 4xx code (fixes Cloudflare isolation mechanism), and we disabled our NGINX load balancer dead worker detection. It fixed all our issues, but I believe some people still get 5xx errors. At least it's not propagated to everyone via the NGINX health check.

This issue might be related to uWS as we didn't experience such issues before we bumped up to the reworked uWS. But, you can alleviate it on an higher level.

**Comment by prdn** [comment]
@valeriansaliou thanks for sharing your experience.
I will for sure mimic your solution until a general fix is found.
We use the same setup (CloudFlare included!).

**Comment by valeriansaliou** [comment]
@prdn do you need the configs we use to trick it emailed? We can continue this by email as it's more related to our setups than uWS, I guess.

**Comment by prdn** [comment]
sure thing @valeriansaliou 
paolo@bitfinex.com
thanks for helping

**Comment by alexhultman** [comment]
I cant think of any reason why 0.9 would work better than 0.11. If you are sure the process where uws runs in does not crash or hang but still works after the 5xx then I can only suspect the setup. If nginx has a timeout and the socket server does not respond in time then that sounds more like a load balancing issue rather than an uws issue. Socket.io is not known for being reliable and fast you know.

If you can show a crash or hang or restart of the socket server then I can help with fixing it but otherwise I cannot possibly help.

**Comment by alexhultman** [comment]
I do however appreciate info like how you solved it, etc. Keep that debugging info coming.

**Comment by valeriansaliou** [comment]
@prdn email sent.

@alexhultman I will be waiting for feedback from @prdn - if it fixes all errors for him too, and will suggest the NGINX configuration tricks here so that it can help other people having such issue.

I have no socket server crash or hang on my side. So I guess it's a misconfiguration issue.
