### ISSUE TITLE
uws incompatible with node 7.x on win

### ISSUE THREAD

**Issue by Shastel** [uWebSockets/uWebSockets#315]
Unhandled exception throw while executing `uws/uws.js`.
That's behaviour wasn't observed with node 6.9.1
![image](https://cloud.githubusercontent.com/assets/6017041/19837275/2a61268a-9ebf-11e6-9263-5ab6c9eafbd4.png)

**Comment by SEAPUNK** [comment]
Yeah, that's probably because the ABI number for Node v7 has changed, so the packaged binaries aren't available for uWS.

You'll need node-gyp and its requirements installed if you want it to compile the binary for you when the precompile check fails, see "On windows" of the [node-gyp readme](https://github.com/nodejs/node-gyp#installation)

**Comment by Shastel** [comment]
So as far as i undersand that issue can be solved for futher release by adding few lineslines to Makefile simillar to othe other node versions

**Comment by alexhultman** [comment]
Yes, there will always be a slight gap of incompatibility with the latest version of Node.js. This happened to 5, it happened to 6 and it will happen to 8.

**Comment by silverwind** [comment]
Regarding `node-gyp`: Can't it be bundled with the module as a dependency? I don't think I've ever had to install it manually for other native modules.

**Comment by SEAPUNK** [comment]
@silverwind `node-gyp` the program is bundled with Node.js itself. However, that's not the issue -- `node-gyp` requires compilation prerequisites installed, and those are platform independent.

**Comment by alexhultman** [comment]
Is the raspberry fun? I wanted the zero version but then I realized you need a lot of utilities like keyboard and screen and all of that to run it. Would be nice to set up it as some kind of ssh terminal thing you can login to.

**Comment by silverwind** [comment]
Yes, I run a number of web services on it and it's more than enough for my purpose. I run it purely headless and access it only over SSH. I'd advice to at least get a 2, better 3. The zero and the 1 are far to low-powered to run anything of use (compiling node.js takes 7 hrs on a 1, compared to 1 hr on a 3). Oh and I run [Arch Linux ARM](http://archlinuxarm.org/).

**Comment by alexhultman** [comment]
So the naming will need to include process.arch. And on Windows we cannot use "cp" to copy the module. #315

**Comment by alexhultman** [comment]
#304
