### ISSUE TITLE
About multithreaded echo

### ISSUE THREAD

**Issue by smallnewer** [uWebSockets/uWebSockets#316]
I want to multithread, but the `examples/multithreaded_echo.cpp` is empty. 

I use uWebSockets@v0.11 with libuv。 Can I use uWebSockets@v0.11 like `examples/multithreaded_echo.cpp`@v0.9 ？Thank you.

**Comment by alexhultman** [comment]
You can check in tests folder for examples of multithreading

**Comment by smallnewer** [comment]
I get tip `//testMultithreading(); // FAILS IN µUV` from `tests/main.cpp`.
It's mean "works on libuv" ?? I'm not sure~~

**Comment by alexhultman** [comment]
#244
