### ISSUE TITLE
websockets/ws faster than uws?

### ISSUE THREAD

**Issue by netwriter2** [uWebSockets/uWebSockets#321]
Or at least it claims to be? o.O

"probably the fastest WebSocket library for node.js"

**Comment by SEAPUNK** [comment]
Oh boy.

**Comment by alexhultman** [comment]
Isis claims to win the war.

**Comment by netwriter2** [comment]
Alright thanks. It's confusing though.

**Comment by SEAPUNK** [comment]
Well, y'know how marketing goes. Every car salesman against each other.

**Comment by alexhultman** [comment]
@netwriter2 Created user today, has two comments in total, both in this thread. Hello troll, you are blocked.
