### ISSUE TITLE
Simple handler for non-websocket connections in websocket-server

### ISSUE THREAD

**Issue by not-implemented** [uWebSockets/uWebSockets#323]
Is there currently a possibility to handle non-websocket clients, too?

If I am right, those connections are currently just closed in https://github.com/uWebSockets/uWebSockets/blob/master/src/HTTPSocket.cpp#L121 ... does it make sense to implement a Callback and a simple interface here?

**Use-Case:** Implement a **HTTP-Long-Polling-Fallback** for non-websocket-clients in one single Server.

Do you have a better idea for this? Do you like the idea of an additional callback here? If yes, I'll try to implement this as a pull-request.

**Comment by alexhultman** [comment]
Yeah there will be Http support at some point. But it has to be very fast. I have an experimentation repo that is 7x faster than Node.js (well a monkey can write a faster Http server than Node.js but still).

**Comment by alexhultman** [comment]
You know, if I get the foundation done in uws I can just slap on V8 and release my own infrastructure and have Node.js users swap to my platform.

**Comment by not-implemented** [comment]
Hehe ... so, you already have a test-implementation of pure HTTP-Request handling?

**Comment by alexhultman** [comment]
I have a prototype that is separate from this project. If you want, go ahead and add an onHttp callback and we can take it from there.

**Comment by hekigan** [comment]
Long polling as a fallback would be definitely great to have

**Comment by alexhultman** [comment]
It's not for long polling I'm interested in this, long polling is very over hyped and is not needed for a modern web app anyways. WebSockets are like 6 years old and if your browser does not have WebSockets then it probably does not have any of those fancy other things. If you want to support IE6 you should probably write your app in ActiveX or Flash :wink:

**Comment by not-implemented** [comment]
I completely agree ... but sometimes it is not a problem with old browsers, but with old or restricted proxys or firewalls of companies. And if you have requirements to also support users behind them, you definitely need a Long-Polling-Fallback ...

But anyway, if we have a onHttpRequest()-Callback, it is up to the application how it will use it :-)

**Comment by alexhultman** [comment]
I heard that's a long lived myth. SocketCluster authour claims that wss (SSL WebSockets) work with all proxies. He is known to be very much against long polling: https://blog.baasil.io/why-you-shouldnt-use-long-polling-fallbacks-for-websockets-c1fff32a064a#.krpyb3yaf

Long polling is just a myth created by Socket.IO author to have a feature to sell his garbage with.

**Comment by alexhultman** [comment]
My understanding is that a proxy cannot possibly read the stream when it is SSL:ed so it cannot differ between HTTP and WS, so it simply will have to let it pass. So yeah, if that is correct then you can actually guarantee that all proxies will work (if they support SSL). If the proxy could read the SSL stream then the entire idea of encryption would be lost. The proxy does not have the same certificate as your private server behind the proxy.

So yeah, my understanding is that long polling is completely over engineering / myth / FUD.

**Comment by not-implemented** [comment]
Ok yes, with TLS this may be correct. But yes, it's an interesting approach in any case. I'll try to evaluate if we can drop our WS-without-TLS support completely (it's currently also a CPU issue for us) and then try to drop Long-Polling-Support, which is of course a big overhead in the C++ re-implementation and for the net/bandwidth.

**Comment by jondubois** [comment]
@not-implemented As Alex mentioned Using wss:// instead of ws:// fixes the proxy issue. You can get free TLS certs from letsencrypt.org or you can generate self-signed ones for testing - I think that this solution is much better, simpler and more scalable than long polling.

I think that there is a lot of misinformation about WebSockets - Companies like Pusher and PubNub (among many other as-a-service offerings and even some open source solutions like Socket.io) leverage this misinformation to convince developers that WebSockets is difficult and basically doesn't work.

**Comment by not-implemented** [comment]
@jondubois I completely agree. There are just some more things for us to think about - we are currently pushing about 200.000-1.000.000 packets per second to the clients - so we have to care about CPU usage and backward-compatibility and such things, when re-implementing the server side :-)

**Comment by alexhultman** [comment]
I'm very much interested in adding HTTP support. It's one missing feature that could transform this lib into a complete server solution, pretty much.

I'm thinking of adding onHttpRequest and onHttpDisconnection - that should be enough to expose the HTTP protocol. This will also clean up the whole HTTP part of the lib (which currently is a mess).

**Comment by not-implemented** [comment]
@alexhultman sounds good :-)

**Comment by alexhultman** [comment]
http://79.136.86.141:3000/

**Comment by alexhultman** [comment]
uWS::Hub h;

    h.onHttpRequest([](uWS::HTTPSocket<uWS::SERVER> s) {
        char response[] = "<html><body><div style=\"background-color: red; text-align: center; color: white; border-radius: 5em; margin-bottom: 1em\">µWebSockets v0.13.0</div><center><img src=\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRUCEoO6dkQsWZdvGqpJkDLdnkdEHCo-1a6Yf5k_HwjO1VrdbAiOg\" /><center></body></html>";
        s.respond(response, sizeof(response) - 1);
    });

    h.listen(3000);
    h.run();

**Comment by not-implemented** [comment]
Very cool. Looks good on the first look. (But an interface for setting the headers in respond() is needed in any case I think :-))

**Comment by alexhultman** [comment]
Lol I made this today - didn't know it would be so straightforward :tada:

**Comment by alexhultman** [comment]
The Node.js wrapper seems to perform 5.75x faster than Node.js which is a significant speed-up.

**Comment by alexhultman** [comment]
Lol and I haven't even optimized the parser - it is just a for-loop now ROFL Node.js is such garbage
