### ISSUE TITLE
Websocket Server callback not being called

### ISSUE THREAD

**Issue by soylomass** [uWebSockets/uWebSockets#324]
In my application I launch a websocket server with a different port per game room, and it happens randomly (but once it happens once it keeps repeating, and it always happens after I have 2 websockets servers running with 25 people connected each, more or less) that when I launch a Server, the callback isn't being called:

`
this.socketServer = new WebSocket.Server({
            port: port,
            perMessageDeflate: false
        }, function() {
            setTimeout(this.mainLoop.bind(this), 1);

            console.log("Listening on port " + port);

        }.bind(this));
`

It also doesn't call the "error" event.

What could be happening?

My OS is Debian 7.5 with 12GB of RAM and 6 cores

**Comment by alexhultman** [comment]
The callback is passed to the Node.js http server, uws never calls it directly.

**Comment by soylomass** [comment]
Can you guide me on where I should look for a solution please?

**Comment by alexhultman** [comment]
It's not realted to uws, if the Node.js HTTP server does not call the callback that is not up to uws
