### ISSUE TITLE
Make Utf8 validation optional

### ISSUE THREAD

**Issue by jgupta** [uWebSockets/uWebSockets#328]
Can we make isValidUtf8 optional?

**Comment by alexhultman** [comment]
No it is a strict part of the standard. Send as binary to get away without this check.

**Comment by jgupta** [comment]
Yes, you are correct but given we are sure all messages are UTF8 or we just want to go nuts and have maximum performance, we should have that flexibility.

http://autobahn.ws/python/reference/autobahn.websocket.html#autobahn.websocket.protocol.WebSocketServerFactory.setProtocolOptions

Autobahn lets us set utf8validateIncoming to false to avoid validation.

**Comment by alexhultman** [comment]
So send the text as binary.

**Comment by jgupta** [comment]
If we do that, we loose compression ratio.

Plus, we do some actions based on message so we would have to convert binary to text on server which would waste CPU.

**Comment by SEAPUNK** [comment]
How do you lose compression ratio? The message packet is practically the same thing, just under a different bit flag.

**Comment by SEAPUNK** [comment]
That, and you'd still be converting binary to text regardless. The only difference is _where_ it's being converted -- inside of uws, or inside your code.
