### ISSUE TITLE
Does not compile against libUV 2.x

### ISSUE THREAD

**Issue by kolis** [uWebSockets/uWebSockets#329]
In livUV 2.x we have version tags like
```
#define UV_VERSION_MAJOR 2
#define UV_VERSION_MINOR 0
#define UV_VERSION_PATCH 0
```
https://github.com/libuv/libuv/blob/master/include/uv-version.h

But Hub.h only check minor version, which does not accept the 2.x version
```
static_assert (UV_VERSION_MINOR >= 3, "µWebSockets requires libuv >=1.3.0");
```

**Comment by alexhultman** [comment]
There is no libuv 2
