### ISSUE TITLE
core in websocket::close problem

### ISSUE THREAD

**Issue by luxiao9999** [uWebSockets/uWebSockets#330]
in multithreaded_echo.cpp example ，if we do a really long time blocking job in onMessage callback, the server will core 
occasionally in WebSocket::close function (uv_close)，i did not find  the reason，why？

following is the code:

#include <iostream>
#include <string>
#include <thread>
#include"CJsonWrap.h"
using namespace std;
#include <uWS.h>
using namespace uWS;
#define THREADS 4
Server *threadedServer[THREADS];
int DoTask(WebSocket socket, char *message, size_t length, OpCode opCode)
{
    CJObject stObj;
    string sMsg="";
    if(!stObj.Parse(string(message,length)))
    {
        sMsg="parse request error";
        socket.send(sMsg.data(), sMsg.size(), opCode);
        return -1;
    }
    string script=stObj["script"];
    script=replace_all(script,"\\n","\n");
    string sFilePath="/tmp/"+sSessionid+".sh";
    SaveFile(sFilePath.c_str(),(char *)script.data(),script.size());
    chmod(sFilePath.c_str(), S_IXUSR|S_IWUSR|S_IRUSR);
    char buf[2048];
    int n;
    FILE  * stream=popen(sFilePath.c_str(),"r");
    if(stream==NULL)
    {
        sMsg="\tcmd excuse failed\n";
        socket.send(sMsg.data(), sMsg.size(), opCode);
        remove
            (sFilePath.c_str());
        return -2;
    }
    while((n=fread( buf, 1, sizeof(buf), stream))>0)
    {
        buf[n]=0;
        socket.send(buf, n, opCode);
    }
    pclose(stream);
    remove
        (sFilePath.c_str());
    return 0;
}

int main()
{
    try
    {
        EventSystem es(MASTER);
        Server server(es, 3000);

        server.onUpgrade([](uv_os_fd_t fd, const char *secKey, void *ssl, const char *extensions, size_t extensionsLength){
                             threadedServer[rand() % THREADS]->upgrade(fd, secKey, ssl, extensions, extensionsLength);
                         });
        // launch the threads with their servers
        for (int i = 0; i < THREADS; i++)
        {
            new thread([i];
                      {
                           EventSystem tes(WORKER);
                           threadedServer[i] = new Server(tes, 0);
                           threadedServer[i]->onMessage([i](WebSocket socket, char *message, size_t length, OpCode opCode){
                                                            DoTask(socket, message, length, opCode);
                                                        });

                           tes.run();
                       });
        }
        // run listener
        es.run();
    }
    catch (...)
    {
        cout << "ERR_LISTEN" << endl;
    }

    return 0;
}

**Comment by alexhultman** [comment]
This version is no longer supported. You should upgrade to 0.11
