### ISSUE TITLE
WebSocket close should accept a const char* message

### ISSUE THREAD

**Issue by llchan** [uWebSockets/uWebSockets#333]
It currently takes a `char *` and should take a `const char*` instead. I can send over a PR unless there's a legitimate reason for it to be able to mutate the message.

**Comment by alexhultman** [comment]
It would be nice if you could PR all the const misses. Make everything const that can be const.

**Comment by llchan** [comment]
Yep, was going to sprinkle const where it makes sense to.

It's not clear what tests should pass before submitting the PR, am I supposed to uncomment the autobahn test in tests/main.cpp and build/run that? For this particular change, I expect functionality to remain unchanged, so as long as everything compiles it should work the same as before.

Btw, just to be clear, this commit would have to be released on a major (well, minor since we're pre-release) version bump since the callback function signatures will change.
