### ISSUE TITLE
uWS and Node.js 7.1.0

### ISSUE THREAD

**Issue by VooVoo01** [uWebSockets/uWebSockets#339]
After upgrade node.js by version 7.1.0 the uws has stopped work with message:
_/node_modules/uws/uws.js:25
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'._
I’ve tried to reinstall uws and C++ compiler without any success. Only recover the node 6.9.1 makes possible to use the uws.

Operating system: Linux and Windows
Platform/language: Node.js

**Comment by rensrongen** [comment]
Yes, check out #315 
This should be resolved in the next version.

**Comment by xFirez** [comment]
@rensrongen What version is compatible then?

**Comment by alexhultman** [comment]
It's released as 0.11.1 now
