### ISSUE TITLE
Use C++-style casts

### ISSUE THREAD

**Issue by llchan** [uWebSockets/uWebSockets#343]
Are there any objections to using C++-style casts and just tightening up type handling in general?

It makes me nervous to see C-style casts everywhere. I noticed this most in the callbacks where a `*this` of type `WebSocket<isServer>&` is passed in as a `void*` argument and then casted to a `uv_poll_t*` on the other side. This is very tightly coupled to the exact memory layout of `WebSocket<isServer>`, and if that ever changed we could have a problem.

I'm happy to put together a PR, but this will most likely change some function signatures so wanted to get some feedback first.

**Comment by llchan** [comment]
To be more explicit about the "tightening up type handling in general": I don't think we should be using `void*` anywhere outside of maybe user-supplied data (even then, I think I'd rather have that be a std::function or somesuch). I'd propose we replace those with the proper types. Even if we object to inheritance or virtual function calls, I'm sure we can still come up with something that's type safe.

**Comment by alexhultman** [comment]
The general idea is to do it "C with classes" rather than "die hard C++" where it makes sense to. For instance a lot of people have made remarks about not using "feature X" of STL instead of rolling that particular feature from scratch.

Everything that has a runtime overhead (memory or performance) of C++ is disqualified from the internals. So the issue is really about syntax preference: static_cast type(x) or (type).

If you mean the send callback where a void ptr is used to construct a WebSocket then yes I agree that is kind of strange but there is nothing wrong with it, the void ptr is a uv_poll_t ptr and WebSocket constructor takes a uv_poll_t

**Comment by llchan** [comment]
I agree with what you're saying, and have no problems with avoiding the STL to maintain control over implementation and memory allocations. I work with high performance code and we basically never use the STL when performance matters, so I understand where you're coming from. That said, STL and C++ are not the same thing, and I'm only talking about C++ type safety here.

A C-style cast is a `reinterpret_cast`, not a `static_cast`, and it just throws everything the compiler knows about the type out the window. So it's not merely a syntax difference, it changes the types of errors the compiler can catch. I have no serious concerns about correctness of your code, and I'm sure you can reason about your types mentally without the compiler's safety checks, but having the typing explicitly laid for the compiler makes it easier for others to dive in and make modifications without having to replicate your mental model.

The send callback is indeed what I was looking at, and I'm not saying it's wrong, I would just prefer for a cast through `void*` to have same type on both sides, or at least both be pointers instead of casting a reference to a pointer. i.e. instead of `callback(*this, ...)` it could be `callback(static_cast<uv_poll_t*>(*this), ...)` or better yet there could be an accessor on `Socket` to get the underlying `uv_poll_t*` instead of relying on the conversion operator. The code as it stands now relies on the `uv_poll_t*` pointer being at the same address as the websocket itself, which makes a very strong assumption about the memory layout. The field is also protected, and pulling it out via a C-style cast seems like a violation of its encapsulation.

I want to make it clear that I'm not judging the code or your abilities (in fact, I want to say that I am impressed so far), nor am I here to be a purist about C++ or anything, I'm just suggesting changes to make it easier for other people to help out more easily and more safely by relying on the compiler more.

**Comment by alexhultman** [comment]
That's not entirely true. C styled casts have static type checks, but not to the same extent. If you look in Socket.h you see there's a conversion operator to uv_poll_t ptr. So what happens is WebSocket implicitly converts to uv_poll_t ptr as is allowed only to then convert to void ptr and then at the receiving end convert the void ptr to an uv_poll_t ptr which is used to construct the WebSocket. This entire chain of conversion is statically checked and valid and does not rely on any particular memory layout. It is strange, yes. I would like to have it simpler yes but this was done to allow separation of modules while still providing zero-cost passing of the WebSocket.

**Comment by alexhultman** [comment]
Well obviously any void ptr is not statically checked but I meant the chain of conversion is valid and allowed.

**Comment by alexhultman** [comment]
C styled casts are like static_cast but can fall back to reinterpret_cast. So if you try to convert an integer to a string (with C styled cast) this will statically fail, while reinterpret_cast would succeed. There are static checks in C but what C++ casts add is a more explicit mark where things are totally static and where things are unsafe. As long as you have a decent idea of what you are doing C should be fine.

**Comment by llchan** [comment]
Ah you're totally right on that one, it just feels unnatural so my gut reaction was to reject it. I actually didnt see the conversion operator on Socket until I was writing my comment, so I didnt realize it was doing the static cast. In retrospect I should have re-evaluated my original claim once I saw the conversion operator. My bad :)

Nevertheless, I think using an explicit static_cast there and would have made the intentions more obvious, and I still stand by my request to replace the C-casts with C++-casts.

**Comment by llchan** [comment]
With regards to allowing separation of modules without any overhead, I think that's a fine goal to strive for, but I'm curious why we dont use `uv_poll_t*` instead of `void*`? Is there something I'm not considering?

**Comment by alexhultman** [comment]
uv_poll_t ptr would be better than void ptr yeah. Esp since that is the type you pass to WebSocket constructor. But this is just how it is currently, there can always be improvements.

**Comment by alexhultman** [comment]
I mean, changing void ptr to uv_poll_t would be a good idea. I don't care for a stable API, people will have to change with it.

**Comment by llchan** [comment]
Cool, got it. Just wanted to verify that there wasn't a case where something else is passed through the `void*`.

Do you have any thoughts on using C++ style casts in general? If you feel strongly about it I'm not pushing for it that hard, but I think it would be a net benefit to be precise at the expense of a few extra characters of typing. I'll even do it for you ;)

**Comment by alexhultman** [comment]
Sure if you feel like replacing all C styled casts with static_cast (and whatever else is needed) then I won't hold that back. But there are a lot of them.
