### ISSUE TITLE
Can't run Benchmarks?

### ISSUE THREAD

**Issue by pyros2097** [uWebSockets/uWebSockets#344]
Include the following information (where applicable):

* What operating system are you running?
  * Linux
* What platform/language are you using?
  * C++
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* Can you show me some short code that triggers your issue?
    running sudo make in benchmarks folder
    This is the error I get
     ```
      g++: error: /usr/lib/libwebsockets.a: No such file or directory
    ```

I followed the instructions and did make install in the make project folder and it added a file to
`/usr/lib64/libuWS.so` but how do you build the libwebsockets.a file. Then found out that I needed to get libwebsockets and then I couldn't get that installed. Maybe there should be more documentation on how to do this. I seriously want to test the benchmark on my overpowered gaming laptop.

Also to verify this https://github.com/amark/gun/issues/261

**Comment by pyros2097** [comment]
More light on this issue.
I downloaded libwebsockets 2.0.3 and then read README.build.md and then built it using this command,
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .
```

and then tried running the benchmarks and this is the error I get. What version does the latest master use to benchmark it.
```
g++ -std=c++11 -O3 lws.cpp -o lws /usr/lib/libwebsockets.a -lev -lssl -lz -lcrypto
lws.cpp: In function ‘int main(int, char**)’:
lws.cpp:138:46: error: ‘ev_default_loop’ was not declared in this scope
     lws_ev_initloop(context, ev_default_loop(), 0);
                                              ^
lws.cpp:138:50: error: ‘lws_ev_initloop’ was not declared in this scope
     lws_ev_initloop(context, ev_default_loop(), 0);
                                                  ^
lws.cpp:139:29: error: ‘ev_run’ was not declared in this scope
     ev_run(ev_default_loop());
                             ^
make: *** [Makefile:7: default] Error 
```

**Comment by alexhultman** [comment]
libwebsockets is very complex and requires you to have compiled it with libev support. I checked your repo though, and you are talking about swapping from ws in JS.

You don't need to check with libwebsockets to make that decision.
