### ISSUE TITLE
Optimize JS part

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#345]
Finally someone who shows how extremely slow most of JavaScript is: https://youtu.be/BEqH-oZ4UXI

I will need to go through the current JS code and see if things can improve.

**Comment by sapeien** [comment]
Sounds interesting. Would there need to be a uWS + Node.js benchmark to actually measure performance improvements here?

I only found JS benchmarks for `ws` and socket.io: 
https://github.com/uWebSockets/uWebSockets/blob/master/benchmarks/ws.js
https://github.com/uWebSockets/uWebSockets/blob/master/benchmarks/socketio.js

**Comment by alexhultman** [comment]
You can use the same benchmarks against uws (the Node.js addon) as with µWebSockets (the C++ only server library). Yes, I cannot even keep up with my own naming schemes anymore.

**Comment by kapouer** [comment]
Interesting, for example in paths.js i'm not sure the listeners are cached functions.

**Comment by alexhultman** [comment]
The problem with videos like this one: https://www.youtube.com/watch?v=UJPdhx5zTaw is that they focus so hard on one single for-loop (which in itself doesn't even perform the same as native!!) and don't really dig into the **other parts** that JS devs just take for granted and add and add and add and add until there is nothing but a miserable blob of terrible performance.

**Comment by kapouer** [comment]
Precisely. That's why i only mention the point he makes about functions not declared on the root scope.

**Comment by alexhultman** [comment]
The fact that Array.forEach(cb) performs 6x worse than a for-loop is a real testimony to how out of touch JS developers are. You constantly get this idea of "functional scripting" being the only right way shoved down your throat, and yet it absolutely wrecks your program. Literally - using Array.forEach turns your entire program into garbage. Calling functions turns your program into garbage too. Pretty much everything that is not a 1 line for-loop running with an integer for several seconds turns your program into garbage. The problem with JS is, JS. The more JS features you use in your JS program the worse it gets.

**Comment by sapeien** [comment]
Well, not all JS developers are mouth-breathers. Some of us do care about performance.

The reason why `Array.prototype` methods are slow in general is because of the edge cases they have to consider, such as skipping indices in sparse arrays, which incur some runtime cost.

As for the function call cost, there's no way around that, other than using a language with macros than can translate to JS and inline the function that way.

Otherwise it is often faster to re-implement JS in JS: https://github.com/fortunejs/fortune/blob/master/lib/common/array/map.js

Also, a lot of the new ES6 features such as Promises are significant slower than callbacks and userland implementations are much faster.

**Comment by alexhultman** [comment]
Yeah but it's just so frustrating having a server that can go up to 150x faster than ws only to have it crippled by a few lines of JS down to only 10x faster when used from JS. I get really really upset when that happens -> the cost of calling a JS function that in turn calls a JS send function bottlenecks the server completely.

**Comment by billouboq** [comment]
The problem with JS is not JS, it's V8. He seems to be slower than other actual javascript engine and that is sad since it's the one used in NodeJS. One day we could use other engine like chakra or LLV8 and it will be fine.

**Comment by alexhultman** [comment]
That's a very naive and ignorant claim. JavaScript is a **scripting language** just like Python, Ruby, Perl and Lua. It is not a **systems programming language** like Fortran, C, C++, Rust or Swift.

The difference is a script displays no kind of static information whatsoever, while a non-script does. The more scripting features you use the more confused the interpreter/"compiler" gets. Do you really think that 8 years of hard work by the best Google engineers in creating V8 has failed to provide any kind of real performance simply because they were incompetent? V8 cannot even "compile" a single for loop as performant as Swift. That's about two or three Intel CPU instructions!

**Comment by billouboq** [comment]
>  Do you really think that 8 years of hard work by the best Google engineers in creating V8 has failed to provide any kind of real performance simply because they were incompetent?

I'm not saying they are incompetent, I'm saying they are not working on javascript performance as much as other Javascript Engine, and that's because they are focusing on other things like memory consumption, garbage collector and that's great too.

But my claim is real, you just have to do hybrid application to see it. Android webview is using v8 and it is in some cases it is 5x slower than iOS hybrid application which has a different javascript engine.

**Comment by alexhultman** [comment]
If they are "focusing on memory consumption" then they have failed astronomically. 1 mil connections without JS requires roughly 200 mb of user space memory while those 2% JS boost that requirement up to 2 gb. There is no doubt whatsoever that JS and JS only majorly bottlenecks this project in all measurable dimension. Majorly.

**Comment by socmag** [comment]
This reminds me of one of my rants...  Only better.

Yep,  script is script is script.  Can be faster or slower script, but at
the end of the day...  You guessed it!!

**Comment by alexhultman** [comment]
Simply by replacing this usage:

```javascript
wss.on('connection', function connection(ws) {
  ws.on('message', function(message) {
    ws.send(message);
  });
});
```
with this:
```javascript
function message(message) {
	this.send(message);
}

function connection(ws) {
	ws.on('message', message);
}

wss.on('connection', connection);
```

You go from 1.2 GB per 1 mil connections down to 800 mb and you also improve the throughput noticeable. Anonymous functions are killing performance just like this video explained.

**Comment by alexhultman** [comment]
So ws does 100k connections in 1.6 GB (pretty much identical with both ways), while uws does 1 million in 781 mb with the "cached function approach" and about 1.2 GB with the "anonymous function approach".

So that's a 20x better memory scalability when not using anonymous functions vs. only maybe a 12x better memory scalability when using them. By pushing the usage of "cached functions" we could see dramatic memory usage improvements for Node.js apps.

**Comment by alexhultman** [comment]
In fact, you can get the same memory boost by doing this:

```javascript
function message(message) {
	this.send(message);
}

wss.on('connection', function(ws) {
    ws.on('message', message);
});
```

Aka, as long as you make sure not to attach any of the scope to the message handler (which belongs to the socket, you are safe). I guess it works like this: when the connection handler gets called, it is called in a context where the scope is very large and has a lot of shit in it. As long as you return from that handler without spreading any of that scope into something persistent (like the socket) it should be deleted by the GC. But if you attach any of that scope to the message handler (by having the message handler be an anonymous function created in that bloated context, it will keep references to the scope which will hinder it from being deleted by the GC). That's my very shallow understanding of how it works at least.

**Comment by kapouer** [comment]
cached functions
cached functions
cached functions
cached functions
cached functions
cached functions
cached functions

next time i want to make a point i'll repeat it

**Comment by alexhultman** [comment]
Node.js 7 is worse than 5: 796mb vs. 781mb. Throughput was also (insignificantly) lower on 7. My theory is that Node.js 0.8 was *way* faster than what Node.js has deteriorated into nowadays.

**Comment by alexhultman** [comment]
My testing also shows that "cached functions" are not really significantly faster than anonymous ones. The same difference between "cached functions" and anonymous can be seen when testing "fat arrow" functions vs. "old style" anonymous functions. It's just too random to make out any kind of conclusion.

The only real conclusion is that any function will hold the entire scope hostage for as long as that function is referenced by anything. So this is not really anything I can do something about inside the library, but completely up to the user:

```javascript
function message(message) {
    this.send(message);
}

wss.on('connection', function(ws) {
    // worst - 1.2 GB
    ws.on('message', (message) => {
        ws.send(message);
    });

    // better - 1.0 GB
    ws.on('message', function (message) {
        this.send(message);
    });

    // best - 781 MB
    ws.on('message', message);
});
```

**Comment by alexhultman** [comment]
Since this is pretty much completely up to the user I made this wiki: https://github.com/uWebSockets/uWebSockets/wiki/The-importance-of-JavaScript-scope-control
