### ISSUE TITLE
Replacing `.emit` on ws versus uws

### ISSUE THREAD

**Issue by jamen** [uWebSockets/uWebSockets#346]
* What operating system are you running?
  * Linux
* What platform/language are you using?
  * Node.js

I'm not completely sure if you are aiming for 100% compatibility with the `ws` module.  I thought I would open this issue anyways.

I've created a module called [`event-intercept`](https://github.com/jamen/event-intercept) that replaces the `.emit` method with something that allows me to change the data before it reaches a listener.  However, it still uses the previous `.emit` internally to preserve behavior.

I'm using `event-intercept` in another module called [`ws-rate-limit`](https://github.com/jamen/ws-rate-limit) (currently redoing it, so code not up to date master).  So it replaces `emit` on the websocket client to achieve this.

With `ws`, this works fine because it probably references `ws.emit` directly somewhere in the code.  But with `uws` it is a problem because I think it just keeps a single persistent reference to `emit` and calls that instead.

I understand that `event-intercept` can be unstable in the long run for these reasons; however, I thought that this was still noteworthy difference in behavior, and I still think think the module is very useful for injecting functionality.

* Can you show me some short code that triggers your issue?

I've created branch called [`new-intercept`](https://github.com/jamen/ws-rate-limit/tree/new-intercept), and you can see in the `test` folder a basic example.  Try changing between `uws` and `ws` and testing with `wscat`

**Comment by alexhultman** [comment]
I don't understand the problem. uws does not implement a full EventEmitter and what you are trying to do sounds like something that goes against every "best practice" out there. You cannot expect that code relying on internal details of another module will just work as it does with a completely different module.

**Comment by jamen** [comment]
I did acknowledge the downsides of `event-intercept`, and I get this is an edge case.  But like I said I thought I would try opening anyways.

On the "best practice" piece, you may be right, but in this case I either I go this intercept route or the module becomes a bit harder to use, just because of how `EventEmitter` works (I hate it!).

For example, with `ws-rate-limit`, I either emit a secondary `'safe-message'` event, or I suppress the `'message'` event so it becomes more "drop-in usable" (they could add it to existing code easily).

I wouldn't call this a bug exactly.  Just thought I would at least point out the difference, and maybe someone would have made an easy patch.
