### ISSUE TITLE
Release 0.11.1 doesn't work on Linux

### ISSUE THREAD

**Issue by VooVoo01** [uWebSockets/uWebSockets#347]
Release 0.11.1 works properly with Node.js 7.2.0 on Windows but doesn't work on Linux, with error:
_Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system._

  * Linux 3.2.0-4-amd64
  * Node.js 6.9.1 || 7.2.0
  * SSL via µWS and Node.js

**Comment by alexhultman** [comment]
What version of GCC do you have?

**Comment by VooVoo01** [comment]
gcc (Debian 4.7.2-5) 4.7.2

**Comment by alexhultman** [comment]
That version is not compatible with C++11 and I guess you also have some ancient version of libc since the binaries also fail. Currently there is only support for modern Linux distros, so you will have to find something newer.
