### ISSUE TITLE
example echo linking error. undefined symbol uS::NodeData::asyncCallback

### ISSUE THREAD

**Issue by liketemple** [uWebSockets/uWebSockets#351]
Hello, everyone. I use to employ uWS on OSX, and it works very well.
Recently, I have to use uWS under Windows 10 with visual studio 2015.

I successfully compile the library with CMake and Visual Studio. But When coming to echo example, there is a wired linking error: undefined symbol "public: static void __cdecl uS::NodeData::asyncCallback(struct uv_async_s *)".

I am pretty sure the project setting was right, and there is just only this one linking error.
Any help would be grateful, thanks a lot!

**Comment by alexhultman** [comment]
I don't use Windows and I don't recommend using it. I cannot help, I have never gotten CMake to work on Windows. Maybe you can tinker with the dllexport things, I don't know.

**Comment by liketemple** [comment]
Thanks fot the clue. 
Add WIN32_EXPORT to NodeData declare in Networking.h works, The echo example could link right.
But, echo doesn't work, a normal websocket client could not connect to it correctly.
I tried the old version of uWS(before rewrite with Node), it works fine.
Anyway thanks again!

**Comment by ice1835** [comment]
@liketemple 
How to compile  uWS under Windows 10 with visual studio 2015?
I'm a beginner。

**Comment by MergHQ** [comment]
Adding `WIN32_EXPORT ` infront of  `asyncCallback` fixed the problem for me. Echo works fine.

**Comment by alexhultman** [comment]
Could you PR the needed changes to get it working?
