### ISSUE TITLE
ahmm.. I just want to confirm, even if I use it as a socket.io adapter, it will work only for websockets ?

### ISSUE THREAD

**Issue by kfirufk** [uWebSockets/uWebSockets#355]
Hi! 
we have a massive online game that is written on nodejs with socket.io. 
stress testing our application using your solution provided amazingly better results.

I know that socket.io support several transports (such as xhr-polling,jsonp-polling,websockets,htmlfile and so on)..

socket.io also supports upgrading protocols from one protocol to another on certain conditions. 

my question is, if I attach uws to the ws engine of socket.io, does it mean that it will restrict socket.io to only use web sockets?

does it mean that only users that connect with websockets will enjoy this wonderful performance upgrade?

any information regarding the issue would be greatly appreciated.

**Comment by alexhultman** [comment]
No, Socket.IO will work just as if run with ws. But you will only see performance changes when doing websockets since that is the only thing being swapped out.

Socket.IO is a massive mountain of bloat and it makes no sense to focus on long polling when doing a game (those browsers without WebSockets are also lacking other gaming related features).

**Comment by alexhultman** [comment]
Hi :smiley:

**Comment by kfirufk** [comment]
:) i must say that the performance and memory consumption improvements are crazy!! :) nice work

**Comment by alexhultman** [comment]
What game is it? Can I test it?

**Comment by kfirufk** [comment]
currently the only app that we opened for the public that also uses nodejs and socket.io is Bingo Drive on facebook. we already implemented your solution there and the results .. with no surprise.. are awesome.

apps.facebook.com/bingodrive
