### ISSUE TITLE
Message Type, Nodejs

### ISSUE THREAD

**Issue by jincio92** [uWebSockets/uWebSockets#359]
I'm trying to get the message type recived from the websocket, in ws there is a flag that indicate if the message is binary, but i found that uws dose not have it. There is any way in which i can find the type of the message? i need to check if the message is binary or not.

Include the following information (where applicable):

* What operating system are you running?
  * Any
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* Can you show me some short code that triggers your issue?

```
'use strict';
var WebSocket = require("uws");
var port = 3000;
var WebSocketServer = WebSocket.Server;
var server = new WebSocketServer({ port: port });
server.on('connection', function (ws) {
    console.log('Server connected');
    ws.on('message', broadcast);
 
});
function broadcast(message) {
    if(message.type != "binary"){
        this.send(message);
    } else{
        console.log("wrong type")
    }
};

console.log('Server is running on port: ', port);

```

**Comment by SEAPUNK** [comment]
It's either text, or binary.

```js
if (typeof message !== 'string') {
  // binary
} else {
  // text
}
```

**Comment by jincio92** [comment]
ok, seems to work! thanks!
