### ISSUE TITLE
Cmake and C++11 standard

### ISSUE THREAD

**Issue by matovitch** [uWebSockets/uWebSockets#360]
Hello,

FYI, under ubuntu 16.04, compiling with g++ 5.4.0 and cmake 3.5.1, I have an issue with the current definition of the c++11 standard (wasn't compiling because `-std=gnu++11` was missing). From what I found (I dont know a thing about cmake), the `set_property` on the `uWS` target was not working and I replaced it with `set(CMAKE_CXX_STANDARD 11)` before the `add_library` to make it work.

Regards,

**Comment by qwename** [comment]
The first pull request I sent did not fix it properly. I misread the documentation and thought that `CMAKE_CXX_STANDARD` is a property. Rather, it is a variable, while `CXX_STANDARD` is a property. Sending another PR soon.

**Comment by alexhultman** [comment]
Is this fixed?
