### ISSUE TITLE
some questions about packaging for debian

### ISSUE THREAD

**Issue by kapouer** [uWebSockets/uWebSockets#370]
Hi,

before anything, are you all right with uwebsockets 0.12.0 being packaged into debian ?

If yes, the packages would typically be:
libuws-0.12-dev (the headers)
libuws-0.12 (the shared lib)
node-uws (linked against the shared lib built in libuwebsocket)

That's the usual treatment, which rises two questions:
- do you maintain a soname ?
- is it possible to link the node.js addon against libuWS.so ?

Regards,
Jérémy

**Comment by alexhultman** [comment]
Hey, yeah sure you can package things. I don't know how you mean with soname but I guess libuWS.so is fine? I don't have any plans to mess with the Node.js distribution right now though.

**Comment by kapouer** [comment]
Let's put Node.js questions aside since it pisses you off.
The soname is to be understood as "name + abi compatibility versioning", and you maintaining it requires extra care about how you change the exported c++ symbols of the shared library. I suppose 0.12 means "you don't care" but i have to ask before assuming !

**Comment by alexhultman** [comment]
Hmmm..

You can assume every minor version is a breaking one, and every path version is *probably* compatible with the prior patch version. I do believe this scheme has been *kind of* followed for the last couple of months, especially since Primus depends on this versioning.

**Comment by alexhultman** [comment]
But isn't Debian a project where every package is 10 years old, unmaintained for 11 years? Do they really let you add new stuff that is still changing?

**Comment by kapouer** [comment]
Well there are two ways to use debian: stable or testing. Stable is every two years (ish). Testing is every 5 days without reported bugs, unstable is immediate. A package in testing can be rc-buggy, in which case it does not go in the next stable. Since this project is still a work-in-progress i would just do that - keep the debian package out of stable until next stable in two or three years.

**Comment by alexhultman** [comment]
:wink:
