### ISSUE TITLE
Never receiving messages from thor

### ISSUE THREAD

**Issue by albanm** [uWebSockets/uWebSockets#371]
linux/nodejs/no ssl

I just tried using [thor](https://github.com/observing/thor) for a small benchmark but something is off. Connections are ok, but the 'message' event is never emitted. I tried switching to ws and the same code works without problem. Nothing special in the code, I use "new uws.Server()".

Thanks !

**Comment by alexhultman** [comment]
* You cannot benchmark a C++ server with a JavaScript client -> especially true given that Thor makes use of `ws` which, as I hope you understand, makes it hilariously invalid. You cannot benchmark a sports car with your grandma as the driver.

* I cannot take this issue anywhere without any kind of information -> stating that uws does not emit messages is not true given that this project is used by more than just you, with success. I cannot hallucinate up some explanation to your problems given no input at all.

**Comment by albanm** [comment]
Wow, the tone of your response is weird ! But I realize that my issue was not very well written. I did not state a very clear question, so ok my bad, fair enough I guess.

First a few remarks:

  - I don't see the relevance of the programming language. Web socket is a protocol and valid implementations should communicate together whatever the language.
  - I did not try to benchmark uws, I tried to benchmark my application which uses uws and is written in nodejs, not C++.
  - Obviously uws is used by others, so is thor and so is ws. Still bugs/incompatibilities can exist and be tracked down I suppose.
  - [nginx used thor](https://www.nginx.com/blog/nginx-websockets-performance/) for some performance benchmarks, I guess they didn't understand how the whole thing is "hilariously invalid".

The code is very simple:

```
const uws = require('uws')
const wss = new uws.Server({
  port: 5603
})

wss.on('connection', ws => {
  console.log('Connection ok')
  ws.on('message', message => {
    console.log('Incoming message !')
  })
  ws.on('close', () => {
    console.log('Connection closed')
  })
})
```

Then for example:

```
thor --amount 1 --messages 1 ws://localhost:5603
```

Output is 'Connection ok' then nothing else.

Replace uws with ws and you get 'Connection ok' then 'Incoming message !'

**Comment by albanm** [comment]
Oh, and the uws server works fine when I call it from a browser, so it is not broken in a general manner.

**Comment by stormwin** [comment]
Try like this. it works for me on my small app

let WebSocketServer = require('uws').Server;

	let wss = new WebSocketServer({port: 3000});

	function onMessage(message) {
		console.log(message);
	}

	function onClose(){
		console.log('ws is closing');
	}

	wss.on('connection', function(ws) {
		ws.on('message', onMessage);
		ws.on('close', onClose);
	});

**Comment by albanm** [comment]
Thanks, but no luck. As far as I can see the only change is that you don't use arrow functions on events callbacks, it doesn't seem to make a difference.

**Comment by alexhultman** [comment]
I get the same stall with both versions + with only the C++ server. I get a connection followed by no messages and then I get a disconnection when I close Thor. I don't know what Thor wants the server to do.

Anyways, you still need to understand that a benchmarking client has to outperform the server in order to give accurate results. Otherwise you are only benchmarking the client. I have explained this to about 20 people by now and my tone is accordingly. I don't consider this project to be in need to prove itself anymore - you can just ask the industry what they think. This project is used by many companies which have reported major gains in their server performances.

A quick search on Twitter gives things like this: https://twitter.com/GoldFireStudios/status/806138191455617024

**Comment by alexhultman** [comment]
I did some digging and Thor is always leaving 4 bytes unsent, thus never finishing the message. I get a fragment that is 4 bytes too short, so I always have 4 bytes remaining until I should emit a message. After this I never get any more data. Also, the length of the mesage seems to be random and it contains strange data. Maybe Thor is broken, I don't know.

**Comment by albanm** [comment]
Ok, thank you very much for digging and for this great project. This issue is linked to another on the Thor project so maybe they will find something. Data is random by default I think but I get the same issue when using a message generator.

It was not clear in my first message, but I don't try to prove/disprove uWebSockets nor benchmark it. It is simply the transport layer of the application I am trying to benchmark as a whole. And this application can clearly be outperformed by a few nodejs processes as clients.

**Comment by d3x0r** [comment]
packet sent from thor.  1028 bytes.  I don't understand why you think there's 4 bytes missing.
The default option in ws is to send permessage-deflate; disabling this option got me this packet (kind of a bad benchmark option to leave it enabled anyway, not a real test of data throughput)  The deflated packet is 16 bytes; but I'm not sure about the validity of that packet... have to finish implementing support for that in my lib.

```
0000   81 7e 04 00 00 00 00 00 00 00 00 00 00 00 00 00  .~..............
0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0100   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0110   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0120   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0130   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0140   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0150   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0160   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0170   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0180   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0190   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0200   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0210   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0220   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0230   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0240   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0250   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0260   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0270   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0280   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0290   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
02f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0300   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0310   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0320   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0330   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0340   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0350   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0360   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0370   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0380   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0390   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
03f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0400   00 00 00 00                                      ....````

**Comment by alexhultman** [comment]
@d3x0r I don't care. Why are you insisting on using thor even though I have said it is a completely invalid stress test? Don't use a limiting client or else you will only benchmark the client. I have said this aboit five trillion times now. I see this mistake over and over and over and over again and only mentioning thor and uws in the same sentence is spreading misinformation. See this report for yet another moron idiot spreading mis fucking information because of a lack of brain cells and logical thinking: https://github.com/now-examples/ws-servers/issues/2
