### ISSUE TITLE
uws Server does not emit 'headers' event specified by ws Server docs

### ISSUE THREAD

**Issue by dscherger** [uWebSockets/uWebSockets#372]
wss = new uws.Server({ 
   server: server, 
   path: path,
   perMessageDeflate: { serverNoContextTakeover: true, clientNoContextTakeover: true }
});

wss.on('headers', function (headers) {
 ... do stuff with headers ...
});

The headers event is never emitted.

I'm using this to support safari's use of x-webkit-deflate-frame which is apparently synonymous with permessage-deflate so a better way to support this would also be fine.

The ws docs have this:

Event: 'headers'

headers {Array}
Emitted before the response headers are written to the socket as part of the handshake. This allows you to inspect/modify the headers before they are sent.

**Comment by alexhultman** [comment]
I think a simple PR to nodejs/dist/uws.js can fix this up?

**Comment by dscherger** [comment]
It looks to me like the upgrade response headers are created and written directly to the socket in HTTPSocket.cpp (lines 240 - 280) so I'm not sure if it's as simple as that.

**Comment by alexhultman** [comment]
There are two HTTP servers: the native one used by C++ (and the one that will later be exposed to Node.js) and Node.js's own HTTP server. When running in Node.js the HTTP is completely handled by Node.js and its HTTP server so any JS scripting in uws.js should fix that. Sockets are transferred from Node.js's TCP stack over to µWS's TCP stack in the handleUpgrade function so it is only after this point it becomes native.

**Comment by dscherger** [comment]
Yes, so handleUpgrade in uws.js calls native.upgrade with values for sec-websocket-extensions and sec-websocket-protocol (from the upgrade request headers) and then HTTPSocket.cpp creates the upgrade response headers with Sec-WebSocket-Accept and writes them directly to the socket.

It is the response headers that are exposed by the ws 'headers' event. Are these somehow visible to uws.js after HTTPSocket.cpp writes them out?

I'm not at all familiar with the uWS codebase at this point so I could easily be missing something.

Like I say, my requirement here is really to support permessage-deflate for safari which expects this extension to be called x-webkit-deflate-frame. Fiddling with the headers just a bit to rename this to permessage-deflate on the way in and back to x-webkit-deflate-frame on the out seems to do the job.

I'm using the http server 'upgrade' event and the ws 'headers' event to do this header twiddling which is not very pretty but seems to work ok. A better solution would be fine.

**Comment by alexhultman** [comment]
Ah! 'headers' event is the *outgoing* headers, not the incoming. That's some very strange feature of ws.

You could probably achieve the same effect by having an HTTP server, listen to 'upgrade' and replace x-webkit-deflate-frame with permessage-deflate in the *incoming* headers before you pass them to handleUpgrade. That way uws will negotiate permessage-deflate. This is against the standard but yolo, right?

**Comment by dscherger** [comment]
Yes, that's what I'm doing with the http server 'upgrade' event (rewriting the incoming headers). The catch is that the outgoing headers also need to be rewritten back from 'permessage-deflate; server_no_context_takeover; client_no_context_takeover' to 'x-webkit-deflate-frame; no_context_takeover' to be compatible with safari.

Definitely against the standard, or using an old version of the rfc, I'm not even sure if the current version is actually fully standardized or not, I'm just trying to make thins work.

**Comment by alexhultman** [comment]
Hmmm... I get the problem but it sounds too specific, non-critical and non-standard to be a high priority right now.

Maybe you just have to leave Safari users without compression? You could also toy with the Extensions.cpp - tokens are a sum of their ascii values.
