### ISSUE TITLE
client connection does not return EMFILE error

### ISSUE THREAD

**Issue by albanm** [uWebSockets/uWebSockets#373]
linux / node.js / no ssl

While running a small benchmark for my application (not with Thor this time) I encountered some errors when reaching about 4000 connections. Turns out I need to allow my OS to open more file descriptors. The problem is that uws didn't return any information with the error event.

The error event callback (client side):

```
ws.on('error', err => {
    console.error('ws error', err)
})
```

The result with uws: "ws error undefined"

The result with ws:

```
  ws error { Error: getaddrinfo EMFILE localhost:5603
  at Object.exports._errnoException (util.js:1022:11)
  at errnoException (dns.js:33:15)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'EMFILE',
  errno: 'EMFILE',
  syscall: 'getaddrinfo',
  hostname: 'localhost',
  host: 'localhost',
  port: '5603' }
```

Both fail in the same way but uWebSockets doesn't give any error code to its user.

The bad news is that I also had a segfault in the server's trace at some point. But it only happened once in about 4 or 5 attempts.

**Comment by alexhultman** [comment]
Yeah the client code is known to have problems. If you send larger than medium files it will write out of bounds. Should fix it, but focus has been on the server code.

**Comment by alexhultman** [comment]
Btw, I appreciate any issue report. This issue is very valuable and I will fix the client support up. It's just that I have had a lot of benchmarking issues that are getting quite tedious by now.

**Comment by alexhultman** [comment]
#320

**Comment by alexhultman** [comment]
The known overwrite is in formatMessage in WebSocketParser.h. It should not write past the end.
