### ISSUE TITLE
Compilation error - Fedora 24 GCC 6.2.1

### ISSUE THREAD

**Issue by ng5** [uWebSockets/uWebSockets#375]
Hi,

I'm unable to compile the code due to below error. Can you please take a look?

thanks

/home/rohitv/GitHub/uWebSockets/examples/multithreaded_echo.cpp:19:59: error: ‘uWS::UpgradeInfo’ has not been declared
   h.onConnection([&](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo upgInfo){
                                                           ^~~~~~~~~~~
/home/rohitv/GitHub/uWebSockets/examples/multithreaded_echo.cpp:23:4: error: no matching function for call to ‘uWS::Hub::onConnection(main()::<lambda(uWS::WebSocket<true>, int)>)’
   });
    ^
In file included from /home/rohitv/GitHub/uWebSockets/examples/../src/Hub.h:4:0,
                 from /home/rohitv/GitHub/uWebSockets/examples/../src/uWS.h:4,
                 from /home/rohitv/GitHub/uWebSockets/examples/multithreaded_echo.cpp:1:
/home/rohitv/GitHub/uWebSockets/examples/../src/Group.h:52:10: note: candidate: void uWS::Group<isServer>::onConnection(std::function<void(uWS::WebSocket<isServer>, uWS::HTTPRequest)>) [with bool isServer = true]
     void onConnection(std::function<void(WebSocket<isServer>, HTTPRequest)> handler);
          ^~~~~~~~~~~~

**Comment by qwename** [comment]
`uWS::UpgradeInfo` doesn't exist anywhere in the source, change the parameter to `uWS::HTTPRequest httpReq` to make it build.

**Comment by alexhultman** [comment]
The general idea is that if something is broken -> check the latest released version.
