### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by debdattabasu** [uWebSockets/uWebSockets#377]
Hi. I am currently using a makeshift renamed version of ws type definitions for uws. It will be helpful if it were part of the official repository. Is this something that you guys are considering? 

Regards
Debdatta

**Comment by alexhultman** [comment]
I have no idea about TypeScript and I have no plan to support it currently

**Comment by debdattabasu** [comment]
This is just what I needed. Thanks. :)
