### ISSUE TITLE
Implementing callbacks along with client implementation

### ISSUE THREAD

**Issue by sacOO7** [uWebSockets/uWebSockets#380]
How many types of callbacks does this library support in client implementation?
There are following necessary callbacks required to use in production.

onconnect
onreceive
onconnecterror
send
ondisconnect

Can you please provide me with example where I can refer to implement those APIs?

**Comment by alexhultman** [comment]
Well I wouldn't use µWS as the client. It is not fully finished and has issues like not properly resolving all addresses of a domain and such. Will fix but is low prio. You could probably get better results with other clients right now.

**Comment by sacOO7** [comment]
Ok , thanks for the reply
