### ISSUE TITLE
Electron Help

### ISSUE THREAD

**Issue by digitronics** [uWebSockets/uWebSockets#382]
* What operating system are you running?
  * Windows
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation

Not really an issue, but not sure who to ask. Trying to build this for Electron, just wondering if anyone has done it and could point me in the right direction. I've got the dependencies installed and I have been able to compile for a normal node.js environment. But not sure where to get started for building this for Electron. Any help would be much appreciated.

**Comment by jamen** [comment]
Hello, I am interested in this too.  I did [see this issue](https://github.com/uWebSockets/uWebSockets/issues/373#issuecomment-257434813) recently about the client though, which I was planning to use.

**Comment by chovy** [comment]
iojs is pretty old. use node v7

**Comment by digitronics** [comment]
Can't (Electron)[http://electron.atom.io/] is built off of iojs I believe, or at least that's what they give you to compile with via node-gyp. I've tried using node 6.5, but the module wont load.

**Comment by alexhultman** [comment]
#386

**Comment by alexhultman** [comment]
Electron is not something I support or have the resources to support. You should be perfectly fine with any other websocket implementation in these cases. uws is about server problems where you hold many connections. It doesn't matter if you use ws or uws in a client unless you plan on sending life threatening information over the wire, in which case you shouldn't even be using Node.js to begin with. You have to solve it yourself if it doesn't work.
