### ISSUE TITLE
Can't properly handle EADDRINUSE 

### ISSUE THREAD

**Issue by dzek69** [uWebSockets/uWebSockets#384]
Linux Mint 18.1 x64, Node.js 6.8.1, no SSL

I am not able to properly handle situation when port is already used. No error event is generated, things are not running synchronously, so I cannot wrap it with `try/catch`.

Example 1:1 copied from my code
```javascript
const ws = require("uws"); // was "ws"

// other imports

const startServer = () => {
    return new Promise((resolve, reject) => {
        let wsServer = new ws.Server({
            port: config.streamServer.port,
        });
        wsServer.on("error", (error) => {
            if (error.errno === 'EACCES') {
                reject("Can't access port for socket server (try port >= 1024)");
                return;
            }
            if (error.errno === 'EADDRINUSE') {
                reject("Can't use port for socket server (already in use)");
                return;
            }
            console.error("Unknown Socket Server error", error);
        });
        wsServer.on("listening", () => {
            resolve(wsServer);
        });
    });
};
```

This was working just fine with `ws`. I replaced it with `uws` in my require and now things are crashing:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9999
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at Server (/home/dzek/Projects/cam/node_modules/uws/uws.js:441:33)
    at Promise (/home/dzek/Projects/cam/src/modules/stream/services/server/index.js:30:24)
    at startServer (/home/dzek/Projects/cam/src/modules/stream/services/server/index.js:29:12)
    at start (/home/dzek/Projects/cam/src/modules/stream/services/server/index.js:94:12)
    at Object.<anonymous> (/home/dzek/Projects/cam/src/index.js:10:5)
```

**Comment by alexhultman** [comment]
Easiest is probably for you to fix this yourself and PR it. Look in nodejs/dist/uws.js. It should be a simple fix.

**Comment by RainingChain** [comment]
When creating the new ws.Server, pass a server rather than just the port if you're planning to have both a HTTP and a WS server running on the same port.

`new ws.Server({server:server})` instead of `new ws.Server({port:port})`

**Comment by rezoner** [comment]
Not a fix but if you need to check if the port is taken before initializing your server here is a gist I am using https://gist.github.com/rezoner/166bfed454d4a982eb2d36e2d0bd3c65

**Comment by ai** [comment]
I need this feature too. I can ask friends to make PR: any advice for them where to look to fix it?

**Comment by alexhultman** [comment]
Everything JS is in nodejs/dist/uws.js
