### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system.

### ISSUE THREAD

**Issue by inf3cti0n95** [uWebSockets/uWebSockets#386]
* What operating system are you running?
  * Linux
  * OS X
  * Windows
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  no
* Can you show me some short code that triggers your issue?

Getting the following error while using uws with electron.
`Uncaught Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.`

Tried it on all 3 Operating Systems.

Any solution would be helpful.

build logs for the C++ compiler http://pastebin.com/phe5JstR

**Comment by DiegoRBaquero** [comment]
Do you have a full log of building?

Are you sure you have C++ compiler?

**Comment by inf3cti0n95** [comment]
@DiegoRBaquero How to I configure the C++ compiler ? for windows and ubuntu 16.04, any guides?
