### ISSUE TITLE
Support mask option when sending binary message

### ISSUE THREAD

**Issue by plantain-00** [uWebSockets/uWebSockets#387]
Include the following information (where applicable):

* What operating system are you running?
  * OS X
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* Can you show me some short code that triggers your issue?

My code is from the `ws` library, something like this:
```js
ws.send(array, { binary: true, mask: true });
```
But when I move from ws to uws, I find that the browser(chrome) shows the message is not mask.

ws:

```
Binary Frame (Opcode 2, mask)
```

uws:

```
Binary Frame (Opcode 2)
```

So can uws support mask option when sending binary message?

**Comment by alexhultman** [comment]
The server is not supposed to mask, only the client. uws masks according to standard and there is no mask option to pass, this is legacy of the ws module and not according to the standard.

**Comment by plantain-00** [comment]
All right.
