### ISSUE TITLE
Message being received with no data

### ISSUE THREAD

**Issue by deniskrop** [uWebSockets/uWebSockets#389]
I am using Node.js on Linux, no SSL, and trying to implement uws to my current project. All I've done is changed ws to uws. My message is being received but with no data, the on('message') callback is called, but with an empty buffer, and it's called when I refresh the browser page. Is the client interface is any different?

**Comment by alexhultman** [comment]
Sounds strange but you should probably not use the client of uws right now. It is "meh" right now and should be improved. Do you have any kind of reproducible case?

**Comment by alexhultman** [comment]
You are using the server? And you receive binary data? Did you read the notes on how binary data differs from ws? uws makes use of ArrayBuffer and they are only valid during the callback.

**Comment by deniskrop** [comment]
Thanks Alex, it was an error on my part, this has since been solved.
