### ISSUE TITLE
Node.js cluster

### ISSUE THREAD

**Issue by zaksmok** [uWebSockets/uWebSockets#390]
Hey. Is there any example how to setup node.js clustering with uws? Is there any tool to communicating between instances or I have to build overlay for this?

**Comment by alexhultman** [comment]
Any cluster or similar is up to you. There are many solutions for this in the Node.js universe.

**Comment by zaksmok** [comment]
do you have any suggestions which way should I choose?

**Comment by japrescott** [comment]
I'd suggest using [node's native cluster](https://nodejs.org/api/cluster.html) implementation to benefit from a multi-core cpu. In regards to sockets, you will need to create sticky connections. Information about that can be found in the documentations of the libs that actually use uWebSocket under the hood ->deepstream.io, SocketCluster, socket.io etc
