### ISSUE TITLE
Connection only possible from localhost

### ISSUE THREAD

**Issue by Nevergonnachange** [uWebSockets/uWebSockets#391]
Hello,

I am having a issue with the example websocket servers. 
They only listen for connections from localhost. When I try connection to an IP adress the connection cannot be established.

Is there any way to change this?

* What operating system are you running?
  * Windows

* What platform/language are you using?
  * C++

* Are you using SSL, if so, how?
  * SSL is not part of the equation

* Can you show me some short code that triggers your issue?
  * C++ examples from this repo

Thank you very much in advance

Regards
Robin Gruschke

**Comment by RobCob** [comment]
Just had the same problem, try listening with the option uS::ONLY_IPV4

**Comment by alexhultman** [comment]
Ah yeah Windows is the only platform that either only listens to ipv6 or ipv4, not both. Microsoft did great there :thumbsup:
