### ISSUE TITLE
Networking.h:4:30: fatal error: openssl/opensslv.h: No such file or directory

### ISSUE THREAD

**Issue by SzAmmi** [uWebSockets/uWebSockets#393]
I have **Windows** and I program in **C++** using **MinGW and CLion IDE**

I get this error:
`C:/.../CPPLibs/uWebSockets/Networking.h:4:30: fatal error: openssl/opensslv.h: No such file or directory`

Do I have to compile this lib before?
How I can properly import uWebSockets into my C++ project?

**Comment by SzAmmi** [comment]
On Windows you need to search the web for pre-compiled binaries or simply compile the dependencies yourself.

libuv 1.3+
OpenSSL 1.0.x
zlib 1.x
CMake 3.x
Compilation

Obviously you will need to clone this repo to get the sources. We use CMake as build system.

git clone https://github.com/uWebSockets/uWebSockets.git && cd uWebSockets
cmake .
Now, on Unix systems it should work by simply running make. Run [sudo] make install as you wish.

Windows, in all its glory

If you are running Windows you should now have a bunch of Visual Studio project files and one solution file. Open the solution file, now you need to make sure the header include paths and library paths are all set according to where you installed the dependencies. You might also need to change the names of the libraries being linked against, all according to the names of the installed library files. You know the drill.

**Comment by petachew** [comment]
How do you build these dependencies?
