### ISSUE TITLE
socket.close(),but it still receives messages;

### ISSUE THREAD

**Issue by ydcoming** [uWebSockets/uWebSockets#396]
Include the following information (where applicable):

* What operating system are you running?
  * Windows
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL via µWS or Node.js
* Can you show me some short code that triggers your issue?
In client, i have 800 clients each client sends messages per 500ms.
when i close the server sokcet ,like this 
                       this.socket.removeAllListeners("close");
			this.socket.removeAllListeners("error");
			this.socket.removeAllListeners("message");
			this.socket.terminate(); 
but the client still try to connet server,and the server still receive messages.
I think the server socket.close() Invalid.

**Comment by alexhultman** [comment]
I don't understand - are you using uws as the server and something else as client? The problem is with the server, not the client?

Maybe a complete source example can show your problem?
