### ISSUE TITLE
Test & release v0.13.0

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#397]
I recently tagged v0.13.0 alpha 1 - it's an alpha because I feel v0.13 needs some extra testing by someone with a real production set-up before I put it on NPM. If anyone wants to compile the Node.js addon (or the C++ lib) and run it in production for a while that would be nice.

I will tag a new alpha in a while and if that runs stable it shouldn't be that far to a new release. I want v0.13 to be a stable update from v0.12 while also having some new HTTP features to toy around with. If you see any new issues with the alphas please report them here.

**Comment by kapouer** [comment]
Hi,
what's your agenda ? I've setup `@kapouer/uws` so one can test uws 0.13 alpha 1 (that npm module does not have any precompiled lib in it), and put it to use on two staging servers.
I'll probably find some time to put it in production this week-end.

Besides that, i've tried to run engine.io using your http server, but since it (seemingly, i did not look at the code) doesn't expose `req.headers` and probably some other API, it cannot work - i suppose that's expected.

**Comment by alexhultman** [comment]
* Fix some http parser bugs, add more tests
* Add req.getHeader function, req.headers[] requires Proxies which are only in Node.js 7+
* Implement proper upgrade from uws.http -> uws websocket

**Comment by rockmacaca** [comment]
Why not set it up under a prelease npm tag so it's easier to get to, e.g. `npm install uws@alpha`?

**Comment by alexhultman** [comment]
@rockmacaca Ah, didn't know about that. Don't have a lot of time to mess with NPM right now though.

Tagged alpha 2 just now, fixes tons of bugs in HTTP and *should* be very stable.

**Comment by alexhultman** [comment]
I'm testing a simple bootstrap site here (will only be up for a short while): http://79.136.86.141:3000/

Btw, I don't know exactly why but my wrk benchmarks are up over 300k requests per second now - before I only got maximum 260k. Well good news anyways and this basic bootstrap site seems to work pretty okay :+1:

**Comment by alexhultman** [comment]
Did anyone put alpha 3 in production?

**Comment by kapouer** [comment]
I just published "@kapouer/uws" and put it in production. Basic testing works, and i'll have some mild load this evening (thousands of real connections).
FYI @alexhultman if you want to publish the npm module as alpha, the [npm documentation](https://docs.npmjs.com/misc/semver#prerelease-tags) precisely give this example about alpha version, so you just have to publish the npm module with version in package.json: `0.13.0-alpha.3`.

**Comment by alexhultman** [comment]
Nice! I'm really excited about the 0.13 release - will be awesome!

**Comment by alexhultman** [comment]
The Node.js http support is now a lot more complete, as an example this complete server is working:

```javascript
'use strict';

const uws = require('./dist/uws');

// the page that will connect back over EventSource
const document = '<script>var es = new EventSource(\'/eventSource\'); es.onmessage = function(message) {document.write(\'<p><b>Server sent event:</b> \' + message.data + \'</p>\');};</script>';

const server = uws.http.createServer((req, res) => {
    if (req.url === '/') {
        res.end(document);
    } else if (req.url === '/eventSource') {
        // write the event-stream HTTP head so that we can send chunks back later
        res.writeHead(200, {'Content-Type': 'text/event-stream'});

        // start a timer that will send back events over this HTTP socket
        var that;
        setTimeout(that = () => {
            // important to not end the socket, but write instead!
            res.write('data: Some message from server here!\n\n');

            // todo: cancel timer when socket closes!
            setTimeout(that, 1000);
        }, 1000);
    } else {
        // todo: terminate
        console.log('Unsupported url: ' + req.url);
        res.end('Nope, nope!');
    }
});

server.listen(3000);
```

It does not currently update on disconnection so it will crash when you disconnect but this will be fixed soon. Performance is still very good as long as writeHead is not called in a hot path (this function is very slow). If you only res.end('some data here'); you get 230k requests per second.

**Comment by kapouer** [comment]
Alpha3 in production trapped inside socket.io worked without any kind of problem.

**Comment by creole** [comment]
@kapouer Just out of curiosity: do you use the 2.0 version of engine.io, where uws is the default websocket engine?

**Comment by kapouer** [comment]
@creole no i'm using old socket.io 1.5 / engine.io 1.7, just replacing `io.engine.ws` after instanciation on the fly.

**Comment by creole** [comment]
Thanks for specifying. I'd be interested to hear how you fare with the latest version.

**Comment by alexhultman** [comment]
@kapouer thanks for testing!

**Comment by kapouer** [comment]
@alexhultman got a single segfault in libuv this morning on one of the socket.io instances using uws 0.13.0-alpha.3. It's probably caused by the uws update because nothing else changed and there is usually no segfault on that server at all.
Unfortunately i have no further information :( I'll install apha.4 today and will continue to report here until nothing weird happens.

**Comment by alexhultman** [comment]
If you could build the addon with asan that would help a lot: https://github.com/uWebSockets/uWebSockets/issues/288#issuecomment-253384725

uWebSockets/nodejs/Makefile

Linux line should have -lasan immediately after g++ and instead of -s it should have -g then make and use this binary.

Also make sure you have all matching versions of every component as I know you have had issues where you linked to one version of OpenSSL while compiling using another version of the headers.

**Comment by alexhultman** [comment]
Ah, btw I know what it can be. I have marked this as an issue: https://github.com/uWebSockets/uWebSockets/blob/master/src/HTTPSocket.cpp#L302

If a socket closes mid upgrade it will crash, this is one of the main remaining things to fix up and I have postponed it until last because I'll rewrite the upgrade flow since I need to supoort upgrades from two different http servers now (uws.http and nodejs http).

**Comment by alexhultman** [comment]
You see in Hub::upgrade (called from Node.js) the HttpSocket is not added into a group so if upgrade fails it will crash and burn in onEnd: https://github.com/uWebSockets/uWebSockets/blob/master/src/Hub.cpp#L143

**Comment by alexhultman** [comment]
The nodejs/http.js example now does 1.1 million req/sec in Node.js (beating Japronto by ~100k) when benchmarking with pipelining and about 230k without (beatign Japronto by about 40k):

```
[alexhultman@localhost wrk]$ ./wrk -c 400 -t 3 -d 10 http://localhost:3000Running 10s test @ http://localhost:3000
  3 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.98ms  107.59ms   1.64s    98.18%
    Req/Sec    78.76k     5.42k   89.39k    70.33%
  2351520 requests in 10.01s, 132.31MB read
  Socket errors: connect 0, read 0, write 0, timeout 37
Requests/sec: 234902.23
Transfer/sec:     13.22MB
[alexhultman@localhost wrk]$ ./wrk -c 400 -t 3 -d 10 -s ../pipeline.lua http://localhost:3000
Running 10s test @ http://localhost:3000
  3 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    24.12ms  140.72ms   1.67s    97.05%
    Req/Sec   375.86k    47.80k  472.00k    46.33%
  11218920 requests in 10.02s, 631.25MB read
  Socket errors: connect 0, read 0, write 0, timeout 48
Requests/sec: 1119874.55
Transfer/sec:     63.01MB
[alexhultman@localhost wrk]$ ./wrk -c 400 -t 3 -d 10 -s ../pipeline.lua http://localhost:3000
Running 10s test @ http://localhost:3000
  3 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.95ms  149.65ms   1.67s    96.46%
    Req/Sec   394.86k    57.85k  593.28k    78.67%
  11783328 requests in 10.02s, 573.11MB read
  Socket errors: connect 0, read 0, write 0, timeout 48
Requests/sec: 1176494.64
Transfer/sec:     57.22MB
```

**Comment by andreimavenhut** [comment]
Hi, i tried compiling but i cannot make it work on debian7. Is there any way i could get pre-compiled libraries ?

**Comment by doesdev** [comment]
I hate to clutter this thread with Windows build issues for the temp / alpha NPM module but couldn't find a better place to put it. 

@kapouer : Are you able to compile from node-gyp on Windows with the published alpha module?

I'm getting syntax errors starting in HTTPSocket.h. I've linked a paste of my output below. When I get to a PC that has VS installed I'll see if I can track down the cause in it, but just wanted to make sure it wasn't an issue isolated to my setup before I get there. So if you can build it then I'll look more into why it's occurring for me.

[full paste of node-gyp output](http://pastebin.com/CwaRTQU7)

First error thrown:
`@kapouer\uws\src\HTTPSocket.h(30): error C2059: syntax error: '(' (compiling source file ..\src\WebSocketImpl.cpp) [@kapouer\uws\build\uws.vcxproj]`

**Comment by doesdev** [comment]
Okay, got it working on my machine. I definitely don't recommend that this change be integrated as is without inspection as (A) my C++ experience is minimal (B) it isn't tested on anything but my Windows machine. Hence no PR for these changes.

That being said, [here are my changes](https://github.com/doesdev/uWebSockets/commit/4c2fd3572a12b0711af34f7bd7e07c6a877dbbab) for reference.

**Comment by alexhultman** [comment]
@kapouer I fixed the potential crash bug I wrote about before. You want to give master a spin and see if it fixed your stability issues?

**Comment by kapouer** [comment]
I've put 0.13 in production and today there's some load on the server (about 15.000 browser clients in socket.io). Nothing weird is happening.
