### ISSUE TITLE
Add MinGW support

### ISSUE THREAD

**Issue by ghost** [uWebSockets/uWebSockets#399]
Is it possible to compile `uWS` using MinGW64 (downloaded using MSYS2) on Windows?
```bash
$ cmake .
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /mingw64/bin/cc.exe
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /mingw64/bin/cc.exe -- works
-- Detecting C compiler ABI info
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting C compiler ABI info - done
-- Detecting C compile features
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting C compile features - done
-- Check for working CXX compiler: /mingw64/bin/CC.exe
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working CXX compiler: /mingw64/bin/CC.exe -- works
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-6.2 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compile features - done
-- Found OpenSSL: /mingw64/lib/libssl.a;/mingw64/lib/libcrypto.a (found version "1.0.2j")
-- Found ZLIB: /mingw64/lib/libz.a (found version "1.2.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /c/users/marczak/uWebSockets-master

$ make
Scanning dependencies of target uWS
[  7%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.obj
[ 14%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.obj
In file included from C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:5:0,
                 from C:/users/marczak/uWebSockets-master/src/WebSocket.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.cpp:1:
C:/users/marczak/uWebSockets-master/src/Networking.h:29:19: error: conflicting declaration 'typedef uintptr_t DWORD'
 #define pthread_t DWORD
                   ^
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8:0,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/WinSock2.h:2 ,
                 from C:/users/marczak/uWebSockets-master/src/Networking.h:23,
                 from C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:5,
                 from C:/users/marczak/uWebSockets-master/src/WebSocket.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.cpp:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:141:29: note: previous declaration as 'typedef long unsigned int DWORD'
   typedef unsigned __LONG32 DWORD;
                             ^~~~~
In file included from C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:5:0,
                 from C:/users/marczak/uWebSockets-master/src/WebSocket.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.h:4,
                 from C:/users/marczak/uWebSockets-master/src/Group.cpp:1:
C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h: In static member function 'static size_t uWS::WebSocketProtocol<isServer>::formatMessage(char*, const char*, size_t, uWS::OpCode, size_t, bool)':
C:/users/marczak/uWebSockets-master/src/Networking.h:26:28: error: there are no arguments to 'htonll' that depend on a template parameter, so a declaration of  htonll' must be available [-fpermissive]
 #define htobe64(x) htonll(x)
                            ^
C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:280:39: note: in expansion of macro 'htobe64'
             *((uint64_t *) &dst[2]) = htobe64(reportedLength);
                                       ^
C:/users/marczak/uWebSockets-master/src/Networking.h:26:28: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
 #define htobe64(x) htonll(x)
                            ^
C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:280:39: note: in expansion of macro 'htobe64'
             *((uint64_t *) &dst[2]) = htobe64(reportedLength);
                                       ^
C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h: In member function 'void uWS::WebSocketProtocol<isServer>::consume(char*, unsigned int, void*)':
C:/users/marczak/uWebSockets-master/src/Networking.h:27:28: error: there are no arguments to 'ntohll' that depend on a template parameter, so a declaration of  ntohll' must be available [-fpermissive]
 #define be64toh(x) ntohll(x)
                            ^
C:/users/marczak/uWebSockets-master/src/WebSocketProtocol.h:346:74: note: in expansion of macro 'be64toh'
                 } else if (consumeMessage<LONG_MESSAGE_HEADER, uint64_t>(be64toh(*(uint64_t *) &src[2]), src, length, frame, user)) {
                                                                          ^
make[2]: *** [CMakeFiles/uWS.dir/build.make:87: CMakeFiles/uWS.dir/src/Group.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/uWS.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by SzAmmi** [comment]
Yeah, cmake is garbage.

**Comment by SzAmmi** [comment]
I meant uWS, libuv compiled successfully.

**Comment by alexhultman** [comment]
I don't have any specific goal to support mingw but if anyone would get it to work without any significant changes that would be okay. I know mingw has problems with std::mutex though?

**Comment by SzAmmi** [comment]
Right, but I'm using MinGW-w64 which has `std::mutex` support. I'm using CLion, which needs MinGW enviroment. I can switch to Visual Studio, if needed.

**Comment by alexhultman** [comment]
Yeah well then it should work. If you can tinker with it and get it to work that would certainly be good

**Comment by SzAmmi** [comment]
Ok, 'll try :)

**Comment by SzAmmi** [comment]
@alexhultman Probably it fails because of MinGW. It has something wrong... Lemme see.

**Comment by SzAmmi** [comment]
For example, it says, that `pthread_t` is defined before :O I see only one `pthread_t` definition.

**Comment by ssj17vegeta** [comment]
Ok, I finally got it working under MinGW64 after a few hours of debugging, browsing the web and so on.

As I'm neither familiar with Git nor with CMake, the current solution doesn't come as a pull request (that, and my company's proxy prevents git from actually working >_<) AND the whole CMake part is not done, apologies for that. I used Eclipse CDT for my project, so I can only give you GCC arguments to put in it.

First, since uWebSocket relies on C++11 threads/mutex, you have to enable them in MinGW64 as they are not included in the default distribution. Unzip / git clone / https://github.com/meganz/mingw-std-threads and put it in uWebSocket's include paths (-I). That should take care of GCC not knowing what pthread_t.

Here's my setup to compile the library :
OS : Win 7 64 bits.
Compiler : MinGW64 (brought by win-builds).
Compiler arguments provided : -c -fmessage-length=0 -std=c++11
Pre-processor : _WIN32_WINNT=0x601 (not sure if needed, but forces the Windows API to use functions at least available in WinXP).
Linker arguments : -lssl -iphlpapi -lcrypto -luserenv -lpsapi -lws2_32
Linked objects : libz.dll.a provided on default MinGW, libUV.a provided by LibUV, libcrypto-1_1-x64.dll and libssl-1_1-x64.dll both provided by OpenSSL 1.1.0 for MinGW64.

I also had to make a few changes to the code. For the record, I worked on a version cloned on February 3rd, so the current code might be a bit different now. The code had to be made in haste so obviously it's not perfect style either.

[b]HTTPSocket.h :[/b]

In the enum HttpMethod, the value "DELETE" seems to be actually mistaken for the "delete" keyword by the compiler (quite weird when you think about it...). Renaming it does the trick (_DELETE). Hacky hack but it works. [i]EDIT: Seems to be fixed as of now, being renamed as METHOD_DELETE. Nice one ;)[/i]

[b]Networking.h :[/b]

This is where the more serious modifications occur. MinGW misses the functions htonll and ntohll, and does not require pthread_t redefinition.

So in the current "trunk" we have :

[code]
#ifdef _WIN32
	#define NOMINMAX
	#include <WinSock2.h>
	#include <Ws2tcpip.h>
	#define SHUT_WR SD_SEND
	#define htobe64(x) htonll(x)
	#define be64toh(x) ntohll(x)
	#define __thread __declspec(thread)
	#define pthread_t DWORD
	#define pthread_self GetCurrentThreadId
	#define WIN32_EXPORT __declspec(dllexport)
	... other code
#endif
[/code]

On my version, I have :

[code]
#ifdef _WIN32
	#define NOMINMAX
	#include <WinSock2.h>
	#include <Ws2tcpip.h>
	#define SHUT_WR SD_SEND
	#ifdef _MSC_VER
		#define htobe64(x) htonll(x)
		#define be64toh(x) ntohll(x)
	#endif
	#define __thread __declspec(thread)
	#ifdef _MSC_VER // Here we have MS Compilers
		#define pthread_t DWORD
		#define pthread_self GetCurrentThreadId
	#else // Here MinGW
		#ifdef __MINGW32__
			static __inline unsigned short bswap_16 (unsigned short __x)
			{
			  return (__x >> 8) | (__x << 8);
			}

			static __inline unsigned int bswap_32 (unsigned int __x)
			{
			  return (bswap_16 (__x & 0xffff) << 16) | (bswap_16 (__x >> 16));
			}
			static __inline unsigned long long bswap_64 (unsigned long long __x)
			{
			  return (((unsigned long long) bswap_32 (__x & 0xffffffffull)) << 32) | (bswap_32 (__x >> 32));
			}
			#define htobe64(x) bswap_64(x)
			#define be64toh(x) bswap_64(x)
		#endif
	#endif
	#define WIN32_EXPORT __declspec(dllexport)
	... other code ...
#endif
[/code]

I still have warnings about NOMINMAX being redefined, so I guess moving #define NOMINMAX to #ifdef _MSC_VER could be fine, and the code could be simplified.

And voilà, it should work (again, tested with the version of February 3rd) !

In case I forgot something, don't hesitate to ask, I'll be watching this issue closely. Again, sorry for not being able to file a proper pull request. I hope my explanations were useful :-)

**Comment by ssj17vegeta** [comment]
OK, got it to compile on the latest version from today.

My modifications on Networking.h still apply, and you must add this in Asio.h to compile, juste after #include <iostream> :

<pre>
#ifdef __MINGW32__
#include "sys/epoll.h"
#endif
</pre>

I also noticed that the library DLL size shrank a *lot*. With the exact same compiler configuration, I went from a huge 30Mb file size to 649Kb. So, great work @alexhultman :D.

Unfortunately, my (really simple) program crashes almost one second after calling Hub::run(). So no client had the time to connect.

In Node.h, method accept_cb(), on that line
<pre>
if (!TIMER && errno != EAGAIN && errno != EWOULDBLOCK) {
    listenData->**listenPoll**->stop();
</pre>

At that particular moment, listenPoll = nullptr. In the console, just before the crash I see :

<pre>
Poll::setCb
Poll::start
Poll::stop
Poll::stop
</pre>

I unplugged all the handlers, so basically my main() looks like to this :
<pre>
uWS::Hub h;
if(h.listen(18950, nullptr, uS::ONLY_IPV4))
{
   h.run();
}
</pre>

But then again, uWS is still in heavy development / refactoring so there's no rush, just wanted to help :)

**Comment by 0x111111111** [comment]
I'm interested in MinGW also :+1:

@ssj17vegeta Could you do a pull request with a version v0.13.0?

**Comment by 0x111111111** [comment]
@ssj17vegeta By the way, did you use [MSYS2](http://www.msys2.org/) to install MinGW? If not, please make sure it'll work there too (remember: after MinGW installation run the MinGW console, not the MSYS one).
