### ISSUE TITLE
Use prebuild?

### ISSUE THREAD

**Issue by ralphtheninja** [uWebSockets/uWebSockets#401]
Have you considered using [prebuild](https://github.com/mafintosh/prebuild) for prebuilt binaries?

**Comment by alexhultman** [comment]
I have had it come up a couple of times. I don't get what it would add that's not already solved though? I'm not a fan of implicit compiler flags and enforced project structures.

**Comment by ralphtheninja** [comment]
Not sure what you mean by implicit compiler flags and enforced structures.

**Comment by alexhultman** [comment]
I'm not a fan of how node-gyp decides what flags addons get based on what flags Node.js was compiled with: -fno-strict-aliasing -fno-exceptions, etc.

**Comment by ralphtheninja** [comment]
Got it :) Anyway, it seems you have a functioning system here so I'll leave it at that. Cheers
