### ISSUE TITLE
Error whilst building multithreaded echo example

### ISSUE THREAD

**Issue by TheMegaTB** [uWebSockets/uWebSockets#403]
First off some contextual information:
 - ArchLinux on amd64 architecture
 - Using C++
 - Using SSL? Nope, it doesn't even compile so no way to use it ;)
 - Code that triggers the issue:
```
ExternalProject_Add(
    websocket
    GIT_REPOSITORY https://github.com/uWebSockets/uWebSockets
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION} -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    UPDATE_DISCONNECTED 1
)
```

![img-2017-01-24-190135](https://cloud.githubusercontent.com/assets/5037967/22260167/7738c732-e268-11e6-93bf-1ce55617a1b1.png)

**Comment by alexhultman** [comment]
Fixed
