### ISSUE TITLE
Feature request - "webSocket acts like an EventEmitter with one listener per event maximum."

### ISSUE THREAD

**Issue by ORESoftware** [uWebSockets/uWebSockets#407]
On linux

I have the need to have more than one listener per event (I wrote a library with ws, and then discovered this library) is there perhaps a setting I can use to override the default behavior of only having one listener per event?

here is my use case. ws is initialized in the constructor, and the following code is in a method:

```js
    function send() {
        ws.send(JSON.stringify({
            uuid: uuid,
            key: key,
            type: 'lock-info-request',
        }));
    }

     if (ws.isOpen) {
        send();
    }
    else {
        ws.once('open', send);
    }
```

every time this method is called, I check to see if ws is open, if not I wait until it opens

I suppose I could try to utilize an async constructor somehow and wait for ws to open before allowing methods to execute which call ws.send but that makes things a little trickier.

**Comment by alexhultman** [comment]
You don't need multiple listeners. What you need to do is to rethink your solution and fix your (in any case) need for up to infinite listeners. You are not following the priper flow of events - don't try and send on sockets that haven't fired the open event.

**Comment by alexhultman** [comment]
In fact this whole idea of having one (or many) listener per socket is really just due to lazyness and inefficiency in the Node.js universe. A proper solution would have one listener per server, not per socket. This is how the C++ interface works and nobody is complaining about this.

**Comment by ORESoftware** [comment]
You're right, I can pair mine down to one listener, but it just takes some design effort. My other issue ticket is more important - do not know why the error handler is being fired with an undefined error.
