### ISSUE TITLE
Can't compile µWebSockets on Manjaro (Arch Linux)

### ISSUE THREAD

**Issue by liamcurry** [uWebSockets/uWebSockets#408]
I am trying to use µWebSockets with Node.js/NPM, but every time I try to use the module I get this error:

    Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

Here's some info about my system:

    [0] % uname -a
    Linux sagan-manjaro 4.4.41-1-MANJARO #1 SMP PREEMPT Mon Jan 9 09:33:22 UTC 2017 x86_64 GNU/Linux
    
    [0] % gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
    Thread model: posix
    gcc version 6.3.1 20170109 (GCC)
    
    [0] % make -v
    GNU Make 4.2.1
    Built for x86_64-pc-linux-gnu
    Copyright (C) 1988-2016 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    [0] % node -v
    v7.4.0
    
    [0] % npm -v
    4.0.5

I've also tried running `sudo npm cache clean` and  installing `node-gyp` globally, but neither seemed to help. Any idea what's going on? Thanks.

**Comment by alexhultman** [comment]
What does `g++ --version` show you?

**Comment by liamcurry** [comment]
@alexhultman 

    [0] % g++ --version
    g++ (GCC) 6.3.1 20170109
    Copyright (C) 2016 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by alexhultman** [comment]
In that case you should have a build_log.txt in your node_modules/uws folder

**Comment by liamcurry** [comment]
@alexhultman yep, here are the contents:

```
make: Entering directory '/home/sagan/Dropbox/Projects/wod-app/node_modules/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
./Release/.deps/Release/obj.target/uws/src/Extensions.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 86,
  blocks: 8,
  atime: 2017-01-25T15:13:56.000Z,
  mtime: 2017-01-25T15:13:56.000Z,
  ctime: 2017-01-25T15:13:56.855Z,
  birthtime: 2017-01-25T15:13:56.855Z }
  CXX(target) Release/obj.target/uws/src/Group.o
./Release/.deps/Release/obj.target/uws/src/Group.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2928,
  blocks: 8,
  atime: 2017-01-25T15:13:57.000Z,
  mtime: 2017-01-25T15:13:57.000Z,
  ctime: 2017-01-25T15:13:57.715Z,
  birthtime: 2017-01-25T15:13:57.715Z }
  CXX(target) Release/obj.target/uws/src/WebSocketImpl.o
./Release/.deps/Release/obj.target/uws/src/WebSocketImpl.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 3077,
  blocks: 8,
  atime: 2017-01-25T15:13:58.000Z,
  mtime: 2017-01-25T15:13:58.000Z,
  ctime: 2017-01-25T15:13:58.635Z,
  birthtime: 2017-01-25T15:13:58.635Z }
  CXX(target) Release/obj.target/uws/src/Networking.o
./Release/.deps/Release/obj.target/uws/src/Networking.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2838,
  blocks: 8,
  atime: 2017-01-25T15:13:59.000Z,
  mtime: 2017-01-25T15:13:59.000Z,
  ctime: 2017-01-25T15:13:59.041Z,
  birthtime: 2017-01-25T15:13:59.041Z }
  CXX(target) Release/obj.target/uws/src/Hub.o
./Release/.deps/Release/obj.target/uws/src/Hub.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 3077,
  blocks: 8,
  atime: 2017-01-25T15:13:59.000Z,
  mtime: 2017-01-25T15:13:59.000Z,
  ctime: 2017-01-25T15:13:59.711Z,
  birthtime: 2017-01-25T15:13:59.711Z }
  CXX(target) Release/obj.target/uws/src/Node.o
./Release/.deps/Release/obj.target/uws/src/Node.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2856,
  blocks: 8,
  atime: 2017-01-25T15:14:00.000Z,
  mtime: 2017-01-25T15:14:00.000Z,
  ctime: 2017-01-25T15:14:00.145Z,
  birthtime: 2017-01-25T15:14:00.145Z }
  CXX(target) Release/obj.target/uws/src/WebSocket.o
./Release/.deps/Release/obj.target/uws/src/WebSocket.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2936,
  blocks: 8,
  atime: 2017-01-25T15:14:01.000Z,
  mtime: 2017-01-25T15:14:01.000Z,
  ctime: 2017-01-25T15:14:01.065Z,
  birthtime: 2017-01-25T15:14:01.065Z }
  CXX(target) Release/obj.target/uws/src/HTTPSocket.o
./Release/.deps/Release/obj.target/uws/src/HTTPSocket.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2958,
  blocks: 8,
  atime: 2017-01-25T15:14:01.000Z,
  mtime: 2017-01-25T15:14:01.000Z,
  ctime: 2017-01-25T15:14:01.821Z,
  birthtime: 2017-01-25T15:14:01.821Z }
  CXX(target) Release/obj.target/uws/src/Socket.o
./Release/.deps/Release/obj.target/uws/src/Socket.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 2846,
  blocks: 8,
  atime: 2017-01-25T15:14:02.000Z,
  mtime: 2017-01-25T15:14:02.000Z,
  ctime: 2017-01-25T15:14:02.218Z,
  birthtime: 2017-01-25T15:14:02.218Z }
  CXX(target) Release/obj.target/uws/src/addon.o
In file included from ../src/addon.cpp:2:0:
../src/addon.h: In function ‘void getSize(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/addon.h:417:14: warning: unused variable ‘isolate’ [-Wunused-variable]
     Isolate *isolate = args.GetIsolate();
              ^~~~~~~
./Release/.deps/Release/obj.target/uws/src/addon.o.d.raw { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17582,
  size: 3532,
  blocks: 8,
  atime: 2017-01-25T15:14:03.000Z,
  mtime: 2017-01-25T15:14:03.000Z,
  ctime: 2017-01-25T15:14:03.478Z,
  birthtime: 2017-01-25T15:14:03.478Z }
  SOLINK_MODULE(target) Release/obj.target/uws.node
  COPY Release/uws.node
  ACTION binding_gyp_action_after_build_target_move_lib uws
  TOUCH Release/obj.target/action_after_build.stamp
Release/obj.target/action_after_build.stamp { dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 17607,
  size: 0,
  blocks: 0,
  atime: 2017-01-25T15:14:03.000Z,
  mtime: 2017-01-25T15:14:03.000Z,
  ctime: 2017-01-25T15:14:03.615Z,
  birthtime: 2017-01-25T15:14:03.615Z }
make: Leaving directory '/home/sagan/Dropbox/Projects/wod-app/node_modules/uws/build'
```

**Comment by alexhultman** [comment]
I don't see any compilation problems. You can look into uws.js where it prints the error message and remove the try / catch so that you get the full error.

**Comment by VooVoo01** [comment]
@alexhultman ,
I have the same problem on my Linux Debian 8 with _gcc+Debian 4.9.2-10_ and _Node.js 7.5.0_.
Is it right version of gcc+ and Node for successfully using uws?
The build_log.txt file has been attached.
[build_log.txt](https://github.com/uWebSockets/uWebSockets/files/767195/build_log.txt)

When I remove try-catch block the full error message was:
`uws_linux_51.node: failed to map segment from shared object: Operation not permitted`

**Comment by VooVoo01** [comment]
I have solved the problem with error:
`uws_linux_51.node: failed to map segment from shared object: Operation not permitted`

In my case the disk with application has been mounted with the `noexec `flag in `/etc/fstab`
So, I just removed the flag.
