### ISSUE TITLE
WebSocketServer should emit 'listening' event, not just call the listening callback

### ISSUE THREAD

**Issue by ORESoftware** [uWebSockets/uWebSockets#410]
On linux

Having a bit of trouble converting this project from ws to uWs - speed enhancement would be really nice, because this is a locking library which receives tons of requests.

https://github.com/ORESoftware/live-mutex

looking for help in converting this project, but I am stuck; when I swap out ws for uWs things don't work but there is no error trace or anything.

**Comment by ORESoftware** [comment]
I sort of got it to work, but I have one question:

```js
 const ee = new EE();

    wss.on('open',() => {
        wss.isOpen = true;
        ee.emit('open', true);
    });

    this.init = function(cb){

        cb = cb.bind(this);

        if(wss.isOpen){
            process.nextTick(cb);
        }
        else{

            setTimeout(cb,2000);
            // ee.once('open', function(){
            //     process.nextTick(cb);
            // });
        }

        return this;
    };
```

how can I listen for the wss to open? The open event is not firing as far as I can tell. Is it on('listening')  instead of on('open')?

**Comment by ORESoftware** [comment]
@alexhultman could really use help with this question regarding listening for when the socket server is ready to accept connections - I don't know what event to use - 'open' is not firing for the socket server.

**Comment by stormwin** [comment]
Try 'connection' instead of 'open'

**Comment by alexhultman** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/uws.js#L444

#384

**Comment by ORESoftware** [comment]
No connection wont work sir, because if i attempt to connect to the socket
server before its ready I get errors, there must be some event that lets us
know the WSS is ready to accept connections...pls

**Comment by ORESoftware** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/uws.js#L442

I think you should fire a 'listening' event when this callback fires

also, just curious why you use an http server instead of just a tcp server?

**Comment by ORESoftware** [comment]
Ok, I can do this:


```js
   const wss = this.wss = new WebSocketServer({
        port: this.port,
        host: this.host
    }, 
        function(){
          ee.emit('listening');
    });
```

I will submit a PR as a suggestion

**Comment by alexhultman** [comment]
Ah, I see. You can actually pass a callback to the WebSocketServer, but it is also supposed to emit 'listening' event. That's redundant IMO, why have two paths for the same thing?
