### ISSUE TITLE
Not Compatible with Node Version 7.4.0

### ISSUE THREAD

**Issue by DevEclipse** [uWebSockets/uWebSockets#412]
Windows 7

![image](https://cloud.githubusercontent.com/assets/19868205/22344327/a582e642-e3b0-11e6-9a45-c021a7022c55.png)

**Comment by alexhultman** [comment]
Did you install a compiler? Is this 32-bit Windows 7 or 64-bit. Would be nice if you could provide some more info and some more digging.

**Comment by DevEclipse** [comment]
its a 32 bit Windows 7

**Comment by alexhultman** [comment]
The prebuilt binaries are 64-bit only so I'm guessing you don't have a compiler installed as per the error message? Can't help you if you won't answer questions in a timely manner.
