### ISSUE TITLE
sendfile

### ISSUE THREAD

**Issue by ronag** [uWebSockets/uWebSockets#424]
Given that NodeJS doesn't seem to have any plans to add support for [sendfile](http://man7.org/linux/man-pages/man2/sendfile.2.html). Maybe this is something that could be added to uws for improved performance when transferring files?

Something like:

```js
res
  .readfile(path, {
    start,
    end,
    fd
  })
  .on('finish', onFinish)
  .on('error', onError)
```

i.e. similar options & params as `fs.createReadStream`. For platforms that don't properly implement `sendfile` (OSX & Windows) we could have a fallback.

With this I believe uws could compete with NGINX as a file server.

**Comment by ronag** [comment]
https://blog.plenz.com/2014-04/so-you-want-to-write-to-a-file-real-fast.html

**Comment by ronag** [comment]
a similar `writefile` would also be nice:

```
req
  .writefile(path, {
    start,
    end,
    fd
  })
  .on('finish', onFinish)
  .on('error', onError)
```

**Comment by alexhultman** [comment]
This is out of scope of this project

**Comment by ronag** [comment]
@alexhultman: Could we at least get access to the socket descriptor on the response object (if that is not already the case?) so that this can be implemented outside of this project?

**Comment by alexhultman** [comment]
It is getHttpSocket().getFd()
