### ISSUE TITLE
expressjs compatibility

### ISSUE THREAD

**Issue by ronag** [uWebSockets/uWebSockets#425]
How's the compatibility with expressjs? Can uws be used instead of `http.createServer` as a drop in replacement?

**Comment by kapouer** [comment]
The first thing that prevented me from using `require('uws').http.createServer(app);` is the missing `res.setHeader` method.

**Comment by alexhultman** [comment]
setHeader, writeHead, write, end <- these are the top wanted functions that will be in v0.13.0.

**Comment by kapouer** [comment]
can't you just rewrite Node.js ?

**Comment by alexhultman** [comment]
I did apply to StrongLoop like half a year ago but they only hire people with significant amounts of commits and now I'm banned from the organization so I cannot open issues or PRs rofl

**Comment by kapouer** [comment]
Isn't StrongLoop IBM ? Maybe you'd have more success (or more heart attacks) with zeit.

**Comment by alexhultman** [comment]
Zeit is shit

**Comment by alexhultman** [comment]
I just managed to get ExpressJS running on uws after hours of debugging this mountain of dynamic bloat. It is actually completely insane how bloated ExpressJS is, it is like they entered a competition on making the most use of bloated dynamic features of JS as possible and won. Every single request is dynamically inherited from some application prototype that adds the send function to the res object - holy shit dude.

Performance is shit - uws only doubled the requests/second on this machine: 8k req/sec with vanilla Node.js and 18k with uws. It is required that upstream ExpressJS change 2 lines of code to make it compatible with uws (ExpressJS has hardcoded dependency on http.ServerResponse.prototype and http.IncomingMessage.prototype.

As a reference point, this laptop of mine does 130k requests/sec without ExpressJS inside of Node.js.

ExpressJS needs some serious performance optimizations: even the low level finalhandler library cut the performance from 130k down to 80k req/sec and ExpressJS on top of that cuts it down to 18k like mentioned.

**Comment by alexhultman** [comment]
With the latest commit you can actually run a complete demo app built in Express. Some functions are still unimplemented placeholders but the page loads and everything seems to work.

**Comment by alexhultman** [comment]
The flow is now:

var express = require('express')
var uws = require('uws')
var app = uws.http.getExpressApp(express)

// do stuff with app

uws.http.createServer(app).listen(3000)

**Comment by alexhultman** [comment]
@kapouer Zeit is actually hiring if you're interested

**Comment by ddibiase** [comment]
I just tried this (in complete excitement) but got the error:

    TypeError: Cannot read property '_header' of undefined

Starting the server with this:

    import express from 'express';
    import bodyParser from 'body-parser';
    import uws from 'uws';

    this.app = express();
    this.api = uws.http.getExpressApp(this.app);
    this.api.disable('x-powered-by');
    this.api.use(bodyParser.json({ limit: config.json_limit }));
    this.api.use(bodyParser.raw({ limit: config.raw_limit }));

    this.server = uws.http.createServer(this.api).listen(
      this.config.port,
      (err) => {
        if (err) {
          throw err;
        }
        console.log('Server online...')
      }
    );

Are there any documented gotchas or considerations that need to be made with this replacement? Also
