### ISSUE TITLE
Can't compile project which includes uWS

### ISSUE THREAD

**Issue by SzAmmi** [uWebSockets/uWebSockets#428]
I started writing a game server built with uWS. I can't compile it, I'm using CLion IDE (on Ubuntu) and the compiler gives me this:

```
error while loading shared libraries: libuWS.so: cannot open shared object file: No such file or directory
```

Here's my `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.6)
project(GameServer)

set(CMAKE_CXX_STANDARD 11)

set(SOURCE_FILES main.cpp)
add_executable(GameServer ${SOURCE_FILES})

target_link_libraries(GameServer uWS)
target_link_libraries(GameServer z)
```

I had to add `libz` to my CMakeLists because the compiler said it's missing.

**Comment by alexhultman** [comment]
These issues are not caused by uws and should not be posted here. You have general programming issues to solve yourself.

**Comment by SzAmmi** [comment]
@alexhultman I think you should add `libuWS.so` to `/usr/lib` (not `lib64`) because gcc doesn't check `lib64` for default as far as I know.
