### ISSUE TITLE
Add vector<uint8_t> support to `ws.send `function

### ISSUE THREAD

**Issue by SzAmmi** [uWebSockets/uWebSockets#431]
C++ here. This is how my code looks like:
```c++
std::vector<uint8_t> v;
v.push_back(90);

char *data = (char *) v.data();
ws.send(data, uWS::BINARY);
```

The message I receive: (client coded in NodeJS, output in hex):
```
<Buffer 5a 1b b1 08 a9 7f>
```
I think it should be:
```
<Buffer 5a>
```

What's `1b b1 08 a9 7f`? How I can send the message right way as expected?

**Comment by SzAmmi** [comment]
```c++
char *data = "a";
```
It'll show `<Buffer 61>`

**Comment by SzAmmi** [comment]
I think it would be easier if we add `std::vector<uint8_t>` or `uint8_t pointer` support to the `send` function.

**Comment by SzAmmi** [comment]
Solution: http://stackoverflow.com/questions/18410234/how-does-one-represent-the-empty-char

**Comment by alexhultman** [comment]
Again, this is not a bug but rather you not understanding C fundamentals. Don't open bug reports regarding generic C fundamentals because they do not belong here.
