### ISSUE TITLE
Sending data after \0 byte?

### ISSUE THREAD

**Issue by SzAmmi** [uWebSockets/uWebSockets#432]
In JavaScript:
```javascript
var d = new DataView(new ArrayBuffer(3));
d.setUint8(0, 1);
d.setUint8(1, 0);
d.setUint8(2, 2);
console.log(new Uint8Array(d.buffer));
```

It'll return bytes:
```javascript
[1, 0, 2]
```

As far as I can see the data in char after null byte look like "deleted". Hmm, would you add `std::vector<uint8_t>` support to `ws.send` **C++** function? In vector I can add multiple `\0` bytes. In zaphoyd's websocketpp it's possible to send data using the vector. I just switched to uWebSockets for speed =)

**Comment by alexhultman** [comment]
Send takes char ptr and optionally length, this should be obvious as this is the only way to represent binary data not being a C string. In C, you represent non-strings as char ptr and length. This is also the convention when constructing a std::string - if you leave out the length this means it is a string that ends with a null char. This is C amd C++ fundamentals ehich can be logically inferred sinve only strings can end with null char.

**Comment by SzAmmi** [comment]
@alexhultman Thanks for information! Really appreciate your help :)
