### ISSUE TITLE
Versions + Branches

### ISSUE THREAD

**Issue by andymans** [uWebSockets/uWebSockets#435]
Node.js - I'm confused. 

In your dist directory under nodejs there is a uws.js file. 

That file is dated yesterday. And shows you've bumped the version to 0.12.0.

I install uws with npm, specifying 0.12.0 and I get a uws.js dated 3 Dec 2016. The api offered by *this* uws is nothing like that illustrated in your examples. For example uws.http.createServer is met with an error on uws.http being "undefined".

Am I doing something completely stupid? Or would it make sense to move your node.js code into its own repo and put it under version control?

**Comment by alexhultman** [comment]
As is written in the post, version 0.13.0 is not yet released to NPM. As is also written, you need to compile the addon youtself for now. I am working on it.

**Comment by andymans** [comment]
Ah cool, thx. 

Great work by the way - I'm testing w/ the existing version for now and the performance / stability seem excellent.
