### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by EduardoRFS** [uWebSockets/uWebSockets#437]
UWS 0.12 works fine, but 0.13(cloned from git) cause node to crash

Linux, Nodejs, AMD Bulldozzer(FX 8120)

```
#
# Fatal error in ../deps/v8/src/api.cc, line 1062
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

    node(v8::base::debug::StackTrace::StackTrace()+0x16) [0x158c2f6]
    node(V8_Fatal+0xd6) [0x1587016]
    node(v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)+0xf7) [0xaa9af7]
    /home/eduardo/JSProjects/uWebSockets/nodejs/dist/uws_linux_52.node(Main(v8::Local<v8::Object>)+0x145a) [0x7f322e7a3c7a]
    node(node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)+0x325) [0x12c6cb5]
    node(v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))+0x184) [0xad1fc4]
    node() [0xb5453c]
    node(v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)+0x155) [0xb55375]
    [0x31a5a07843a7]
[1]    31728 illegal hardware instruction (core dumped)  node
`

**Comment by kapouer** [comment]
Same here:

<pre>
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x29a8e26cfb51 <JS Object>#0#
    1: .node [module.js:597] [pc=0x1ee7cb0d6bc4] (this=0x3d6dd08d5289 <an Object with map 0x2698f031a991>#1#,module=0x2a8086497639 <a Module with map 0x2698f031b859>#2#,filename=0x2a8086495291 <String[67]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws_linux_48.node>)
    2: load [module.js:487] [pc=0x1ee7cb03ea12] (this=0x2a8086497639 <a Module with map 0x2698f031b859>#2#,filename=0x2a8086495291 <String[67]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws_linux_48.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:446] [pc=0x1ee7cb03e53d] (this=0x29a8e2604381 <undefined>,module=0x2a8086497639 <a Module with map 0x2698f031b859>#2#,filename=0x2a8086495291 <String[67]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws_linux_48.node>)
    4: _load [module.js:438] [pc=0x1ee7cb033de2] (this=0x3d6dd08d5241 <JS Function Module (SharedFunctionInfo 0x3d6dd082c231)>#3#,request=0x2a80864937b9 <String[14]: ./uws_linux_48>,parent=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,isMain=0x29a8e2604271 <false>)
    5: require [module.js:~494] [pc=0x1ee7cb0a5dec] (this=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,path=0x2a80864937b9 <String[14]: ./uws_linux_48>)
    6: require(aka require) [internal/module.js:20] [pc=0x1ee7cb048986] (this=0x29a8e2604381 <undefined>,path=0x2a80864937b9 <String[14]: ./uws_linux_48>)
    7: /* anonymous */(aka /* anonymous */) [/home/dev/Software/github/uWebSockets/nodejs/dist/uws.js:21] [pc=0x1ee7cb0d46f3] (this=0x29a8e2604381 <undefined>)
    8: /* anonymous */ [/home/dev/Software/github/uWebSockets/nodejs/dist/uws.js:35] [pc=0x1ee7cb0d4aa8] (this=0x2a808647d5e1 <an Object with map 0x3d7f2c075e9>#5#,exports=0x2a808647d5e1 <an Object with map 0x3d7f2c075e9>#5#,require=0x2a8086493111 <JS Function require (SharedFunctionInfo 0x3d6dd085f9d1)>#6#,module=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,__filename=0x2a808647b7a9 <String[56]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws.js>,__dirname=0x2a80864930a9 <String[49]: /home/dev/Software/github/uWebSockets/nodejs/dist>)
    9: _compile [module.js:570] [pc=0x1ee7cb047150] (this=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,content=0x2a808647e5e1 <Very long string[18105]>#7#,filename=0x2a808647b7a9 <String[56]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws.js>)
   10: .js [module.js:579] [pc=0x1ee7cb03ffeb] (this=0x3d6dd08d5289 <an Object with map 0x2698f031a991>#1#,module=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,filename=0x2a808647b7a9 <String[56]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws.js>)
   11: load [module.js:487] [pc=0x1ee7cb03ea12] (this=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,filename=0x2a808647b7a9 <String[56]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws.js>)
   12: tryModuleLoad(aka tryModuleLoad) [module.js:446] [pc=0x1ee7cb03e53d] (this=0x29a8e2604381 <undefined>,module=0x2a808647d591 <a Module with map 0x2698f031b859>#4#,filename=0x2a808647b7a9 <String[56]: /home/dev/Software/github/uWebSockets/nodejs/dist/uws.js>)
   13: _load [module.js:438] [pc=0x1ee7cb033de2] (this=0x3d6dd08d5241 <JS Function Module (SharedFunctionInfo 0x3d6dd082c231)>#3#,request=0x3d6dd085e5c1 <String[12]: @kapouer/uws>,parent=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,isMain=0x29a8e2604271 <false>)
   14: require [module.js:~494] [pc=0x1ee7cb0a5dec] (this=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,path=0x3d6dd085e5c1 <String[12]: @kapouer/uws>)
   15: require(aka require) [internal/module.js:20] [pc=0x1ee7cb048986] (this=0x29a8e2604381 <undefined>,path=0x3d6dd085e5c1 <String[12]: @kapouer/uws>)
   16: /* anonymous */ [/home/dev/Projects/nsocket/site/app.js:61] [pc=0x1ee7cb047fa4] (this=0x3d6dd08d6bb9 <an Object with map 0x3d7f2c075e9>#9#,exports=0x3d6dd08d6bb9 <an Object with map 0x3d7f2c075e9>#9#,require=0x3d6dd08d6a71 <JS Function require (SharedFunctionInfo 0x3d6dd085f9d1)>#10#,module=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,__filename=0x3d6dd08d6b79 <String[38]: /home/dev/Projects/nsocket/site/app.js>,__dirname=0x3d6dd08d6b51 <String[31]: /home/dev/Projects/nsocket/site>)
   17: _compile [module.js:570] [pc=0x1ee7cb047150] (this=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,content=0x3d6dd08d74e9 <Very long string[2168]>#11#,filename=0x3d6dd08d6b79 <String[38]: /home/dev/Projects/nsocket/site/app.js>)
   18: .js [module.js:579] [pc=0x1ee7cb03ffeb] (this=0x3d6dd08d5289 <an Object with map 0x2698f031a991>#1#,module=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,filename=0x3d6dd08d6b79 <String[38]: /home/dev/Projects/nsocket/site/app.js>)
   19: load [module.js:487] [pc=0x1ee7cb03ea12] (this=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,filename=0x3d6dd08d6b79 <String[38]: /home/dev/Projects/nsocket/site/app.js>)
   20: tryModuleLoad(aka tryModuleLoad) [module.js:446] [pc=0x1ee7cb03e53d] (this=0x29a8e2604381 <undefined>,module=0x3d6dd08d69e1 <a Module with map 0x2698f031b859>#8#,filename=0x3d6dd08d6b79 <String[38]: /home/dev/Projects/nsocket/site/app.js>)
   21: _load [module.js:438] [pc=0x1ee7cb033de2] (this=0x3d6dd08d5241 <JS Function Module (SharedFunctionInfo 0x3d6dd082c231)>#3#,request=0x3d6dd08531d9 <String[38]: /home/dev/Projects/nsocket/site/app.js>,parent=0x29a8e2604201 <null>,isMain=0x29a8e26043c1 <true>)
   22: /* anonymous */(aka /* anonymous */) [module.js:604] [pc=0x1ee7cb0338aa] (this=0x29a8e2604381 <undefined>)
   23: run(aka run) [bootstrap_node.js:394] [pc=0x1ee7cb033730] (this=0x29a8e2604381 <undefined>,entryFunction=0x3d6dd0851d11 <JS Function Module.runMain (SharedFunctionInfo 0x3d6dd082d071)>#12#)
   24: startup(aka startup) [bootstrap_node.js:149] [pc=0x1ee7caf44932] (this=0x29a8e2604381 <undefined>)
   25: /* anonymous */(aka /* anonymous */) [bootstrap_node.js:509] [pc=0x1ee7caf42759] (this=0x29a8e2604201 <null>,process=0x29a8e26e1959 <a process with map 0x3d7f2c11671>#13#)
=====================


==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: Main(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: 0x75884b
 6: 0x758f18
 7: 0x75907e
 8: 0x1ee7caf092a7

</pre>

**Comment by alexhultman** [comment]
#439 thanks
