### ISSUE TITLE
Server initiated data along with client initiated data

### ISSUE THREAD

**Issue by hiharsh** [uWebSockets/uWebSockets#441]
Hi,
I am fairly new to this web programming and would appreciate your help.
I would like to achieve following

1) Start a websocket server on C++ running on Ubuntu 16.
2) Listen for messages from client
3) Send response for messages based on some processing in my custom code.
4) SEND SERVER INITIATED text message/string to client when something changes on my custom code running on Server.
For # 1 to 3 I can use the echo server for 1 to 1 message handling. **However, to achieve the #4  I believe I will have to launch a server thread to send data to client(s) on the same websocket port.**

**Any example code how to create  a thread to send data to all clients as well as to an individual client?** 

```
dummy test class below.

test.cpp
class test
{
public:
void processDataFromClient(const string & data);//this needs to get filled by websocket read method? how?
void pushDataToClient(const string & data);

};
test::pushDataToClient(const string & data)
{
async_write(socketId, text) // how do I call this from my test.cpp?
}

test::void processDataFromClient(const string & data)
{
//do some computation based on the text received
//turn on the light
//once Light is on for a minute call
  pushDataToClient( lighton) ;
}

//web_socket_server.cpp
main
{
//open a webSocket
//listen for messages from client //notify test class
//create a server thread to send data to all client whenever server wants to push data? how to achieve this? Could you please provide complete syntax/snippet with server thread? 
}

```

**Comment by hiharsh** [comment]
Hi Alex,
May I know the resolution/answer to the question? I really liked the library but can't figure out how to use it for the above mentioned purpose.

**Comment by alexhultman** [comment]
This is not C++ 101. You have already opened 5 identical issues in libwebsockets, Beast, WebSocket++ and others. If you don't know how to do C++ then don't.
