### ISSUE TITLE
uws和ws不完全兼容

### ISSUE THREAD

**Issue by leeyo** [uWebSockets/uWebSockets#442]
<pre>
var WebSocketServer = require('ws').Server;
var clients = new WebSocketServer(options);
clients.on('connection',function(client){
   client.on('something',function(val){
       
   });

    client.emit('something','test');
});
</pre>
如上代码，在ws里面可以自定义事件监听。在uws 里面，返回的 class WebSocket { } 没有继承自 EventEmitter，不能够自定义事件监听

**Comment by alexhultman** [comment]
Mycket bra rapport här, va. Ska vi ta den på latin också?

**Comment by leeyo** [comment]
@alexhultman what do you mean？

**Comment by alexhultman** [comment]
If you write your reports in mandarin, I'll respond in swedish.

**Comment by daliwali** [comment]
@leeyo `emit`和`on`不可能用所有的字 (https://github.com/uWebSockets/uWebSockets/blob/b2b51a3ee04141cded43414b24b54002defd475d/nodejs/dist/uws.js#L125-L136) 因为这是最优化的。

**Comment by leeyo** [comment]
@alexhultman Sorry... I can't read swedish,let me ask in english again

<pre>
var WebSocketServer = require('ws').Server;
var clients = new WebSocketServer(options);
clients.on('connection',function(client){
   client.on('something',function(val){
       
   });

    client.emit('something','test');
});
</pre>


For the example above,in `ws` it can define custom event and emit it. But in `uws`, `clients.on('connection',function(client){});`,this line return the object of `class WebSocket { }`,but it's not inheritance of `EventEmitter`,so in `uws` i can't define custom event.
