### ISSUE TITLE
How to route different urls?

### ISSUE THREAD

**Issue by WeissGotsman** [uWebSockets/uWebSockets#444]
Websocket:

how to make the server able to handle the following two urls 
"ws://localhost:3000/A" --> e.g. push message "A" every 10 seconds
"ws://localhost:3000/B" --> e.g. push message "B" every 20 seconds

looks like map ports to different urls might be the most close solution?

HTTP:

Is there any example on how to setup an http server and make routes for different requests? the module seems partially done.

SOME MINOR ISSUES:

1. in HTTPSocket.h, #undef DELETE because it's already defined in winnt.h
2. link ws2_32.lib on windows for example projects
3. use debug version of libuv in cmake for debug build

Include the following information (where applicable):

* What operating system are you running?
  * Windows
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL is not part of the equation

**Comment by alexhultman** [comment]
Fill the issue template

**Comment by alexhultman** [comment]
Your onConnection callback gets an HttpRequest which has getUrl method you can switch on. You can use this at connection to transfer the WebSocket to a different group. You can view groups as "protocols".
