### ISSUE TITLE
100% cpu usage when ulimit cap is reached

### ISSUE THREAD

**Issue by jimmyt857** [uWebSockets/uWebSockets#445]
Include the following information (where applicable):

* What operating system are you running?
  * Linux
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL via µWS

When there are enough connections to reach the linux file descriptor limit, the server begins using 100% of the cpu. The cpu usage comes from the server continually reaching this line (with errno set to EMFILE in my case):

https://github.com/uWebSockets/uWebSockets/blob/master/src/Node.h#L81

I assume this means that when accept() is unable to open a new file descriptor, it leaves the pending connection in the queue and so the listening socket continues to stay ready for reading. I'm reporting this not because I think the behavior should be changed, but because it took me awhile to track this down, so I think it would be nice to have some sort of logging (which could be turned on by an environment flag) to avoid the silent failure.

If you're happy with this solution I can make a PR. It does feel a bit silly though to add in a compiler flag for what is currently a single logging statement.

**Comment by alexhultman** [comment]
A better solution would be to stop the polling of the listen fd and replace it with a 10 second timer which starts the polling again.

**Comment by jimmyt857** [comment]
Haha, I actually just thought of this in the shower. But we could instead remove the listen callback from the libuv event queue and re-add it as a 50ms timer event. Whenever the accept works again it could switch back to read polling.

**Comment by alexhultman** [comment]
Shower programming is the best

**Comment by jimmyt857** [comment]
👍 

I'll work on this and submit a PR.

**Comment by mafrost** [comment]
Nice solution. We have also encountered this with no good solution on how to handle it.

**Comment by arputcu** [comment]
how can i debug/see if ulimit cap is reached?

**Comment by jimmyt857** [comment]
Just add a print statement right before the return statement (the line of code in my first post) that prints errno after accept failure, then look up the errno code on google.
