### ISSUE TITLE
Slow response time when using http server

### ISSUE THREAD

**Issue by Rece** [uWebSockets/uWebSockets#448]
Thanks so much for this super cool project. I'm running into an odd issue where I don't get anywhere near the performance you are reporting for the http server. I'm wondering if you have any idea of what I might be doing wrong.

* What operating system are you running?
  * OS X

* What platform/language are you using?
  * Node.js

* Are you using SSL, if so, how?
  * SSL is not part of the equation

* Can you show me some short code that triggers your issue?

When I clone the repo, make the project, and then start the `http_demo.js` node server I get the following performance stats:

`ab -c 1 -n 10 localhost:3000/`

```Server Software:
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      1
Time taken for tests:   20.059 seconds
Complete requests:      10
Failed requests:        0
Total transferred:      510 bytes
HTML transferred:       120 bytes
Requests per second:    0.50 [#/sec] (mean)
Time per request:       2005.893 [ms] (mean)
Time per request:       2005.893 [ms] (mean, across all concurrent requests)
Transfer rate:          0.02 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:  2002 2006   1.9   2006    2009
Waiting:        0    0   0.1      0       0
Total:       2002 2006   1.9   2006    2009

Percentage of the requests served within a certain time (ms)
  50%   2006
  66%   2007
  75%   2007
  80%   2007
  90%   2009
  95%   2009
  98%   2009
  99%   2009
 100%   2009 (longest request)
```

This seems way off. Any idea where I am going wrong?

**Comment by alexhultman** [comment]
I think this is a bad reporting by ab. 20 seconds is about the time it takes for an http socket to time out and close. I guess ab expects the server to close the connection, which it won't until timeout.

**Comment by alexhultman** [comment]
No wait the timeout is about 2 seconds so maybe ab expects the server to close every connection which is absurd.

**Comment by Rece** [comment]
Ah, Interesting. What tool do you use to test requests/second. I'll give it a try to see if this really is ab's fault

**Comment by alexhultman** [comment]
Maybe you can pass -k as argument to ab?

**Comment by Rece** [comment]
Tried using wrk and got the numbers I was expecting. Thanks for the help!

**Comment by Helidium** [comment]
Correct me if I am wrong, but I think ab is using http 1.0, which by default doesnt enable keep-alive connections. By using -k switch keep alive connections are enabled and thus not expected to be closed.

**Comment by alexhultman** [comment]
Yes exactly. Ab is a tool that measures Http 1.0, not really Http 1.1 performance. Since Http 1.1 is from 1997 I think it is quite okay to target that version. Apache benchmark is an old relic and should not be used IMO.

**Comment by FlorentMasson** [comment]
I can confirm I also have an additional 2s delay on every regular HTTP Request, with wget, curl or my browser.
I tried with `wget --no-http-keep-alive` but I still had the delay.
It looks like `response.end()` does not add the _Content-Length_ header. Adding this header to the response effectively removed the delay for the client to get the response.
But I think it still takes 2s to close the connection, I'm not sure where this delay comes from. It looks like it takes 2 epoll_wait timeout (1024) to effectively do it. Not sure also if/how keep-alive is implemented.
