### ISSUE TITLE
cannot read property createServer of undefined

### ISSUE THREAD

**Issue by prakashgp** [uWebSockets/uWebSockets#451]
* Linux
  * Node.js
```
'use strict';

const uws = require('uws');

const document = Buffer.from('Hello world!');

const server = uws.http.createServer((req, res) => {
    // handle some POST data
    if (req.method === 'POST') {
        var postString = '';
        req.on('data', (arrayBuffer) => {
            postString += Buffer.from(arrayBuffer).toString();
        }).on('end', () => {
            res.end('You posted me this: ' + postString);
        });
    // handle some GET url
    } else if (req.url === '/') {
        res.end(document);
    } else {
        res.end('Unknown request by: ' + req.headers['user-agent']);
    }
});

const wss = new uws.Server({server: server});

wss.on('connection', (ws) => {
    ws.send('Welcome to the 10s!');
});

server.listen(3000);
```

Console Out put 
```

gpz@gpz-K54C:/mnt/dev/NodeJS/server$ node index.js
/mnt/dev/NodeJS/server/index.js:7
const server = uws.http.createServer((req, res) => {
                       ^

TypeError: Cannot read property 'createServer' of undefined
    at Object.<anonymous> (/mnt/dev/NodeJS/server/index.js:7:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by alexhultman** [comment]
NPM hold v0.12.0 and the http support is in v0.13.0 which is not released yet.

**Comment by andymans** [comment]
The below will work on v 0.12.0 - it's quite easy to get hold of the uws http server object and use it for e.g. your route handling. Not nearly as pretty as we'll have in  0.13.0 but an acceptable stop-gap.


`'use strict'`

`const Server = require('uws').Server`

`const wss = new Server({ port: 3000 })`

`wss.httpServer.listeners('request').forEach(function(listener) {
     wss.httpServer.removeListener('request', listener)
})`

`wss.httpServer.on('request', function(req, res){
   if('/' == req.url){
     //your route handling code here
  }
})`

**Comment by alexhultman** [comment]
That is not http from uws, it is the regular old Node.js http server. This is obvious if you benchmark it. Http is in 0.13, not in 0.12

**Comment by andymans** [comment]
Aha. Yes, I shd have pointed that out. It's even more obvious from the source :-) )

**Comment by prakashgp** [comment]
@alexhultman I don't understand what you are saying, i found this example on nodejs folder of this repository, so i think it would work, is there any way i can get this uws.http.createServer working ?(of course with high performance)

I tried to build from source using `make ` command, and that too gave me error, i've opened another issue for that.

I'm really excited to try this please help
