### ISSUE TITLE
Custom headers & response code for HTTP server

### ISSUE THREAD

**Issue by jlisee** [uWebSockets/uWebSockets#459]
I am on Linux using µWS without SSL to create a C++ server application.  It's awesome to see that you have basic server support but I had to patch the `HttpResponse` in order to be use custom headers.  My use case was serving HTML directly from the same binary that serves the WebSocket.

Do you have interest in a pull request for this or plans yourself?  I am not very familiar with the internals but it looks like to handle the dynamic size of the headers two messages will have to be pushed onto the socket message queue.

**Comment by jlisee** [comment]
Ok sorry for the noise this is possible with the following code:

```c++
int main()
{
    uWS::Hub h;
    std::string document = "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Length: 48\r\n\r\n<h2>Well hello there, this is a basic test@</h2>";

    h.onHttpRequest([&document](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
            res->write(document.data(), document.length());
            res->end();
    });

    h.listen(3000);
    h.run();
}
```

**Comment by FlorentMasson** [comment]
Thanks, I was looking for it and it was not obvious
