### ISSUE TITLE
Error in node: Double free or corruption

### ISSUE THREAD

**Issue by porsager** [uWebSockets/uWebSockets#461]
Linux / Node.js / SSL is not part of the equation

Hi. 

When sending some binary data i sporadically receive the following error.

```
*** Error in `node': double free or corruption (!prev): 0x0000000003dbaee0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f08d6cee7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7f08d6cf6e0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f08d6cfa98c]
/home/parallels/Downloads/supervisor-client/node_modules/uws/uws_linux_51.node(_ZN3uWS9WebSocketILb0EE4sendEPKcmNS_6OpCodeEPFvPvS5_bS5_ES5_+0x9e0)[0x7f08d49a1d40]
/home/parallels/Downloads/supervisor-client/node_modules/uws/uws_linux_51.node(_Z4sendILb0EEvRKN2v820FunctionCallbackInfoINS0_5ValueEEE+0x17c)[0x7f08d49abd9c]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x129)[0xa21ea9]
node[0xa99e9d]
node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xec)[0xa9accc]
[0x337fe55063a7]
```

I'm specifically getting a buffer from fs.execFile, and then sending the buffer retrieved from stdout.

Like:
```
fs.execFile('something', {
  encoding: 'buffer',
  maxBuffer: 500 * 1024
}, (err, buffer) => socket.send(buffer, { binary: true }))
```

**Comment by alexhultman** [comment]
What version of uws is this?

**Comment by alexhultman** [comment]
You are using the client, nlt server?

**Comment by hmalphettes** [comment]
I am getting the same error on debian:testing (inside a container)
```
root@05084a9427ca:/apps/marcus# npm ls uws
marcus@0.6.209 /apps/marcus
`-- uws@0.12.0
uws@0.12.0
root@05084a9427ca:/apps/marcus# node --version
v6.9.5
root@05084a9427ca:/apps/marcus# node -e 'console.log(`uws_${process.platform}_${process.versions.modules}.node`)'
uws_linux_48.node
```

The same test unit works fine on my mac with node-7.5.0

**Comment by porsager** [comment]
Sorry, forgot to specify that. It's the client and version 0.12

**Comment by alexhultman** [comment]
It might be fixed in v0.13

**Comment by porsager** [comment]
Ah perfect.. I'll do a test with the current master.

**Comment by porsager** [comment]
It doesn't happen anymore here. Thanks a lot @alexhultman

**Comment by alexhultman** [comment]
Nice but would you mind resetting to before this commit: https://github.com/uWebSockets/uWebSockets/commit/fdd025e16a882dad04e24269a069dd3aa810509b

And then see if you can reproduce it? This has been a known issue but I want to know for sure that this fixed it

**Comment by porsager** [comment]
Sure.. I just tried it, and it happened almost immediately..

I then tried with https://github.com/uWebSockets/uWebSockets/commit/fdd025e16a882dad04e24269a069dd3aa810509b, and couldn't reproduce, so seems to be that ;)

**Comment by alexhultman** [comment]
:+1: very nice

**Comment by porsager** [comment]
Just a little note and a thank you ;)
We switched our clients (raspberry pi's) from ws to use 'uws' after 0.13 with the fix was released, and they're now using half the cpu (from 20% down to 10%).

**Comment by alexhultman** [comment]
Nice but currently the client code is masking 1 byte a time so you can improve this significantly by optimizing the code changed in this commit. Best is to mask 4 bytes a time and not rotate with mod.
