### ISSUE TITLE
Missing SNI from uws client

### ISSUE THREAD

**Issue by jimdebeer** [uWebSockets/uWebSockets#462]
When connecting trough a NGINX proxy it seems that the UWS client does not add SNI. Is this intentional? It would be nice to add a host to the client, since it allows us to not allocate public ip addresses to every domain. Could be another issue but I am getting `failed to get SNI name from client` when trying to find the host name it results in `null`.

Using any browser client or the websocket client (v1.0.24) does work

We use a nginx setup with https://github.com/openresty/lua-nginx-module#ssl_certificate_by_lua_block

 * Linux (nginx server)
 * OS X (client)
 * Node.js
 * SSL via proxy over nginx
 * uws version 0.12

ps - big fan of your work -- uws is one of the best pieces of software I've ever used

**Comment by jimdebeer** [comment]
I've setup a test app on cloudflare (they use a similar nginx setup) http://ssltest.myfancydomain.com/ and https://ssltest.myfancydomain.com/

**Comment by alexhultman** [comment]
It should be as simple as calling SSL_set_tlsext_host_name(ssl, hostname) when connecting, will add this

**Comment by jimdebeer** [comment]
Any estimate for when you will add it?

**Comment by alexhultman** [comment]
It should be in master now

**Comment by jimdebeer** [comment]
awesome man!
