### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by jclc** [uWebSockets/uWebSockets#463]
Okay, I can understand the lack of documentation, but Jesus Christ, would it kill you to add some comments in the code? I'm trying to understand how this works but it's incredibly frustrating as NOTHING is commented or explained and this isn't exactly what I'd call self-documenting code

**Comment by alexhultman** [comment]
It should be pretty self explanatory. I prefer good variable- and function names over comments. The general design is Node + Socket classes provide TCP support, HttpSocket and WebSocket both extend Socket while implementing their respective protocol ontop. Then you have HttpResponse which further abstracts HttpSocket (needed to support out of order http pipelining). Hub extends Node and acts as a per-thread resource.

**Comment by jclc** [comment]
It might be self-explanatory for someone who knows the ins and outs of the protocol, but the point of a high level library is to abstract the inner workings for other developers. 'Hub' doesn't really explain a lot other than that it's a hub for something. I thought it was a hub for websocket connections. I still don't know what Group is for. I appreciate the explanation, but developers themselves often grossly overestimate the readability of their own code. I think all developers should always be adding occasional comments to explain what's happening - not afterwards, but as they're adding code.

There are some self explanatory functions and classes, but the entire library? Oh, no.

**Comment by alexhultman** [comment]
There are many examples in tests/main.cpp that should be enough to understand the basic idea of the lib. I'm not going to argue about this -> things are the way they are and if its not what you need then there are other good alternatives like WebSocket++ which has better documentation.

**Comment by dnlbazac** [comment]
Hello.

I agree with jclc, I also feel the need for some documentation.
How about adding some 'story' about each class? "A Node is ... A Group contains ... and is used to ... etc."
I guess that shouldn't take long to write.
That would really help.
Many thanks in advance.

**Comment by alexhultman** [comment]
There are now a few comments in WebSocket.h and .cpp and more will be added
