### ISSUE TITLE
Linker error on Mac OS X when using HttpResponse write/end functions

### ISSUE THREAD

**Issue by mafrost** [uWebSockets/uWebSockets#464]
Using OS X, C++, not wss/https, using latest commit (751e17c9adad8594d6b714b3a7c4281f3ae2f381).

A linker error is thrown when making the project if write/end functions on the HttpResponse struct is used. This works on linux but not on mac.

Code to duplicate:

```
...
h->onHttpRequest([](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
    std::string responseString = "test";
    res->end(responseString.data(), responseString.length()); // this line errors on mac os x
}
...
```

Linker error:

```
Undefined symbols for architecture x86_64:
  "_SSL_get_error", referenced from:
      uS::Socket::write(uS::SocketData::Queue::Message*, bool&) in test.cpp.o
  "_SSL_write", referenced from:
      uS::Socket::write(uS::SocketData::Queue::Message*, bool&) in test.cpp.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by alexhultman** [comment]
Is this also the case in v0.12?

**Comment by mafrost** [comment]
I don't think 0.12 had the HttpResponse. It was introduced in 0.13, along with support for HTTP. Right?

**Comment by alexhultman** [comment]
No but 0.12 makes use of the same underlying SSL functions so you should get the same linker errors either way

**Comment by mafrost** [comment]
0.12 works. The latest version also works, as long as I don't call a function on the HttpResponse. Could it be related to the fixed issue #430 perhaps?

**Comment by alexhultman** [comment]
I cannot reproduce this. I just compiled the lib with the Makefile and tested both WebSocket echo and HTTP and it worked as it should.

There are certainly things to improve when it comes to the Makefile on OS X, but it was actually quite easy to get it working:

/usr/local/lib should hold libuWS.dylib
/usr/local/include/uWS should hold all headers

Boom! Now it works just like on Linux.

**Comment by alexhultman** [comment]
You need ofc link to all dependencies. I get similar errors when not linking to OpenSSL.
