### ISSUE TITLE
cpu used in benchmarks

### ISSUE THREAD

**Issue by devlo** [uWebSockets/uWebSockets#466]
Could you tell me which CPU you used in your http single thread benchmarks? and was the clock stock on that cpu. I ask because this are impressive results considering you just use libuv. Benchmarks were made on Linux, right?

**Comment by alexhultman** [comment]
I have an Intel i5 with stock clock, it's a shitty CPU you can buy for nothing at all. I do have a GTX 980 though ;)

**Comment by devlo** [comment]
@alexhultman 

Thanks, but could you be more specific? Which i5 was it? I am interested in clock on that CPU.

**Comment by alexhultman** [comment]
I'm not at home right now but I can check when I come home. I think it's the latest gen i5 or at least last last gen. It was very cheap because I wanted to build a Vulkan gaming computer so CPU doesn't really matter I get those 150 fps :+1:

**Comment by devlo** [comment]
> I can check when I come home.

That would be great, thanks.

**Comment by alexhultman** [comment]
Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
