### ISSUE TITLE
uWebSockets support express now, can support Koa2?

### ISSUE THREAD

**Issue by arden** [uWebSockets/uWebSockets#467]
uWebSockets support express now, can support Koa2?

**Comment by alexhultman** [comment]
Maybe

\<Controversy alert\>

Looking at the code and performance of Express has drained my hopes for Node.js completely. It is hard to describe with words how inefficient and overrated Express is. Same goes with Koa. It completely sucks my inspiration dry working with things this bad. Express is written in playdough by a 3 year old snotty kid with way too rich parents.

Express does 7k req/sec 18k with uws. Express is so bloated and extremely inefficient that it completely clogs up at only 2x the perf. This alone makes me want to stop supporting Node.js completely. Everywhere I look, Node.js blows my mind with never before seen inefficiencies and bloat world records. This paired with an audience so brainwashed it's reminding one of a sect.

While Express has 30k GitHub stars and AeroJs has 60 (as in sixty) we can apply the rule of inverted quality:

`The quality of a GitHub project is in direct opposition to the number of GitHub stars.`

AeroJs does 16k req/sec and 82k with uws. It has an almost identical interface as Express and that's what I want to support.

https://github.com/aerojs/aero

**Comment by wtgtybhertgeghgtwtg** [comment]
As is, `aero` doesn't look like it'd be a viable replacement for `express`.  What does `express` do that slows things down so much?  What does `aero` do to minimize the overhead?

**Comment by alexhultman** [comment]
As mentioned it is hard to describe with words. There is no single bottleneck but rather the problem is spread like a cancer throughout the entire project. It's both in terms of programming but also algorithmic. If I pulled down my pants and took a shit on my keyboard it would result in a better project.

**Comment by alexhultman** [comment]
Same applies to Socket.IO. It also applies to 99.7% of everything in NPM

**Comment by alexhultman** [comment]
Koa does 9k req/sec and 27k with uws so it is less bloated but still not very impressive. It also has a more sane access pattern - where Express will query the url string and method like 8 times per request, Koa only does it once which is less retarded. It also *almost* manages to perform everything inside of the request handler but it still does defer some stuff to the next iteration (what did I expect?). It's clearly a lot better than Express but still very bad.

**Comment by alexhultman** [comment]
Ah, I forgot about routing. I added koa-router and now it does 21k so yeah it is not that much better than Express when you add routing.

**Comment by wtgtybhertgeghgtwtg** [comment]
Maybe you could write a framework, then.  If you have an API in mind, I'd love to help.

**Comment by stormwin** [comment]
@wtgtybhertgeghgtwtg 
https://github.com/alexhultman/Dreamstack

**Comment by alexhultman** [comment]
It's not just one or two modules that need fixing -> it's the entire Node.js universe that has been built on lies and deceit. You have these superstar fuckbois like TJ and Rauchg that write 500 modules and have 4 billion followers yet everything they produce is completely worthless and only needs to be rewritten later on. It's not a sustainable solution to go fix every flaw of their incompetent output. They should go be designers and models and not do programming at all and the world would be a better place

**Comment by ansarizafar** [comment]
Unfortunately I can  star a repository only once. We all must support @alexhultman and Dreamstack as much as we can.

**Comment by alexhultman** [comment]
That's nice and all but you cannot buy anything with GitHub stars, they are only a measurement of hype and won't fund the party

**Comment by alexhultman** [comment]
If you right click, open image in new tab you can see it better:
![koa_demo](https://cloud.githubusercontent.com/assets/3397140/23103150/7a7634d6-f6b6-11e6-875a-983a04d74eb4.gif)

**Comment by nitrocode** [comment]
The dreamstack link is broken..

**Comment by alexhultman** [comment]
Yes I deleted it
