### ISSUE TITLE
Can`t send

### ISSUE THREAD

**Issue by Edisoni** [uWebSockets/uWebSockets#470]
* What operating system are you running?
OS X

* What platform/language are you using?
Node.js
* Are you using SSL, if so, how?
No
* Can you show me some short code that triggers your issue?
When i try send:
![image](https://cloud.githubusercontent.com/assets/10086099/23104665/5c32e65e-f6e3-11e6-8c27-bc096e8c5064.png)
![image](https://cloud.githubusercontent.com/assets/10086099/23104666/68cdec60-f6e3-11e6-8948-ef7703b96d89.png)
i use protobuf:
          var binary = ProtoPlayer.encode(data).finish();
          socket.send(binary);

It work on 'ws', but when i start server with uWS it show this error.

**Comment by SzAmmi** [comment]
@Edisoni I'll help. Try using DataView instead of Uint8Array, ok?

**Comment by SzAmmi** [comment]
@Edisoni 

```javascript
    var bytes = new Uint8Array(binary);
    var buffer = new ArrayBuffer(binary.byteLength);
    var view = new DataView(buffer);
    for (var i = 0; i < bytes.length; i++)
        view.setUint8(i, bytes[i])
    
    socket.send(buffer);
```

**Comment by Edisoni** [comment]
https://github.com/Edisoni/uWebsocketServer/blob/master/public/src/app.js#L109
the same mistake, when i try send binary data
![2017-02-21 18 25 31](https://cloud.githubusercontent.com/assets/10086099/23171529/c4082dbc-f863-11e6-8f95-a0a18c9fce7d.png)

**Comment by Edisoni** [comment]
@alexhultman that the setup is not correct?
https://github.com/Edisoni/uWebsocketServer/blob/master/main.js#L12

**Comment by SzAmmi** [comment]
@Edisoni Yes, it is. So it seems the binary data is sent correctly. That's not caused by sending binary data. As I see, you want to send UTF8 string. What's the 97th line of your code? Click on `VM580:97`.

**Comment by Edisoni** [comment]
@SzAmmi 
![2017-02-21 18 55 33](https://cloud.githubusercontent.com/assets/10086099/23172602/59ace7d8-f867-11e6-8380-25fbe3fca8d7.png)

**Comment by Edisoni** [comment]
@SzAmmi 
https://github.com/Edisoni/uWebsocketServer/blob/master/public/src/app.js#L21
![2017-02-21 18 56 59](https://cloud.githubusercontent.com/assets/10086099/23172669/9a2402ba-f867-11e6-9f3d-214e4551953b.png)

**Comment by SzAmmi** [comment]
Does it work on Mozilla?

**Comment by Edisoni** [comment]
@SzAmmi no,
![2017-02-21 20 25 27](https://cloud.githubusercontent.com/assets/10086099/23176444/042e17d4-f874-11e6-9437-8e895ca82719.png)

**Comment by alexhultman** [comment]
You can both track this issue where it belongs, in your own repo.

**Comment by Edisoni** [comment]
@alexhultman that the setup is not correct?
https://github.com/Edisoni/uWebsocketServer/blob/master/main.js#L12

**Comment by ronag** [comment]
@Edisoni: Do you have a minimal repo? Have you tried with another websocket server?
