### ISSUE TITLE
Remove libuv, insert low level layer, implement this layer using libuv, C++17 networking and raw epoll

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#471]
I'm thinking something like this:

```c++
struct Loop {
  unsigned char loopId; // needed?

  Loop();
  createPoll(fd);
  run();
};

struct Poll {
  epoll_event event;
  int fd;
  unsigned char cbIndex;
  unsigned char loopIndex;
  void *data;

  getLoop(); // lookup
  getCb(); // lookup
  getFd();
  stop(); //uv_poll_stop

// uv_poll_start is split into 3 different functions
  start(int events); //uv_poll_start
  change(int events) // uv_poll_start
  setCb(callback); //uv_poll_start, slow but only done rarely

// uv_close
  close(); // sets FD = -1 to denote "closing"
  isClosing();
  
};
```

This interface will not guarantee anything, so it will be easy to wrap libuv in this lower level interface since libuv guarantees more than this.

**Comment by alexhultman** [comment]
Does anyone know how C++17 networking fits in with this? Is is possible to use the networking support of C++17 only for polls and send data directly over the FD?

**Comment by alexhultman** [comment]
Yes it does seem that you can create a C++17 socket from a file descriptor. That makes it possible to implement this using either libuv, epoll directly or C++17 networking which is great for portability :+1:

**Comment by ronag** [comment]
@alexhultman: Have you considered boost::asio? It's quite fast and stable. Though one might argue it is a little bloated...

**Comment by alexhultman** [comment]
C++17 networking is asio standardized

**Comment by alexhultman** [comment]
@jimmyt857 Okay now it can compile completely without any libuv symbols and it has its own low level interface now. This means we can put epoll in and disregard libuv's flaws completely. As you can see it is only using 4 features of libuv so it should be very minimal.

**Comment by ronag** [comment]
@alexhultman: Rather passing around this small structures as pointer I believe you could gain both simplicity and performance by passing it around by value and reference. The extra "cost" of copying copying a few bytes extra would probably be better than doing all of these small allocations.

**Comment by alexhultman** [comment]
Another thing I'm working on is to transition to an immediate close of polls. So compared to libuv which will defer the actual deletion of the poll until next tick (which requires tracking a bunch of stuff) we can just instantly delete it and skip this whole step. I'm calling this Poll::closeAndSuicide() so it should be obvious that it's poof gone immediately. This whole removal of libuv is more than just making a better libuv -> it's about making something tailor made for µWS and skipping a lot of unnecessary bookkeeping.
