### ISSUE TITLE
0.13.0 Static Files

### ISSUE THREAD

**Issue by andymans** [uWebSockets/uWebSockets#475]
NodeJS, MacOSX, uws 0.13 built locally.

No rush as I know you're busy. But an example of using the new http to serve up some static content (an index.html plus e.g. a .js file) would be cool. It's taking a few secs to load a page if I use fs.readFile(path-to-myfile) and using fs.createReadStream seems not to work at all.

Otherwise 0.13.0 looks great - it's clearly fast as hell.

**Comment by DiegoRBaquero** [comment]
Shouldn't this work?

```js
var http = require('uws').http;
var fs = require('fs');

var server = http.createServer(function (req, res) {
    var stream = fs.createReadStream(__dirname + '/my-file');
    stream.pipe(res);
});
server.listen(8000);
```

**Comment by andymans** [comment]
I was trying something similar and it didn't work; but will re-check.

**Comment by DiegoRBaquero** [comment]
Ah, I see the issue now:

```
Warning: res.on(unpipe) is not implemented!
Warning: res.on(drain) is not implemented!
Warning: res.on(error) is not implemented!
_stream_readable.js:590
  dest.once('close', onclose);
       ^

TypeError: dest.once is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:590:8)
    at /Users/diego/Projects/node-bench/test.js:6:12
```

**Comment by 0x111111111** [comment]
@alexhultman Has created a good example, look at here: https://github.com/uWebSockets/website/blob/master/main.cpp#L34
