### ISSUE TITLE
can uWebSockets support hapi?

### ISSUE THREAD

**Issue by bnusunny** [uWebSockets/uWebSockets#483]
With express and koa supported, can hapi supported as well?

**Comment by antoine-duchenet** [comment]
Hello,

I tried to replace the Node's core HTTP module by the UWS one in the Hapi connection system.

However, Hapi depends on Node's [Events](https://nodejs.org/api/events.html) methods, such as `.on `, `.once` and `.removeListener` which seems not to be implemented by the current UWS HTTP server wrapper.

As a consequence, make Hapi fully compatible with the current UWS implementation would require to change both the server/connection initialization system and the request dispatch mechanics.

On the other side, make UWS fully compatible with the current Hapi implementation would require to implement methods such as  `.on `, `.once`, `.removeListener` and  `.address` for the UWS HTTP server wrapper.

> I did not looked deeply at this problem, and I'm not UWS nor Hapi contributor, my conclusions may be wrong and any constructive corrections would be appreciated.

**Comment by antoine-duchenet** [comment]
With only a few minor modifications on both UWS C++ code and Hapi JS code, I can get the connection and dispatch system barely working (some of those are currently glitchy and could create unexpected side effects on Hapi features but I suppose it could be relatively easily implemented the right and clean way).

However, I currently end up blocked by the current UWS HTTP request wrapper not implementing every Node's core HTTP request methods. I'll keep working on it.

**Comment by alexhultman** [comment]
If you have any further issues report them in the bindings repo

**Comment by alexhultman** [comment]
There is no point in this. Hapi is its own bottleneck and won't see any improvements by swapping the underlying http server whatsoever.

**Comment by alexhultman** [comment]
I thought I had seen it all by now but Hapi is actually slower than Sails.js. I thought it would be theoretically impossible to build anything slower than Sails.js, you know as a scientific low point kind of like the 0 Kelvin absolite zero point. I was wrong, Hapi lowers the bar below what was before imaginable. Mind blown, text books will need to be rewritten.
