### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#485]
![website](https://cloud.githubusercontent.com/assets/3397140/23183458/673bddf4-f87c-11e6-8f90-c6a72af3afd8.png)

Very simple site with global chat with rainbow colors to replace the Gitter room and act as a basic production test. You go to the site and the whole page is a chat room and you have some logo or something in the middle, maybe you can also see the server's memory and cpu usage or something. Very minimal, "vanilla JS", C++ server code

**Comment by alexhultman** [comment]
Basic foundation can be tested here: http://79.136.86.141:3000/ it is very fragile right now but it is taking shape

**Comment by alexhultman** [comment]
Okay I'm hosting the server now, it is written in C++ and it was pretty awesome writing it: http://79.136.86.141:3000/

It runs on v0.13 and makes use of the HTTP stuff. Let's see if this is stable enough to run for a while

**Comment by alexhultman** [comment]
Fyi the server is still running but my internet broke. Using my phone internet now. Will deploy this and have it run all the time as a place to talk random stuff.

**Comment by alexhultman** [comment]
Internet is up again :)

**Comment by arpu** [comment]
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
