### ISSUE TITLE
Perfomance broadcast

### ISSUE THREAD

**Issue by Edisoni** [uWebSockets/uWebSockets#487]
![2017-02-22 10 30 47](https://cloud.githubusercontent.com/assets/10086099/23206425/aa51e53e-f8fe-11e6-98a3-dd08814a756d.png)

50 clients * 60 requests per second
My repo for info
https://github.com/Edisoni/uWebsocketServer

**Comment by ronag** [comment]
What does this have to do with uWebSocket?

**Comment by Edisoni** [comment]
No, it`s on server side,
just run server and open link for profiling, 
node --inspect main.js
![2017-02-22 13 13 18](https://cloud.githubusercontent.com/assets/10086099/23206980/b407459a-f900-11e6-9aae-a7ddf1d3a1ca.png)
and run stress test
node main.js

**Comment by ronag** [comment]
Well since the time is spent in `onmessage`  I would guess that this code is what is caused your performance issue:

```js
    client.onmessage = function(e) {
        if (typeof e.data === 'string') {

        } else {
            var data = ProtoPlayer.decode(new Uint8Array(e.data));
            if (data.uid == client.uid) {
                client.x = data.x;
                client.y = data.y;
            }
        }
    };
```

**Comment by Edisoni** [comment]
But it`s just bot(client), but broadcast on server is slow

**Comment by ronag** [comment]
@Edisoni: What is it you don't understand? The code I posted is probably what is causing it to be slow. I don't think this has anything to do with uws...

**Comment by DiegoRBaquero** [comment]
You must be blocking the event-loop right about here: `var data = ProtoPlayer.decode(new Uint8Array(e.data));`
