### ISSUE TITLE
cannot connect to prosody

### ISSUE THREAD

**Issue by sonnyp** [uWebSockets/uWebSockets#492]
* What operating system are you running?
  * Linux
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * Release v0.13.0
* What features of µWS are involved in the issue?
  * Client support (WebSocket)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

I'm considering making the switch from `ws` to `uws` on https://github.com/node-xmpp/node-xmpp. 

I'm having an issue connecting to prosody; an XMPP server with support for [XMPP over WebSocket](http://tools.ietf.org/html/rfc7395)

```javascript
'use strict'

const WS = require('uws')
// const WS = require('ws')

const sock = new WS('wss://ws.jabberfr.org', ['xmpp'])
sock.on('error', (err) => {
  console.log('error', err)
})
sock.on('open', () => {
  console.log('open')
})

```
results in 

```
{ message: 'uWs client connection error',
  stack: 'uWs client connection error' }
```

while it connects with `ws`.

Same with bare prosody without SSL on `localhost`.

**Comment by alexhultman** [comment]
uws still does not properly iterate the list of addresses of dns lookup so in cases where the first address in the list is unavailable it will fail to connect

**Comment by sonnyp** [comment]
@alexhultman it's not DNS related, I can reproduce on localhost and with `127.0.0.1`
