### ISSUE TITLE
Can't compile uWS on Linux

### ISSUE THREAD

**Issue by ghost** [uWebSockets/uWebSockets#494]
Running Ubuntu Gnome 16.10. I run 64-bit in the year 2017. Trying to compile the newest uWebSockets update. Here's the `cmake .`:
```bash
$ cmake .
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
CMake Error at CMakeLists.txt:18 (add_library):
  Cannot find source file:

    src/uUV.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: uWS
CMake Error: Cannot determine link language for target "uWS".
-- Generating done
```

As I see, there's no file called `uUV.cpp` in the `src` folder.

**Comment by alexhultman** [comment]
Ah for fucks sake just read the fucking issue template it is literally straight in your face. Let me quote it:

## Frequently posted issues
**I cannot compile or link the project \<insert compiler or linker error\>**  
Try a released version, master branch is where development happens. If you still have issues then you need to check your end very thoroughly before posting this issue. You are not the only one using µWS and it is probably not this broken.

I'm banning you for 1 week now.

**Comment by SzAmmii** [comment]
Ah for your fucking sake just check it for yourself: the file in the master branch is missing. Just do that fucking thing.

**Comment by SzAmmii** [comment]
Check CMakeLists, okay? There's 'uUV.cpp' to compile, but it doesn't even exist. Next time be careful.

**Comment by SzAmmii** [comment]
Hello? Is anybody here? Will I be unbanned?
