### ISSUE TITLE
ECONNREFUSED when using node client on Windows

### ISSUE THREAD

**Issue by doesdev** [uWebSockets/uWebSockets#497]
* What operating system are you running?
  * Windows
* Are you running any CPU architechute out of the normal?
  * no
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * Release v0.13.0
* What features of µWS are involved in the issue?
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

## Issue

In Windows environment (tested on two separate Win 10 x64 machines) node based clients get ECONNREFUSED trying to connect to uws HTTP server. Requests are handled as expected connecting via browser. I've also tried 127.0.0.1 as well as running on port 80 with host redirection. All result in the same.

The same codebase runs and passes connection related tests on Linux, but fails with said error on Win.

### Server
```js
require('uws').http.createServer((req, res) => res.end('hello')).listen(3000)
```

### Client
```js
require('http').get('http://localhost:3000', console.log)
```

**Comment by alexhultman** [comment]
Nice report, will check this.

**Comment by alexhultman** [comment]
I get the same behavior. Works in the browser, does not work from Node.js.

**Comment by 0x111111111** [comment]
On Linux this works ok, no problems.

**Comment by mikybone** [comment]
Hi friends
change h.listen(3000); to
**h.listen("localhost", 3000);**
so that listen on ipv4 : http://localhost:3000

thanks to @alexhultman for this projects :+1:
