### ISSUE TITLE
Correct way to shutdown server

### ISSUE THREAD

**Issue by zer0-x** [uWebSockets/uWebSockets#498]
I'm using C++ library on Linux and don't know how to shutdown the server correctly.

What I did:

- Call socket.terminate() on all clients
- Call group.terminate()
- Let the hub destructs itself

I get the segfault at ~Hub(), console output:
```
src/uv-common.c:624: uv_loop_delete: Assertion `err == 0' failed.
```

**Comment by alexhultman** [comment]
group.terminate or group.close will close all sockets so you cannot close them twice. Otherwise you are doing it correctly.

**Comment by zer0-x** [comment]
Alright, So now I do these steps:

- Call socket.terminate() on all clients
- Let the hub destructs itself

But the segfault is not going away with same output. Any suggestions for me to investigate it more?

**Comment by alexhultman** [comment]
You only call group.terminate or group.close. Then you wait until it falls through Hub::run. Now you can destroy the Hub.

**Comment by zer0-x** [comment]
Yeah, that solved the problem. Thank you.
