### ISSUE TITLE
Rename shared library path from /usr/lib64 to /usr/lib

### ISSUE THREAD

**Issue by 0x111111111** [uWebSockets/uWebSockets#501]
What operating system are you running? **Linux**
Are you running any CPU architechute out of the normal? **No**
What platform/language are you using? **C++**
Are you using SSL, if so, how? **SSL is not part of the equation**
What version of uws are you using? **Release v0.13.0**

Just a small notice: the libuWS.so library should be installed in `/usr/lib`. For example, CLion doesn't search shared libraries in `/usr/lib64`. I have to do `sudo cp /usr/lib64/libuWS.so /usr/lib/` everytime the update is released.

**Comment by alexhultman** [comment]
What distro is this? The current Makefile works on Ubuntu (picks /usr/lib) and Fedora (picks /usr/lib64)

**Comment by 0x111111111** [comment]
Ubuntu. Notice, that in my case folder `lib64` was created by another program somehow. We could detect distros in Makefile. Btw, when I am home I will try to delete it and install uWS again.

**Comment by 0x111111111** [comment]
I just forgot to mention that v0.13 uses CMakeLists.txt, not Makefile. I saw there this line:
```cmake
install (TARGETS uWS DESTINATION /usr/lib64)
```
I deleted the `lib64` folder. After running `sudo make install` the directory `lib64` is created.
So I replaced the code with:
```cmake
install (TARGETS uWS DESTINATION /usr/lib)
```
Now it works.
I'm so glad CMake will be removed in 0.14, really appreciate that :D

In v0.13 it should look something like this:
```cmake
if (EXISTS /usr/lib64)
    install (TARGETS uWS DESTINATION /usr/lib64)
else
    install (TARGETS uWS DESTINATION /usr/lib)
endif
```

**Comment by alexhultman** [comment]
Ah, CMake. The piece of shit project who cannot find Zlib in C:/Zlib and cannot figure out /usr/lib or /usr/lib64 on different Linux distros. Yeah it is gone and will never come back.
