### ISSUE TITLE
Proxy help..

### ISSUE THREAD

**Issue by g00dnatur3** [uWebSockets/uWebSockets#502]
My work computer internet is behind an http proxy.

I want to connect to a Watson websocket, but it fails because of the proxy.

It works fine  if I switch to an internet that is not behind a proxy...

How do I fix this?

Thanks

**Comment by 0x111111111** [comment]
This issue is not related with uWS.

**Comment by shakespark** [comment]
maybe your http proxy doesn't support websocket...

**Comment by ad34** [comment]
does the uWebSocket lib support http proxies? I cant find any option to specify an http proxy to use?
