### ISSUE TITLE
getAddress() wrongly return family IPv6

### ISSUE THREAD

**Issue by shakespark** [uWebSockets/uWebSockets#504]
* What operating system are you running?
  * Linux centos 6.3 x64

* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL is not part of the equation

* What version of uws are you using?
  * Release v0.13.0

* What features of µWS are involved in the issue?
  * Server support (WebSocket)

* How does the issue reproduce?
  * All the time

* Can you show me some short code that triggers your issue or any other important information?

#include <uWS.h>
#include <iostream>

using namespace std;

int main()
{
    uWS::Hub h;
    	
    h.onConnection([](uWS::WebSocket<uWS::SERVER> ws, uWS::HttpRequest req){
			cout << "socket" << ws.getAddress().address << ":" << ws.getAddress().port << " " << ws.getAddress().family << " connected" << endl;
		});

    h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode) {
        ws.send(message, length, opCode);
    });

    h.listen(3000);
    h.run();
}

output:
[root@server examples]# ./echo 
socket::ffff:192.216.20.216:3233 IPv6 connected

-------------------------------------------------------
Today I update from 0.7.1 to 0.13.0 and found this problem.
0.7.1 is correct

**Comment by shakespark** [comment]
changed my code from
h.listen(3000)
to
h.listen(3000, nullptr, uS::ONLY_IPV4)
,and solved this problem

**Comment by alexhultman** [comment]
:+1: Veteran user :1st_place_medal:
