### ISSUE TITLE
what  is right way handling binary message from client 

### ISSUE THREAD

**Issue by meiry** [uWebSockets/uWebSockets#508]
* What operating system are you running?
  * Windows
* Are you running any CPU architechute out of the normal?
  * I run 64-bit in the year 2017
* What platform/language are you using?
  * C++
 * Are you using SSL, if so, how?
 no
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

im sending binary massage from HTML5 client 
the massage recived fine in the server BUT it reviced as string that include the header 
what is the proper way to get only the massage recived from the client in server 

for example im receiving the massage in the function :

```
h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode) {
		if (opCode == uWS::OpCode::BINARY) 
		{
			printf("%s\n", message);
			char *messageToClient = "{ \"msg\":\"send from server\"}";
			size_t messageLength = strlen(messageToClient);
			
			uWS::WebSocket<uWS::SERVER>::PreparedMessage *prepared = 
									ws.prepareMessage(messageToClient, messageLength, uWS::OpCode::BINARY, false, nullptr);
			ws.sendPrepared(prepared, nullptr);
			ws.finalizeMessage(prepared);
			
		}
```

 and the printed massage is :  
```
{"msg":"Hello From Client"}┐╛'G   ost:3000
connection: Upgrade
pragma: no-cache
cache-control: no-cache
upgrade: websocket
origin: http://127.0.0.1:8887
sec-websocket-version: 13
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
accept-encoding: gzip, deflate, sdch, br
accept-language: en-US,en;q=0.8,he;q=0.6
sec-websocket-key: 1gGIb49pUMGRSLv+246kqg==
sec-websocket-extensions: permessage-deflate; client_max_window_bits
```
to get the string : {"msg":"Hello From Client"} 
Do i need to do my own string manipulation and extract the massage or is there any more officiant way with build in functions ?

**Comment by alexhultman** [comment]
Not all char pointers point to 0-terminated strings. You can only read *length* amount of bytes from the address given in *message*. You also don't need to prepare a message if you only are to send it once. Just call ws.send directly. Prepared messages are when you send one message to many recipients or send a batch of messages.

**Comment by meiry** [comment]
Thanks for the fast replay , so if I understand I need to extract the json from the client , am I right ?

**Comment by alexhultman** [comment]
This is not an issue with uws

**Comment by meiry** [comment]
Hey , its not issue i just try to understand what you did .
as i see that you are sending the length of the string massage itself which can be extract from the 
*massage pointer like this :
std::string(message, length)
but what about other parameters which has been send in the header how can i get them also ? (loop the char* ?)

Thanks

**Comment by WesThorburn** [comment]
Hey meiry, I'm in exactly the same spot right now. Did you end up coming up with a solution? We can discuss further via email if you wish.
