### ISSUE TITLE
mTCP support / refactor networking into separate layer

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#513]
* Refactor networking code into separate layer a la BSD sockets
* Implement that layer using BSD sockets, Winsock and finally mTCP

These are all very similar in how they are used and mTCP has epoll as polling interface which is excellent since µWS recently got ported to raw epoll.

**Comment by ng5** [comment]
this is great. If we can attach mTCP to http/uwebsocket application, this will be totally mind blowing server.

**Comment by alexhultman** [comment]
So I experimented a bit and put µWS on my experimental TCP implementation and I just managed to establish 1 million websockets in 179 mb of user space memory (0 bytes of kernel space memory). This is very tiny and means that a 5$ raspberry pi zero (512mb of ram) could keep more connections than what you would ever need. I think this track is worth further investigation and I will probably be spending some time on this idea. It is obviously never before done and by far the world record and then some.

**Comment by jimmyt857** [comment]
How much kernel space memory is normally used / million connections?

**Comment by alexhultman** [comment]
4gb from what I can see but this can also be 8gb, depends on configuration

**Comment by alexhultman** [comment]
Thing is, even if I'm only at a skeleton implementation (will take at least 1 year to complete this) I'm already capable of running websocket throughput and scalability benchmarks on this thing. Performs pretty much identical to the kernel (I guess the most performance gain is at the IP level, where DPDK will come in later on). But yeah, I can have 100 connections send websocket data back and forth using only a few bytes of state. This is a friggen gold mine, this TCP thing.

**Comment by alexhultman** [comment]
I'm willing to openly say that all user space TCP implementaions that target BSD sockets completely miss the point of doing user space: now you can innovate on the interface and make things far more efficient since you don't have to actively avoid the performance and security barrier of TCP (kernel) <-> application. Things like piggybacking ACK's to next data send and corking data flow becomes obvious since it's all about callbacks: you immediately know when to send ACKs and when not to.

And, by not implementing this gigantic BSD interface with 8902734109479028412790849 features it becomes simpler.

**Comment by alexhultman** [comment]
I've made some thinking and it looks like I will move all TCP/Socket stuff to a separate library, completely separate from µWS. You can track this work at https://github.com/alexhultman/uSockets

Goal is to combine all the socket "research" done in µWS with a better interface, and also merge in my own skeleton TCP stack so that I can play with it below all of µWS. I want to finish my TCP work, but taking baby steps and making sure µWS benefits along the way is important. It would probably benefit more users if I could get mTCP working before doing my own thing.
