### ISSUE TITLE
Linker error on Windows 10 VS 2015 (vcpkg aswell)

### ISSUE THREAD

**Issue by perara** [uWebSockets/uWebSockets#514]
```
1>main.obj : error LNK2019: unresolved external symbol __imp_closesocket referenced in function "void __cdecl close(unsigned __int64)" (?close@@YAX_K@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_send referenced in function "public: bool __cdecl uS::Socket::write(struct uS::SocketData::Queue::Message *,bool &)" (?write@Socket@uS@@QEAA_NPEAUMessage@Queue@SocketData@2@AEA_N@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_shutdown referenced in function "public: void __cdecl uS::Socket::shutdown(void)" (?shutdown@Socket@uS@@QEAAXXZ)
1>main.obj : error LNK2019: unresolved external symbol "public: static void __cdecl uS::NodeData::asyncCallback(struct uv_async_s *)" (?asyncCallback@NodeData@uS@@SAXPEAUuv_async_s@@@Z) referenced in function "public: void __cdecl uS::Socket::transfer(struct uS::NodeData *,void (__cdecl*)(struct uv_poll_s *))" (?transfer@Socket@uS@@QEAAXPEAUNodeData@2@P6AXPEAUuv_poll_s@@@Z@Z)
```

i'm getting following linker errors after attempting to use uWebSockets.
Getting this on both vcpkg and manual compilation. 
Bug?

**Comment by jgilje** [comment]
closesocket, send and shutdown indicates you're not linking against winsocks2 (ws2_32)

**Comment by WesThorburn** [comment]
I'm having the same issue, actually. Although, I've been able to fix the first three errors.

In Visual Studio 2015, go to Project->ProjectName Properties to open up the Property Pages window. Under configuration properties, go to Linker->Input, then in the 'Additional Dependencies' field, add 'ws2_32.lib;' click OK and rebuild the project. Then you'll only be left with the last error (uS::NodeData::asyncCallback) which i'm still trying to find a solution for.

**Comment by WesThorburn** [comment]
Alright, I've made some progress. Here you can see in the [list of triplets](https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/), Vcpkg uses uWebSockets v0.12.0. As mentioned in [issue #351 ](https://github.com/uWebSockets/uWebSockets/issues/351), v0.12.0 appears to have a Windows bug that wasn't fixed until issue #402. 

So I guess, if we're using Vcpkg, our two options are to try implementing the workarounds mentioned in issue #351 (which hasn't worked for me). Or try installing a more recent version uWebSockets without using Vcpkg which I'm trying to figure out how to do right now.

**Comment by perara** [comment]
i read the issues / workarounds described in #351 but did not have any luck implementing these using the master branch.

**Comment by WesThorburn** [comment]
Neither did I, the error message is exactly the same. I'm still trying to work out how to manually install uWebSockets. In the [uWebSockets docs](https://github.com/uWebSockets/uWebSockets#windows), it says:
> Compile with Visual C++ Community Edition 2015 or later. This workflow requires previous usage of vcpkg
> - Open the VC++ project file
> - Click Build

But it doesn't specify which directory to clone the repository into. I've tried a couple of different ones, but Visual Studio couldn't find the <uWS/uWS.h> header file.

**Comment by WesThorburn** [comment]
Good news, Vcpkg has been updated to use uWebSockets v0.13.0 which fixes the "NodeData::asyncCallback" error, however, the following three errors are now showing up.
```
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "void __cdecl uv_close(struct uv_poll_s *,void (__cdecl*)(struct uv_handle_s *))" (?uv_close@@YAXPEAUuv_poll_s@@P6AXPEAUuv_handle_s@@@Z@Z) referenced in function "public: void __cdecl uS::Socket::close(void)" (?close@Socket@uS@@QEAAXXZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "void __cdecl uv_close(struct uv_timer_s *,void (__cdecl*)(struct uv_handle_s *))" (?uv_close@@YAXPEAUuv_timer_s@@P6AXPEAUuv_handle_s@@@Z@Z) referenced in function "public: void __cdecl uS::Socket::cancelTimeout(void)" (?cancelTimeout@Socket@uS@@QEAAXXZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "bool __cdecl uv_is_closing(struct uv_poll_s *)" (?uv_is_closing@@YA_NPEAUuv_poll_s@@@Z) referenced in function "public: bool __cdecl uS::Socket::isClosed(void)" (?isClosed@Socket@uS@@QEAA_NXZ)
```
I'm guessing these are related to libuv. Anyone have any ideas?

**Comment by meiry** [comment]
If it helps i succesfuly compiled the lib on windows 7 using libuv and VS 2015 
what i did is not using this wired Vcpkg  tool as it didn't compile on my pc 
my setup is this :

1. i created new console application in VS 
put all the uWS files and my server Main file which contains in my example the echo.cpp example
then i downloaded openssl openssl-1.1.0e-vs2015 from https://www.npcglib.org/~stathis/blog/precompiled-openssl/
libuv from the site and zlib-1.2.8.tar
all defined as multi threaded debug dll in VS
then go to this issue i opened and fix the stuff there and compile . 
https://github.com/uWebSockets/uWebSockets/issues/529

**Comment by alexhultman** [comment]
Don't listen to that nonsense. You are of course not supposed to edit the library just to get it compiling. 0.14.0a3 is tested to build without any issues whatsoever using the VC++ project file
