### ISSUE TITLE
Is there any socket transfer capability for the Node Module?

### ISSUE THREAD

**Issue by FMarxis** [uWebSockets/uWebSockets#515]
Hello, since I could not find a good place to ask this question (if there is please tell me), I am just wondering if there is any socket transfer capability for the Node Module? If not, any plans to add this capability later down the road?

From what I understand, this gives multiple uWebSocket server processes the ability to transfer clients between each other, which would be very useful. Say I spawned a newer version of a service process on the server, it would nice if I can tell the older service to transfer all its clients onto the new service before exit.

* What operating system are you running?
  Linux
* Are you running any CPU architechute out of the normal?
  No
* What platform/language are you using?
  Node.js
* Are you using SSL, if so, how?
  SSL via µWS or Node.js
* What version of uws are you using?
  master
* What features of µWS are involved in the issue?
  Server support (WebSocket)

**Comment by alexhultman** [comment]
It sounds like a reasonable feature but if this is not already supported by other Node.js modules (I don't know if) then I don't see why I should add it. The C++ interface has all of this already though.

**Comment by FMarxis** [comment]
Thanks. As far as I know, none other Node.js modules have this functionality. Like what you said, would be nice to have is the only reason I'm asking about this, and I thought it might be easy to add this since C++ interface already have it.

To keep a minimal footprint we wanted to keep the code base simple, that means sticking to Node.js and JavaScript as much as possible. I guess we will scale to C++ when we find this functionality a necessity. For now unless a fully distributed and parallel solution is imminent, we should be okay.

**Comment by alexhultman** [comment]
You should definitely consider a C++ solution if you care about what you are doing. Maybe even consider implementing the WebSocket part in a Node.js addon if you develop separation anxiety disorder traits.
