### ISSUE TITLE
Question: Windows installation directory with respect to vcpkg

### ISSUE THREAD

**Issue by WesThorburn** [uWebSockets/uWebSockets#516]
I'm trying to use uWebsockets in a C++ project. I'm running Windows 7, 64bit. I've used Vcpkg to install all the dependencies and i'm trying to install uWebSockets. In the [uWebSockets docs](https://github.com/uWebSockets/uWebSockets#windows), it says:
> Compile with Visual C++ Community Edition 2015 or later. This workflow requires previous usage of vcpkg
> - Open the VC++ project file
> - Click Build

But it doesn't specify which directory to clone the repository into. I've had a couple of attempts at cloning the master branch into vcpkg/downloads, vcpkg/installed, vcpkg/packages, but Visual Studio couldn't find the <uWS/uWS.h> header file. 

I'd appreciate it if someone could point me in the right direction.

**Comment by ras0219-msft** [comment]
You don't need to clone the repo inside Vcpkg at all.

This worked for me:
```powershell
PS D:\src\vcpkg> .\vcpkg install --triplet x64-windows libuv boost zlib openssl
PS D:\src\vcpkg> .\vcpkg integrate install
```
Then, in a totally different folder:
```powershell
PS D:\src> git clone https://github.com/uWebSockets/uWebSockets.git; cd uWebSockets
```
Then, open the VC++.vcxproj. Say **yes** if you're prompted to upgrade the project -- trying to build the 2015 project inside 2017 _will not work_.

Then, hit build.
```
1>Target Link:
1>     Creating library D:\src\uWebSockets\x64\Release\uWS.lib and object D:\src\uWebSockets\x64\Release\uWS.exp
1>  VC++.vcxproj -> D:\src\uWebSockets\x64\Release\uWS.dll
1>Target AppLocalFromInstalled:
1>  D:\src\uWebSockets\x64\Release\LIBEAY32.dll
1>  D:\src\uWebSockets\x64\Release\libuv.dll
1>  D:\src\uWebSockets\x64\Release\SSLEAY32.dll
1>  D:\src\uWebSockets\x64\Release\LIBEAY32.dll
1>  D:\src\uWebSockets\x64\Release\zlib.dll
1>Target FinalizeBuildStatus:
1>  Deleting file "x64\Release\uWS.tlog\unsuccessfulbuild".
1>  Touching "x64\Release\uWS.tlog\uWS.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:12.27
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by ras0219-msft** [comment]
Of course, this also worked:
```
.\vcpkg install uwebsockets:x64-windows
```

**Comment by WesThorburn** [comment]
Thanks very much for that!
