### ISSUE TITLE
Sockets block using large data - C++ & Windows

### ISSUE THREAD

**Issue by GGRI** [uWebSockets/uWebSockets#517]
Hi,

Using uWS (0.13.0 or the latest master branch) as a C++ websocket server on Windows 7, I have an issue using large data, especially using SSL. I reproduce this every time with 2 clients: after less than 2 minutes, one or more sockets are blocked and can't send data anymore while they continue to receive. 

After digging into uWS code, libuv, openSSL, stackoverflow & co I found the solution: Windows send & receive buffer size.
They could be configured in the registry on:  **HKLM/SYSTEM/CurrentControlSet/services/AFD/Parameters** using 2 DWORD entries:
- DefaultReceiveWindow
- DefaultSendWindow 
The value is the result of: bandwith_in_kBps / 8 * 1024. It seems the default value is: 8192.

Since it's not the best way to use the Windows registry, this can be done using C++ code:
```
int bufSize = 128000;
int ret = setsockopt(ws.getFd(), SOL_SOCKET, SO_SNDBUF, &bufSize, sizeof(int));
ret = setsockopt(ws.getFd(), SOL_SOCKET, SO_RCVBUF, &bufSize, sizeof(int));
```
Of course I don't reproduce the issue using a properly configured buffer size with the above code.

My problem is **ws.getFd()** isn't natively possible because WebSocket derivates from a protected uS::Socket.

My request is simple: Can you add some code to allow developpers to configure those buffers or a simple way to access ws.getFd()?

Guillaume

**Comment by alexhultman** [comment]
getFD should be public, yes. But otherwise this "solution" is kind of insane. I believe you have some other kind of issue instead. Is this Windows only?

**Comment by GGRI** [comment]
I don't think so. 
My program can't be tested on Linux because of the windows library used but I think I can reproduce this behavior on a small software.

**Comment by alexhultman** [comment]
If your solution involves having a 128 kb large kernel space buffer then you might as well use Socket.IO because this will kill scalability. I think best is to try and understand why this happens and solve it instead.

**Comment by alexhultman** [comment]
If you have portable code to reproduce the issue please post

**Comment by GGRI** [comment]
ok, i'm working on it.

**Comment by GGRI** [comment]
I don't reproduce this behavior on a simple example code.
I can just confirm since we use  **setsockopt(ws.getFd(), SOL_SOCKET, SO_SNDBUF, &bufSize, sizeof(int));** everything works well.

**Comment by alexhultman** [comment]
It might work but it is not a real solution. You should look at why this happens and solve it. A proper solution should work as expected even with only 1 byte of buffer.

**Comment by alexhultman** [comment]
You are probably hitting a bug on Windows where EWOULDBLOCK is not properly handled. Please try master and see if that solves your problems. It makes a lot of sense that Windows would break without this fix.

**Comment by GGRI** [comment]
Hi,

I merged your commit **Fix broken Winsock error handling** into the 0.13.0 release I use but I still have the problem.
I will try the master branch as soon as possible, last thursday it didn't compile on Visual Studio 2015, a class was missing or not found.

Anyway, thanks for your work.
