### ISSUE TITLE
Correct way to save reference for connected user

### ISSUE THREAD

**Issue by tarokker** [uWebSockets/uWebSockets#521]
Hi all,
there's something I cannot understand looking at examples/sources.

I wonder what's the correct way to save a reference for each socket used by each connect user, in order to contact each one later (for example inside a timer).

Can I safe a reference of "uWS::WebSocket<uWS::SERVER> ws" object (from onConnect callback) for each user and use that reference later calling "reference.send(..." ?

Thanks for your time, best regards

**Comment by alexhultman** [comment]
The socket is valid from onConnection to onDisconnection. Attach user data with ws.setUserData

**Comment by tarokker** [comment]
great! thanks a lot!
