### ISSUE TITLE
Receiving binary data from the client [Question]

### ISSUE THREAD

**Issue by tklein92** [uWebSockets/uWebSockets#523]
When receiving binary data from the client, what is the correct way to access the message on the server side? Consider this client:
```
var socket = new WebSocket("ws://localhost:3000");
socket.binaryType = "arraybuffer";

socket.addEventListener('open', function(event){
	var testUintArray = new Uint16Array([116,288]);
	socket.send(testUintArray);
});
```
This will send a binary frame to the server. The server looks like this:
```
h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode opCode){
    cout << "Message Received: " << message << endl;
});
```
The 'message' simply appears as 't' when receiving this Uint16Array and will often appear as different symbols with other types of arrays. I know this is most likely being caused by the lack of a Null-terminated string. What is the correct way to access the contents of the message variable?

**Comment by alexhultman** [comment]
length

**Comment by alexhultman** [comment]
#508

**Comment by WesThorburn** [comment]
The message string on the client-side has to first be converted to an array of ASCII values. JavaScript has the String.charCodeAt() function which comes in handy. The array of ASCII values has to be converted to a Uint8Array which can then be sent to the server via socket.send();

On the server side, you have to first create a char array with the length of the message received. Then iterate through the message, adding each message character to the char array.

I've made a gist with the working code: https://gist.github.com/WesThorburn/581d8b7a0ed70bc386b8c388336ad318
