### ISSUE TITLE
[nodejs] Busy loop (100% CPU) with Node.js cluster after a connection error

### ISSUE THREAD

**Issue by feldgendler** [uWebSockets/uWebSockets#524]
When using the `uws` module in a service that users Node.js `cluster`, a connection failure causes 100% CPU.

Here is a minimal test case:

```
'use strict';
const cluster = require('cluster');
const uws = require('uws');

if (cluster.isMaster)
{
    new uws('ws://localhost:1'); // will definitely fail
    cluster.fork();
}
```

This always reproduces the bug for me (Ubuntu 14.04.5 LTS, x86-64, Node.js 6.10.0). Note that `uws` is only invoked in the master process, and the child process does nothing at all. However, if `cluster.fork` is not called, the bug does not manifest.

When I run the above code, it starts using 100% CPU. The worker is idle (as expected). The master is busy doing this:

```
[pid 21529] epoll_ctl(5, EPOLL_CTL_DEL, 9, {EPOLLHUP, {u32=9, u64=9}}) = -1 EBADF (Bad file descriptor)
[pid 21529] epoll_wait(5, {{EPOLLHUP, {u32=9, u64=9}}}, 1024, -1) = 1
[pid 21529] epoll_ctl(5, EPOLL_CTL_DEL, 9, {EPOLLHUP, {u32=9, u64=9}}) = -1 EBADF (Bad file descriptor)
[pid 21529] epoll_wait(5, {{EPOLLHUP, {u32=9, u64=9}}}, 1024, -1) = 1
[pid 21529] epoll_ctl(5, EPOLL_CTL_DEL, 9, {EPOLLHUP, {u32=9, u64=9}}) = -1 EBADF (Bad file descriptor)
[pid 21529] epoll_wait(5, {{EPOLLHUP, {u32=9, u64=9}}}, 1024, -1) = 1
```

**Comment by feldgendler** [comment]
Also, if `fork` is called before the connection attempt, the problem disappears.

This way, it works as expected:
```
'use strict';
const cluster = require('cluster');
const uws = require('uws');

if (cluster.isMaster)
{
    cluster.fork();
    new uws('ws://localhost:1'); // will definitely fail
}
```

`O_CLOEXEC` not set where it should?

**Comment by feldgendler** [comment]
Adding `SOCK_CLOEXEC` when opening sockets seems to fix the problem. Pull request #525.

**Comment by alexhultman** [comment]
#308 

Thanks, I need to refactor the networking into a separate layer anyways so let's implement this when that happens. There are some bugs and differences between the platforms that needs to be fixed in a more structured way.

What I want is a layer with a common interface of simple functions that are consistent across platforms.

**Comment by alexhultman** [comment]
This is fixed for FreeBSD and Linux on master now. Will need to add some fix for OS X later on.
