### ISSUE TITLE
examples/multithreaded_echo.cpp slow connection transfer to websocket

### ISSUE THREAD

**Issue by ng5** [uWebSockets/uWebSockets#530]
Hi, I did a benchmark between echo & multithread echo and noticed that ws.transfer is using mutex under the hood and this is causing very slow connection accept rate. However once connections was accepted, multithreaded echo performance has no issues and runs faster than single threaded version. Can you please advise if this is accepted behavior from multithreaded echo?

it is just connection accept is very slow compared to single threaded echo.

		h.onConnection([&](uWS::WebSocket<uWS::SERVER> ws, uWS::HttpRequest req){
			int t = rand() % THREADS;
			cout << "Transfering connection to thread " << t << endl;
			**ws.transfer(&threadedServer[t]->getDefaultGroup<uWS::SERVER>());**
		});

**Comment by alexhultman** [comment]
tinymem branch of 0.14.0 has lock-free and immediate transfers when running on epoll. What platform is this?

If you want faster connections you should use the reuse port feature of Linux primarily and transfer secondarily.

**Comment by ng5** [comment]
Thanks for your reply Alex. Platform is fedora 24 gcc 6.3 - i7 4790K - 32gb ram, 1tb ssd. 
Is there a uWS class/function wrapper I can call for reuse port feature? I was working separately on enabling mTCP, but couldn't get it work because lack of DPDK drivers for my NIC. I will now try your 0.14.0 branch and report back the new results.

**Comment by alexhultman** [comment]
Maybe I should update the multithreaded example so that it makes use of all the performance features. So far it has only been a very basic example. If you look in tests testReuseport you see how two groups can listen to the same port (each group on a separate thread).

**Comment by ng5** [comment]
By the way I have couple of more benchmarks to compare uWS against tomcat and spark java micro web servers, needless to say uWS outperforms them easily. I can send you these benchmark code and if you like you can commit it to uWS source tree.

**Comment by alexhultman** [comment]
I can probably merge them if they are small and self-contained but I'm no longer actively benchmarking as many libraries as I can - that was more important in the early stages of marketing this lib, not so much right now.

**Comment by alexhultman** [comment]
Also, any GC-language / VM-language will perform worse than native ones by default (this is why all the top performing libraries are C++/C and the bottom ones are JavaScript).

**Comment by alexhultman** [comment]
Sorry I changed my mind! I would like to have those Java benchmarks. I want the chart to show the three categories of languages: (static types, manual memory), (static types, GC), (dynamic types, GC).

**Comment by ng5** [comment]
sure alex, will send it over the weekend.

**Comment by ng5** [comment]
here it is: https://github.com/ng5/benchmarks

**Comment by ng5** [comment]
Hi,
I'm unable to send reuse port onMessage to different thread, it always prints main thread ID. 
although reuse port distributes messages to both groups. I even tried to put onMessage inside separate threads, but still it always runs from main thread and it is not scaling because of this. Can you please provide a working example with multithreaded echo server. (without using transfer API)

#include <uWS/uWS.h>
#include "thread" 

using namespace std;
using namespace uWS;
void testReusePort() {
    cout << "main thread ID: " << this_thread::get_id() << endl;
    uWS::Hub h;
    uWS::Group<uWS::SERVER> *group1 = h.createGroup<uWS::SERVER>();
    uWS::Group<uWS::SERVER> *group2 = h.createGroup<uWS::SERVER>();
    h.listen(3000, nullptr, uS::REUSE_PORT, group1);
    h.listen(3000, nullptr, uS::REUSE_PORT, group2);
    group1->onMessage(
            [&](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode code) {
                cout << "group 1 thread ID: " << this_thread::get_id() << endl;
                ws.send((char *) message, length, code);
            });
    group2->onMessage(
            [&](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode code) {
                cout << "group 2 thread ID: " << this_thread::get_id() << endl;
                ws.send((char *) message, length, code);
            });
    h.run();
}

int main() {
    testReusePort();
    return 0;
}

**Comment by ng5** [comment]
Please see working code here, I'm closing this issue, it will be great if you can add it to reuseport multithreaded echo server so that others can also use it. thread affinity is also set to ensure no context switching. 

```
#include <uWS/uWS.h>
#include <thread>

using namespace std;

void addthread(vector<thread> &v, int port, mutex &iomutex) {

    v.emplace_back(thread([&iomutex, port] {
        // lock threads to specific core as well to reduce context switch
        while (true) {
            {
                std::lock_guard<std::mutex> iolock(iomutex);
                cout << "thread started " << this_thread::get_id() << " : on CPU=" << sched_getcpu() << endl;
            }
            uWS::Hub h;
            uWS::Group<uWS::SERVER> *group = h.createGroup<uWS::SERVER>();
            h.listen(port, nullptr, uS::REUSE_PORT, group);
            group->onMessage(
                    [&](uWS::WebSocket<uWS::SERVER> ws, char *message, size_t length, uWS::OpCode code) {
                        ws.send((char *) message, length, code);
                    });
            group->addAsync();
            h.run();
        }
    }));
}

void jointhreads(vector<thread> &v) {
    for (auto x = v.begin(); x != v.end(); ++x)
        (*x).join();
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        cout << "Usage: reuseport [port] [threads]" << endl;
        return -1;
    }
    int port = atoi(argv[1]);
    int threads = atoi(argv[2]);
    std::mutex iomutex;
    vector<thread> v;
    for (int i = 0; i < threads; ++i)
        addthread(v, port, iomutex);

    cout << "Main thread waiting::" << this_thread::get_id() << endl;
    jointhreads(v);

    return 0;
}
