### ISSUE TITLE
A client is closed with { code: 1006, reason: '' } when a server sends a big message.

### ISSUE THREAD

**Issue by V1c70r** [uWebSockets/uWebSockets#533]
I have a test project https://github.com/V1c70r/test-uws to reproduce this.
server.js sends a big message (50 000 000 bytes) after a client was connected.
client.js connects to the server and immediately got closed with { code: 1006, reason: '' }.

I use Node.js 7.7.3 and MacOS X 10.11.6.

If I use ws instead of uws in client.js then everything is ok.

**Comment by alexhultman** [comment]
This is by design. 16mb is a hard limit of what you can receive in one message

**Comment by V1c70r** [comment]
@alexhultman How can I increase this limit?

**Comment by alexhultman** [comment]
You can't

**Comment by lpinca** [comment]
https://tools.ietf.org/html/rfc6455#section-5.5

> All control frames MUST have a payload length of 125 bytes or less and MUST NOT be fragmented.

**Comment by alexhultman** [comment]
That quote doesn't have any relevance in this issue

**Comment by lpinca** [comment]
Oh ops, I misread. Ignore me.

**Comment by alexhultman** [comment]
#468

**Comment by lpinca** [comment]
@alexhultman anyway I think it's better to use close code 1009 when a frame is too big.
