### ISSUE TITLE
Suggested pattern for multithread sample

### ISSUE THREAD

**Issue by fbacreator** [uWebSockets/uWebSockets#535]
Hi all,
this project is stunning!
I was wonder what's the best pattern for sending a periodic message to all connected users, in a multithread context.
Do you have a suggestion, considering that each client can be connected using a different thread?
In the multithread echo sample, we have a one-to-one message, so sending an 'echo' message to the user who originated the onMessage callback, is safe.
But what if i want to send a message to another client, connected in another thread?
Sorry for messing explanation :)
Thanks in advance for your time.

**Comment by alexhultman** [comment]
You want to have threading at a high level, putting complete groups and hubs separate on their own threads. Keep sockets that belong to one thread to that thread and only send from it. If you need to send from a separate thread it depends on if you send many different messages or send the same to multiple recipients. If many, then it makes sense to defer the send to next iteration of the thread that owns the sockets.
