### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary...

### ISSUE THREAD

**Issue by Ryshard** [uWebSockets/uWebSockets#536]
Windows_NT, Node 6.9.1, python 2.7.8,

I am getting a "Compilation of µWebSockets has failed and there is no pre-compiled binary..." error,
on "require('uws')".
It works perfectly on my localhost (Windows 8), but fails when pushed to Azure webApp.

I have checked variables on Azure server:
 'process.platform'  - win32 
 'process.versions.modules' - 48

And the file 'uws_win32_48.node' exists on the server (inside node_modules/uws folder)

What else could cause it to fail on require ?

**Comment by Ryshard** [comment]
Solved. There was problem was in the 32bit OS on the server. 
Rebuild in the uws folder, with 'target' and 'arch' flags sorted it out
node-gyp  rebuild -std=c++11 --arch=ia32 --target=v6.9.1

**Comment by alexhultman** [comment]
Why are you running a server on a 32-bit Windows system in 2017? Run 64-bit Linux if you want any kind of result.

**Comment by Ryshard** [comment]
You should ask guys in MS Azure ;)
That is a development server, so for the moment cost is more important to us, than speed.
And so happens that lowest tier webbApps on Azure have 32-bit Windows by default.
