### ISSUE TITLE
Compiles fine, can't run echo example

### ISSUE THREAD

**Issue by Octylpy** [uWebSockets/uWebSockets#537]
I'm able to compile the echo example, but I get the following errors when trying to run it:
```
dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: libuWS.dylib
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: libuWS.dylib
  Expected in: flat namespace
```

I'm on OSX (with uWS `v0.14.0 alpha 1`) and trying to run the example from `examples/echo.cpp`. I installed openssl 1.0.2k from source. I can't seem to figure out what's going on, any help is appreciated. Thanks

**Comment by alexhultman** [comment]
You are not linking to OpenSSL. I just ran the echo on Os X and it worked. When I removed SSL from my linking line I got identical errors as you. Make sure to always link against correct dependencies.

**Comment by Octylpy** [comment]
@alexhultman Alright, thanks
