### ISSUE TITLE
 Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by Ryshard** [uWebSockets/uWebSockets#540]
When trying to connect to ws server I receive following error: 

> WebSocket connection to 'wss://myserver.foo/echo' failed: Error during WebSocket handshake: Unexpected response code: 200

When I try to connect to localhost server (same node.js code) I got no errors. 

  
## Include the following information (where applicable):

* What operating system are you running?
  Windows
* Are you running any CPU architechute out of the normal?
   I run 32-bit in the year 2017 (low tier dev server on Azure)
* What platform/language are you using?
  Node.js

* What version of uws are you using?
   master

* What features of µWS are involved in the issue?
  * Server support (WebSocket)
  * Client support (WebSocket)

* How does the issue reproduce?
All the time

* Can you show me some short code that triggers your issue or any other important information?

Server:
```
var express = require('express'),
      config  = require('./config/config'),
      WebSocket = require('uws').Server,
      app = express();

app.all('*', function(req, res, next) {

      /**
     * Response settings
     * @type {Object}
     */
    var responseSettings = {
        "AccessControlAllowOrigin": req.headers.origin,
        "AccessControlAllowHeaders": "Content-Type,X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5,  Date, X-Api-Version, X-File-Name",
        "AccessControlAllowMethods": "POST, GET, PUT, DELETE, OPTIONS",
        "AccessControlAllowCredentials": true
    };

    /**
     * Headers
     */
    res.header("Access-Control-Allow-Credentials", responseSettings.AccessControlAllowCredentials);
    res.header("Access-Control-Allow-Origin",  responseSettings.AccessControlAllowOrigin);
    res.header("Access-Control-Allow-Headers", (req.headers['access-control-request-headers']) ? req.headers['access-control-request-headers'] : "x-requested-with");
    res.header("Access-Control-Allow-Methods", (req.headers['access-control-request-method']) ? req.headers['access-control-request-method'] : responseSettings.AccessControlAllowMethods);
    res.header("X-Frame-Options", "SAMEORIGIN");
    res.header("X-XSS-Protection", "0");
    if ('OPTIONS' == req.method) {
        res.send(200);
    }
    else {
        next();
    }


});

var server = app.listen(config.port);

var wss = new WebSocket({ 
      server: server,
      path: 'echo'
    });
```

FrontEnd: 
`this.socket = new WebSocket("wss://myserver.foo/echo", []);`

**Comment by alexhultman** [comment]
You are connecting from a browser? To a µWS server? "wss://myserver.foo/echo" is the SSL:ed websocket server?

And the problem is the browser tells you it got 200 as response code? If so, then it is not caused by µWS since it never sends 200, only 101.

**Comment by dmrntpv** [comment]
Did you use any proxy i.e. nginx reverse proxy? I got similar error when connection upgrade was not configured correctly.

**Comment by Ryshard** [comment]
Thank you. Yes I am connecting from a browser to uWS server on Azure. If I run the same server on localhost (node app.js), it is connecting with no problems. I will double check my web.config - maybe something weird happening on the Azure server

**Comment by Ryshard** [comment]
I am not using any proxies. It is an Azure WebApp running node.js on 32-bit windows (with url *.azurewebsites.net). Unless Azure itself is using any.

**Comment by alexhultman** [comment]
You have something between µWS and the browser. Like I said µWS does never send 200 back and it makes a lot more sense that there is something with the Azure set up. I'm closing this until later.
