### ISSUE TITLE
Overhaul sending / corking

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#541]
I made some prototype where corking is done in user space and not via the kernel TCP_CORK feature and the difference in batched scenarios is major: I can get from max 5 million echoes/s before, to well over 30 million. It also improves throughput of HTTP pipelining and similar cases.

This is also needed to get corking cross-platform as Windows has no TCP_CORK and FreeBSD & OS X has limited support via TCP_NOPUSH. With user space corking the networking syscalls would be fully cross-platform so it's good for compatibility as well.

**Comment by alexhultman** [comment]
After lots of thinking it all comes down to not being a problem. Sure, you can improve this but it won't make any difference in real world use cases.

What makes a lot more sense is to focus on pub/sub fundamentals because it is here the real problem is: pub/sub is astronomically inefficient in all implementations I have seen and here is where help is needed: some kind of pub/sub batching abstraction that can easily be used to boost broadcasting / pub performance thousands of times. People simply do not understand how to properly cork / delay publishes.

**Comment by alexhultman** [comment]
Implemented in µS

**Comment by ng5** [comment]
i'm seeing a consistent 200ms(+) latency on linux/epoll while processing http post requests. i'm not networking expert, but it seems like something to do with nagle's default timeout.  

i'm not seeing any delay in much less powerful windows 7/libuv virtual machine.  application code is identical between windows and linux. single thread hub. (no websocket yet, just plain http server) actual processing time within application code is less than 10ms. 

problem happens on popular browser like chrome, firefox and opera. 
with a libcurl client in C, it is harder to reproduce as it uses larger packet size to do POST.

is there any setting in the library to control it?
