### ISSUE TITLE
Identifying sockets in client code

### ISSUE THREAD

**Issue by kolis** [uWebSockets/uWebSockets#546]
We are using a `uWS::Hub` in a client application which sets up multiple sockets to the same server host. It is a bit difficult to identify which socket is which.

Is there a preferred way of identifying sockets?

I have two suggestions for how this can be solved.

* `Hub::connect` return the `WebSocket` handle directly, which can matched against the socket in onConnect and onMessage

* Add a userdata (`void *`) parameter in the connect call, which is added as a member to the socket, which then can be checked in onConnect, onMessage, etc

**Comment by alexhultman** [comment]
Second point is already how it works -> you specify user data in connect call, this is what you get in ws->getUserData().
