### ISSUE TITLE
Info about threading

### ISSUE THREAD

**Issue by tarokker** [uWebSockets/uWebSockets#547]
Hi all,
sorry to bother you again, but I'm having some problems with latest release. Since 0.14.0 alpha 4 it looks like the multithreading example is not working anymore. I'm using a macosx; it could be related to the fact that libUV doesn't support fast switching?
(I was wondering why uWebsockets doesn't use libevents as universal layer for networking...)

I would like to achieve some sort of thread pool system that works both on mac (my development platform) and linux (which will be my production system).

Do you have some suggestions to have multithreading work on both platforms?

Thanks again for your patience.

**Comment by alexhultman** [comment]
Yes absolutely - multithreading is broken on master currently, that's why I only tagged the 0.14.0 for Node.js so far. The "real" 0.14.0 will have working multithreading and also feature optional thread safety on Linux systems.

**Comment by alexhultman** [comment]
You can write a libevent backend if you want - should be very similar to the libuv backend. The epoll backend is far more optimized though, libuv is not really that efficient and I don't know about libevent.

**Comment by tarokker** [comment]
ok thanks a lot for your time.
I'll benefit from epoll optimizations when I'll switch to production on linux machine ;)

**Comment by loint** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/src/Socket.h#L86
Sorry guys but I believe that many projects are using and have bugs with multiple threads can break development.

Honestly I'm using it for development in MacOS but it does not work anymore, LibUV is unstable but I think we can still live with it until better solution for replacement.

Thanks.

**Comment by loint** [comment]
Solved issue by switching to v0.13.0 and it works !

**Comment by alexhultman** [comment]
Of course it works

**Comment by alexhultman** [comment]
Transfer is now implemented and tests pass

**Comment by tarokker** [comment]
thanks a lot, I'm going to check it now!
