### ISSUE TITLE
Common identifiers should also live in the uWS namespace

### ISSUE THREAD

**Issue by jeremyong** [uWebSockets/uWebSockets#550]
The library as-is creates a number of symbols that are far too common to not have a collision when used with a large existing codebase (and may likely collide with other third party libraries as well). The most egregious examples are structs like `Timer` and `Poll` which live in the root level namespace. Since the library is intended to be embedded, these utility classes should likely live in the same namespace as other user-space functions/classes, or be relegated to some sort of `internal` namespace nested under `uWS`.

Thanks for the great library!

**Comment by alexhultman** [comment]
This is fixed in dev branch
