### ISSUE TITLE
Memory leak when sending message?

### ISSUE THREAD

**Issue by MarcelNehring** [uWebSockets/uWebSockets#553]
I am using the master version of µWS and might have found a memory leak. When sending a message `Socket::sendTransformed` allocates memory for the message and calls `Socket::write`. It tries to send the message over the socket immediately and if not all could be sent at once the rest of the message is placed in the message queue for later transmission via the appropriate  ioHandler. However, after successful transmission of the rest of the message I don't see where the allocated memory is freed. Is this a memory leak or am I missing something?

**Comment by alexhultman** [comment]
It is removed in pop: https://github.com/uWebSockets/uWebSockets/blob/master/src/Socket.h#L52

**Comment by MarcelNehring** [comment]
🤦 Of course you are right, sorry I missed that.

However, two memory leak detection tools report a memory leak for the allocation in some rare occasions. I will investigate this further. Not sure if it is a false positive, though.

**Comment by alexhultman** [comment]
No problem, keep on vetting the code and report any flaws you find. You could run some stress test with asan for some days and then gracefully close down the server and see if asan reports anything. Of course, you will need to gracefully close the server down to get accurate memory leak reports.
