### ISSUE TITLE
ws->getUserData() is always returning the newest client's data

### ISSUE THREAD

**Issue by WesThorburn** [uWebSockets/uWebSockets#557]
I can use ws->setUserData() and ws->getUserData() to set and retrieve a clientNumber variable for a single client, however as soon as a second client connects, ws->getUserData() always returns the clientNumber of the second (newest) client, regardless which client the messages are coming from.

I'm getting the exact same error with uWS v0.14.1 and v0.14.0. I'm running Ubuntu 16.04.2 LTS.

Here is a short code segment that I can use to replicate it:
```
int main(){
	int clientNumber = 0;
	uWS::Hub h;

	h.onConnection([&](uWS::WebSocket<uWS::SERVER> *ws, uWS::HttpRequest req){
		cout << "Setting user data to " << ++clientNumber << endl;
		ws->setUserData((void *) &clientNumber);
	});

	h.onMessage([](uWS::WebSocket<uWS::SERVER> *ws, char *message, size_t length, uWS::OpCode opCode){
		cout << "Input received from client: " << *(int*)ws->getUserData() << endl;
    });

    h.listen(3000);
    h.run();
}
```
Here is what the output would look like:
```
Setting user data to 1      <-- Client 1 connects
Input received from client: 1
Input received from client: 1
Input received from client: 1
Setting user data to 2      <-- Client 2 connects
Input received from client: 2
Input received from client: 2
Input received from client: 2
Input received from client: 2      <-- These messages are from Client 1
Input received from client: 2
Input received from client: 2

```
Even after reading through these two issues: https://github.com/uWebSockets/uWebSockets/issues/521 https://github.com/uWebSockets/uWebSockets/issues/546, I'm still not sure what I'm doing wrong.

**Comment by jimmyt857** [comment]
You're setting both user data values as pointers to the same integer, which is changing.  =D

**Comment by WesThorburn** [comment]
Oh, of course. Thanks!
