### ISSUE TITLE
Linux compilation problem

### ISSUE THREAD

**Issue by Bursable** [uWebSockets/uWebSockets#561]
* What operating system are you running?
  * Linux
* Are you running any CPU architechute out of the normal?
  * No
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL via µWS
* What version of uws are you using?
  * Release v0.14.1
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
1. make
`
make `(uname -s)`
make[1]: entrant dans le répertoire « /home/xxx/Bureau/uWebSockets-0.14.1 »
g++   -std=c++11 -O3 -I src -shared -fPIC src/Extensions.cpp src/Group.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp src/Epoll.cpp -s -o libuWS.so
make[1]: quittant le répertoire « /home/xxx/Bureau/uWebSockets-0.14.1 »
`

2. sudo make install
`
make install`(uname -s)`
make[1]: entrant dans le répertoire « /home/xxx/Bureau/uWebSockets-0.14.1 »
if [ -d "/usr/lib64" ]; then cp libuWS.so /usr/lib64/; else cp libuWS.so /usr/lib/; fi
mkdir -p /usr/include/uWS
cp src/*.h /usr/include/uWS/
make[1]: quittant le répertoire « /home/xxx/Bureau/uWebSockets-0.14.1 »
`
3. make tests
`
g++ -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -std=c++11 -O3 tests/main.cpp -Isrc -o testsBin -lpthread -luWS -lssl -lcrypto -lz -luv
/tmp/ccMmNvnc.o : Dans la fonction « std::_Function_handler<void (uWS::WebSocket<false>*, uWS::HttpRequest), measureInternalThroughput(unsigned int, int, bool)::{lambda(uWS::WebSocket<false>*, uWS::HttpRequest)#1}>::_M_invoke(std::_Any_data const&, uWS::WebSocket<false>*&&, uWS::HttpRequest&&) » :
main.cpp:(.text+0x700) : référence indéfinie vers « uWS::WebSocket<false>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<false>*, void*, bool, void*), void*) »
/tmp/ccMmNvnc.o : Dans la fonction « std::_Function_handler<void (uWS::WebSocket<true>*, uWS::HttpRequest), testMessageBatch()::{lambda(uWS::WebSocket<true>*, uWS::HttpRequest)#1}>::_M_invoke(std::_Any_data const&, uWS::WebSocket<true>*&&, uWS::HttpRequest&&) » :
main.cpp:(.text+0x75b) : référence indéfinie vers « uWS::WebSocket<true>::prepareMessageBatch(std::vector<std::string, std::allocator<std::string> >&, std::vector<int, std::allocator<int> >&, uWS::OpCode, bool, void (*)(uWS::WebSocket<true>*, void*, bool, void*)) »
/tmp/ccMmNvnc.o : Dans la fonction « std::_Function_handler<void (uWS::WebSocket<true>*, uWS::HttpRequest), testSendCallback()::{lambda(uWS::WebSocket<true>*, uWS::HttpRequest)#1}>::_M_invoke(std::_Any_data const&, uWS::WebSocket<true>*&&, uWS::HttpRequest&&) » :
main.cpp:(.text+0xa86) : référence indéfinie vers « uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*) »
/tmp/ccMmNvnc.o : Dans la fonction « std::_Function_handler<void (uWS::WebSocket<false>*, uWS::HttpRequest), testTransfers()::{lambda(uWS::WebSocket<false>*, uWS::HttpRequest)#3}>::_M_invoke(std::_Any_data const&, uWS::WebSocket<false>*&&, uWS::HttpRequest&&) » :
main.cpp:(.text+0x1572) : référence indéfinie vers « uWS::WebSocket<false>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<false>*, void*, bool, void*), void*) »
/tmp/ccMmNvnc.o : Dans la fonction « std::_Function_handler<void (uWS::WebSocket<true>*, uWS::HttpRequest), testReceivePerformance()::{lambda(uWS::WebSocket<true>*, uWS::HttpRequest)#1}>::_M_invoke(std::_Any_data const&, uWS::WebSocket<true>*&&, uWS::HttpRequest&&) » :
main.cpp:(.text+0x1a1b) : référence indéfinie vers « uWS::WebSocket<true>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*) »
main.cpp:(.text+0x1d23) : référence indéfinie vers « uWS::WebSocket<true>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*) »
main.cpp:(.text+0x1fb6) : référence indéfinie vers « uWS::WebSocket<true>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*) »
main.cpp:(.text+0x2137) : référence indéfinie vers « uWS::WebSocket<true>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*) »
main.cpp:(.text+0x2d01) : référence indéfinie vers « uWS::WebSocket<true>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*) »
etc...
`

**Comment by alexhultman** [comment]
I think you have linking errors, try and change the order of the libraries, sometimes that helps but I don't know

![](http://3.bp.blogspot.com/-EP5p1fCI0OQ/UuLYBlOHl0I/AAAAAAAAA9M/Z6a3OJZc978/s1600/frenchman.jpg)

**Comment by Bursable** [comment]
ldd libuWS.so gives me :

linux-vdso.so.1 =>  (0x00007fff8a5fe000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8cffc2e000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8cffa17000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8cff64e000)
/lib64/ld-linux-x86-64.so.2 (0x00007f8d00191000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8cff348000)

Some libraries are missing, so I change Linux compile line to :

$(CXX) $(CPPFLAGS) $(CFLAGS) $(CPP_SHARED) -L/usr/local/lib/ssl/lib -I/usr/local/lib/ssl/include -s -o libuWS.so -lssl -lcrypto


Now "make tests" only gives me that error :

g++ -L/usr/local/lib/ssl/lib -I/usr/local/lib/ssl/include -std=c++11 -O3 tests/main.cpp -Isrc -o testsBin -luWS -lz -lpthread
/usr/bin/ld: /tmp/ccG7IhDt.o: undefined reference to «SSL_write@@OPENSSL_1.0.0»
//lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [tests] Erreur 1

Which could be because of my custom openssl installation (needed for another project).
I'll try to fix it tomorrow.

![Sweden sauna](https://lukeinsweden.files.wordpress.com/2010/03/sauna.jpg)

**Comment by alexhultman** [comment]
gcc --baguette

**Comment by jeremyong** [comment]
g++ -L/usr/local/lib/ssl/lib -I/usr/local/lib/ssl/include -std=c++11 -O3 tests/main.cpp -Isrc -o testsBin -luWS -lz -lpthread

This line adds the link folder and include folder but doesn't link ssl itself

**Comment by Bursable** [comment]
Well seen @jeremyong, I had actually forgotten to link ssl.
The complete line is: 
$(CXX) $(CPP_OPENSSL_OSX) -L/usr/lib64 -std=c++11 -O3 tests/main.cpp -Isrc -o testsBin -luWS -lz -lpthread -lssl -lcrypto
Then I just had to add -L/usr/lib64
