### ISSUE TITLE
Extending HttpRequest struct - support for request body and multipart/form-data

### ISSUE THREAD

**Issue by ng5** [uWebSockets/uWebSockets#562]
Hi, 

At the moment HttpRequest only has access to headers, Is there a plan to extend this class to get access to body and other multipart data. Or alternatively we will have to use another http parser if we can get access to raw data pointer. 

group.onHttpRequest() method - Just want to avoid 2nd parsing of raw data if possible so ideally extending HttpRequest would be better. Can you please confirm if this is something already available in the library or outside the scope of this project?

also onHttpData() - Is this an alternative form of onHttpRequest() where raw *data can be parsed to extract additional http fields therefore avoiding 2nd parsing?

thanks

**Comment by alexhultman** [comment]
onHttpRequest gives you the first data segment. If remainingBytes then get those in onHttpData

**Comment by ng5** [comment]
So if I register both callback handlers - will they be automatically called (in correct sequence and with same pair of request/response) if there are remainingbytes or do I need to invoke it from inside onHttpRequest()?

In the example code (tests/main.cpp) - controlData() is being called from inside onHttpData() as well as from inside onHttpRequest() ?

**Comment by alexhultman** [comment]
onHttpRequest comes with headers and potentially data. onHttpData is called only with data and only for remaining bytes that come in later. Same data is never shown twice to the application, these handlers get exclusive data segments.

**Comment by ng5** [comment]
So If I've understood correctly - depending on SO_SNDBUF & SO_RCVBUF size,  If webpage is uploading a large file or multiple large files input - I need to continuously read data from both onHttpRequest() and onHttpData() until remainingBytes==0 and these callbacks may be invoked on different threads. (incase of multithreaded server - linux/epoll/reuseport), so i need a way to store the buffer data inside request object. once all packets are assembled inside (either onHttpRequest() or onHttpData() until remainingBytes==0), http parser can be called to extract POST or file(s) data. 

also I'm assuming there is no way to force callback (For next packet) to be called in the same thread?

**Comment by ng5** [comment]
I think it will be easier to call onHttpRequest() only when HttpRequest has been fully read, it will be easier for people using the library. Possibly adding a new callback like onHttpRequestFullyRead() for compatibility
and extending HttpRequest class.

I will send a pull request after making this change, if you think it makes sense to do so.

**Comment by alexhultman** [comment]
These callbacks and all other callbacks are same-thread (Hub is 1:1 with Thread). The only exception is onTransfer but this callback will probably be moved to another place.
