### ISSUE TITLE
More info on the ws-rs benchmark

### ISSUE THREAD

**Issue by lilianmoraru** [uWebSockets/uWebSockets#565]
Could you please offer more info on how to run or how was the `ws-rs` benchmark run?
The code is not available under `benchmarks`.
I am curious because I would also like to add `tungstenite-rs` and `tokio-tungstenite` and compare those too.

**Comment by alexhultman** [comment]
ws-rs was run like all the other servers (which is openly documented and linked to). It is an echo server so you can set that up without sources.
