### ISSUE TITLE
timer bug when use re-added timer 

### ISSUE THREAD

**Issue by ZDzhao** [uWebSockets/uWebSockets#570]
When I use a re-added timer, the cpu usage is tooo much high, so I check the epoll-loop timeout, as it is the loop->delay, I find when I use timer start in the timer cb, timer[0].timepoint must "<" loop->timepoint, so the loop->delay will be 0 which cause a too busy eventloop.

**Comment by ZDzhao** [comment]
The timer above is the epoll timer. I think it's a bug, and  sometimes when I have delete the epoll timer, but  it can also call the timercallback function, which cause core dump, now I can't find where is the bug, so I push the issue.

**Comment by alexhultman** [comment]
I'll reopen if and when you fill the template out with proper sample.
