### ISSUE TITLE
How exchange messages between client sockets on websocket server?

### ISSUE THREAD

**Issue by juliao** [uWebSockets/uWebSockets#574]
Hi, I'm trying to repass a message received on a websocket server from client A (browser), to client B (browser), but I cannot figure out how can I get the socket handler of a specific client to send the message (the setUserData and getUserData seems to be not usefull here, except for identify from the message came), below is what I tried, but the result is that *source and *dest will have the same address, I using the code from echo server.

```
int source_id = 0;
int dest_id = 1;
uWS::WebSocket<uWS::SERVER> *source;
uWS::WebSocket<uWS::SERVER> *dest;

// inside h.onMessage(uWS::WebSocket<uWS::SERVER> ws, ...)
// message type is "login", so will be executed just one time for each client
	if (msg_id == source_id) {
		source = &ws;
	}
	else if (msg_id == dest_id) {
		dest = &ws;
	}

// and I will use the code below to send the message
source->send(message, length, opCode);
```

**Comment by alexhultman** [comment]
I'm sorry but this is not a question specific to uWS but rather a general programming question. You didn't fill the issue template so I cannot know for sure but you seem to take the address of a temporary which is invalid C++. I don't provide general C++ language support.

**Comment by juliao** [comment]
OK, I already figured out the problem, the version of uWS that was using (commit 31c28321964917d4c2164211715d61fb857fa754, less than 1 month ago) act like I described, so I synced the last version and compiled, I just needed to change the ws parameter in onMessage to pointer type, now my code works.

**Comment by alexhultman** [comment]
0.14 is more obvious than 0.13 yes
