### ISSUE TITLE
[Node.js]When client connect to server,but server not yet ready,client will crash.

### ISSUE THREAD

**Issue by richardlin2014** [uWebSockets/uWebSockets#578]
I use Node.js
When client connect to server,but server not yet ready,client will crash.

[My Enviroment]
OS : Linux Ubuntu 14.04
uname -r : 3.19.0-73-generic
uname -m : x86_64
node version : v4.6.1
uws version : 0.14.1

[Test code]
var WebSocket = require('uws');
var ws = new WebSocket('ws://127.0.0.1:3000');
ws.on('open', function () {
    console.log('Connected!');
});

ws.on('error', function (err) {
    console.log(err);
});

[Result]
$ node client.js
{ message: 'uWs client connection error',
  stack: 'uWs client connection error' }
node: ../deps/uv/src/unix/core.c:168: uv_close: Assertion `0' failed.
(core dumped)

**Comment by SkeLLLa** [comment]
The same on node v7.8.0, but sometimes it segfaults:
```
segmentation fault  node test.js
```
and sometimes it produces:
```
error { message: 'uWs client connection error',
  stack: 'uWs client connection error' }
node: /tmp/portage/dev-libs/libuv-1.11.0/work/libuv-1.11.0/src/unix/core.c:101: uv_close: Assertion `!uv__is_closing(handle)' failed.

```

**Comment by FMarxis** [comment]
I am having the same issue with Node.js, segmentation fault is thrown while connection fails on error (e.g. server not ready).
```
var WebSocket = require('uws');

function connect () {
    let promise = new Promise(function (resolve, reject) {
        var ws = new WebSocket('wss://192.168.30.117:9002');
        ws.on('error', function error() {
            console.log('Error connecting!');
            setTimeout(function () {
                reject(false);
            }, 1000);
        });
    });
    return promise;
}

async function start() {
    try {
        await connect();
    } catch(error) {
        console.log(error);
    }
}

start();
```

Process will crash within 10 seconds, there can be multiple retries before the crash but eventually the client will segfault, causing process to crash, catching by different methods would show
> Assertion `!(((handle)->flags & (UV_CLOSING | UV_CLOSED)) != 0)' failed
> node: ../deps/uv/src/unix/core.c:166: uv_close: Assertion `0' failed. Aborted (core dumped)
> Segmentation fault (core dumped)

Seems to be a libuv problem, [https://github.com/joyent/libuv/issues/949](url).

**Comment by FMarxis** [comment]
UPDATE: Reverted back to uws@0.13.0 since I had a local compiled package at this version (npm does not have old versions anymore, only 0.14.1 is available). The same piece of code would not segfault and exit as soon as error is printed, while in 0.14.1 the code would hang until segfault.

I have written test code that has a simple retry logic, in 0.14.1 this would segfault after a few retries, while in 0.13.0 will keep retrying.
```
var WebSocket = require('uws');

function connect () {
    let promise = new Promise(function (resolve, reject) {
        var ws = new WebSocket('wss://192.168.30.117:9002');
        ws.on('error', function error() {
            console.log('Error connecting!');
            setTimeout(function () {
                reject(false);
            }, 1000);
        });
    });
    return promise;
}
```

async function start() {
    setInterval(async function(){
        try {
            await connect();
        } catch(error) {
            console.log(error);
        }
    }, 1000);
}

start();

**Comment by alexhultman** [comment]
Very nice report, I can trigger it and I can also trigger it without Node.js. It seems like a major flaw for connection errors, it seems sockets are not really closed at all in that case leaving them still in the loop while having no memory which is very broken. Will fix in next patch release.
