### ISSUE TITLE
process.nextTick() taking longer than expected

### ISSUE THREAD

**Issue by jondubois** [uWebSockets/uWebSockets#58]
I'm playing around with uWebSockets and I noticed that `process.nextTick(callback)` takes longer than normal (it takes over 3 seconds for me) when I call it inside an `on('message', hander)` handler immediately after the connection has been established. I did a console.log() before invoking `process.nextTick(callback)` and then did another console.log() from inside the callback and there is a significant gap.

Switching back to `require('ws')` fixes the issue immediately.

I've got a lot of code on top of uWS in my case but I think you should be able to reproduce the issue by following these steps:
- Listen to the 'connection' event on the server
- Inside the connection handler, listen to the socket's message event using `on('message', messageHandler)`
- From the client, send a simple string message to the server as soon as possible.
- Inside the messageHandler, do:

```
var startTime = Date.now();
process.nextTick(function () {
  var endTime = Date.now();
  console.log('DURATION: ', endTime - startTime);
});
```

The duration is almost 4 seconds for me.

It only happens for the first message immediately after the 'connection' is triggered on the server, but not subsequent messages.

I'm using node v5.4.1

**Comment by alexhultman** [comment]
Why would 4 seconds be longer than normal? What are you using nextTick for and what delay did you expect? The loop is not going to spin all the time? Sorry if I don't see the problem?

**Comment by alexhultman** [comment]
So nextTick should be similar to setting a timer with time 0? And it is taking longer, okay I see the problem. This is still very strange because the callback code is so simple and small.

**Comment by lpinca** [comment]
Tried with this:
```js
'use strict';

const uws = require('uws');

const server = new uws.Server({ port: 8080 });

server.on('connection', function (ws) {
  console.log('connection');

  ws.on('message', function (msg) {
    console.log(msg);
    const start = Date.now();

    process.nextTick(function () {
      const end = Date.now();

      console.log('DURATION:', end - start);
    });
  });
});

server.on('error', function (err) {
  console.error(err.message);
});
```

nextTick callback does not fire in my case. Works fine if I replace `process.nexTick` with `setImmediate`.

This is the client-side code:
```js
(function () {
  var ws = new WebSocket('ws://localhost:8080');

  ws.onopen = function () {
    console.log('open');
    ws.send('message');
  };
})();
```

**Comment by alexhultman** [comment]
I found this: https://github.com/frankwallis/next-tick-test/blob/master/addon.cc

Seems there is a MakeCallback function that should be called to allow nextTick to fire correctly. Will see if this is the case.

**Comment by alexhultman** [comment]
Seems to be legit, 459cac06c07b0278810b0051f01bbff626f6db10

I will push a new version later today

**Comment by alexhultman** [comment]
e22e552861edbc2b594f154fc0fc20025ea1c75c

**Comment by alexhultman** [comment]
There is a massive cost of calling into JS via Node.js's wrapper instead of using the pure V8 call. I changed back to a mix between the old and the new: every NEW message of this iteration will be called with MakeCallback and every following message that originates from the same iteration is called with pure V8. This will probably break some stuff but I'm willing to ignore that fact based on the enormous retake of lost performance. Maybe things can be further improved to maybe call with MakeCallback each 100th call or something to give a good balance between performance and process.nextTick behavior.

There is really nothing stating the exact behavior of process.nextTick

**Comment by alexhultman** [comment]
By limiting the number of skips to 100 the perf goes to 694 echoes/ms while still providing a 0ms delay for any process.nextTick. Something like that would be a good mix between the two behaviors.

**Comment by alexhultman** [comment]
I've done some testing and it seems to be as simple as just calling MakeCallback *lastly* and it works.
