### ISSUE TITLE
get socket by an ID

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [uWebSockets/uWebSockets#580]
Whenever a socket is opened, I generate a **sid** for it and attach it to the socket object.

Each time a socket **message** event fires, I get the message received from the client and send a packet with this message to a message broker with the socket's **sid** attached.

Upon the message is processed the message broker returns a reply supplied, again, with the **sid** of the socket the reply should be sent to.

The question: is there a way to get a socket by it's ID apart from using the **forEach** function?

**Comment by alexhultman** [comment]
In C++ you can just take the WebSocket pointer and cast it to a 64-bit integer, send it, get it, and then "lookup" the WebSocket using that integer (there is no lookup cost, you already know the address).

In JavaScript, I think the closest thing would be to put the WebSocket object in a hash map with your sid as key and then look it up via hash - this is of course more costly but JS has no pointers so yolo `¯\_(ツ)_/¯`

**Comment by alexhultman** [comment]
Oh never mind, that would be crazy insecure if you got some bad address. I think a hash map is the simplest but you can of course tinker with any kind of container - it's up to the application to hold the sockets, the server only holds a linked list of sockets for cases like broadcasting, pinging and to shut down timed out sockets.

**Comment by alexhultman** [comment]
No, if YOU own both the broker and the server then the prior pointer-based approach should be the most efficient. If you can make sure the broker and the server communicate securely then it should be secure.

**Comment by Dmitry-N-Medvedev** [comment]
Yes-yes, I am currently using a Map object in NodeJS to hold the references to sockets. So, the _key_ is the **sid** generated, whereas the _value_ is a weak reference to the socket object ( there is a [weak](https://github.com/TooTallNate/node-weak) module for weak references in NodeJS ).

Anyway, I feel as if this construct with weak references should be seen as a memory hungry approach. I would definitely prefer a native lookup function for NodeJS. Say, and **id** in the connection event along with the socket object, and a mechanism to get a reference to a websocket by the said **id** later. It's kind of strange such functionality has not yet been requested...

PS: sorry, I don't know how to program in C++. unfortunately.

**Comment by alexhultman** [comment]
Oh wow, "weak" module. Why?

A Persistent<Object> is 64-bit big, but they smack a full blown EventEmitter, JS callbacks and a lot of shit to it so yeah I can understand if that garbage module eats up all your memory. It wouldn't surprise me if that "weak" *reference* is 4x the size of a complete WebSocket (I'm fairly sure this is the case by looking at it).

**Comment by alexhultman** [comment]
Why would anyone replace a 64-bit *reference* with a 200 byte bloat-bomb? Holy shit I thought I had seen it all. *references* bigger than the actual object the refer to! I must lay down and rest :scream:

**Comment by alexhultman** [comment]
So I removed my comments about the weak module because I think its better for me to not bother. You have to find a solution that works for you, like I said it is up to the application to solve lookup.

**Comment by lpinca** [comment]
@Dmitry-N-Medvedev why not using a [`Map`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) or [`WeakMap`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)?

```js
server.on('connection', (ws) => {
  const id = uuid();
  ws.id = id;
  map.set(id, ws);
});
```

then when you need to get a socket by its id

```js
const ws = map.get(id);
```

The map stores only ids and references to `WebSocket` objects. It can't be better than this. You can assume a complexity of `O(1)` or `O(log(n))` at max as it is sublinear per spec.

**Comment by Dmitry-N-Medvedev** [comment]
@lpinca, I have implemented it in exactly the same way. There is no problem with this approach besides it assumes references to sockets are kept outside of the uws library in a non-native manner. I would definitely prefer to have it implemented natively for the sake of speed and memory efficiency.

**Comment by Dmitry-N-Medvedev** [comment]
@alexhultman,

> So I removed my comments about the weak module because I think its better for me to not bother. You have to find a solution that works for you, like I said it is up to the application to solve lookup.

If only I was in a position to recommend you to never delete your comments I would do it - you possess knowledge of what you talk about way deeper than me. How would I know that the weak module consumes 200 bytes per reference without you disclosing it? No way. So, please, do not remove your comments.

> I can say though, that weak-module looks to be extremely heavy weight and you should never need it in the first place. It is just a bad hack.

I have removed it.

**Comment by lpinca** [comment]
> There is no problem with this approach besides it assumes references to sockets are kept outside of the uws library in a non-native manner.

You already have references to those sockets in your app code for the whole life of the sockets.
I also highly doubt you'll get better performance by doing this in C++ and then using it in JS.
