### ISSUE TITLE
Stuck on onConnection callback

### ISSUE THREAD

**Issue by jcifuentes91** [uWebSockets/uWebSockets#582]
* What operating system are you running?
  * OS X

* What platform/language are you using?
  * C++
  * QT

* Are you using SSL, if so, how?
  * SSL is not part of the equation

* What features of µWS are involved in the issue?
  * Client support (WebSocket)

Im building a UI in Qt to use uWebSockets in order to create a stress test to a uWebSockets server, I'm not quite familiar with C++ but I managed to compile and start using your library, I can connect to a web socket server, but when I try to execute some other code, it seems like the hub is stuck at the onConnection callback and never leaves so the thread im using is blocked and I cant seem to communicate with it. I'm using QThreads, Signals and Slots:

```
## File: wsworker.h
#include <uWS/uWS.h>
#include <iostream>
#include <QThread>
class WsWorker : public QObject
{
    Q_OBJECT
    uWS::Hub hub;
    uWS::WebSocket<uWS::CLIENT> *socket;

public slots:
    void connect(QString url ){
        std::cout<<"worker::connect"<<std::endl;
        this->hub.onConnection([this](uWS::WebSocket<uWS::CLIENT> *ws, uWS::HttpRequest req) {
             std::cout<<"worker::connected"<<std::endl;
             this->socket = ws;
             this->onConnected();
         });
        this->hub.connect(url.toStdString(),nullptr);
        this->hub.run();
    }
    void send(QString message){
        std::cout<<"worker::send"<<std::endl;
        this->socket->send("some dummy message");
        emit sent();
    }
 void onConnected(){
        emit connected();
    }
signals:
    void connected();
    void sent();
};
```
```
## file: MainWindow.cpp ....
void MainWindow::on_connectionButton_clicked()
{
    if(this->connected == false){
       WsWorker *worker = new WsWorker;
       worker->moveToThread(&workerThread);
       connect(&workerThread, SIGNAL(finished()), worker, SLOT(deleteLater()));
       connect(worker, SIGNAL(connected()), this, SLOT(onConnect()));
       connect(worker, SIGNAL(sent()), this, SLOT(onSent()));
       workerThread.start();
       this->location = this->ui->urlLineEdit->text();
       this->ui->urlLineEdit->setEnabled(false);
       this->ui->connectionButton->setEnabled(false);
       std::cout<<"mainwindow::connecting"<<std::endl;
       QMetaObject::invokeMethod(worker,"connect",Qt::QueuedConnection,Q_ARG(QString,this->location));
    }else{
        std::cout<<"mainwindow::disconnecting"<<std::endl;
        //QMetaObject::invokeMethod(worker,"disconnect",Qt::QueuedConnection);
    }

}
void MainWindow::on_inputSendButton_clicked()
{
    if(this->connected){
        std::cout<<"mainwindow::sending"<<std::endl;
        QMetaObject::invokeMethod(worker,"send",Qt::QueuedConnection,Q_ARG(QString,this->ui->inputTextEdit->toPlainText()));
    }
}
void MainWindow::onSent(){
    std::cout<<"mainwindow::sent"<<std::endl;
    this->ui->inputTextEdit->setPlainText("");
}
void MainWindow::onConnect(){
    this->ui->connectionButton->setEnabled(true);
    this->ui->connectionButton->setText("Desconectar");
    this->connected = true;
    std::cout<<"mainwindow::connected"<<std::endl;
}
```

My code manages to execute the slot onConnect() on the MainWindow, but after that when I try to send a message (MainWindow::on_inputSendButton_clicked()) it just executes the MainWindow method and the worker seems to be stuck on the onConnection callback. The question here is, am I doing it wrong? I looked up at the examples, but all of them seem to have the execution code before the hub.run() call and I would like to send user generated messages outside of the onConnection method. Thanks

**Comment by alexhultman** [comment]
See if 0.14.3 fixes this for you

**Comment by jcifuentes91** [comment]
I tried the following, downloaded 0.14.3, cd to the folder, make, sudo make install, then recompiled my sourcecode, still the same.

**Comment by meiry** [comment]
please update if solution is found  .
i will try to test older versions 
Thanks

**Comment by meiry** [comment]
@alexhultman @Rubonnek
Checked version v0.5.0 which is year old and it is working fine . 
so some where in between gone wrong .

**Comment by jcifuentes91** [comment]
@alexhultman  @meiry  how do you install 0.5 correctly? I tried the following

- cmake CMakeLists.txt
- make

but when I try make install it wont work

**Comment by alexhultman** [comment]
@jcifuentes91 You are not going to "fix" the problem by swapping to 0.5. You clearly have threading issues to solve in your app.

**Comment by alexhultman** [comment]
You are calling onConnect from your µWS thread. I suspect this is very much invalid usage of Qt - I don't think Qt is thread safe this way.

**Comment by alexhultman** [comment]
@meiry you are referring to a completely different issue that, from what I can read in your linked issue, is purely Windows specific.

**Comment by alexhultman** [comment]
I'm closing this @meiry if you can give me steps to reproduce Windows specific issues then open a new issue for that.

**Comment by meiry** [comment]
You have problem in your code ignore it or not it's yours issue . 
Reproduce it you just use libwebsockets clients from window to make simple ws call

**Comment by meiry** [comment]
@jcifuentes91
Just use the c/h files in your project in VC++
But I really recommend you to use libwebsockets as your ws framework

**Comment by alexhultman** [comment]
@meiry If we focus on @jcifuentes91 and his issue, which is separate from yours. He is violating the Qt threading model by calling Qt UI functions from a separate thread. This is not in any way an issue in uWS but purely invalid threading by the user.

Your issue @meiry is not at all involving threads but instead you are complaining about not being able to connect to the echo server on Windows. This is a separate issue and you need to report it separately.

In any case, you are free to use whatever software you want if you believe that will help you.

**Comment by jcifuentes91** [comment]
@alexhultman  I have a question, how am i violating qt threading?, I'm placing uws on a separate thread and using signals and slots, I never update ui from the uws thread, but from the main thread, my problem is that when I try to invoke any other method on the uws thread it is stuck on the onConnected callback, i took out the signals and slots that update the ui and the problem persists, like i said im no expert on Qt or c++, but I'm trying to implement a way with UI to test your library, maybe im not understanding how your lib works, but what i see from the examples is that the run method is executed after you gave all the behavior you want from your lib, but in my case im trying to send messages after the run method is invoked.

**Comment by alexhultman** [comment]
I don't know, your example is incomplete

**Comment by meiry** [comment]
The Qt code is fine . In termed of creating the thread 
What I think he meant is that your client examples are confusing as you mix server and client in the same function 
Can you suplay please simple client example

**Comment by alexhultman** [comment]
Btw Qt has its own WebSocket module that perfectly integrates with Qt.

**Comment by meiry** [comment]
@jcifuentes91
found the problem long time ago .
change the run method to support ipv4
so it should look like this : 
```
h.listen(3000,nullptr, uS::ONLY_IPV4);
```
