### ISSUE TITLE
Nodejs version is surprisingly slow with close connection

### ISSUE THREAD

**Issue by hbakhtiyor** [uWebSockets/uWebSockets#588]
i recently did simple [benchmark](https://github.com/hbakhtiyor/node-frameworks-benchmark) with wrk and [uws](https://github.com/hbakhtiyor/node-frameworks-benchmark/blob/master/servers/uws.js) is very slow with close connection.
and with [koa + uws](https://github.com/hbakhtiyor/node-frameworks-benchmark/blob/master/servers/ukoa.js) is fast with close connection.

why is slow with single uws and fast using koa framework?

**Comment by alexhultman** [comment]
#511

**Comment by alexhultman** [comment]
You don't have any content-length header
