### ISSUE TITLE
How to make the server close a websocket

### ISSUE THREAD

**Issue by MarcelNehring** [uWebSockets/uWebSockets#589]
Hi,

what is the correct way of closing a single connection from within the server? In the [`measureInternalThroughput`](https://github.com/uWebSockets/uWebSockets/blob/master/tests/main.cpp#L138) test you simply call `WebSocket.close()`. Is this also sufficient in a multi threaded environment? Can I call it from anywhere / any thread? Some people told me it has to be called from within libuv's loop but then it occasionally crashes in `uv_process_endgames`.

```
void closeSocketAsync(uWS::WebSocket<uWS::SERVER> &ws)
{
    auto wsPtr = new uWS::WebSocket<uWS::SERVER>(ws);
    auto loop = hub->getLoop();
    auto closeAsync = new uv_async_t;
    closeAsync->data = wsPtr;

    auto asyncCallback = [](uv_async_t * async)
    {
        auto wsPtr = static_cast<uWS::WebSocket<uWS::SERVER> *> (async->data);
        wsPtr->close();
        delete wsPtr;
        async->data = nullptr;
        uv_close(reinterpret_cast<uv_handle_t*>(async), nullptr);
        delete async;
    };

    uv_async_init(loop, closeAsync, asyncCallback);
    uv_async_send(closeAsync);
}
```

**Comment by alexhultman** [comment]
You  need to check up with the libuv documentation

**Comment by alexhultman** [comment]
And you need to check up how close works, there are examples

**Comment by MarcelNehring** [comment]
Based on your comments I guess your answers to my questions are:

- It is not sufficient to simply call `WebSocket.close()` like in [`measureInternalThroughput`](https://github.com/uWebSockets/uWebSockets/blob/master/tests/main.cpp#L138) in a multi-threaded environment.
- I have to call it from the same thread that runs libuv's main loop.
- My current code is broken in two ways: The way I inject the callback into libuv's main loop and the way I call `WebSocket.close()`.

After consulting libuv's documentation again I might have an idea what is wrong with the way I inject my callback into libuv's main loop. So thanks for your hint about that.
However, I seem to be unable to figure out what is wrong with the call to `WebSocket.close()`. Any chance that you could give a hint on which example you were talking about? So far I was unable to find an example where `WebSocket.close()` is called in a multi-threaded environment. I had a look at `Group.close`, though, and it simply calls `WebSocket.close()` on all its sockets. Similarly in case a socket runs into a timeout due to the use of `Group.startAutoPing()` a simple call to `WebSocket.terminate()` is made. So I cannot see what special steps do I have to perform.

**Comment by alexhultman** [comment]
You need to comöare what you do and what the examples do. Hint: delete

**Comment by alexhultman** [comment]
Also, if you have problems in native programs it is very helpful to use AddressSanitizer, it would have pointed out that you double free stuff.

**Comment by MarcelNehring** [comment]
Yes, the examples do not delete the WebSocket object after closing it, but they also didn't allocate it on the heap like I did here. As far as my analysis goes a WebSocket object can be copied without any side effects since the only member is a pointer to the corresponding poll handle and the instance does not own the pointer. Also since neither the `WebSocket` nor the `Socket` class have a destructor, calling delete on the `WebSocket` should not have any side effects either. So I must say that I don't see what could be wrong with calling `delete wsPtr` here, I'm afraid.

Unfortunately ASan is not available for my toolchain, AFAIK. Similar tools like Dr. Memory do not report any issues with my current code.

I really appreciate that you spend your valuable time assisting me with this but I don't see the mistake here and seem to need another hint.
Just in case there is a misunderstanding: the problem with deleting the `uv_async_t` is fixed and thus the current code does no longer crash.

**Comment by alexhultman** [comment]
I missed your copy. Why are you copying? It shouldn't be allowed. You cannot create an async like that, it needs to be created prior. You shouldn't use internal stuff, uv_async_t is wrapped as Async you can use instead. You should never copy a websocket

**Comment by Oipo** [comment]
@MarcelNehring Perhaps this will help you: https://github.com/RealmOfAesir/gateway/blob/13a082d9372bafec99ecda05b7ca0f85109cba1a/src/main.cpp#L309

There is a double free there though, once Hub goes out of scope, it also tries to delete the loop.
