### ISSUE TITLE
Why uWebSockets does not support xp?

### ISSUE THREAD

**Issue by jchdng** [uWebSockets/uWebSockets#591]
## Frequently posted issues
**I cannot compile or link the project \<insert compiler or linker error\>**  
I can not compile the project with msys2-mingw32."inet_ntop" function in Socket .cpp is not defined and does not support with windows xp.

**Comment by alexhultman** [comment]
Does it work in Windows 3.1?

**Comment by smasherprog** [comment]
I checked win95 and it works there so I think it should support xp. Not sure about win 3.1. 
Ill have to get my win 3.1 disks out to double check. Maybe this should support DOS as well ....
