### ISSUE TITLE
Maximum Message Size

### ISSUE THREAD

**Issue by aurelw** [uWebSockets/uWebSockets#593]
I use the minimal example provided in the README.

There is a limit to the maximum message length accepted by the websocket server. I couldn't really figure out the exact value but some hundreds of MB is not possible. If I send such a large message from a (python) client to the server, the server closes the connection. On the server side this happens quietly. As far as I can see there is no mechanism to catch this error.

Is it possible to change the maximum length of accepted messages and if not, can wen have an interface to do so? 

I know that it is not best practice to send very large messages. However, in my particular case I just want  to do so and have a way to configure this value.

**Comment by alexhultman** [comment]
https://github.com/uWebSockets/uWebSockets/blob/master/src/Hub.h#L46

maxPayload is 16mb by default
