### ISSUE TITLE
nodejs: 'listening' event

### ISSUE THREAD

**Issue by kalitine** [uWebSockets/uWebSockets#596]
* What platform/language are you using?
  * Node.js
* What version of uws are you using?
  * Release v0.14.5
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

Expected behavior:
```javascript
// server.js
const WebSocketServer = require('uws').Server

const wss = new WebSocketServer({ port: 8080 })

wss.on('listening', () => console.log('The server has been bound!'))

```
After run we have the expected output:
```shell
$ node server.js
The server has been bound!
```
What I think a WRONG behavior:
```javascript
// server.js
const http = require('http')
const WebSocketServer = require('uws').Server

const server = http.createServer()
const wss = new WebSocketServer({ server })

wss.on('listening', () => console.log('The server has been bound!'))

server.listen(8080, () => {
  console.log('Listening on %d', server.address().port)
})
```
After run we have:
```shell
$ node server.js
Listening on 8080
```
but expect:
```shell
$ node server.js
The server has been bound!
Listening on 8080
```

**Comment by alexhultman** [comment]
It looks like this is not the case. So you'll have to use the http.Server.listen cb.

**Comment by kalitine** [comment]
In my use case I have done the following trick:
```javascript
const server = new WebSocketServer(options)
const serverListening = options.server || server
serverListening.on('listening', () => {
 // this callback will be executed in all cases despite how user starts the server.
})
```
This is because I am developing a library and is up to the library's consumer to decide how to start the server. But inside of the library I need to know when the server has started, so this callback is important.
I've discovered this behavior after having switched from `ws` to `uws` module.
