### ISSUE TITLE
Sending binary data; can only send Blobs; how to send ArrayBuffer?

### ISSUE THREAD

**Issue by Yatekii** [uWebSockets/uWebSockets#597]
## Include the following information (where applicable):

* What operating system are you running?
  Linux
* Are you running any CPU architechute out of the normal?
  I run 32-bit in the year 2017
* What platform/language are you using?
  C++
* Are you using SSL, if so, how?
  SSL is not part of the equation
What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  Server support (WebSocket)
* How does the issue reproduce?
  All the time
* Can you show me some short code that triggers your issue or any other important information?

```
#include <uWS.h>
#include <Node.h>
#include <iostream>
#include <cmath>
#include <vector>

struct state {
    uWS::WebSocket<uWS::SERVER>* sock;
    bool sock_open;
};

int main() {
    uWS::Hub h;
    size_t framesize = 2000;
    size_t connections = 0;
    struct state s;
    s.sock_open = false;

    std::cout << "Server started." << std::endl;

    h.onHttpRequest([](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
        res->end("KEKE", 4);
    });

    h.onConnection([&s, &connections](uWS::WebSocket<uWS::SERVER> *ws, uWS::HttpRequest req) mutable {
        s.sock = ws;
        s.sock_open = true;
        std::cout << "[New Connection] # clients: " << ++connections << std::endl;
    });

    h.onMessage([](uWS::WebSocket<uWS::SERVER> *ws, char *message, size_t length, uWS::OpCode opCode) {
        // if isBinary:
        //     print("Binary message received: {} bytes".format(len(payload)))
        // else:
        //     payload = payload.decode('utf8')
        //     print("Text message received: {}".format(payload))
        //     cmd = json.loads(payload)
        //     if 'frameSize' in cmd:
        //         self.frameSize = int(cmd['frameSize'])
        std::cout << "Got message: " << message << std::endl;
    });

    h.onDisconnection([&s, &connections](uWS::WebSocket<uWS::SERVER> *ws, int code, char *message, size_t length) mutable {
        s.sock_open = false;
        std::cout << "[Connection lost] # clients: " << --connections << std::endl;
    });

    Timer *timer = new Timer(h.getLoop());
    timer->setData(&s);
    timer->start([](Timer *timer) {
        std::vector<unsigned short> sinus(2000);
        for(size_t i = 0; i < 2000; i++){
            sinus.push_back(16384 + 7000 * sin(i/2000*40*M_PI));
        }
        struct state* s = (struct state*)timer->getData();
        std::cout << "Try Send: " << std::endl;
        if(s->sock_open){
            std::cout << "Send: " << sinus.size() << std::endl;
            s->sock->send((char*)&sinus[0], sinus.size(), uWS::OpCode::BINARY);
        }
    }, 0, 350);

    h.listen(50090);
    h.run();
}
```

This is the server side. It works great as far as it can open and close connections properly. It also receives messages properly. Where I am stuck is the line: `s->sock->send((char*)&sinus[0], sinus.size(), uWS::OpCode::BINARY);`. It get's transmitted and I get a message on the JS-Client side.

If I just open a WebSocket with

```
var sock = WebSocket('ws://localhost:9000');
```

the data contained is

```
data: Blob {
    size: 4000
    type: ""
}
```

but if I want to convert the data to an array buffer and I set

```
var sock = WebSocket('ws://localhost:9000');
socket.binaryType = 'arraybuffer';
```

i will get an ArrayBuffer with `length === undefined`.

When I use the Autobahn python library this works properly when I send binary data, so I assume that it's something I do not understand with uWS.

Could you give me a hint?

Everything works fine and it was really easy to code a simple sever :)

Thank you!

**Comment by alexhultman** [comment]
It is called byteLength

**Comment by Yatekii** [comment]
If the property in JS was the wrong one why would it work with the Autobahn server? I don't understand.

**Comment by alexhultman** [comment]
No idea, that is a front-end question. Server side doesn't deal with ArrayBuffer or Blob - it's just binary or text.

**Comment by Yatekii** [comment]
No, that is my point. The client side is the same, the only thing I changed was the server side. Anyways, works like a charm now, thank you very much kind sir!
