### ISSUE TITLE
need to check basic authentication header for onHttpUpgrade callback

### ISSUE THREAD

**Issue by ng5** [uWebSockets/uWebSockets#604]
Hi,  
I'm trying to use this library as a pure c++ http server as well as websocket. I need to add some basic authentication using Authorization header, onHttpRequest has access to HttpRequest and i can easily check the headers for allowing the connection. 

However onHttpUpgrade() i only need to add a check ( check if Authentication header or SessionID is valid) on top of default behaviour, but I can't copy and paste that code(HTTPSocket.cpp)  to my own handler, a lot of functions like removeWebSocket or addWebSocket are protected. 

Is it possible to wrap default handler (for onHttpUpgrade) as a public method, so that it can be called back after header checks are complete. or is there a better way to achieve this? 
`   
 h.onHttpUpgrade([](uWS::HttpSocket<uWS::SERVER> *s, uWS::HttpRequest req) {

           // check required headers for Authorization or session ID

           if (good)

              call default handler

           else

              reject upgrade
    });`

**Comment by alexhultman** [comment]
onConnection gives you the HttpRequest and you can terminate the connection if you wish.

**Comment by ng5** [comment]
thanks for the answer, but this may not be a new connection. If I have already returned a static webpage (running on same server) - and then just upgrading the request to web socket, I believe onConnection will not be invoked (if keep alive is enabled). I will try your suggestion anyway. thanks.

**Comment by alexhultman** [comment]
onConnection is when the HttpSocket has been upgraded to a WebSocket. onHttpConnection is when the actual TCP connection is established.

**Comment by ng5** [comment]
Hi Alex, this solution will work for me. however looking at source code there is an opportunity to terminate connection much earlier (based on header credentials) without incurring overhead of creating web socket only to terminate it later. I'm happy to work on it and create a PR to introduce a new callback, just need your opinion if this is something worth putting in the library.  thanks a lot.

**Comment by alexhultman** [comment]
I don't think that's worth caring for right now. The feature you want is already implemented and you will anyways have a lot of creation of stuff going on. You are looking at removing one memory allocation per connection termination which is some nanoseconds. Compare that with the time it takes to establish a TCP connection which can be up to 1 second.
