### ISSUE TITLE
string to char

### ISSUE THREAD

**Issue by psdn** [uWebSockets/uWebSockets#607]
debian linux
c++
SSL via µWS
Master
Latest
Server support (WebSocket)
everytime

Aside from my class function, the code is take directly from example.cpp.

Can you confirm that on onmessage, the char* message data contains and is supposed to contain:
1. The client message
2. 3 high ascii characters and a blank character
3. The entire http header.

with every client message received?

I'm struggling to get char data to string data back to char data and it would make my struggle easier to know exactly what I should be seeing if it is different than what I'm getting.

If the client send the word hello, type_t length is 5, sizeof(message) is 8. Niether are the same, and neither account for the entire http header when I cout "message"

ref: issue #606

**Comment by alexhultman** [comment]
Like I said you are not taking length into account. The message is two parts: message and length. Length is the message length. You simply cannot skip fundamental 101 programming and then report issues in libs, caused by your own lack of fundamentals.

**Comment by psdn** [comment]
I understand that length is the message length, but it is not accurate. Is there a NULL char at the end? what are the 3 high ascii characters? This is the only place I see where there is any source of help. I'd rather not ask here, but this it it. Sorry to bother.

**Comment by alexhultman** [comment]
I don't know what more to say. I have already told you twice. If you don't want to listen then don't ask. This is not FreeCodeCamp.

**Comment by ronag** [comment]
@psdn: Please use http://stackoverflow.com
