### ISSUE TITLE
Improve, polish & test SSL support

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#68]
Initial SSL support seems to work pretty nicely. Will need some more polishing and error handling, etc.

**Comment by alexhultman** [comment]
* First goal would be to pass Autobahn over SSL. There are 6 or so cases which currently fails.
* Make sure any callbacks registered to the SSL from Node.js gets removed / replaced (renegotiation callbacks, info callbacks, etc).

**Comment by LordMajestros** [comment]
Is this on npm yet?

**Comment by alexhultman** [comment]
No but I might publish a 3.1 or something like that with initial (very unstable) SSL soon.

**Comment by alexhultman** [comment]
There is initial (very broken) SSL support published as v0.2.7.

**Comment by alexhultman** [comment]
The last issues seems to be because socket.destroy() is not really destroying the socket immediately but rather in the following tick. It emits 'close' when really closed. I need to make sure not to upgrade the connection before this event, otherwise I sometimes do not get the initial sent package and therefore the test times out and fails. I guess the not-yet-closed socket sometimes consumes the packet before we do because it is still not fully closed. I hope this is the solution.

**Comment by alexhultman** [comment]
Yes that fixed it. Now every Autobahn test pass.
