### ISSUE TITLE
Port Node.js addon to Windows (done)

### ISSUE THREAD

**Issue by suhaotian** [uWebSockets/uWebSockets#72]
win 7!

**Comment by alexhultman** [comment]
Windows is not supported (yet) for the Node.js addon.

**Comment by ericmdantas** [comment]
:cry:

**Comment by alexhultman** [comment]
I don't have Windows anymore, my VM's Windows license expired some days ago. If you want Windows support you could compile it yourself and see how it works. It should be simple as there is no other dependencies than Node itself (which is libuv + OpenSSL + V8). If you write a binding.gyp a la the tutorials and node-gyp configure build with (I assume) Visual Studio Community Edition installed it should kind of work, I guess.

**Comment by alexhultman** [comment]
If we get PR #88 it should be possible to install for Windows but I need to fix a few things to get it fully working.

**Comment by alexhultman** [comment]
If you clone the repo and cd into uWebSockets/nodejs/dist and run `npm install` it should build on Windows. I don't know how good node-gyp is at finding Visual C++ on the system but you could try. `npm install` will write a file `build_log.txt` with output from the compilation.

**Comment by alexhultman** [comment]
You need to copy the src folder into dist and also copy addon.cpp into src. I tried it and it works better than I thought. There are some compilation errors that I need to fix but node-gyp is actually able to automatically find and use Visual C++.

**Comment by alexhultman** [comment]
Well it seems Node.js is pretty much broken on Windows. It does compile if I remove everything SSL from the source because the Node.js binary is only exporting V8 and libuv - OpenSSL and libz is not exported and some node-gyp documentation is claiming one needs to link against some separate installation of OpenSSL on Windows, which is absurd and possibly unstable. I cannot build a server library with only V8 and libuv - I need OpenSSL for SSL and libz for permessage-deflate. Unless I'm missing something here this would be impossible until Node.js gets an overhaul on Windows.

**Comment by alexhultman** [comment]
https://nodejs.org/api/addons.html#addons_linking_to_node_js_own_dependencies

**Comment by alexhultman** [comment]
https://github.com/nodejs/node/pull/6274

**Comment by NoelAbrahams** [comment]
It's a shame we cannot use this library because of the lack of support on windows. 

It's probably worth prioritising a bit higher because of the huge number of deployments on Microsoft Azure that use windows machines.

**Comment by alexhultman** [comment]
@NoelAbrahams This issue is blocked by the linked Node.js issue. They need to fix the Node.js Windows SDK to properly export the OpenSSL symbols so that our addon can be built. Good news is, they seem to be actively working on this issue and it was reported only 22 days ago.

**Comment by Dillybob92** [comment]
Just to add to @NoelAbrahams:  I'm using the `ws` module to dev on windows and have `perMessageDeflate` set to false, and the performance is fine for devving.  Once you launch for production, just switch to `uws` and that's it. Since the API is roughly if not identical, it helps a lot. 

Also, IIRC node-gyp on windows is a nightmare. Much easier on linux imo.

**Comment by alexhultman** [comment]
If anyone wants to, I could strip away SSL and permessage-deflate from the Windows version and have it run?

**Comment by NoelAbrahams** [comment]
We require SSL I'm afraid.

**Comment by SEAPUNK** [comment]
You could always run it behind a reverse proxy that handles the SSL for the server.

**Comment by alexhultman** [comment]
Did anyone try out the Linux runtime for Windows 10? You should be able to run the verbatim Node.js linux binary on Windows 10. https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

**Comment by alexhultman** [comment]
I just managed to build Node.js on Windows with all the OpenSSL symbols exported. Waiting for node devs to respond.

**Comment by alexhultman** [comment]
From the looks of it, the current PR works with one small modification. I think this will get merged soon.

**Comment by alexhultman** [comment]
Yeah so this looks very positive now. The PR that fixes OpenSSL on Windows passed all tests just now and is about to be merged. After this they/we need to also fix up zlib which should be pretty easy. When all this is done and there is a released version of Node.js with these fixes I can start work on porting whatever needs to be fixed to support Windows.

**Comment by kurtextrem** [comment]
Node 6.3.0 is out which fixed the issue!

**Comment by alexhultman** [comment]
That's cool, I will test this. There is still zlib missing but that should be easy to disable until they also fix that. I still need to get some info on how to transfer the socket from Node.js to the addon though, there is no file descriptor on Windows, I need the native SOCKET handle.

**Comment by alexhultman** [comment]
These symbols are still not exported:

```
Server.obj : error LNK2001: unresolved external symbol SSL_CTX_use_PrivateKey_file [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol SSL_set_fd [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol inflateInit2_ [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol deflateInit2_ [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol deflateReset [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol SSL_CTX_use_certificate_chain_file [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol deflateEnd [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
Server.obj : error LNK2001: unresolved external symbol deflate [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
WebSocket.obj : error LNK2001: unresolved external symbol inflateEnd [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
WebSocket.obj : error LNK2001: unresolved external symbol inflate [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
C:\Users\alex\uWebSockets\nodejs\dist\build\Release\uws.node : fatal error LNK1120: 10 unresolved externals [C:\Users\alex\uWebSockets\nodejs\dist\build\uws.vcxproj]
```

**Comment by kurtextrem** [comment]
Interesting, because https://github.com/nodejs/node/pull/6274 / the commit is mentioned in the changelog.

**Comment by alexhultman** [comment]
That commit is in 6.3.0, a lot of missing symbols are now present. There are some missing though, I checked the .num file that is being processed into openssl.def and SSL_set_fd and the two other are present so it is a script bug in the mkssldef.py added in that commit. The rest are zlib functions.

**Comment by alexhultman** [comment]
The addon is now ported to Windows and works. It cannot link against current versions of Node.js because of missing symbols but this will be fixed soon. I tested the current master of µWS by simply commenting out all usages of missing symbols and it seemed to work pretty nicely.
